// **********************************************************************
// *           Segment Name: Skald.baf
// **********************************************************************
// *
// * Skald.baf
// * -----------
// * AI Script for:             BGEET with Sword Coast Stratagems
// * Written by:                Mark Evinger (morpheus562)
// * Version:                   Version 2.0 (12 March 2021)
// * Comments to:               mark.evinger@hotmail.com
// * Depends on:                BGEET
//                              Sword Coast Stratagems
//                              Spell Revisions (Revised)
//
//
// * Description:
// * This is a script specifically designed for the Skald Kit. This script will cast 
// * pre-buff spells when the D key is pressed. The following spells will be pre-buffed: 
// * Fire Shield Red/Blue, (Minor) Globe of Invulnerability, Improved Haste, Mirror Image, 
// * Protection from Energy, Protection from Normal Missiles, Protection from the Elements, 
// * (Minor) Spell Deflection, Spell Immunity: Abjuration*, Spell Shield, and 
// * (Minor) Spell Turning. Will pre-buff using the following potions: Potion of Fire/Cold 
// * Resistance, Potion of Absorption, and Potion of Magic Protection. Outside of pre-buffing, 
// * the script uses healing potions and healing/curative spells as appropriate. Automatic use 
// * of Vocalize if the player gets muted. The script also keeps constant uptime of stoneskins. 
// * If the character's life drops below 50%, will automatically 
// * cast PfMW. Once those are taken care of, the next priority is detecting any invisible 
// * enemies and debuffing them. The script will also cast many of the spells and abilities in 
// * the pre-buffing section if certain types and quantities of enemies appear. When not casting 
// * spells, the Skald will constantly be singing the Skald song. Additionally, between casting 
// * spells, the Skald will start singing again to attempt to keep the Skald song up constantly 
// * in combat. This script is written to use up to Level 8 Spells. Items used by the script 
// * are: Methild's Harp, and Azlaer's Harp.

IF
  PartyRested()
THEN
  RESPONSE #100
    SetGlobal("MO_MethildHarp","LOCALS",0)
    SetGlobal("MO_AzlaerHarp","LOCALS",0)
END

IF
  OR(7)
    AreaCheck("AR0700")  // Waukeen's Promenade
    AreaCheck("AR0020")  // City Gates
    AreaCheck("AR0800")  // Graveyard
    AreaCheck("AR0400")  // Slums
    AreaCheck("AR0300")  // The Docks
    AreaCheck("AR1000")  // Government District
    AreaCheck("AR0900")  // Temple District
  Global("BRIBEDCOWLED","GLOBAL",0)
  GlobalLT("CowledWarning","GLOBAL",7)
  Global("MO_CastAthkatla","LOCALS",1)
THEN
  RESPONSE #100
    SetGlobal("MO_CastAthkatla","LOCALS",0)
END

IF
  !AreaCheck("AR0700")  // Waukeen's Promenade
  !AreaCheck("AR0020")  // City Gates
  !AreaCheck("AR0800")  // Graveyard
  !AreaCheck("AR0400")  // Slums
  !AreaCheck("AR0300")  // The Docks
  !AreaCheck("AR1000")  // Government District
  !AreaCheck("AR0900")  // Temple District
  Global("MO_CastAthkatla","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("MO_CastAthkatla","LOCALS",1)
END

IF
  OR(2)
    Global("BRIBEDCOWLED","GLOBAL",1)
    Global("CowledWarning","GLOBAL",7)
  Global("MO_CastAthkatla","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("MO_CastAthkatla","LOCALS",1)
END

IF
  Global("MO_BUFF","LOCALS",0)
  HotKey(D)
THEN
  RESPONSE #50
    SetGlobal("MO_BUFF","LOCALS",1)
    DisplayStringHead(Myself,91061)  // Right. I'll get started then.
  RESPONSE #50
    SetGlobal("MO_BUFF","LOCALS",1)
    DisplayStringHead(Myself,91057)  // Right, I'll get started then. Please excuse me.
END

IF
  Global("MO_BUFF","LOCALS",1)
  OR(2)
    HotKey(D)
    See([EVILCUTOFF])
THEN
  RESPONSE #100
    SetGlobal("MO_BUFF","LOCALS",0)
    DisplayStringHead(Myself,50742)  // I have not yet completed the task.
END

IF
  Global("MO_BUFF","LOCALS",1)
  HasItemEquiped("potn02",Myself)  // Potion of Fire Resistance
THEN
  RESPONSE #100
    UseItem("potn02",Myself)  // Potion of Fire Resistance
END

IF
  Global("MO_BUFF","LOCALS",1)
  HasItemEquiped("potn22",Myself)  // Potion of Cold Resistance
THEN
  RESPONSE #100
    UseItem("potn22",Myself)  // Potion of Cold Resistance
END

IF
  Global("MO_BUFF","LOCALS",1)
  HasItemEquiped("potn18",Myself)  // Potion of Absorption
  CheckStatLT(Myself,100,RESISTELECTRICITY)
THEN
  RESPONSE #100
    UseItem("potn18",Myself)  // Potion of Absorption
END

IF
  Global("MO_BUFF","LOCALS",1)
  HasItemEquiped("potn34",Myself)  // Potion of Magic Blocking
THEN
  RESPONSE #100
    UseItem("potn34",Myself)  // Potion of Magic Blocking
END

IF
  Global("MO_BUFF","LOCALS",1)
  IfValidForPartyDialog(Myself)
  HaveSpell(WIZARD_PROTECTION_FROM_MAGIC_ENERGY)  // SPWI606.SPL (Protection from Magic Energy)
  !CheckStatGT(Myself,0,WIZARD_PROTECTION_FROM_MAGIC_ENERGY)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_MAGIC_ENERGY)  // SPWI606.SPL (Protection from Magic Energy)
    RemoveSpell(WIZARD_PROTECTION_FROM_MAGIC_ENERGY)  // SPWI606.SPL (Protection from Magic Energy)
END

IF
  Global("MO_BUFF","LOCALS",1)
  IfValidForPartyDialog(Myself)
  HaveSpell(WIZARD_RESIST_FEAR)  // SPWI210.SPL (Resist Fear)
  !CheckSpellState(Myself,RESIST_FEAR)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(Myself,WIZARD_RESIST_FEAR)  // SPWI210.SPL (Resist Fear)
    RemoveSpell(WIZARD_RESIST_FEAR)  // SPWI210.SPL (Resist Fear)
END

IF
  Global("MO_BUFF","LOCALS",1)
  IfValidForPartyDialog(Myself)
  HaveSpell(WIZARD_PROTECTION_FROM_THE_ELEMENTS)  // SPWI702.SPL (Protection from the Elements)
  !CheckStatGT(Myself,0,WIZARD_PROTECTION_FROM_ENERGY)
  !CheckStatGT(Myself,0,WIZARD_PROTECTION_FROM_THE_ELEMENTS)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_THE_ELEMENTS)  // SPWI702.SPL (Protection from the Elements)
    RemoveSpell(WIZARD_PROTECTION_FROM_THE_ELEMENTS)  // SPWI702.SPL (Protection from the Elements)
END

IF
  Global("MO_BUFF","LOCALS",1)
  IfValidForPartyDialog(Myself)
  HaveSpell(WIZARD_PROTECTION_FROM_NORMAL_MISSILES)  // SPWI311.SPL (Protection from Missiles)
  !CheckSpellState(Myself,PROTECTION_FROM_NORMAL_MISSILES)
  !CheckSpellState(Myself,MINOR_GLOBE)
  !CheckSpellState(Myself,GLOBE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_NORMAL_MISSILES)  // SPWI311.SPL (Protection from Missiles)
    RemoveSpell(WIZARD_PROTECTION_FROM_NORMAL_MISSILES)  // SPWI311.SPL (Protection from Missiles)
END

IF
  Global("MO_BUFF","LOCALS",1)
  IfValidForPartyDialog(Myself)
  HaveSpell(WIZARD_SPELL_SHIELD)  // SPWI519.SPL (Spell Shield)
  !CheckSpellState(Myself,SPELL_SHIELD)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(Myself,WIZARD_SPELL_SHIELD)  // SPWI519.SPL (Spell Shield)
    RemoveSpell(WIZARD_SPELL_SHIELD)  // SPWI519.SPL (Spell Shield)
END

IF
  Global("MO_BUFF","LOCALS",1)
  IfValidForPartyDialog(Myself)
  HaveSpell(WIZARD_GREATER_SPELL_DEFLECTION)  // SPWI701.SPL (Greater Spell Deflection)
  !CheckSpellState(Myself,GREATER_SPELL_DEFLECTION)
  !CheckSpellState(Myself,SPELL_DEFLECTION)
  !CheckSpellState(Myself,MINOR_SPELL_DEFLECTION)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(Myself,WIZARD_GREATER_SPELL_DEFLECTION)  // SPWI701.SPL (Greater Spell Deflection)
    RemoveSpell(WIZARD_GREATER_SPELL_DEFLECTION)  // SPWI701.SPL (Greater Spell Deflection)
END

IF
  Global("MO_BUFF","LOCALS",1)
  IfValidForPartyDialog(Myself)
  HaveSpell(WIZARD_SPELL_DEFLECTION)  // SPWI522.SPL (Spell Deflection)
  !CheckSpellState(Myself,GREATER_SPELL_DEFLECTION)
  !CheckSpellState(Myself,SPELL_DEFLECTION)
  !CheckSpellState(Myself,MINOR_SPELL_DEFLECTION)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(Myself,WIZARD_SPELL_DEFLECTION)  // SPWI522.SPL (Spell Deflection)
    RemoveSpell(WIZARD_SPELL_DEFLECTION)  // SPWI522.SPL (Spell Deflection)
END

IF
  Global("MO_BUFF","LOCALS",1)
  IfValidForPartyDialog(Myself)
  HaveSpell(WIZARD_MINOR_SPELL_DEFLECTION)  // SPWI318.SPL (Minor Spell Deflection)
  !CheckSpellState(Myself,GREATER_SPELL_DEFLECTION)
  !CheckSpellState(Myself,SPELL_DEFLECTION)
  !CheckSpellState(Myself,MINOR_SPELL_DEFLECTION)
  !CheckSpellState(Myself,MINOR_GLOBE)
  !CheckSpellState(Myself,GLOBE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(Myself,WIZARD_MINOR_SPELL_DEFLECTION)  // SPWI318.SPL (Minor Spell Deflection)
    RemoveSpell(WIZARD_MINOR_SPELL_DEFLECTION)  // SPWI318.SPL (Minor Spell Deflection)
END

IF
  Global("MO_BUFF","LOCALS",1)
  IfValidForPartyDialog(Myself)
  !StateCheck(Myself,STATE_MIRRORIMAGE)
  HaveSpell(WIZARD_MIRROR_IMAGE)  // SPWI212.SPL (Mirror Image)
  !CheckSpellState(Myself,MINOR_GLOBE)
  !CheckSpellState(Myself,GLOBE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStat(Myself,1,PUPPETTYPE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(Myself,WIZARD_MIRROR_IMAGE)  // SPWI212.SPL (Mirror Image)
    RemoveSpell(WIZARD_MIRROR_IMAGE)  // SPWI212.SPL (Mirror Image)
END

IF
  Global("MO_BUFF","LOCALS",1)
  IfValidForPartyDialog(Myself)
  HaveSpell(WIZARD_DISPELLING_SCREEN)  // spwi525.spl (Dispelling Screen)
  !CheckSpellState(Myself,DISPEL_SCREEN)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(Myself,WIZARD_DISPELLING_SCREEN)  // spwi525.spl (Dispelling Screen)
    RemoveSpell(WIZARD_DISPELLING_SCREEN)  // spwi525.spl (Dispelling Screen)
END

IF
  Global("MO_BUFF","LOCALS",1)
  IfValidForPartyDialog(Myself)
  HaveSpellRES("SPIN103")  // Draw Upon Divine Might
  !StateCheck(Myself,STATE_DRAWUPONHOLYMIGHT)
  !CheckSpellState(Myself,MINOR_GLOBE)
  !CheckSpellState(Myself,GLOBE)
  CheckStatLT(Myself,25,STR)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    ReallyForceSpellRES("SPIN103",Myself)  // Draw Upon Divine Might
    RemoveSpellRES("SPIN103")  // Draw Upon Divine Might
END

IF
  Global("MO_BUFF","LOCALS",1)
  IfValidForPartyDialog(Myself)
  HaveSpell(WIZARD_PROTECTION_FROM_ENERGY)  // SPWI803.SPL (Protection from Energy)
  !CheckStatGT(Myself,0,WIZARD_PROTECTION_FROM_ENERGY)
  !CheckStatGT(Myself,0,WIZARD_PROTECTION_FROM_THE_ELEMENTS)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_ENERGY)  // SPWI803.SPL (Protection from Energy)
    RemoveSpell(WIZARD_PROTECTION_FROM_ENERGY)  // SPWI803.SPL (Protection from Energy)
END

IF
  Global("MO_BUFF","LOCALS",1)
  IfValidForPartyDialog(Myself)
  HaveSpell(WIZARD_MESTILS_ACID_SHEATH)  // SPWI524.spl (Mestil's Acid Sheath)
  !CheckSpellState(Myself,RED_FIRESHIELD)
  !CheckSpellState(Myself,ACID_SHEATH)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(Myself,WIZARD_MESTILS_ACID_SHEATH)  // SPWI524.spl (Mestil's Acid Sheath)
    RemoveSpell(WIZARD_MESTILS_ACID_SHEATH)  // SPWI524.spl (Mestil's Acid Sheath)
END

IF
  Global("MO_BUFF","LOCALS",1)
  IfValidForPartyDialog(Myself)
  HaveSpell(WIZARD_FIRE_SHIELD_RED)  // SPWI418.SPL (Fire Shield)
  !CheckSpellState(Myself,RED_FIRESHIELD)
  !CheckSpellState(Myself,ACID_SHEATH)
  !CheckSpellState(Myself,GLOBE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(Myself,WIZARD_FIRE_SHIELD_RED)  // SPWI418.SPL (Fire Shield)
    RemoveSpell(WIZARD_FIRE_SHIELD_RED)  // SPWI418.SPL (Fire Shield)
END

IF
  Global("MO_BUFF","LOCALS",1)
  IfValidForPartyDialog(Myself)
  HaveSpell(WIZARD_HASTE)  // SPWI305.SPL (Haste)
  !StateCheck(LastSeenBy(Myself),STATE_HASTED)
  CheckStat(LastSeenBy(Myself),0,IMPROVEDHASTE)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_VISIBLE)
  !CheckSpellState(Myself,MINOR_GLOBE)
  !CheckSpellState(Myself,GLOBE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(Myself,WIZARD_HASTE)  // SPWI305.SPL (Haste)
    RemoveSpell(WIZARD_HASTE)  // SPWI305.SPL (Haste)
END

IF
  Global("MO_BUFF","LOCALS",1)
  IfValidForPartyDialog(Myself)
  HaveSpell(WIZARD_IMPROVED_HASTE)  // SPWI613.SPL (Improved Haste)
  !CheckStatGT(Myself,0,IMPROVEDHASTE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(Myself,WIZARD_IMPROVED_HASTE)  // SPWI613.SPL (Improved Haste)
    RemoveSpell(WIZARD_IMPROVED_HASTE)  // SPWI613.SPL (Improved Haste)
END

IF
  Global("MO_BUFF","LOCALS",1)
  IfValidForPartyDialog(Myself)
  HaveSpell(WIZARD_SPELL_TRAP)  // SPWI902.SPL (Spell Trap)
  CheckStatLT(Myself,1,WIZARD_SPELL_TRAP)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(Myself,WIZARD_SPELL_TRAP)  // SPWI902.SPL (Spell Trap)
    RemoveSpell(WIZARD_SPELL_TRAP)  // SPWI902.SPL (Spell Trap)
END

IF
  Global("MO_BUFF","LOCALS",1)
THEN
  RESPONSE #100
    SetGlobal("MO_BUFF","LOCALS",0)
    DisplayStringHead(Myself,421)  // Combat ready!
END

IF
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  OR(2)
    StateCheck(Myself,STATE_POISONED)
    CheckSpellState(Myself,DISEASED)
  HasItemEquiped("POTN17",Myself)  // Elixir of Health
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    UseItem("POTN17",Myself)  // Elixir of Health
    DisplayString(Myself,46150)  // *quaffs a potion*
END

IF
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  StateCheck(Myself,STATE_POISONED)
  HasItemEquiped("POTN20",Myself)  // Potion of Antidote
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    UseItem("POTN20",Myself)  // Potion of Antidote
    DisplayString(Myself,46150)  // *quaffs a potion*
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  HaveSpellRES("SPIN102")  // Slow Poison
  See([PC])
  StateCheck(LastSeenBy(Myself),STATE_POISONED)
  OR(2)
    Range(LastSeenBy(Myself),6)
    !Range(NearestEnemyOf(Myself),30)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(LastSeenBy(Myself),MINOR_GLOBE)
  !CheckSpellState(LastSeenBy(Myself),GLOBE)
  !CheckSpellState(LastSeenBy(Myself),MINOR_SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),GREATER_SPELL_DEFLECTION)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    SpellRES("SPIN102",LastSeenBy(Myself))  // Slow Poison
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_SpellCast","LOCALS")
  HaveSpellRES("SPIN102")  // Slow Poison
  See(Nearest([PC]))
  StateCheck(LastSeenBy(Myself),STATE_POISONED)
  OR(2)
    Range(LastSeenBy(Myself),6)
    !Range(NearestEnemyOf(Myself),30)
  !CheckSpellState(LastSeenBy(Myself),MINOR_GLOBE)
  !CheckSpellState(LastSeenBy(Myself),GLOBE)
  !CheckSpellState(LastSeenBy(Myself),MINOR_SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),GREATER_SPELL_DEFLECTION)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCast","LOCALS",ONE_ROUND)
    SetInterrupt(FALSE)
    SpellRES("SPIN102",LastSeenBy(Myself))  // Slow Poison
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  HaveSpellRES("SPIN102")  // Slow Poison
  See(SecondNearest([PC]))
  StateCheck(LastSeenBy(Myself),STATE_POISONED)
  OR(2)
    Range(LastSeenBy(Myself),6)
    !Range(NearestEnemyOf(Myself),30)
  !CheckSpellState(LastSeenBy(Myself),MINOR_GLOBE)
  !CheckSpellState(LastSeenBy(Myself),GLOBE)
  !CheckSpellState(LastSeenBy(Myself),MINOR_SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),GREATER_SPELL_DEFLECTION)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    SpellRES("SPIN102",LastSeenBy(Myself))  // Slow Poison
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  HaveSpellRES("SPIN102")  // Slow Poison
  See(ThirdNearest([PC]))
  StateCheck(LastSeenBy(Myself),STATE_POISONED)
  OR(2)
    Range(LastSeenBy(Myself),6)
    !Range(NearestEnemyOf(Myself),30)
  !CheckSpellState(LastSeenBy(Myself),MINOR_GLOBE)
  !CheckSpellState(LastSeenBy(Myself),GLOBE)
  !CheckSpellState(LastSeenBy(Myself),MINOR_SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),GREATER_SPELL_DEFLECTION)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    SpellRES("SPIN102",LastSeenBy(Myself))  // Slow Poison
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  HaveSpellRES("SPIN102")  // Slow Poison
  See(FourthNearest([PC]))
  StateCheck(LastSeenBy(Myself),STATE_POISONED)
  OR(2)
    Range(LastSeenBy(Myself),6)
    !Range(NearestEnemyOf(Myself),30)
  !CheckSpellState(LastSeenBy(Myself),MINOR_GLOBE)
  !CheckSpellState(LastSeenBy(Myself),GLOBE)
  !CheckSpellState(LastSeenBy(Myself),MINOR_SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),GREATER_SPELL_DEFLECTION)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    SpellRES("SPIN102",LastSeenBy(Myself))  // Slow Poison
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  HaveSpellRES("SPIN102")  // Slow Poison
  See(FifthNearest([PC]))
  StateCheck(LastSeenBy(Myself),STATE_POISONED)
  OR(2)
    Range(LastSeenBy(Myself),6)
    !Range(NearestEnemyOf(Myself),30)
  !CheckSpellState(LastSeenBy(Myself),MINOR_GLOBE)
  !CheckSpellState(LastSeenBy(Myself),GLOBE)
  !CheckSpellState(LastSeenBy(Myself),MINOR_SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),GREATER_SPELL_DEFLECTION)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    SpellRES("SPIN102",LastSeenBy(Myself))  // Slow Poison
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  HaveSpellRES("SPIN102")  // Slow Poison
  See(SixthNearest([PC]))
  StateCheck(LastSeenBy(Myself),STATE_POISONED)
  OR(2)
    Range(LastSeenBy(Myself),6)
    !Range(NearestEnemyOf(Myself),30)
  !CheckSpellState(LastSeenBy(Myself),MINOR_GLOBE)
  !CheckSpellState(LastSeenBy(Myself),GLOBE)
  !CheckSpellState(LastSeenBy(Myself),MINOR_SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),GREATER_SPELL_DEFLECTION)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    SpellRES("SPIN102",LastSeenBy(Myself))  // Slow Poison
    SetInterrupt(TRUE)
END

IF
  ActionListEmpty()
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  HaveSpellRES("SPIN101")  // Cure Light Wounds
  !See([EVILCUTOFF])
  See(MostDamagedOf([PC]))
  HPPercentLT(LastSeenBy(Myself),80)
  IfValidForPartyDialog(LastSeenBy(Myself))
  OR(2)
    Range(MostDamagedOf([PC]),6)
    !Range(NearestEnemyOf(Myself),30)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_VISIBLE)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_APPROACHABLE)
  !StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
  !CheckSpellState(LastSeenBy(Myself),MINOR_GLOBE)
  !CheckSpellState(LastSeenBy(Myself),GLOBE)
  !CheckSpellState(LastSeenBy(Myself),MINOR_SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),GREATER_SPELL_DEFLECTION)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREPRIEST)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    SpellRES("SPIN101",LastSeenBy(Myself))  // Cure Light Wounds
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  See(NearestEnemyOf(Myself))
  StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  HaveSpell(WIZARD_VOCALIZE)  // SPWI219.SPL (Vocalize)
  !CheckSpellState(LastSeenBy(Myself),MINOR_GLOBE)
  !CheckSpellState(LastSeenBy(Myself),GLOBE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_VOCALIZE)  // SPWI219.SPL (Vocalize)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  See([EVILCUTOFF])
  HPPercentLT(Myself,51)
  IfValidForPartyDialog(Myself)
  HaveSpell(WIZARD_ABSOLUTE_IMMUNITY)  // SPWI907.SPL (Absolute Immunity)
  !CheckSpellState(Myself,PROTECTION_FROM_MAGICAL_WEAPONS)
  !CheckSpellState(Myself,ABSOLUTE_IMMUNITY)
  !CheckSpellState(Myself,MANTLE)
  !CheckSpellState(Myself,IMPROVED_MANTLE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_ABSOLUTE_IMMUNITY)  // SPWI907.SPL (Absolute Immunity)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  See([EVILCUTOFF])
  HPPercentLT(Myself,51)
  IfValidForPartyDialog(Myself)
  HaveSpell(WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)  // SPWI611.SPL (Protection from Magical Weapons)
  !CheckSpellState(Myself,PROTECTION_FROM_MAGICAL_WEAPONS)
  !CheckSpellState(Myself,ABSOLUTE_IMMUNITY)
  !CheckSpellState(Myself,MANTLE)
  !CheckSpellState(Myself,IMPROVED_MANTLE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)  // SPWI611.SPL (Protection from Magical Weapons)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  See([EVILCUTOFF])
  HPPercentLT(Myself,51)
  IfValidForPartyDialog(Myself)
  HaveSpell(WIZARD_MOMENT_OF_PRESCIENCE)  // SPWI808.SPL (Moment of Prescience)
  !CheckSpellState(Myself,PROTECTION_FROM_MAGICAL_WEAPONS)
  !CheckSpellState(Myself,ABSOLUTE_IMMUNITY)
  !CheckSpellState(Myself,MANTLE)
  !CheckSpellState(Myself,IMPROVED_MANTLE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_MOMENT_OF_PRESCIENCE)  // SPWI808.SPL (Moment of Prescience)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  See([EVILCUTOFF])
  HPPercentLT(Myself,51)
  IfValidForPartyDialog(Myself)
  HaveSpell(WIZARD_MANTLE)  // SPWI708.SPL (Prismatic Mantle)
  !CheckSpellState(Myself,PROTECTION_FROM_MAGICAL_WEAPONS)
  !CheckSpellState(Myself,ABSOLUTE_IMMUNITY)
  !CheckSpellState(Myself,MANTLE)
  !CheckSpellState(Myself,IMPROVED_MANTLE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_MANTLE)  // SPWI708.SPL (Prismatic Mantle)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  CheckStatLT(Myself,1,STONESKINS)
  HaveSpell(WIZARD_STONE_SKIN)  // SPWI408.SPL (Stoneskin)
  !CheckSpellState(LastSeenBy(Myself),GLOBE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_STONE_SKIN)  // SPWI408.SPL (Stoneskin)
    SetInterrupt(TRUE)
END

IF
  ActionListEmpty()
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  !See([EVILCUTOFF])
  HaveSpell(WIZARD_ARMOR)  // SPWI102.SPL (Mage Armor)
  !CheckSpellState(Myself,MAGE_ARMOR)
  !CheckSpellState(LastSeenBy(Myself),MINOR_GLOBE)
  !CheckSpellState(LastSeenBy(Myself),GLOBE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_ARMOR)  // SPWI102.SPL (Mage Armor)
    SetInterrupt(TRUE)
END

IF
  ActionListEmpty()
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  !See([EVILCUTOFF])
  HaveSpell(WIZARD_MIND_BLANK)  // SPWI802.SPL (Mind Blank)
  !CheckSpellState(Myself,MIND_BLANK)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_MIND_BLANK)  // SPWI802.SPL (Mind Blank)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  HaveSpell(WIZARD_BREAK_ENCHANTMENT)  // SPWI410.SPL (Break Enchantment)
  See(Nearest([PC]))
  OR(8)
    StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
    StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
    StateCheck(LastSeenBy(Myself),STATE_CHARMED)
    StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
    StateCheck(LastSeenBy(Myself),STATE_SILENCED)
    StateCheck(LastSeenBy(Myself),STATE_PANIC)
    CheckSpellState(LastSeenBy(Myself),DEAFENED)
    CheckStatGT(LastSeenBy(Myself),0,HELD)
  !CheckSpellState(LastSeenBy(Myself),GLOBE)
  !CheckSpellState(LastSeenBy(Myself),MINOR_SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),GREATER_SPELL_DEFLECTION)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_BREAK_ENCHANTMENT)  // SPWI410.SPL (Break Enchantment)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  HaveSpell(WIZARD_BREAK_ENCHANTMENT)  // SPWI410.SPL (Break Enchantment)
  See(SecondNearest([PC]))
  OR(8)
    StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
    StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
    StateCheck(LastSeenBy(Myself),STATE_CHARMED)
    StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
    StateCheck(LastSeenBy(Myself),STATE_SILENCED)
    StateCheck(LastSeenBy(Myself),STATE_PANIC)
    CheckSpellState(LastSeenBy(Myself),DEAFENED)
    CheckStatGT(LastSeenBy(Myself),0,HELD)
  !CheckSpellState(LastSeenBy(Myself),GLOBE)
  !CheckSpellState(LastSeenBy(Myself),MINOR_SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),GREATER_SPELL_DEFLECTION)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_BREAK_ENCHANTMENT)  // SPWI410.SPL (Break Enchantment)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  HaveSpell(WIZARD_BREAK_ENCHANTMENT)  // SPWI410.SPL (Break Enchantment)
  See(ThirdNearest([PC]))
  OR(8)
    StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
    StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
    StateCheck(LastSeenBy(Myself),STATE_CHARMED)
    StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
    StateCheck(LastSeenBy(Myself),STATE_SILENCED)
    StateCheck(LastSeenBy(Myself),STATE_PANIC)
    CheckSpellState(LastSeenBy(Myself),DEAFENED)
    CheckStatGT(LastSeenBy(Myself),0,HELD)
  !CheckSpellState(LastSeenBy(Myself),GLOBE)
  !CheckSpellState(LastSeenBy(Myself),MINOR_SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),GREATER_SPELL_DEFLECTION)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_BREAK_ENCHANTMENT)  // SPWI410.SPL (Break Enchantment)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  HaveSpell(WIZARD_BREAK_ENCHANTMENT)  // SPWI410.SPL (Break Enchantment)
  See(FourthNearest([PC]))
  OR(8)
    StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
    StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
    StateCheck(LastSeenBy(Myself),STATE_CHARMED)
    StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
    StateCheck(LastSeenBy(Myself),STATE_SILENCED)
    StateCheck(LastSeenBy(Myself),STATE_PANIC)
    CheckSpellState(LastSeenBy(Myself),DEAFENED)
    CheckStatGT(LastSeenBy(Myself),0,HELD)
  !CheckSpellState(LastSeenBy(Myself),GLOBE)
  !CheckSpellState(LastSeenBy(Myself),MINOR_SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),GREATER_SPELL_DEFLECTION)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_BREAK_ENCHANTMENT)  // SPWI410.SPL (Break Enchantment)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  HaveSpell(WIZARD_BREAK_ENCHANTMENT)  // SPWI410.SPL (Break Enchantment)
  See(FifthNearest([PC]))
  OR(8)
    StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
    StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
    StateCheck(LastSeenBy(Myself),STATE_CHARMED)
    StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
    StateCheck(LastSeenBy(Myself),STATE_SILENCED)
    StateCheck(LastSeenBy(Myself),STATE_PANIC)
    CheckSpellState(LastSeenBy(Myself),DEAFENED)
    CheckStatGT(LastSeenBy(Myself),0,HELD)
  !CheckSpellState(LastSeenBy(Myself),GLOBE)
  !CheckSpellState(LastSeenBy(Myself),MINOR_SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),GREATER_SPELL_DEFLECTION)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_BREAK_ENCHANTMENT)  // SPWI410.SPL (Break Enchantment)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  HaveSpell(WIZARD_BREAK_ENCHANTMENT)  // SPWI410.SPL (Break Enchantment)
  See(SixthNearest([PC]))
  OR(8)
    StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
    StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
    StateCheck(LastSeenBy(Myself),STATE_CHARMED)
    StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
    StateCheck(LastSeenBy(Myself),STATE_SILENCED)
    StateCheck(LastSeenBy(Myself),STATE_PANIC)
    CheckSpellState(LastSeenBy(Myself),DEAFENED)
    CheckStatGT(LastSeenBy(Myself),0,HELD)
  !CheckSpellState(LastSeenBy(Myself),GLOBE)
  !CheckSpellState(LastSeenBy(Myself),MINOR_SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),GREATER_SPELL_DEFLECTION)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_BREAK_ENCHANTMENT)  // SPWI410.SPL (Break Enchantment)
    SetInterrupt(TRUE)
END

IF
  ActionListEmpty()
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  See([EVILCUTOFF])
  HPPercentLT(Myself,51)
  HasItemEquiped("POTN55",Myself)  // Potion of Superior Healing
  ActuallyInCombat()
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    UseItem("POTN55",Myself)  // Potion of Superior Healing
    DisplayString(Myself,46150)  // *quaffs a potion*
END

IF
  ActionListEmpty()
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  See([EVILCUTOFF])
  HPPercentLT(Myself,51)
  HasItemEquiped("POTN52",Myself)  // Potion of Extra Healing
  ActuallyInCombat()
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    UseItem("POTN52",Myself)  // Potion of Extra Healing
    DisplayString(Myself,46150)  // *quaffs a potion*
END

IF
  ActionListEmpty()
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  See([EVILCUTOFF])
  HPPercentLT(Myself,51)
  HasItemEquiped("POTN08",Myself)  // Potion of Healing
  ActuallyInCombat()
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    UseItem("POTN08",Myself)  // Potion of Healing
    DisplayString(Myself,46150)  // *quaffs a potion*
END

IF
  ActionListEmpty()
  IfValidForPartyDialog(Myself)
  See([GOODCUTOFF])
  OR(2)
    StateCheck(LastSeenBy(Myself),STATE_STUNNED)
    CheckStatGT(LastSeenBy(Myself),0,HELD)
  HasItemEquiped("MISC3O",Myself)  // Methild's Harp
  GlobalLT("MO_MethildHarp","LOCALS",3)
  Global("MO_CastAthkatla","LOCALS",1)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    UseItem("MISC3O",LastSeenBy(Myself))  // Methild's Harp
    IncrementGlobal("MO_MethildHarp","LOCALS",1)
END

IF
  ActionListEmpty()
  IfValidForPartyDialog(Myself)
  See(SecondNearest([GOODCUTOFF]))
  OR(2)
    StateCheck(LastSeenBy(Myself),STATE_STUNNED)
    CheckStatGT(LastSeenBy(Myself),0,HELD)
  HasItemEquiped("MISC3O",Myself)  // Methild's Harp
  GlobalLT("MO_MethildHarp","LOCALS",3)
  Global("MO_CastAthkatla","LOCALS",1)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    UseItem("MISC3O",LastSeenBy(Myself))  // Methild's Harp
    IncrementGlobal("MO_MethildHarp","LOCALS",1)
END

IF
  ActionListEmpty()
  IfValidForPartyDialog(Myself)
  See(ThirdNearest([GOODCUTOFF]))
  OR(2)
    StateCheck(LastSeenBy(Myself),STATE_STUNNED)
    CheckStatGT(LastSeenBy(Myself),0,HELD)
  HasItemEquiped("MISC3O",Myself)  // Methild's Harp
  GlobalLT("MO_MethildHarp","LOCALS",3)
  Global("MO_CastAthkatla","LOCALS",1)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    UseItem("MISC3O",LastSeenBy(Myself))  // Methild's Harp
    IncrementGlobal("MO_MethildHarp","LOCALS",1)
END

IF
  ActionListEmpty()
  IfValidForPartyDialog(Myself)
  See(FourthNearest([GOODCUTOFF]))
  OR(2)
    StateCheck(LastSeenBy(Myself),STATE_STUNNED)
    CheckStatGT(LastSeenBy(Myself),0,HELD)
  HasItemEquiped("MISC3O",Myself)  // Methild's Harp
  GlobalLT("MO_MethildHarp","LOCALS",3)
  Global("MO_CastAthkatla","LOCALS",1)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    UseItem("MISC3O",LastSeenBy(Myself))  // Methild's Harp
    IncrementGlobal("MO_MethildHarp","LOCALS",1)
END

IF
  ActionListEmpty()
  IfValidForPartyDialog(Myself)
  See(FifthNearest([GOODCUTOFF]))
  OR(2)
    StateCheck(LastSeenBy(Myself),STATE_STUNNED)
    CheckStatGT(LastSeenBy(Myself),0,HELD)
  HasItemEquiped("MISC3O",Myself)  // Methild's Harp
  GlobalLT("MO_MethildHarp","LOCALS",3)
  Global("MO_CastAthkatla","LOCALS",1)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    UseItem("MISC3O",LastSeenBy(Myself))  // Methild's Harp
    IncrementGlobal("MO_MethildHarp","LOCALS",1)
END

IF
  ActionListEmpty()
  IfValidForPartyDialog(Myself)
  See(SixthNearest([GOODCUTOFF]))
  OR(2)
    StateCheck(LastSeenBy(Myself),STATE_STUNNED)
    CheckStatGT(LastSeenBy(Myself),0,HELD)
  HasItemEquiped("MISC3O",Myself)  // Methild's Harp
  GlobalLT("MO_MethildHarp","LOCALS",3)
  Global("MO_CastAthkatla","LOCALS",1)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    UseItem("MISC3O",LastSeenBy(Myself))  // Methild's Harp
    IncrementGlobal("MO_MethildHarp","LOCALS",1)
END

IF
  ActionListEmpty()
  IfValidForPartyDialog(Myself)
  See([GOODCUTOFF])
  StateCheck([GOODCUTOFF],STATE_PANIC)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  HasItemEquiped("MISC3N",Myself)  // Azlaer's Harp
  Global("MO_CastAthkatla","LOCALS",1)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    UseItem("MISC3N",LastSeenBy(Myself))  // Azlaer's Harp
    IncrementGlobal("MO_AzlaerHarp","LOCALS",1)
END

IF
  ActionListEmpty()
  IfValidForPartyDialog(Myself)
  See(SecondNearest([GOODCUTOFF]))
  StateCheck(SecondNearest([GOODCUTOFF]),STATE_PANIC)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  HasItemEquiped("MISC3N",Myself)  // Azlaer's Harp
  Global("MO_CastAthkatla","LOCALS",1)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    UseItem("MISC3N",LastSeenBy(Myself))  // Azlaer's Harp
    IncrementGlobal("MO_AzlaerHarp","LOCALS",1)
END

IF
  ActionListEmpty()
  IfValidForPartyDialog(Myself)
  See(ThirdNearest([GOODCUTOFF]))
  StateCheck(ThirdNearest([GOODCUTOFF]),STATE_PANIC)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  HasItemEquiped("MISC3N",Myself)  // Azlaer's Harp
  Global("MO_CastAthkatla","LOCALS",1)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    UseItem("MISC3N",LastSeenBy(Myself))  // Azlaer's Harp
    IncrementGlobal("MO_AzlaerHarp","LOCALS",1)
END

IF
  ActionListEmpty()
  IfValidForPartyDialog(Myself)
  See(FourthNearest([GOODCUTOFF]))
  StateCheck(FourthNearest([GOODCUTOFF]),STATE_PANIC)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  HasItemEquiped("MISC3N",Myself)  // Azlaer's Harp
  Global("MO_CastAthkatla","LOCALS",1)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    UseItem("MISC3N",LastSeenBy(Myself))  // Azlaer's Harp
    IncrementGlobal("MO_AzlaerHarp","LOCALS",1)
END

IF
  ActionListEmpty()
  IfValidForPartyDialog(Myself)
  See(FifthNearest([GOODCUTOFF]))
  StateCheck(FifthNearest([GOODCUTOFF]),STATE_PANIC)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  HasItemEquiped("MISC3N",Myself)  // Azlaer's Harp
  Global("MO_CastAthkatla","LOCALS",1)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    UseItem("MISC3N",LastSeenBy(Myself))  // Azlaer's Harp
    IncrementGlobal("MO_AzlaerHarp","LOCALS",1)
END

IF
  ActionListEmpty()
  IfValidForPartyDialog(Myself)
  See(SixthNearest([GOODCUTOFF]))
  StateCheck(SixthNearest([GOODCUTOFF]),STATE_PANIC)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  HasItemEquiped("MISC3N",Myself)  // Azlaer's Harp
  Global("MO_CastAthkatla","LOCALS",1)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    UseItem("MISC3N",LastSeenBy(Myself))  // Azlaer's Harp
    IncrementGlobal("MO_AzlaerHarp","LOCALS",1)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  HaveSpell(WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Seeing)
  OR(6)
    SpellCast([EVILCUTOFF],WIZARD_PROJECT_IMAGE)  // SPWI703.SPL (Project Image)
    SpellCast([EVILCUTOFF],WIZARD_SIMULACRUM)  // SPWI804.SPL (Simulacrum)
    SpellCast([EVILCUTOFF],WIZARD_MISLEAD)  // SPWI607.SPL (Mislead)
    SpellCast([EVILCUTOFF],WIZARD_SHADOW_DOOR)  // SPWI505.SPL (Shadow Door)
    SpellCast([EVILCUTOFF],WIZARD_IMPROVED_INVISIBILITY)  // SPWI405.SPL (Improved Invisibility)
    SpellCast([EVILCUTOFF],WIZARD_INVISIBILITY)  // SPWI206.SPL (Invisibility)
  CheckStatLT(Myself,1,TRUE_SIGHT)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Seeing)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  HaveSpell(WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Seeing)
  Detect([EVILCUTOFF])
  OR(4)
    StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
    StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
    CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
    Gender(LastSeenBy(Myself),ILLUSIONARY)
  CheckStatLT(Myself,1,TRUE_SIGHT)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Seeing)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  HaveSpell(WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Seeing)
  See(NearestEnemyOf(Myself))
  OR(4)
    StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
    StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
    CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
    Gender(LastSeenBy(Myself),ILLUSIONARY)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
  CheckStatLT(Myself,1,TRUE_SIGHT)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Seeing)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  HaveSpell(WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Seeing)
  See(SecondNearestEnemyOf(Myself))
  OR(4)
    StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
    StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
    CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
    Gender(LastSeenBy(Myself),ILLUSIONARY)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
  CheckStatLT(Myself,1,TRUE_SIGHT)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Seeing)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  HaveSpell(WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Seeing)
  See(ThirdNearestEnemyOf(Myself))
  OR(4)
    StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
    StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
    CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
    Gender(LastSeenBy(Myself),ILLUSIONARY)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
  CheckStatLT(Myself,1,TRUE_SIGHT)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Seeing)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  HaveSpell(WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Seeing)
  See(FourthNearestEnemyOf(Myself))
  OR(4)
    StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
    StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
    CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
    Gender(LastSeenBy(Myself),ILLUSIONARY)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
  CheckStatLT(Myself,1,TRUE_SIGHT)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Seeing)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  HaveSpell(WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Seeing)
  See(FifthNearestEnemyOf(Myself))
  OR(4)
    StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
    StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
    CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
    Gender(LastSeenBy(Myself),ILLUSIONARY)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
  CheckStatLT(Myself,1,TRUE_SIGHT)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Seeing)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  HaveSpell(WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Seeing)
  See(SixthNearestEnemyOf(Myself))
  OR(4)
    StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
    StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
    CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
    Gender(LastSeenBy(Myself),ILLUSIONARY)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
  CheckStatLT(Myself,1,TRUE_SIGHT)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Seeing)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  HaveSpell(WIZARD_DETECT_INVISIBILITY)  // SPWI203.SPL (Detect Invisibility)
  Detect([EVILCUTOFF])
  OR(3)
    StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
    StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
    CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_NONDETECTION)
  CheckStatLT(Myself,1,TRUE_SIGHT)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_DETECT_INVISIBILITY)  // SPWI203.SPL (Detect Invisibility)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  HaveSpell(WIZARD_DETECT_INVISIBILITY)  // SPWI203.SPL (Detect Invisibility)
  See(NearestEnemyOf(Myself))
  OR(3)
    StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
    StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
    CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
  !StateCheck(LastSeenBy(Myself),STATE_NONDETECTION)
  CheckStatLT(Myself,1,TRUE_SIGHT)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_DETECT_INVISIBILITY)  // SPWI203.SPL (Detect Invisibility)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  HaveSpell(WIZARD_DETECT_INVISIBILITY)  // SPWI203.SPL (Detect Invisibility)
  See(SecondNearestEnemyOf(Myself))
  OR(3)
    StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
    StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
    CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
  !StateCheck(LastSeenBy(Myself),STATE_NONDETECTION)
  CheckStatLT(Myself,1,TRUE_SIGHT)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_DETECT_INVISIBILITY)  // SPWI203.SPL (Detect Invisibility)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  HaveSpell(WIZARD_DETECT_INVISIBILITY)  // SPWI203.SPL (Detect Invisibility)
  See(ThirdNearestEnemyOf(Myself))
  OR(3)
    StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
    StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
    CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
  !StateCheck(LastSeenBy(Myself),STATE_NONDETECTION)
  CheckStatLT(Myself,1,TRUE_SIGHT)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_DETECT_INVISIBILITY)  // SPWI203.SPL (Detect Invisibility)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  HaveSpell(WIZARD_DETECT_INVISIBILITY)  // SPWI203.SPL (Detect Invisibility)
  See(FourthNearestEnemyOf(Myself))
  OR(3)
    StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
    StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
    CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
  !StateCheck(LastSeenBy(Myself),STATE_NONDETECTION)
  CheckStatLT(Myself,1,TRUE_SIGHT)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_DETECT_INVISIBILITY)  // SPWI203.SPL (Detect Invisibility)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  HaveSpell(WIZARD_DETECT_INVISIBILITY)  // SPWI203.SPL (Detect Invisibility)
  See(FifthNearestEnemyOf(Myself))
  OR(3)
    StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
    StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
    CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
  !StateCheck(LastSeenBy(Myself),STATE_NONDETECTION)
  CheckStatLT(Myself,1,TRUE_SIGHT)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_DETECT_INVISIBILITY)  // SPWI203.SPL (Detect Invisibility)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  HaveSpell(WIZARD_DETECT_INVISIBILITY)  // SPWI203.SPL (Detect Invisibility)
  See(SixthNearestEnemyOf(Myself))
  OR(3)
    StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
    StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
    CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
  !StateCheck(LastSeenBy(Myself),STATE_NONDETECTION)
  CheckStatLT(Myself,1,TRUE_SIGHT)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_DETECT_INVISIBILITY)  // SPWI203.SPL (Detect Invisibility)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  HaveSpell(WIZARD_BREACH)  // SPWI513.SPL (Breach)
  See([EVILCUTOFF])
  !StateCheck(LastSeenBy(Myself),STATE_NOT_VISIBLE)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
  !CheckSpellState(LastSeenBy(Myself),SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),GREATER_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  CheckStatLT(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_BREACH)  // SPWI513.SPL (Breach)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  HaveSpell(WIZARD_BREACH)  // SPWI513.SPL (Breach)
  See(SecondNearest([EVILCUTOFF]))
  !StateCheck(LastSeenBy(Myself),STATE_NOT_VISIBLE)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
  !CheckSpellState(LastSeenBy(Myself),SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),GREATER_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  CheckStatLT(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_BREACH)  // SPWI513.SPL (Breach)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  HaveSpell(WIZARD_BREACH)  // SPWI513.SPL (Breach)
  See(ThirdNearest([EVILCUTOFF]))
  !StateCheck(LastSeenBy(Myself),STATE_NOT_VISIBLE)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
  !CheckSpellState(LastSeenBy(Myself),SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),GREATER_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  CheckStatLT(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_BREACH)  // SPWI513.SPL (Breach)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  HaveSpell(WIZARD_BREACH)  // SPWI513.SPL (Breach)
  See(FourthNearest([EVILCUTOFF]))
  !StateCheck(LastSeenBy(Myself),STATE_NOT_VISIBLE)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
  !CheckSpellState(LastSeenBy(Myself),SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),GREATER_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  CheckStatLT(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_BREACH)  // SPWI513.SPL (Breach)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  HaveSpell(WIZARD_BREACH)  // SPWI513.SPL (Breach)
  See(FifthNearest([EVILCUTOFF]))
  !StateCheck(LastSeenBy(Myself),STATE_NOT_VISIBLE)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
  !CheckSpellState(LastSeenBy(Myself),SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),GREATER_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  CheckStatLT(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_BREACH)  // SPWI513.SPL (Breach)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  HaveSpell(WIZARD_BREACH)  // SPWI513.SPL (Breach)
  See(SixthNearest([EVILCUTOFF]))
  !StateCheck(LastSeenBy(Myself),STATE_NOT_VISIBLE)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
  !CheckSpellState(LastSeenBy(Myself),SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),GREATER_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  CheckStatLT(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_BREACH)  // SPWI513.SPL (Breach)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  HaveSpell(WIZARD_PIERCE_SHIELD)  // SPWI805.SPL (Pierce Shield)
  See([EVILCUTOFF])
  !StateCheck(LastSeenBy(Myself),STATE_NOT_VISIBLE)
  !ImmuneToSpellLevel(LastSeenBy(Myself),8)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
  !CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_PIERCE_SHIELD)  // SPWI805.SPL (Pierce Shield)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  HaveSpell(WIZARD_PIERCE_SHIELD)  // SPWI805.SPL (Pierce Shield)
  See(SecondNearest([EVILCUTOFF]))
  !StateCheck(LastSeenBy(Myself),STATE_NOT_VISIBLE)
  !ImmuneToSpellLevel(LastSeenBy(Myself),8)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
  !CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_PIERCE_SHIELD)  // SPWI805.SPL (Pierce Shield)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  HaveSpell(WIZARD_PIERCE_SHIELD)  // SPWI805.SPL (Pierce Shield)
  See(ThirdNearest([EVILCUTOFF]))
  !StateCheck(LastSeenBy(Myself),STATE_NOT_VISIBLE)
  !ImmuneToSpellLevel(LastSeenBy(Myself),8)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
  !CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_PIERCE_SHIELD)  // SPWI805.SPL (Pierce Shield)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  HaveSpell(WIZARD_PIERCE_SHIELD)  // SPWI805.SPL (Pierce Shield)
  See(FourthNearest([EVILCUTOFF]))
  !StateCheck(LastSeenBy(Myself),STATE_NOT_VISIBLE)
  !ImmuneToSpellLevel(LastSeenBy(Myself),8)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
  !CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_PIERCE_SHIELD)  // SPWI805.SPL (Pierce Shield)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  HaveSpell(WIZARD_PIERCE_SHIELD)  // SPWI805.SPL (Pierce Shield)
  See(FifthNearest([EVILCUTOFF]))
  !StateCheck(LastSeenBy(Myself),STATE_NOT_VISIBLE)
  !ImmuneToSpellLevel(LastSeenBy(Myself),8)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
  !CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_PIERCE_SHIELD)  // SPWI805.SPL (Pierce Shield)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  HaveSpell(WIZARD_PIERCE_SHIELD)  // SPWI805.SPL (Pierce Shield)
  See(SixthNearest([EVILCUTOFF]))
  !StateCheck(LastSeenBy(Myself),STATE_NOT_VISIBLE)
  !ImmuneToSpellLevel(LastSeenBy(Myself),8)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
  !CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_PIERCE_SHIELD)  // SPWI805.SPL (Pierce Shield)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  HaveSpell(WIZARD_SPELL_THRUST)  // SPWI321.SPL (Spell Thrust)
  See([EVILCUTOFF])
  !StateCheck(LastSeenBy(Myself),STATE_NOT_VISIBLE)
  !ImmuneToSpellLevel(LastSeenBy(Myself),3)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
  CheckSpellState(LastSeenBy(Myself),SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),GREATER_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !CheckSpellState(Myself,GLOBE)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_SPELL_THRUST)  // SPWI321.SPL (Spell Thrust)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  HaveSpell(WIZARD_SPELL_THRUST)  // SPWI321.SPL (Spell Thrust)
  See(SecondNearest([EVILCUTOFF]))
  !StateCheck(LastSeenBy(Myself),STATE_NOT_VISIBLE)
  !ImmuneToSpellLevel(LastSeenBy(Myself),3)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
  CheckSpellState(LastSeenBy(Myself),SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),GREATER_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !CheckSpellState(Myself,GLOBE)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_SPELL_THRUST)  // SPWI321.SPL (Spell Thrust)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  HaveSpell(WIZARD_SPELL_THRUST)  // SPWI321.SPL (Spell Thrust)
  See(ThirdNearest([EVILCUTOFF]))
  !StateCheck(LastSeenBy(Myself),STATE_NOT_VISIBLE)
  !ImmuneToSpellLevel(LastSeenBy(Myself),3)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
  CheckSpellState(LastSeenBy(Myself),SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),GREATER_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !CheckSpellState(Myself,GLOBE)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_SPELL_THRUST)  // SPWI321.SPL (Spell Thrust)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  HaveSpell(WIZARD_SPELL_THRUST)  // SPWI321.SPL (Spell Thrust)
  See(FourthNearest([EVILCUTOFF]))
  !StateCheck(LastSeenBy(Myself),STATE_NOT_VISIBLE)
  !ImmuneToSpellLevel(LastSeenBy(Myself),3)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
  CheckSpellState(LastSeenBy(Myself),SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),GREATER_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !CheckSpellState(Myself,GLOBE)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_SPELL_THRUST)  // SPWI321.SPL (Spell Thrust)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  HaveSpell(WIZARD_SPELL_THRUST)  // SPWI321.SPL (Spell Thrust)
  See(FifthNearest([EVILCUTOFF]))
  !StateCheck(LastSeenBy(Myself),STATE_NOT_VISIBLE)
  !ImmuneToSpellLevel(LastSeenBy(Myself),3)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
  CheckSpellState(LastSeenBy(Myself),SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),GREATER_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !CheckSpellState(Myself,GLOBE)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_SPELL_THRUST)  // SPWI321.SPL (Spell Thrust)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  HaveSpell(WIZARD_SPELL_THRUST)  // SPWI321.SPL (Spell Thrust)
  See(SixthNearest([EVILCUTOFF]))
  !StateCheck(LastSeenBy(Myself),STATE_NOT_VISIBLE)
  !ImmuneToSpellLevel(LastSeenBy(Myself),3)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
  CheckSpellState(LastSeenBy(Myself),SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),GREATER_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !CheckSpellState(Myself,GLOBE)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_SPELL_THRUST)  // SPWI321.SPL (Spell Thrust)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  HaveSpell(WIZARD_SECRET_WORD)  // SPWI419.SPL (Secret Word)
  See([EVILCUTOFF])
  !StateCheck(LastSeenBy(Myself),STATE_NOT_VISIBLE)
  !ImmuneToSpellLevel(LastSeenBy(Myself),4)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),GLOBE)
    CheckSpellState(LastSeenBy(Myself),SPELL_DEFLECTION)
    CheckSpellState(LastSeenBy(Myself),GREATER_SPELL_DEFLECTION)
    CheckStatGT(LastSeenBy(Myself),0,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_SECRET_WORD)  // SPWI419.SPL (Secret Word)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  HaveSpell(WIZARD_SECRET_WORD)  // SPWI419.SPL (Secret Word)
  See(SecondNearest([EVILCUTOFF]))
  !StateCheck(LastSeenBy(Myself),STATE_NOT_VISIBLE)
  !ImmuneToSpellLevel(LastSeenBy(Myself),4)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),GLOBE)
    CheckSpellState(LastSeenBy(Myself),SPELL_DEFLECTION)
    CheckSpellState(LastSeenBy(Myself),GREATER_SPELL_DEFLECTION)
    CheckStatGT(LastSeenBy(Myself),0,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_SECRET_WORD)  // SPWI419.SPL (Secret Word)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  HaveSpell(WIZARD_SECRET_WORD)  // SPWI419.SPL (Secret Word)
  See(ThirdNearest([EVILCUTOFF]))
  !StateCheck(LastSeenBy(Myself),STATE_NOT_VISIBLE)
  !ImmuneToSpellLevel(LastSeenBy(Myself),4)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),GLOBE)
    CheckSpellState(LastSeenBy(Myself),SPELL_DEFLECTION)
    CheckSpellState(LastSeenBy(Myself),GREATER_SPELL_DEFLECTION)
    CheckStatGT(LastSeenBy(Myself),0,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_SECRET_WORD)  // SPWI419.SPL (Secret Word)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  HaveSpell(WIZARD_SECRET_WORD)  // SPWI419.SPL (Secret Word)
  See(FourthNearest([EVILCUTOFF]))
  !StateCheck(LastSeenBy(Myself),STATE_NOT_VISIBLE)
  !ImmuneToSpellLevel(LastSeenBy(Myself),4)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),GLOBE)
    CheckSpellState(LastSeenBy(Myself),SPELL_DEFLECTION)
    CheckSpellState(LastSeenBy(Myself),GREATER_SPELL_DEFLECTION)
    CheckStatGT(LastSeenBy(Myself),0,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_SECRET_WORD)  // SPWI419.SPL (Secret Word)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  HaveSpell(WIZARD_SECRET_WORD)  // SPWI419.SPL (Secret Word)
  See(FifthNearest([EVILCUTOFF]))
  !StateCheck(LastSeenBy(Myself),STATE_NOT_VISIBLE)
  !ImmuneToSpellLevel(LastSeenBy(Myself),4)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),GLOBE)
    CheckSpellState(LastSeenBy(Myself),SPELL_DEFLECTION)
    CheckSpellState(LastSeenBy(Myself),GREATER_SPELL_DEFLECTION)
    CheckStatGT(LastSeenBy(Myself),0,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_SECRET_WORD)  // SPWI419.SPL (Secret Word)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  HaveSpell(WIZARD_SECRET_WORD)  // SPWI419.SPL (Secret Word)
  See(SixthNearest([EVILCUTOFF]))
  !StateCheck(LastSeenBy(Myself),STATE_NOT_VISIBLE)
  !ImmuneToSpellLevel(LastSeenBy(Myself),4)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),GLOBE)
    CheckSpellState(LastSeenBy(Myself),SPELL_DEFLECTION)
    CheckSpellState(LastSeenBy(Myself),GREATER_SPELL_DEFLECTION)
    CheckStatGT(LastSeenBy(Myself),0,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_SECRET_WORD)  // SPWI419.SPL (Secret Word)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  HaveSpell(WIZARD_PIERCE_MAGIC)  // SPWI608.SPL (Pierce Magic)
  See([EVILCUTOFF])
  !StateCheck(LastSeenBy(Myself),STATE_NOT_VISIBLE)
  !ImmuneToSpellLevel(LastSeenBy(Myself),6)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),GLOBE)
    CheckSpellState(LastSeenBy(Myself),SPELL_DEFLECTION)
    CheckSpellState(LastSeenBy(Myself),GREATER_SPELL_DEFLECTION)
    CheckStatGT(LastSeenBy(Myself),0,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_PIERCE_MAGIC)  // SPWI608.SPL (Pierce Magic)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  HaveSpell(WIZARD_PIERCE_MAGIC)  // SPWI608.SPL (Pierce Magic)
  See(SecondNearest([EVILCUTOFF]))
  !StateCheck(LastSeenBy(Myself),STATE_NOT_VISIBLE)
  !ImmuneToSpellLevel(LastSeenBy(Myself),6)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),GLOBE)
    CheckSpellState(LastSeenBy(Myself),SPELL_DEFLECTION)
    CheckSpellState(LastSeenBy(Myself),GREATER_SPELL_DEFLECTION)
    CheckStatGT(LastSeenBy(Myself),0,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_PIERCE_MAGIC)  // SPWI608.SPL (Pierce Magic)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  HaveSpell(WIZARD_PIERCE_MAGIC)  // SPWI608.SPL (Pierce Magic)
  See(ThirdNearest([EVILCUTOFF]))
  !StateCheck(LastSeenBy(Myself),STATE_NOT_VISIBLE)
  !ImmuneToSpellLevel(LastSeenBy(Myself),6)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),GLOBE)
    CheckSpellState(LastSeenBy(Myself),SPELL_DEFLECTION)
    CheckSpellState(LastSeenBy(Myself),GREATER_SPELL_DEFLECTION)
    CheckStatGT(LastSeenBy(Myself),0,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_PIERCE_MAGIC)  // SPWI608.SPL (Pierce Magic)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  HaveSpell(WIZARD_PIERCE_MAGIC)  // SPWI608.SPL (Pierce Magic)
  See(FourthNearest([EVILCUTOFF]))
  !StateCheck(LastSeenBy(Myself),STATE_NOT_VISIBLE)
  !ImmuneToSpellLevel(LastSeenBy(Myself),6)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),GLOBE)
    CheckSpellState(LastSeenBy(Myself),SPELL_DEFLECTION)
    CheckSpellState(LastSeenBy(Myself),GREATER_SPELL_DEFLECTION)
    CheckStatGT(LastSeenBy(Myself),0,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_PIERCE_MAGIC)  // SPWI608.SPL (Pierce Magic)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  HaveSpell(WIZARD_PIERCE_MAGIC)  // SPWI608.SPL (Pierce Magic)
  See(FifthNearest([EVILCUTOFF]))
  !StateCheck(LastSeenBy(Myself),STATE_NOT_VISIBLE)
  !ImmuneToSpellLevel(LastSeenBy(Myself),6)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),GLOBE)
    CheckSpellState(LastSeenBy(Myself),SPELL_DEFLECTION)
    CheckSpellState(LastSeenBy(Myself),GREATER_SPELL_DEFLECTION)
    CheckStatGT(LastSeenBy(Myself),0,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_PIERCE_MAGIC)  // SPWI608.SPL (Pierce Magic)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  HaveSpell(WIZARD_PIERCE_MAGIC)  // SPWI608.SPL (Pierce Magic)
  See(SixthNearest([EVILCUTOFF]))
  !StateCheck(LastSeenBy(Myself),STATE_NOT_VISIBLE)
  !ImmuneToSpellLevel(LastSeenBy(Myself),6)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),GLOBE)
    CheckSpellState(LastSeenBy(Myself),SPELL_DEFLECTION)
    CheckSpellState(LastSeenBy(Myself),GREATER_SPELL_DEFLECTION)
    CheckStatGT(LastSeenBy(Myself),0,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_PIERCE_MAGIC)  // SPWI608.SPL (Pierce Magic)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  HaveSpell(WIZARD_WARDING_WHIP)  // SPWI705.SPL (Khelben's Warding Whip)
  See([EVILCUTOFF])
  !StateCheck(LastSeenBy(Myself),STATE_NOT_VISIBLE)
  !ImmuneToSpellLevel(LastSeenBy(Myself),7)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_KHELBANS_WARDING_WHIP)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),GLOBE)
    CheckSpellState(LastSeenBy(Myself),SPELL_DEFLECTION)
    CheckSpellState(LastSeenBy(Myself),GREATER_SPELL_DEFLECTION)
    CheckStatGT(LastSeenBy(Myself),0,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_WARDING_WHIP)  // SPWI705.SPL (Khelben's Warding Whip)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  HaveSpell(WIZARD_WARDING_WHIP)  // SPWI705.SPL (Khelben's Warding Whip)
  See(SecondNearest([EVILCUTOFF]))
  !StateCheck(LastSeenBy(Myself),STATE_NOT_VISIBLE)
  !ImmuneToSpellLevel(LastSeenBy(Myself),7)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_KHELBANS_WARDING_WHIP)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),GLOBE)
    CheckSpellState(LastSeenBy(Myself),SPELL_DEFLECTION)
    CheckSpellState(LastSeenBy(Myself),GREATER_SPELL_DEFLECTION)
    CheckStatGT(LastSeenBy(Myself),0,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_WARDING_WHIP)  // SPWI705.SPL (Khelben's Warding Whip)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  HaveSpell(WIZARD_WARDING_WHIP)  // SPWI705.SPL (Khelben's Warding Whip)
  See(ThirdNearest([EVILCUTOFF]))
  !StateCheck(LastSeenBy(Myself),STATE_NOT_VISIBLE)
  !ImmuneToSpellLevel(LastSeenBy(Myself),7)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_KHELBANS_WARDING_WHIP)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),GLOBE)
    CheckSpellState(LastSeenBy(Myself),SPELL_DEFLECTION)
    CheckSpellState(LastSeenBy(Myself),GREATER_SPELL_DEFLECTION)
    CheckStatGT(LastSeenBy(Myself),0,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_WARDING_WHIP)  // SPWI705.SPL (Khelben's Warding Whip)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  HaveSpell(WIZARD_WARDING_WHIP)  // SPWI705.SPL (Khelben's Warding Whip)
  See(FourthNearest([EVILCUTOFF]))
  !StateCheck(LastSeenBy(Myself),STATE_NOT_VISIBLE)
  !ImmuneToSpellLevel(LastSeenBy(Myself),7)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_KHELBANS_WARDING_WHIP)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),GLOBE)
    CheckSpellState(LastSeenBy(Myself),SPELL_DEFLECTION)
    CheckSpellState(LastSeenBy(Myself),GREATER_SPELL_DEFLECTION)
    CheckStatGT(LastSeenBy(Myself),0,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_WARDING_WHIP)  // SPWI705.SPL (Khelben's Warding Whip)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  HaveSpell(WIZARD_WARDING_WHIP)  // SPWI705.SPL (Khelben's Warding Whip)
  See(FifthNearest([EVILCUTOFF]))
  !StateCheck(LastSeenBy(Myself),STATE_NOT_VISIBLE)
  !ImmuneToSpellLevel(LastSeenBy(Myself),7)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_KHELBANS_WARDING_WHIP)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),GLOBE)
    CheckSpellState(LastSeenBy(Myself),SPELL_DEFLECTION)
    CheckSpellState(LastSeenBy(Myself),GREATER_SPELL_DEFLECTION)
    CheckStatGT(LastSeenBy(Myself),0,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_WARDING_WHIP)  // SPWI705.SPL (Khelben's Warding Whip)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  HaveSpell(WIZARD_WARDING_WHIP)  // SPWI705.SPL (Khelben's Warding Whip)
  See(SixthNearest([EVILCUTOFF]))
  !StateCheck(LastSeenBy(Myself),STATE_NOT_VISIBLE)
  !ImmuneToSpellLevel(LastSeenBy(Myself),7)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_KHELBANS_WARDING_WHIP)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),GLOBE)
    CheckSpellState(LastSeenBy(Myself),SPELL_DEFLECTION)
    CheckSpellState(LastSeenBy(Myself),GREATER_SPELL_DEFLECTION)
    CheckStatGT(LastSeenBy(Myself),0,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_WARDING_WHIP)  // SPWI705.SPL (Khelben's Warding Whip)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  HaveSpell(WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
  See([EVILCUTOFF])
  !StateCheck(LastSeenBy(Myself),STATE_NOT_VISIBLE)
  !ImmuneToSpellLevel(LastSeenBy(Myself),7)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
  OR(5)
    CheckSpellState(LastSeenBy(Myself),GLOBE)
    CheckSpellState(LastSeenBy(Myself),SPELL_DEFLECTION)
    CheckSpellState(LastSeenBy(Myself),GREATER_SPELL_DEFLECTION)
    CheckStatGT(LastSeenBy(Myself),0,CLERIC_SHIELD_OF_THE_ARCHONS)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  HaveSpell(WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
  See(SecondNearest([EVILCUTOFF]))
  !StateCheck(LastSeenBy(Myself),STATE_NOT_VISIBLE)
  !ImmuneToSpellLevel(LastSeenBy(Myself),7)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
  OR(5)
    CheckSpellState(LastSeenBy(Myself),GLOBE)
    CheckSpellState(LastSeenBy(Myself),SPELL_DEFLECTION)
    CheckSpellState(LastSeenBy(Myself),GREATER_SPELL_DEFLECTION)
    CheckStatGT(LastSeenBy(Myself),0,CLERIC_SHIELD_OF_THE_ARCHONS)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  HaveSpell(WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
  See(ThirdNearest([EVILCUTOFF]))
  !StateCheck(LastSeenBy(Myself),STATE_NOT_VISIBLE)
  !ImmuneToSpellLevel(LastSeenBy(Myself),7)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
  OR(5)
    CheckSpellState(LastSeenBy(Myself),GLOBE)
    CheckSpellState(LastSeenBy(Myself),SPELL_DEFLECTION)
    CheckSpellState(LastSeenBy(Myself),GREATER_SPELL_DEFLECTION)
    CheckStatGT(LastSeenBy(Myself),0,CLERIC_SHIELD_OF_THE_ARCHONS)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  HaveSpell(WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
  See(FourthNearest([EVILCUTOFF]))
  !StateCheck(LastSeenBy(Myself),STATE_NOT_VISIBLE)
  !ImmuneToSpellLevel(LastSeenBy(Myself),7)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
  OR(5)
    CheckSpellState(LastSeenBy(Myself),GLOBE)
    CheckSpellState(LastSeenBy(Myself),SPELL_DEFLECTION)
    CheckSpellState(LastSeenBy(Myself),GREATER_SPELL_DEFLECTION)
    CheckStatGT(LastSeenBy(Myself),0,CLERIC_SHIELD_OF_THE_ARCHONS)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  HaveSpell(WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
  See(FifthNearest([EVILCUTOFF]))
  !StateCheck(LastSeenBy(Myself),STATE_NOT_VISIBLE)
  !ImmuneToSpellLevel(LastSeenBy(Myself),7)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
  OR(5)
    CheckSpellState(LastSeenBy(Myself),GLOBE)
    CheckSpellState(LastSeenBy(Myself),SPELL_DEFLECTION)
    CheckSpellState(LastSeenBy(Myself),GREATER_SPELL_DEFLECTION)
    CheckStatGT(LastSeenBy(Myself),0,CLERIC_SHIELD_OF_THE_ARCHONS)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  HaveSpell(WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
  See(SixthNearest([EVILCUTOFF]))
  !StateCheck(LastSeenBy(Myself),STATE_NOT_VISIBLE)
  !ImmuneToSpellLevel(LastSeenBy(Myself),7)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
  OR(5)
    CheckSpellState(LastSeenBy(Myself),GLOBE)
    CheckSpellState(LastSeenBy(Myself),SPELL_DEFLECTION)
    CheckSpellState(LastSeenBy(Myself),GREATER_SPELL_DEFLECTION)
    CheckStatGT(LastSeenBy(Myself),0,CLERIC_SHIELD_OF_THE_ARCHONS)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  HaveSpell(WIZARD_SPELL_STRIKE)  // SPWI903.SPL (Spellstrike)
  See([EVILCUTOFF])
  !StateCheck(LastSeenBy(Myself),STATE_NOT_VISIBLE)
  !ImmuneToSpellLevel(LastSeenBy(Myself),9)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
  OR(5)
    CheckSpellState(LastSeenBy(Myself),GLOBE)
    CheckSpellState(LastSeenBy(Myself),SPELL_DEFLECTION)
    CheckSpellState(LastSeenBy(Myself),GREATER_SPELL_DEFLECTION)
    CheckStatGT(LastSeenBy(Myself),0,CLERIC_SHIELD_OF_THE_ARCHONS)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_SPELL_STRIKE)  // SPWI903.SPL (Spellstrike)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  HaveSpell(WIZARD_SPELL_STRIKE)  // SPWI903.SPL (Spellstrike)
  See(SecondNearest([EVILCUTOFF]))
  !StateCheck(LastSeenBy(Myself),STATE_NOT_VISIBLE)
  !ImmuneToSpellLevel(LastSeenBy(Myself),9)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
  OR(5)
    CheckSpellState(LastSeenBy(Myself),GLOBE)
    CheckSpellState(LastSeenBy(Myself),SPELL_DEFLECTION)
    CheckSpellState(LastSeenBy(Myself),GREATER_SPELL_DEFLECTION)
    CheckStatGT(LastSeenBy(Myself),0,CLERIC_SHIELD_OF_THE_ARCHONS)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_SPELL_STRIKE)  // SPWI903.SPL (Spellstrike)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  HaveSpell(WIZARD_SPELL_STRIKE)  // SPWI903.SPL (Spellstrike)
  See(ThirdNearest([EVILCUTOFF]))
  !StateCheck(LastSeenBy(Myself),STATE_NOT_VISIBLE)
  !ImmuneToSpellLevel(LastSeenBy(Myself),9)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
  OR(5)
    CheckSpellState(LastSeenBy(Myself),GLOBE)
    CheckSpellState(LastSeenBy(Myself),SPELL_DEFLECTION)
    CheckSpellState(LastSeenBy(Myself),GREATER_SPELL_DEFLECTION)
    CheckStatGT(LastSeenBy(Myself),0,CLERIC_SHIELD_OF_THE_ARCHONS)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_SPELL_STRIKE)  // SPWI903.SPL (Spellstrike)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  HaveSpell(WIZARD_SPELL_STRIKE)  // SPWI903.SPL (Spellstrike)
  See(FourthNearest([EVILCUTOFF]))
  !StateCheck(LastSeenBy(Myself),STATE_NOT_VISIBLE)
  !ImmuneToSpellLevel(LastSeenBy(Myself),9)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
  OR(5)
    CheckSpellState(LastSeenBy(Myself),GLOBE)
    CheckSpellState(LastSeenBy(Myself),SPELL_DEFLECTION)
    CheckSpellState(LastSeenBy(Myself),GREATER_SPELL_DEFLECTION)
    CheckStatGT(LastSeenBy(Myself),0,CLERIC_SHIELD_OF_THE_ARCHONS)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_SPELL_STRIKE)  // SPWI903.SPL (Spellstrike)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  HaveSpell(WIZARD_SPELL_STRIKE)  // SPWI903.SPL (Spellstrike)
  See(FifthNearest([EVILCUTOFF]))
  !StateCheck(LastSeenBy(Myself),STATE_NOT_VISIBLE)
  !ImmuneToSpellLevel(LastSeenBy(Myself),9)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
  OR(5)
    CheckSpellState(LastSeenBy(Myself),GLOBE)
    CheckSpellState(LastSeenBy(Myself),SPELL_DEFLECTION)
    CheckSpellState(LastSeenBy(Myself),GREATER_SPELL_DEFLECTION)
    CheckStatGT(LastSeenBy(Myself),0,CLERIC_SHIELD_OF_THE_ARCHONS)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_SPELL_STRIKE)  // SPWI903.SPL (Spellstrike)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  HaveSpell(WIZARD_SPELL_STRIKE)  // SPWI903.SPL (Spellstrike)
  See(SixthNearest([EVILCUTOFF]))
  !StateCheck(LastSeenBy(Myself),STATE_NOT_VISIBLE)
  !ImmuneToSpellLevel(LastSeenBy(Myself),9)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
  OR(5)
    CheckSpellState(LastSeenBy(Myself),GLOBE)
    CheckSpellState(LastSeenBy(Myself),SPELL_DEFLECTION)
    CheckSpellState(LastSeenBy(Myself),GREATER_SPELL_DEFLECTION)
    CheckStatGT(LastSeenBy(Myself),0,CLERIC_SHIELD_OF_THE_ARCHONS)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_SPELL_STRIKE)  // SPWI903.SPL (Spellstrike)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  HaveSpell(WIZARD_PIERCE_SHIELD)  // SPWI805.SPL (Pierce Shield)
  See([EVILCUTOFF])
  !StateCheck(LastSeenBy(Myself),STATE_NOT_VISIBLE)
  !ImmuneToSpellLevel(LastSeenBy(Myself),8)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_PIERCE_SHIELD)  // SPWI805.SPL (Pierce Shield)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  HaveSpell(WIZARD_PIERCE_SHIELD)  // SPWI805.SPL (Pierce Shield)
  See(SecondNearest([EVILCUTOFF]))
  !StateCheck(LastSeenBy(Myself),STATE_NOT_VISIBLE)
  !ImmuneToSpellLevel(LastSeenBy(Myself),8)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_PIERCE_SHIELD)  // SPWI805.SPL (Pierce Shield)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  HaveSpell(WIZARD_PIERCE_SHIELD)  // SPWI805.SPL (Pierce Shield)
  See(ThirdNearest([EVILCUTOFF]))
  !StateCheck(LastSeenBy(Myself),STATE_NOT_VISIBLE)
  !ImmuneToSpellLevel(LastSeenBy(Myself),8)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_PIERCE_SHIELD)  // SPWI805.SPL (Pierce Shield)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  HaveSpell(WIZARD_PIERCE_SHIELD)  // SPWI805.SPL (Pierce Shield)
  See(FourthNearest([EVILCUTOFF]))
  !StateCheck(LastSeenBy(Myself),STATE_NOT_VISIBLE)
  !ImmuneToSpellLevel(LastSeenBy(Myself),8)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_PIERCE_SHIELD)  // SPWI805.SPL (Pierce Shield)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  HaveSpell(WIZARD_PIERCE_SHIELD)  // SPWI805.SPL (Pierce Shield)
  See(FifthNearest([EVILCUTOFF]))
  !StateCheck(LastSeenBy(Myself),STATE_NOT_VISIBLE)
  !ImmuneToSpellLevel(LastSeenBy(Myself),8)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_PIERCE_SHIELD)  // SPWI805.SPL (Pierce Shield)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  HaveSpell(WIZARD_PIERCE_SHIELD)  // SPWI805.SPL (Pierce Shield)
  See(SixthNearest([EVILCUTOFF]))
  !StateCheck(LastSeenBy(Myself),STATE_NOT_VISIBLE)
  !ImmuneToSpellLevel(LastSeenBy(Myself),8)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_PIERCE_SHIELD)  // SPWI805.SPL (Pierce Shield)
    SetInterrupt(TRUE)
END

IF
  ActionListEmpty()
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  OR(17)
    Range([EVILCUTOFF.0.FAIRY],30)
    Range([EVILCUTOFF.0.DEMONIC],30)
    Range([EVILCUTOFF.0.RAKSHASA],30)
    Range([EVILCUTOFF.0.DRAGON],30)
    Range([EVILCUTOFF.0.DEMILICH],30)
    Range([EVILCUTOFF.0.LICH],30)
    Range([EVILCUTOFF.0.SOLAR],30)
    Range([EVILCUTOFF.0.PLANATAR],30)
    Range([EVILCUTOFF.0.ANTISOLAR],30)
    Range([EVILCUTOFF.0.DARKPLANATAR],30)
    See([ENEMY.0.0.MAGE_ALL])
    See([ENEMY.0.0.BARD_ALL])
    See([ENEMY.0.0.CLERIC_ALL])
    See([ENEMY.0.0.DRUID_ALL])
    See([ENEMY.0.0.SORCERER])
    See([ENEMY.0.0.CLERIC_MAGE])
    See([ENEMY.0.0.MAGE_ALL])
  HaveSpell(WIZARD_SPELL_SHIELD)  // SPWI519.SPL (Spell Shield)
  !CheckSpellState(Myself,SPELL_SHIELD)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_SPELL_SHIELD)  // SPWI519.SPL (Spell Shield)
    SetInterrupt(TRUE)
END

IF
  ActionListEmpty()
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  OR(17)
    Range([EVILCUTOFF.0.FAIRY],30)
    Range([EVILCUTOFF.0.DEMONIC],30)
    Range([EVILCUTOFF.0.RAKSHASA],30)
    Range([EVILCUTOFF.0.DRAGON],30)
    Range([EVILCUTOFF.0.DEMILICH],30)
    Range([EVILCUTOFF.0.LICH],30)
    Range([EVILCUTOFF.0.SOLAR],30)
    Range([EVILCUTOFF.0.PLANATAR],30)
    Range([EVILCUTOFF.0.ANTISOLAR],30)
    Range([EVILCUTOFF.0.DARKPLANATAR],30)
    See([ENEMY.0.0.MAGE_ALL])
    See([ENEMY.0.0.BARD_ALL])
    See([ENEMY.0.0.CLERIC_ALL])
    See([ENEMY.0.0.DRUID_ALL])
    See([ENEMY.0.0.SORCERER])
    See([ENEMY.0.0.CLERIC_MAGE])
    See([ENEMY.0.0.MAGE_ALL])
  HaveSpell(WIZARD_SPELL_TRAP)  // SPWI902.SPL (Spell Trap)
  CheckStatLT(Myself,1,WIZARD_SPELL_TRAP)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_SPELL_TRAP)  // SPWI902.SPL (Spell Trap)
    SetInterrupt(TRUE)
END

IF
  ActionListEmpty()
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  OR(17)
    Range([EVILCUTOFF.0.FAIRY],30)
    Range([EVILCUTOFF.0.DEMONIC],30)
    Range([EVILCUTOFF.0.RAKSHASA],30)
    Range([EVILCUTOFF.0.DRAGON],30)
    Range([EVILCUTOFF.0.DEMILICH],30)
    Range([EVILCUTOFF.0.LICH],30)
    Range([EVILCUTOFF.0.SOLAR],30)
    Range([EVILCUTOFF.0.PLANATAR],30)
    Range([EVILCUTOFF.0.ANTISOLAR],30)
    Range([EVILCUTOFF.0.DARKPLANATAR],30)
    See([ENEMY.0.0.MAGE_ALL])
    See([ENEMY.0.0.BARD_ALL])
    See([ENEMY.0.0.CLERIC_ALL])
    See([ENEMY.0.0.DRUID_ALL])
    See([ENEMY.0.0.SORCERER])
    See([ENEMY.0.0.CLERIC_MAGE])
    See([ENEMY.0.0.MAGE_ALL])
  HaveSpell(WIZARD_GREATER_SPELL_DEFLECTION)  // SPWI701.SPL (Greater Spell Deflection)
  !CheckSpellState(Myself,GREATER_SPELL_DEFLECTION)
  !CheckSpellState(Myself,SPELL_DEFLECTION)
  !CheckSpellState(Myself,MINOR_SPELL_DEFLECTION)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_GREATER_SPELL_DEFLECTION)  // SPWI701.SPL (Greater Spell Deflection)
    SetInterrupt(TRUE)
END

IF
  ActionListEmpty()
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  OR(17)
    Range([EVILCUTOFF.0.FAIRY],30)
    Range([EVILCUTOFF.0.DEMONIC],30)
    Range([EVILCUTOFF.0.RAKSHASA],30)
    Range([EVILCUTOFF.0.DRAGON],30)
    Range([EVILCUTOFF.0.DEMILICH],30)
    Range([EVILCUTOFF.0.LICH],30)
    Range([EVILCUTOFF.0.SOLAR],30)
    Range([EVILCUTOFF.0.PLANATAR],30)
    Range([EVILCUTOFF.0.ANTISOLAR],30)
    Range([EVILCUTOFF.0.DARKPLANATAR],30)
    See([ENEMY.0.0.MAGE_ALL])
    See([ENEMY.0.0.BARD_ALL])
    See([ENEMY.0.0.CLERIC_ALL])
    See([ENEMY.0.0.DRUID_ALL])
    See([ENEMY.0.0.SORCERER])
    See([ENEMY.0.0.CLERIC_MAGE])
    See([ENEMY.0.0.MAGE_ALL])
  HaveSpell(WIZARD_SPELL_DEFLECTION)  // SPWI522.SPL (Spell Deflection)
  !CheckSpellState(Myself,GREATER_SPELL_DEFLECTION)
  !CheckSpellState(Myself,SPELL_DEFLECTION)
  !CheckSpellState(Myself,MINOR_SPELL_DEFLECTION)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_SPELL_DEFLECTION)  // SPWI522.SPL (Spell Deflection)
    SetInterrupt(TRUE)
END

IF
  ActionListEmpty()
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  OR(17)
    Range([EVILCUTOFF.0.FAIRY],30)
    Range([EVILCUTOFF.0.DEMONIC],30)
    Range([EVILCUTOFF.0.RAKSHASA],30)
    Range([EVILCUTOFF.0.DRAGON],30)
    Range([EVILCUTOFF.0.DEMILICH],30)
    Range([EVILCUTOFF.0.LICH],30)
    Range([EVILCUTOFF.0.SOLAR],30)
    Range([EVILCUTOFF.0.PLANATAR],30)
    Range([EVILCUTOFF.0.ANTISOLAR],30)
    Range([EVILCUTOFF.0.DARKPLANATAR],30)
    See([ENEMY.0.0.MAGE_ALL])
    See([ENEMY.0.0.BARD_ALL])
    See([ENEMY.0.0.CLERIC_ALL])
    See([ENEMY.0.0.DRUID_ALL])
    See([ENEMY.0.0.SORCERER])
    See([ENEMY.0.0.CLERIC_MAGE])
    See([ENEMY.0.0.MAGE_ALL])
  HaveSpell(WIZARD_MINOR_SPELL_DEFLECTION)  // SPWI318.SPL (Minor Spell Deflection)
  !CheckSpellState(Myself,GREATER_SPELL_DEFLECTION)
  !CheckSpellState(Myself,SPELL_DEFLECTION)
  !CheckSpellState(Myself,MINOR_SPELL_DEFLECTION)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_MINOR_SPELL_DEFLECTION)  // SPWI318.SPL (Minor Spell Deflection)
    SetInterrupt(TRUE)
END

IF
  ActionListEmpty()
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  HaveSpell(WIZARD_MESTILS_ACID_SHEATH)  // SPWI524.spl (Mestil's Acid Sheath)
  See([EVILCUTOFF])
  OR(19)
    NumCreatureGT([EVILCUTOFF],3)
    Range([EVILCUTOFF.0.KUO-TOA],30)
    Range([EVILCUTOFF.0.GENIE],30)
    Range([EVILCUTOFF.0.GITHYANKI],30)
    Range([EVILCUTOFF.0.RAKSHASA],30)
    Range([EVILCUTOFF.0.VAMPYRE],30)
    Range([EVILCUTOFF.0.MIND_FLAYER],30)
    Range([EVILCUTOFF.0.DRAGON],30)
    Range([EVILCUTOFF.0.DEMONIC],30)
    Range([EVILCUTOFF.0.BEHOLDER],30)
    Range([EVILCUTOFF.0.VAMPIRE],30)
    Range([EVILCUTOFF.0.LICH],30)
    Range([EVILCUTOFF.0.DEMILICH],30)
    Range([EVILCUTOFF.0.LICH],30)
    Range([EVILCUTOFF.0.SOLAR],30)
    Range([EVILCUTOFF.0.PLANATAR],30)
    Range([EVILCUTOFF.0.ANTISOLAR],30)
    Range([EVILCUTOFF.0.DARKPLANATAR],30)
    See([ENEMY.0.0.DRUID_ALL])
  !CheckSpellState(Myself,RED_FIRESHIELD)
  !CheckSpellState(Myself,ACID_SHEATH)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_MESTILS_ACID_SHEATH)  // SPWI524.spl (Mestil's Acid Sheath)
    SetInterrupt(TRUE)
END

IF
  ActionListEmpty()
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  HaveSpell(WIZARD_FIRE_SHIELD_RED)  // SPWI418.SPL (Fire Shield)
  See([EVILCUTOFF])
  OR(19)
    NumCreatureGT([EVILCUTOFF],3)
    Range([EVILCUTOFF.0.KUO-TOA],30)
    Range([EVILCUTOFF.0.GENIE],30)
    Range([EVILCUTOFF.0.GITHYANKI],30)
    Range([EVILCUTOFF.0.RAKSHASA],30)
    Range([EVILCUTOFF.0.VAMPYRE],30)
    Range([EVILCUTOFF.0.MIND_FLAYER],30)
    Range([EVILCUTOFF.0.DRAGON],30)
    Range([EVILCUTOFF.0.DEMONIC],30)
    Range([EVILCUTOFF.0.BEHOLDER],30)
    Range([EVILCUTOFF.0.VAMPIRE],30)
    Range([EVILCUTOFF.0.LICH],30)
    Range([EVILCUTOFF.0.DEMILICH],30)
    Range([EVILCUTOFF.0.LICH],30)
    Range([EVILCUTOFF.0.SOLAR],30)
    Range([EVILCUTOFF.0.PLANATAR],30)
    Range([EVILCUTOFF.0.ANTISOLAR],30)
    Range([EVILCUTOFF.0.DARKPLANATAR],30)
    See([ENEMY.0.0.DRUID_ALL])
  !CheckSpellState(Myself,RED_FIRESHIELD)
  !CheckSpellState(Myself,ACID_SHEATH)
  !CheckSpellState(Myself,GLOBE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_FIRE_SHIELD_RED)  // SPWI418.SPL (Fire Shield)
    SetInterrupt(TRUE)
END

IF
  ActionListEmpty()
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  HaveSpell(WIZARD_PROTECTION_FROM_NORMAL_MISSILES)  // SPWI311.SPL (Protection from Missiles)
  OR(11)
    HitBy([ANYONE],MISSILE)
    IsWeaponRanged(NearestEnemyOf(Myself))
    IsWeaponRanged(SecondNearestEnemyOf(Myself))
    IsWeaponRanged(ThirdNearestEnemyOf(Myself))
    IsWeaponRanged(FourthNearestEnemyOf(Myself))
    IsWeaponRanged(FifthNearestEnemyOf(Myself))
    IsWeaponRanged(SixthNearestEnemyOf(Myself))
    IsWeaponRanged(SeventhNearestEnemyOf(Myself))
    IsWeaponRanged(EighthNearestEnemyOf(Myself))
    IsWeaponRanged(NinthNearestEnemyOf(Myself))
    IsWeaponRanged(TenthNearestEnemyOf(Myself))
  !CheckSpellState(Myself,PROTECTION_FROM_NORMAL_MISSILES)
  !CheckSpellState(Myself,MINOR_GLOBE)
  !CheckSpellState(Myself,GLOBE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_PROTECTION_FROM_NORMAL_MISSILES)  // SPWI311.SPL (Protection from Missiles)
    SetInterrupt(TRUE)
END

IF
  ActionListEmpty()
  IfValidForPartyDialog(Myself)
  !StateCheck(Myself,STATE_MIRRORIMAGE)
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  HaveSpell(WIZARD_MIRROR_IMAGE)  // SPWI212.SPL (Mirror Image)
  See(NearestEnemyOf(Myself))
  NumCreatureGT([EVILCUTOFF],3)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(NearestEnemyOf(Myself),0,TRUE_SIGHT)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,TRUE_SIGHT)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,TRUE_SIGHT)
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,TRUE_SIGHT)
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,TRUE_SIGHT)
  !CheckStatGT(SeventhNearestEnemyOf(Myself),0,TRUE_SIGHT)
  !CheckStatGT(EighthNearestEnemyOf(Myself),0,TRUE_SIGHT)
  !CheckStatGT(NinthNearestEnemyOf(Myself),0,TRUE_SIGHT)
  !CheckStatGT(TenthNearestEnemyOf(Myself),0,TRUE_SIGHT)
  !CheckStatGT([EVILCUTOFF.0.PLANATAR],0,TRUE_SIGHT)
  !CheckStatGT([EVILCUTOFF.0.DARKPLANATAR],0,TRUE_SIGHT)
  !CheckStat(Myself,1,PUPPETTYPE)
  !CheckSpellState(Myself,MINOR_GLOBE)
  !CheckSpellState(Myself,GLOBE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_MIRROR_IMAGE)  // SPWI212.SPL (Mirror Image)
    SetInterrupt(TRUE)
END

IF
  ActionListEmpty()
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_BardActionTaken","LOCALS")
  HaveSpell(WIZARD_IMPROVED_HASTE)  // SPWI613.SPL (Improved Haste)
  !CheckStatGT(Myself,0,IMPROVEDHASTE)
  See([EVILCUTOFF])
  OR(6)
    WeaponEffectiveVs(NearestEnemyOf(Myself),MAINHAND)
    WeaponEffectiveVs(SecondNearestEnemyOf(Myself),MAINHAND)
    WeaponEffectiveVs(ThirdNearestEnemyOf(Myself),MAINHAND)
    WeaponEffectiveVs(FourthNearestEnemyOf(Myself),MAINHAND)
    WeaponEffectiveVs(FifthNearestEnemyOf(Myself),MAINHAND)
    WeaponEffectiveVs(SixthNearestEnemyOf(Myself),MAINHAND)
  OR(6)
    WeaponCanDamage(NearestEnemyOf(Myself),MAINHAND)
    WeaponCanDamage(SecondNearestEnemyOf(Myself),MAINHAND)
    WeaponCanDamage(ThirdNearestEnemyOf(Myself),MAINHAND)
    WeaponCanDamage(FourthNearestEnemyOf(Myself),MAINHAND)
    WeaponCanDamage(FifthNearestEnemyOf(Myself),MAINHAND)
    WeaponCanDamage(SixthNearestEnemyOf(Myself),MAINHAND)
  OR(34)
    NumCreatureGT([EVILCUTOFF],3)
    Range([EVILCUTOFF.0.GOLEM],30)
    Range([EVILCUTOFF.0.MIST],30)
    Range([EVILCUTOFF.0.KUO-TOA],30)
    Range([EVILCUTOFF.0.GENIE],30)
    Range([EVILCUTOFF.0.GITHYANKI],30)
    Range([EVILCUTOFF.0.RAKSHASA],30)
    Range([EVILCUTOFF.0.VAMPYRE],30)
    Range([EVILCUTOFF.0.MIND_FLAYER],30)
    Range([EVILCUTOFF.0.DRAGON],30)
    Range([EVILCUTOFF.0.DEMONIC],30)
    Range([EVILCUTOFF.0.BEHOLDER],30)
    Range([EVILCUTOFF.0.UMBERHULK],30)
    Range([EVILCUTOFF.0.MYCONID],30)
    Range([EVILCUTOFF.0.VAMPIRE],30)
    Range([EVILCUTOFF.0.LICH],30)
    Range([EVILCUTOFF.0.DEMILICH],30)
    Range([EVILCUTOFF.0.FAIRY],30)
    Range([EVILCUTOFF.0.0.WRAITH],30)
    Range([EVILCUTOFF.0.0.WIGHT],30)
    Range([EVILCUTOFF.0.0.SPECTRE],30)
    Range([EVILCUTOFF.0.0.WYVERN],30)
    Range([EVILCUTOFF.0.0.BASILISK],30)
    Range([EVILCUTOFF.0.LICH],30)
    Range([EVILCUTOFF.0.SOLAR],30)
    Range([EVILCUTOFF.0.PLANATAR],30)
    Range([EVILCUTOFF.0.ANTISOLAR],30)
    Range([EVILCUTOFF.0.DARKPLANATAR],30)
    See([ENEMY.0.0.MAGE_ALL])
    See([ENEMY.0.0.BARD_ALL])
    See([ENEMY.0.0.CLERIC_ALL])
    See([ENEMY.0.0.DRUID_ALL])
    See([ENEMY.0.0.SORCERER])
    See([ENEMY.0.0.CLERIC_MAGE])
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_BardActionTaken","LOCALS",TWO_ROUNDS)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_IMPROVED_HASTE)  // SPWI613.SPL (Improved Haste)
    SetInterrupt(TRUE)
END

IF
  Class(Myself,BARD_ALL)
  !ModalState(BATTLESONG)
THEN
  RESPONSE #100
    BattleSong()
END

