LOAD_TRA ~enhanced-powergaming-scripts/languages/%LANGUAGE%/script_dialog.tra~

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Add Mod Components to Accelerated Scripts                             //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// MO-Core Initial                                                       //
///////////////////////////////////////////////////////////////////////////
COPY ~enhanced-powergaming-scripts/baf/Accelerated/mocore.baf~  ~enhanced-powergaming-scripts/baf/upload/mocore.baf~
INCLUDE ~enhanced-powergaming-scripts/lib/IWDEE/prebuff_iwd_a.tph~

///////////////////////////////////////////////////////////////////////////
// Remove Dialog Hovertext from Scripts                                  //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF scp_dlg BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/ini/prebuff_dialog.tph~
	END

///////////////////////////////////////////////////////////////////////////
// Hotkey Setup                                                          //
///////////////////////////////////////////////////////////////////////////
INCLUDE ~enhanced-powergaming-scripts/lib/core_hotkey.tph~

///////////////////////////////////////////////////////////////////////////
// Removes Potion Use in Pre-Buffing                                     //
///////////////////////////////////////////////////////////////////////////
ACTION_IF pot_use BEGIN
	INCLUDE ~enhanced-powergaming-scripts/lib/ini/core_pot.tph~
END

///////////////////////////////////////////////////////////////////////////
// Build out MO-Core and MO-BasicAi                                      //
///////////////////////////////////////////////////////////////////////////
COPY ~enhanced-powergaming-scripts/baf/upload/mocore.baf~  ~enhanced-powergaming-scripts/baf/upload/mobasic.baf~

INCLUDE ~enhanced-powergaming-scripts/lib/basic_base.tph~
INCLUDE ~enhanced-powergaming-scripts/lib/core_base.tph~
INCLUDE ~enhanced-powergaming-scripts/lib/IWDEE/core_iwd.tph~

///////////////////////////////////////////////////////////////////////////
// Update ini Presets                                                    //
///////////////////////////////////////////////////////////////////////////
	// Basic AI will Auto-Attack Enemies
	ACTION_IF bsc_atk BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/ini/basic_atk.tph~
	END

	// Removes Dialog Hovertext from Scripts
	ACTION_IF scp_dlg BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/ini/core_dialog.tph~
	END

	// Basic AI will Auto-Heal
	ACTION_IF bsc_heal BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/ini/healing.tph~
		INCLUDE ~enhanced-powergaming-scripts/lib/iwdee/healing_iwd.tph~
	END

	// Add disabling spells
	ACTION_IF ds_spl BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/ini/disabling_spells.tph~
		INCLUDE ~enhanced-powergaming-scripts/lib/ini/remove_wight.tph~
	END

	// Add long duration spells to MO-BasicAI
	ACTION_IF bsc_lng_dur BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/ini/long_duration.tph~
		INCLUDE ~enhanced-powergaming-scripts/lib/bg2ee/basic_iwd_long_dur.tph~
	END

///////////////////////////////////////////////////////////////////////////
// Make Skald Script after Core                                          //
///////////////////////////////////////////////////////////////////////////
INCLUDE ~enhanced-powergaming-scripts/lib/iwdee/skald_base.tph~

///////////////////////////////////////////////////////////////////////////
// Thieving Skills for Bards                                             //
///////////////////////////////////////////////////////////////////////////
ACTION_IF bard_thief BEGIN
	INCLUDE ~enhanced-powergaming-scripts/lib/bard_thief.tph~
	INCLUDE ~enhanced-powergaming-scripts/lib/skald_bard_thief.tph~
END

///////////////////////////////////////////////////////////////////////////
// Removes Targeting Dancing Swords with Magic Missiles                  //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF dnc_swrd BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/ini/rmv_dnc_swrd.tph~
	END

///////////////////////////////////////////////////////////////////////////
// EEex Check                                                            //
///////////////////////////////////////////////////////////////////////////
ACTION_IF eeex_present BEGIN
	COPY ~enhanced-powergaming-scripts/lua/m_actri1.lua~  ~override~ 
END ELSE BEGIN
	INCLUDE ~enhanced-powergaming-scripts/lib/basic_eeex.tph~
	INCLUDE ~enhanced-powergaming-scripts/lib/core_eeex.tph~
	INCLUDE ~enhanced-powergaming-scripts/lib/skald_eeex.tph~
END

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Import AI Scripts into the Game                                       //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Copy .BS files to scripts folder                                      //
///////////////////////////////////////////////////////////////////////////
COPY ~enhanced-powergaming-scripts/baf/upload/mobasic.baf~  ~scripts/mobasic.bs~
	 ~enhanced-powergaming-scripts/baf/upload/mocore.baf~   ~scripts/mocore.bs~
	 ~enhanced-powergaming-scripts/baf/upload/moskd.baf~    ~scripts/moskd.bs~
  COMPILE_BAF_TO_BCS

///////////////////////////////////////////////////////////////////////////
// Add descriptions of the scripts to scrpdesc.2da                       //
///////////////////////////////////////////////////////////////////////////
APPEND ~scrpdesc.2DA~
~mobasic	mbasic1		 mbasic2
mocore      mcore1       mcore2
moskd		mskd1		 mskd2~

///////////////////////////////////////////////////////////////////////////
// Copy the appended scrpdesc.2da to the override folder                 //
///////////////////////////////////////////////////////////////////////////
COPY_EXISTING ~scrpdesc.2da~ ~override~
REPLACE ~mbasic1~ @1090
REPLACE ~mbasic2~ @1091
REPLACE ~mcore1~  @1100
REPLACE ~mcore2~  @1101
REPLACE ~mskd1~   @1070
REPLACE ~mskd2~   @1071