LOAD_TRA ~enhanced-powergaming-scripts/languages/%LANGUAGE%/script_dialog.tra~

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Add Mod Components to Accelerated Scripts                             //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Base Game - IWD: EE                                                   //
///////////////////////////////////////////////////////////////////////////
COPY ~enhanced-powergaming-scripts/baf/Accelerated/mocore.baf~  ~enhanced-powergaming-scripts/baf/upload/mobasic.baf~
COPY ~enhanced-powergaming-scripts/baf/Accelerated/mocore.baf~  ~enhanced-powergaming-scripts/baf/upload/mocore.baf~

INCLUDE ~enhanced-powergaming-scripts/lib/basic_base.tph~
INCLUDE ~enhanced-powergaming-scripts/lib/core_base.tph~

INCLUDE ~enhanced-powergaming-scripts/lib/IWDEE/basic_iwd_a.tph~
INCLUDE ~enhanced-powergaming-scripts/lib/IWDEE/core_iwd_a.tph~

///////////////////////////////////////////////////////////////////////////
// Heart of Winter                                                       //
///////////////////////////////////////////////////////////////////////////
/*
ACTION_IF (MOD_IS_INSTALLED ~setup-stratagems.tp2~ ~1500~ && MOD_IS_INSTALLED ~setup-stratagems.tp2~ ~1510~) || (MOD_IS_INSTALLED ~iwdification/setup-iwdification.tp2~ 30 && MOD_IS_INSTALLED ~iwdification/setup-iwdification.tp2~ 40) BEGIN
	INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/ranger_iwd.tph~
	INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/basic_iwd.tph~
	INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/core_iwd.tph~
END
*/

///////////////////////////////////////////////////////////////////////////
// Update Hot Keys                                                       //
///////////////////////////////////////////////////////////////////////////
	INCLUDE ~enhanced-powergaming-scripts/lib/core_hotkey.tph~
	INCLUDE ~enhanced-powergaming-scripts/lib/basic_hotkey.tph~

///////////////////////////////////////////////////////////////////////////
// Update ini Presets                                                    //
///////////////////////////////////////////////////////////////////////////
	
	// Removes Potion Use in Pre-Buffing
	ACTION_IF pot_use BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/ini/core_pot.tph~
		INCLUDE ~enhanced-powergaming-scripts/lib/ini/basic_pot.tph~
	END

	// Basic AI will Auto-Attack Enemies
	ACTION_IF bsc_atk BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/ini/basic_atk.tph~
	END

	// Removes Dialog Hovertext from Scripts
	ACTION_IF scp_dlg BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/ini/core_dialog.tph~
		INCLUDE ~enhanced-powergaming-scripts/lib/ini/basic_dialog.tph~
	END

///////////////////////////////////////////////////////////////////////////
// Make Skald Script after Core                                          //
///////////////////////////////////////////////////////////////////////////
INCLUDE ~enhanced-powergaming-scripts/lib/iwdee/skald_base.tph~

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Import AI Scripts into the Game                                       //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Copy .BS files to scripts folder                                      //
///////////////////////////////////////////////////////////////////////////
COPY ~enhanced-powergaming-scripts/baf/upload/mobasic.baf~  ~scripts/mobasic.bs~
	 ~enhanced-powergaming-scripts/baf/upload/mocore.baf~   ~scripts/mocore.bs~
	 ~enhanced-powergaming-scripts/baf/upload/moskd.baf~    ~scripts/moskd.bs~
  COMPILE_BAF_TO_BCS

///////////////////////////////////////////////////////////////////////////
// Add descriptions of the scripts to scrpdesc.2da                       //
///////////////////////////////////////////////////////////////////////////
APPEND ~scrpdesc.2DA~
~mobasic	999988		 999987
mocore      999986       999985
moskd		999980		 999979~

///////////////////////////////////////////////////////////////////////////
// Copy the appended scrpdesc.2da to the override folder                 //
///////////////////////////////////////////////////////////////////////////
COPY_EXISTING ~scrpdesc.2da~ ~override~
REPLACE ~999988~ @1090
REPLACE ~999987~ @1091
REPLACE ~999986~ @1100
REPLACE ~999985~ @1101
REPLACE ~999980~ @1070
REPLACE ~999979~ @1071