// **********************************************************************
// *           Segment Name: mocore.baf
// **********************************************************************
// *
// * Description:
// * This script is designed for all core classes: Fighter, Mage, Thief, Cleric, Druid, and 
// * any combination of multiclass/dualclass to include kits. This script will constantly 
// * Turn Undead when the V key is pressed and will cast pre-buffing spells when the D key 
// * is pressed. If the character is able, the script will constantly be detecting traps.

IF
  PartyRested()
THEN
  RESPONSE #100
    SetGlobal("MO_UsedIlbratha","GLOBAL",0)
    SetGlobal("MO_UsedDuplication","GLOBAL",0)
    SetGlobal("MO_UsedGargoyle","GLOBAL",0)
    SetGlobal("MO_UsedCheetah","GLOBAL",0)
    SetGlobal("MO_UsedDevout","GLOBAL",0)
    SetGlobal("MO_UsedFortitude","GLOBAL",0)
    SetGlobal("MO_UsedSpellTurning","GLOBAL",0)
    SetGlobal("MO_UsedClkOfStars","GLOBAL",0)
    SetGlobal("MO_UsedCowlOfStars","GLOBAL",0)
    SetGlobal("MO_UsedBltMnrInv","GLOBAL",0)
    SetGlobal("MO_UsedClkDrkMN","GLOBAL",0)
    SetGlobal("MO_UsedShldFyrus","GLOBAL",0)
END

IF
  Global("MO_TrueSightActive","LOCALS",1)
  CheckStat(Myself,0,TRUE_SIGHT)
THEN
  RESPONSE #100
    SetGlobal("MO_TrueSightActive","LOCALS",0)
    SetGlobal("MO_PartyTrueSight","GLOBAL",0)
END

IF
  Global("MO_TrueSightActive","LOCALS",0)
  CheckStatGT(Myself,0,TRUE_SIGHT)
THEN
  RESPONSE #100
    SetGlobal("MO_TrueSightActive","LOCALS",1)
    SetGlobal("MO_PartyTrueSight","GLOBAL",1)
END

IF
  HaveSpell(CLERIC_PROTECTION_FROM_EVIL_10_FOOT)  // SPPR408.SPL (Protection From Evil, 10' Radius)
  OR(2)
    Global("MO_ProtEvil","LOCALS",0)
    Global("MO_TeamProtEvil","GLOBAL",0)
THEN
  RESPONSE #100
    SetGlobal("MO_ProtEvil","LOCALS",1)
    SetGlobal("MO_TeamProtEvil","GLOBAL",1)
END

IF
  !HaveSpell(CLERIC_PROTECTION_FROM_EVIL_10_FOOT)  // SPPR408.SPL (Protection From Evil, 10' Radius)
  Global("MO_ProtEvil","LOCALS",1)
THEN
  RESPONSE #100
    SetGlobal("MO_ProtEvil","LOCALS",0)
    SetGlobal("MO_TeamProtEvil","GLOBAL",0)
END

IF
  OR(7)
    AreaCheck("AR0700")  // Waukeen's Promenade
    AreaCheck("AR0020")  // City Gates
    AreaCheck("AR0800")  // Graveyard
    AreaCheck("AR0400")  // Slums
    AreaCheck("AR0300")  // The Docks
    AreaCheck("AR1000")  // Government District
    AreaCheck("AR0900")  // Temple District
  Global("BRIBEDCOWLED","GLOBAL",0)
  GlobalLT("CowledWarning","GLOBAL",7)
  Global("MO_CastAthkatla","LOCALS",1)
THEN
  RESPONSE #100
    SetGlobal("MO_CastAthkatla","LOCALS",0)
END

IF
  !AreaCheck("AR0700")  // Waukeen's Promenade
  !AreaCheck("AR0020")  // City Gates
  !AreaCheck("AR0800")  // Graveyard
  !AreaCheck("AR0400")  // Slums
  !AreaCheck("AR0300")  // The Docks
  !AreaCheck("AR1000")  // Government District
  !AreaCheck("AR0900")  // Temple District
  Global("MO_CastAthkatla","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("MO_CastAthkatla","LOCALS",1)
END

IF
  OR(2)
    Global("BRIBEDCOWLED","GLOBAL",1)
    Global("CowledWarning","GLOBAL",7)
  Global("MO_CastAthkatla","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("MO_CastAthkatla","LOCALS",1)
END

IF
  Global("MO_TURNUNDEAD","LOCALS",0)
  Class(Myself,CLERIC_ALL)
  HotKey(V)
THEN
  RESPONSE #100
    SetGlobal("MO_TURNUNDEAD","LOCALS",1)
    DisplayStringHead(Myself,50702)  // Turning Undead
END

IF
  Global("MO_TURNUNDEAD","LOCALS",1)
  HotKey(V)
THEN
  RESPONSE #100
    SetGlobal("MO_TURNUNDEAD","LOCALS",0)
    DisplayStringHead(Myself,50703)  // Stopped Turning Undead
END

IF
  Global("MO_BUFF","LOCALS",0)
  HotKey(D)
THEN
  RESPONSE #50
    SetGlobal("MO_BUFF","LOCALS",1)
    DisplayStringHead(Myself,91061)  // Right. I'll get started then.
  RESPONSE #50
    SetGlobal("MO_BUFF","LOCALS",1)
    DisplayStringHead(Myself,91057)  // Right, I'll get started then. Please excuse me.
END

IF
  Global("MO_BUFF","LOCALS",1)
  OR(2)
    HotKey(D)
    See([EVILCUTOFF])
THEN
  RESPONSE #100
    SetGlobal("MO_BUFF","LOCALS",0)
    DisplayStringHead(Myself,50742)  // I have not yet completed the task.
END

IF
  Global("MO_BUFF","LOCALS",1)
  ActionListEmpty()
  HasItemEquiped("potn09",Myself)  // Potion of Heroism
  !CheckSpellState(Myself,BUFF_ENHANCEMENT)
THEN
  RESPONSE #100
    UseItem("potn09",Myself)  // Potion of Heroism
END

IF
  Global("MO_BUFF","LOCALS",1)
  HasItemEquiped("potn02",Myself)  // Potion of Fire Resistance
THEN
  RESPONSE #100
    UseItem("potn02",Myself)  // Potion of Fire Resistance
END

IF
  Global("MO_BUFF","LOCALS",1)
  HasItemEquiped("potn22",Myself)  // Potion of Cold Resistance
THEN
  RESPONSE #100
    UseItem("potn22",Myself)  // Potion of Cold Resistance
END

IF
  Global("MO_BUFF","LOCALS",1)
  HasItemEquiped("potn18",Myself)  // Potion of Absorption
  CheckStatLT(Myself,100,RESISTELECTRICITY)
THEN
  RESPONSE #100
    UseItem("potn18",Myself)  // Potion of Absorption
END

IF
  Global("MO_BUFF","LOCALS",1)
  HasItemEquiped("potn34",Myself)  // Potion of Magic Protection
THEN
  RESPONSE #100
    UseItem("potn34",Myself)  // Potion of Magic Protection
END

IF
  Global("MO_BUFF","LOCALS",1)
  ActionListEmpty()
  HasItemEquiped("potn07",Myself)  // Potion of Storm Giant Strength
  CheckStatLT(Myself,24,STR)
THEN
  RESPONSE #100
    UseItem("potn07",Myself)  // Potion of Storm Giant Strength
END

IF
  Global("MO_BUFF","LOCALS",1)
  ActionListEmpty()
  HasItemEquiped("potn06",Myself)  // Potion of Cloud Giant Strength
  CheckStatLT(Myself,23,STR)
THEN
  RESPONSE #100
    UseItem("potn06",Myself)  // Potion of Cloud Giant Strength
END

IF
  Global("MO_BUFF","LOCALS",1)
  ActionListEmpty()
  HasItemEquiped("potn05",Myself)  // Potion of Fire Giant Strength
  CheckStatLT(Myself,22,STR)
THEN
  RESPONSE #100
    UseItem("potn05",Myself)  // Potion of Fire Giant Strength
END

IF
  Global("MO_BUFF","LOCALS",1)
  ActionListEmpty()
  HasItemEquiped("potn04",Myself)  // Potion of Frost Giant Strength
  CheckStatLT(Myself,21,STR)
THEN
  RESPONSE #100
    UseItem("potn04",Myself)  // Potion of Frost Giant Strength
END

IF
  Global("MO_BUFF","LOCALS",1)
  ActionListEmpty()
  HasItemEquiped("potn12",Myself)  // Potion of Stone Giant Strength
  CheckStatLT(Myself,20,STR)
THEN
  RESPONSE #100
    UseItem("potn12",Myself)  // Potion of Stone Giant Strength
END

IF
  Global("MO_BUFF","LOCALS",1)
  ActionListEmpty()
  HasItemEquiped("potn03",Myself)  // Potion of Hill Giant Strength
  CheckStatLT(Myself,19,STR)
THEN
  RESPONSE #100
    UseItem("potn03",Myself)  // Potion of Hill Giant Strength
END

IF
  Global("MO_BUFF","LOCALS",1)
  HasItemEquiped("potn11",Myself)  // Potion of Invulnerability
  CheckStatGT(Myself,0,ARMORCLASS)
THEN
  RESPONSE #100
    UseItem("potn11",Myself)  // Potion of Invulnerability
END

IF
  Global("MO_BUFF","LOCALS",1)
  HasItemEquiped("OHRCLCK4",Myself)  // Cloak of the Dark Moon
  GlobalLT("MO_UsedClkDrkMN","GLOBAL",3)
  !CheckStatGT(Myself,0,WIZARD_PROTECTION_FROM_MAGIC_ENERGY)
  Global("MO_CastAthkatla","LOCALS",1)
THEN
  RESPONSE #100
    UseItem("OHRCLCK4",Myself)  // Cloak of the Dark Moon
    IncrementGlobal("MO_UsedClkDrkMN","GLOBAL",1)
END

IF
  Global("MO_BUFF","LOCALS",1)
  HaveSpell(WIZARD_SPIRIT_ARMOR)  // SPWI414.SPL (Spirit Armor)
  CheckStatGT(Myself,1,ARMORCLASS)
  !CheckSpellState(Myself,GLOBE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(Myself,WIZARD_SPIRIT_ARMOR)  // SPWI414.SPL (Spirit Armor)
    RemoveSpell(WIZARD_SPIRIT_ARMOR)  // SPWI414.SPL (Spirit Armor)
END

IF
  Global("MO_BUFF","LOCALS",1)
  HaveSpell(WIZARD_GHOST_ARMOR)  // SPWI317.SPL (Ghost Armor)
  CheckStatGT(Myself,2,ARMORCLASS)
  !CheckSpellState(Myself,MINOR_GLOBE)
  !CheckSpellState(Myself,GLOBE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(Myself,WIZARD_GHOST_ARMOR)  // SPWI317.SPL (Ghost Armor)
    RemoveSpell(WIZARD_GHOST_ARMOR)  // SPWI317.SPL (Ghost Armor)
END

IF
  Global("MO_BUFF","LOCALS",1)
  HaveSpell(WIZARD_SHIELD)  // SPWI114.SPL (Shield)
  !CheckSpellState(Myself,WIZARD_SHIELD)
  !CheckSpellState(Myself,MINOR_GLOBE)
  !CheckSpellState(Myself,GLOBE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(Myself,WIZARD_SHIELD)  // SPWI114.SPL (Shield)
    RemoveSpell(WIZARD_SHIELD)  // SPWI114.SPL (Shield)
END

IF
  Global("MO_BUFF","LOCALS",1)
  HaveSpell(WIZARD_RESIST_FEAR)  // SPWI210.SPL (Resist Fear)
  !CheckSpellState(Myself,RESIST_FEAR)
  !CheckSpellState(Myself,MINOR_GLOBE)
  !CheckSpellState(Myself,GLOBE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(Myself,WIZARD_RESIST_FEAR)  // SPWI210.SPL (Resist Fear)
    RemoveSpell(WIZARD_RESIST_FEAR)  // SPWI210.SPL (Resist Fear)
END

IF
  Global("MO_BUFF","LOCALS",1)
  HaveSpell(CLERIC_REMOVE_FEAR)  // SPPR108.SPL (Remove Fear)
  !CheckSpellState(Myself,RESIST_FEAR)
  !CheckSpellState(Myself,MINOR_GLOBE)
  !CheckSpellState(Myself,GLOBE)
  CheckStatLT(Myself,20,SPELLFAILUREPRIEST)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(Myself,CLERIC_REMOVE_FEAR)  // SPPR108.SPL (Remove Fear)
    RemoveSpell(CLERIC_REMOVE_FEAR)  // SPPR108.SPL (Remove Fear)
END

IF
  Global("MO_BUFF","LOCALS",1)
  HaveSpell(WIZARD_PROTECTION_FROM_NORMAL_MISSILES)  // SPWI311.SPL (Protection From Normal Missiles)
  !CheckSpellState(Myself,PROTECTION_FROM_NORMAL_MISSILES)
  !CheckSpellState(Myself,MINOR_GLOBE)
  !CheckSpellState(Myself,GLOBE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_NORMAL_MISSILES)  // SPWI311.SPL (Protection From Normal Missiles)
    RemoveSpell(WIZARD_PROTECTION_FROM_NORMAL_MISSILES)  // SPWI311.SPL (Protection From Normal Missiles)
END

IF
  Global("MO_BUFF","LOCALS",1)
  HaveSpell(CLERIC_DEATH_WARD)  // SPPR409.SPL (Death Ward)
  See(Myself)
  !Kit(LastSeenBy(Myself),UNDEADHUNTER)
  !CheckSpellState(LastSeenBy(Myself),DEATH_WARD)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),GLOBE)
  !CheckSpellState(LastSeenBy(Myself),MINOR_SPELL_TURNING)
  !CheckSpellState(LastSeenBy(Myself),SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREPRIEST)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(LastSeenBy(Myself),CLERIC_DEATH_WARD)  // SPPR409.SPL (Death Ward)
    RemoveSpell(CLERIC_DEATH_WARD)  // SPPR409.SPL (Death Ward)
END

IF
  Global("MO_BUFF","LOCALS",1)
  HaveSpell(CLERIC_DEATH_WARD)  // SPPR409.SPL (Death Ward)
  See([PC])
  !Kit(LastSeenBy(Myself),UNDEADHUNTER)
  !CheckSpellState(LastSeenBy(Myself),DEATH_WARD)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),GLOBE)
  !CheckSpellState(LastSeenBy(Myself),MINOR_SPELL_TURNING)
  !CheckSpellState(LastSeenBy(Myself),SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREPRIEST)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(LastSeenBy(Myself),CLERIC_DEATH_WARD)  // SPPR409.SPL (Death Ward)
    RemoveSpell(CLERIC_DEATH_WARD)  // SPPR409.SPL (Death Ward)
END

IF
  Global("MO_BUFF","LOCALS",1)
  HaveSpell(CLERIC_DEATH_WARD)  // SPPR409.SPL (Death Ward)
  See(SecondNearest([PC]))
  !Kit(LastSeenBy(Myself),UNDEADHUNTER)
  !CheckSpellState(LastSeenBy(Myself),DEATH_WARD)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),GLOBE)
  !CheckSpellState(LastSeenBy(Myself),MINOR_SPELL_TURNING)
  !CheckSpellState(LastSeenBy(Myself),SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREPRIEST)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(LastSeenBy(Myself),CLERIC_DEATH_WARD)  // SPPR409.SPL (Death Ward)
    RemoveSpell(CLERIC_DEATH_WARD)  // SPPR409.SPL (Death Ward)
END

IF
  Global("MO_BUFF","LOCALS",1)
  HaveSpell(CLERIC_DEATH_WARD)  // SPPR409.SPL (Death Ward)
  See(ThirdNearest([PC]))
  !Kit(LastSeenBy(Myself),UNDEADHUNTER)
  !CheckSpellState(LastSeenBy(Myself),DEATH_WARD)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),GLOBE)
  !CheckSpellState(LastSeenBy(Myself),MINOR_SPELL_TURNING)
  !CheckSpellState(LastSeenBy(Myself),SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREPRIEST)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(LastSeenBy(Myself),CLERIC_DEATH_WARD)  // SPPR409.SPL (Death Ward)
    RemoveSpell(CLERIC_DEATH_WARD)  // SPPR409.SPL (Death Ward)
END

IF
  Global("MO_BUFF","LOCALS",1)
  HaveSpell(CLERIC_DEATH_WARD)  // SPPR409.SPL (Death Ward)
  See(FourthNearest([PC]))
  !Kit(LastSeenBy(Myself),UNDEADHUNTER)
  !CheckSpellState(LastSeenBy(Myself),DEATH_WARD)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),GLOBE)
  !CheckSpellState(LastSeenBy(Myself),MINOR_SPELL_TURNING)
  !CheckSpellState(LastSeenBy(Myself),SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREPRIEST)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(LastSeenBy(Myself),CLERIC_DEATH_WARD)  // SPPR409.SPL (Death Ward)
    RemoveSpell(CLERIC_DEATH_WARD)  // SPPR409.SPL (Death Ward)
END

IF
  Global("MO_BUFF","LOCALS",1)
  HaveSpell(CLERIC_DEATH_WARD)  // SPPR409.SPL (Death Ward)
  See(FifthNearest([PC]))
  !Kit(LastSeenBy(Myself),UNDEADHUNTER)
  !CheckSpellState(LastSeenBy(Myself),DEATH_WARD)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),GLOBE)
  !CheckSpellState(LastSeenBy(Myself),MINOR_SPELL_TURNING)
  !CheckSpellState(LastSeenBy(Myself),SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREPRIEST)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(LastSeenBy(Myself),CLERIC_DEATH_WARD)  // SPPR409.SPL (Death Ward)
    RemoveSpell(CLERIC_DEATH_WARD)  // SPPR409.SPL (Death Ward)
END

IF
  Global("MO_BUFF","LOCALS",1)
  HaveSpell(CLERIC_DEATH_WARD)  // SPPR409.SPL (Death Ward)
  See(SixthNearest([PC]))
  !Kit(LastSeenBy(Myself),UNDEADHUNTER)
  !CheckSpellState(LastSeenBy(Myself),DEATH_WARD)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),GLOBE)
  !CheckSpellState(LastSeenBy(Myself),MINOR_SPELL_TURNING)
  !CheckSpellState(LastSeenBy(Myself),SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREPRIEST)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(LastSeenBy(Myself),CLERIC_DEATH_WARD)  // SPPR409.SPL (Death Ward)
    RemoveSpell(CLERIC_DEATH_WARD)  // SPPR409.SPL (Death Ward)
END

IF
  Global("MO_BUFF","LOCALS",1)
  HaveSpell(CLERIC_PROTECTION_FROM_EVIL_10_FOOT)  // SPPR408.SPL (Protection From Evil, 10' Radius)
  CheckStat(Myself,0,PROTECTION_FROM_EVIL)
  !CheckSpellState(Myself,GLOBE)
  CheckStatLT(Myself,20,SPELLFAILUREPRIEST)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(Myself,CLERIC_PROTECTION_FROM_EVIL_10_FOOT)  // SPPR408.SPL (Protection From Evil, 10' Radius)
    RemoveSpell(CLERIC_PROTECTION_FROM_EVIL_10_FOOT)  // SPPR408.SPL (Protection From Evil, 10' Radius)
END

IF
  Global("MO_BUFF","LOCALS",1)
  See(Myself)
  !CheckSpellState(LastSeenBy(Myself),BARBARIAN_RAGE)
  !CheckSpellState(LastSeenBy(Myself),BERSERKER_RAGE)
  !CheckSpellState(LastSeenBy(Myself),CHAOTIC_COMMANDS)
  HaveSpell(CLERIC_CHAOTIC_COMMANDS)  // SPPR508.SPL (Chaotic Commands)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREPRIEST)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(LastSeenBy(Myself),CLERIC_CHAOTIC_COMMANDS)  // SPPR508.SPL (Chaotic Commands)
    RemoveSpell(CLERIC_CHAOTIC_COMMANDS)  // SPPR508.SPL (Chaotic Commands)
END

IF
  Global("MO_BUFF","LOCALS",1)
  See([PC])
  !CheckSpellState(LastSeenBy(Myself),BARBARIAN_RAGE)
  !CheckSpellState(LastSeenBy(Myself),BERSERKER_RAGE)
  !CheckSpellState(LastSeenBy(Myself),CHAOTIC_COMMANDS)
  HaveSpell(CLERIC_CHAOTIC_COMMANDS)  // SPPR508.SPL (Chaotic Commands)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREPRIEST)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(LastSeenBy(Myself),CLERIC_CHAOTIC_COMMANDS)  // SPPR508.SPL (Chaotic Commands)
    RemoveSpell(CLERIC_CHAOTIC_COMMANDS)  // SPPR508.SPL (Chaotic Commands)
END

IF
  Global("MO_BUFF","LOCALS",1)
  See(SecondNearest([PC]))
  !CheckSpellState(LastSeenBy(Myself),BARBARIAN_RAGE)
  !CheckSpellState(LastSeenBy(Myself),BERSERKER_RAGE)
  !CheckSpellState(LastSeenBy(Myself),CHAOTIC_COMMANDS)
  HaveSpell(CLERIC_CHAOTIC_COMMANDS)  // SPPR508.SPL (Chaotic Commands)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREPRIEST)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(LastSeenBy(Myself),CLERIC_CHAOTIC_COMMANDS)  // SPPR508.SPL (Chaotic Commands)
    RemoveSpell(CLERIC_CHAOTIC_COMMANDS)  // SPPR508.SPL (Chaotic Commands)
END

IF
  Global("MO_BUFF","LOCALS",1)
  See(ThirdNearest([PC]))
  !CheckSpellState(LastSeenBy(Myself),BARBARIAN_RAGE)
  !CheckSpellState(LastSeenBy(Myself),BERSERKER_RAGE)
  !CheckSpellState(LastSeenBy(Myself),CHAOTIC_COMMANDS)
  HaveSpell(CLERIC_CHAOTIC_COMMANDS)  // SPPR508.SPL (Chaotic Commands)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREPRIEST)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(LastSeenBy(Myself),CLERIC_CHAOTIC_COMMANDS)  // SPPR508.SPL (Chaotic Commands)
    RemoveSpell(CLERIC_CHAOTIC_COMMANDS)  // SPPR508.SPL (Chaotic Commands)
END

IF
  Global("MO_BUFF","LOCALS",1)
  See(FourthNearest([PC]))
  !CheckSpellState(LastSeenBy(Myself),BARBARIAN_RAGE)
  !CheckSpellState(LastSeenBy(Myself),BERSERKER_RAGE)
  !CheckSpellState(LastSeenBy(Myself),CHAOTIC_COMMANDS)
  HaveSpell(CLERIC_CHAOTIC_COMMANDS)  // SPPR508.SPL (Chaotic Commands)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREPRIEST)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(LastSeenBy(Myself),CLERIC_CHAOTIC_COMMANDS)  // SPPR508.SPL (Chaotic Commands)
    RemoveSpell(CLERIC_CHAOTIC_COMMANDS)  // SPPR508.SPL (Chaotic Commands)
END

IF
  Global("MO_BUFF","LOCALS",1)
  See(FifthNearest([PC]))
  !CheckSpellState(LastSeenBy(Myself),BARBARIAN_RAGE)
  !CheckSpellState(LastSeenBy(Myself),BERSERKER_RAGE)
  !CheckSpellState(LastSeenBy(Myself),CHAOTIC_COMMANDS)
  HaveSpell(CLERIC_CHAOTIC_COMMANDS)  // SPPR508.SPL (Chaotic Commands)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREPRIEST)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(LastSeenBy(Myself),CLERIC_CHAOTIC_COMMANDS)  // SPPR508.SPL (Chaotic Commands)
    RemoveSpell(CLERIC_CHAOTIC_COMMANDS)  // SPPR508.SPL (Chaotic Commands)
END

IF
  Global("MO_BUFF","LOCALS",1)
  See(SixthNearest([PC]))
  !CheckSpellState(LastSeenBy(Myself),BARBARIAN_RAGE)
  !CheckSpellState(LastSeenBy(Myself),BERSERKER_RAGE)
  !CheckSpellState(LastSeenBy(Myself),CHAOTIC_COMMANDS)
  HaveSpell(CLERIC_CHAOTIC_COMMANDS)  // SPPR508.SPL (Chaotic Commands)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREPRIEST)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(LastSeenBy(Myself),CLERIC_CHAOTIC_COMMANDS)  // SPPR508.SPL (Chaotic Commands)
    RemoveSpell(CLERIC_CHAOTIC_COMMANDS)  // SPPR508.SPL (Chaotic Commands)
END

IF
  Global("MO_BUFF","LOCALS",1)
  See(Myself)
  HaveSpell(WIZARD_PROTECTION_FROM_MAGIC_ENERGY)  // SPWI606.SPL (Protection From Magic Energy)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_PROTECTION_FROM_MAGIC_ENERGY)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_PROTECTION_FROM_MAGIC_ENERGY)  // SPWI606.SPL (Protection From Magic Energy)
    RemoveSpell(WIZARD_PROTECTION_FROM_MAGIC_ENERGY)  // SPWI606.SPL (Protection From Magic Energy)
END

IF
  Global("MO_BUFF","LOCALS",1)
  See([PC])
  HaveSpell(WIZARD_PROTECTION_FROM_MAGIC_ENERGY)  // SPWI606.SPL (Protection From Magic Energy)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_PROTECTION_FROM_MAGIC_ENERGY)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_PROTECTION_FROM_MAGIC_ENERGY)  // SPWI606.SPL (Protection From Magic Energy)
    RemoveSpell(WIZARD_PROTECTION_FROM_MAGIC_ENERGY)  // SPWI606.SPL (Protection From Magic Energy)
END

IF
  Global("MO_BUFF","LOCALS",1)
  See(SecondNearest([PC]))
  HaveSpell(WIZARD_PROTECTION_FROM_MAGIC_ENERGY)  // SPWI606.SPL (Protection From Magic Energy)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_PROTECTION_FROM_MAGIC_ENERGY)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_PROTECTION_FROM_MAGIC_ENERGY)  // SPWI606.SPL (Protection From Magic Energy)
    RemoveSpell(WIZARD_PROTECTION_FROM_MAGIC_ENERGY)  // SPWI606.SPL (Protection From Magic Energy)
END

IF
  Global("MO_BUFF","LOCALS",1)
  See(ThirdNearest([PC]))
  HaveSpell(WIZARD_PROTECTION_FROM_MAGIC_ENERGY)  // SPWI606.SPL (Protection From Magic Energy)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_PROTECTION_FROM_MAGIC_ENERGY)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_PROTECTION_FROM_MAGIC_ENERGY)  // SPWI606.SPL (Protection From Magic Energy)
    RemoveSpell(WIZARD_PROTECTION_FROM_MAGIC_ENERGY)  // SPWI606.SPL (Protection From Magic Energy)
END

IF
  Global("MO_BUFF","LOCALS",1)
  See(FourthNearest([PC]))
  HaveSpell(WIZARD_PROTECTION_FROM_MAGIC_ENERGY)  // SPWI606.SPL (Protection From Magic Energy)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_PROTECTION_FROM_MAGIC_ENERGY)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_PROTECTION_FROM_MAGIC_ENERGY)  // SPWI606.SPL (Protection From Magic Energy)
    RemoveSpell(WIZARD_PROTECTION_FROM_MAGIC_ENERGY)  // SPWI606.SPL (Protection From Magic Energy)
END

IF
  Global("MO_BUFF","LOCALS",1)
  See(FifthNearest([PC]))
  HaveSpell(WIZARD_PROTECTION_FROM_MAGIC_ENERGY)  // SPWI606.SPL (Protection From Magic Energy)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_PROTECTION_FROM_MAGIC_ENERGY)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_PROTECTION_FROM_MAGIC_ENERGY)  // SPWI606.SPL (Protection From Magic Energy)
    RemoveSpell(WIZARD_PROTECTION_FROM_MAGIC_ENERGY)  // SPWI606.SPL (Protection From Magic Energy)
END

IF
  Global("MO_BUFF","LOCALS",1)
  See(SixthNearest([PC]))
  HaveSpell(WIZARD_PROTECTION_FROM_MAGIC_ENERGY)  // SPWI606.SPL (Protection From Magic Energy)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_PROTECTION_FROM_MAGIC_ENERGY)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_PROTECTION_FROM_MAGIC_ENERGY)  // SPWI606.SPL (Protection From Magic Energy)
    RemoveSpell(WIZARD_PROTECTION_FROM_MAGIC_ENERGY)  // SPWI606.SPL (Protection From Magic Energy)
END

IF
  Global("MO_BUFF","LOCALS",1)
  See(Myself)
  HaveSpell(WIZARD_PROTECTION_FROM_FIRE)  // SPWI319.SPL (Protection From Fire)
  CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),MINOR_GLOBE)
  !CheckSpellState(LastSeenBy(Myself),GLOBE)
  !CheckSpellState(LastSeenBy(Myself),MINOR_SPELL_TURNING)
  !CheckSpellState(LastSeenBy(Myself),SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_PROTECTION_FROM_FIRE)  // SPWI319.SPL (Protection From Fire)
    RemoveSpell(WIZARD_PROTECTION_FROM_FIRE)  // SPWI319.SPL (Protection From Fire)
END

IF
  Global("MO_BUFF","LOCALS",1)
  See([PC])
  HaveSpell(WIZARD_PROTECTION_FROM_FIRE)  // SPWI319.SPL (Protection From Fire)
  CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),MINOR_GLOBE)
  !CheckSpellState(LastSeenBy(Myself),GLOBE)
  !CheckSpellState(LastSeenBy(Myself),MINOR_SPELL_TURNING)
  !CheckSpellState(LastSeenBy(Myself),SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_PROTECTION_FROM_FIRE)  // SPWI319.SPL (Protection From Fire)
    RemoveSpell(WIZARD_PROTECTION_FROM_FIRE)  // SPWI319.SPL (Protection From Fire)
END

IF
  Global("MO_BUFF","LOCALS",1)
  See(SecondNearest([PC]))
  HaveSpell(WIZARD_PROTECTION_FROM_FIRE)  // SPWI319.SPL (Protection From Fire)
  CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),MINOR_GLOBE)
  !CheckSpellState(LastSeenBy(Myself),GLOBE)
  !CheckSpellState(LastSeenBy(Myself),MINOR_SPELL_TURNING)
  !CheckSpellState(LastSeenBy(Myself),SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_PROTECTION_FROM_FIRE)  // SPWI319.SPL (Protection From Fire)
    RemoveSpell(WIZARD_PROTECTION_FROM_FIRE)  // SPWI319.SPL (Protection From Fire)
END

IF
  Global("MO_BUFF","LOCALS",1)
  See(ThirdNearest([PC]))
  HaveSpell(WIZARD_PROTECTION_FROM_FIRE)  // SPWI319.SPL (Protection From Fire)
  CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),MINOR_GLOBE)
  !CheckSpellState(LastSeenBy(Myself),GLOBE)
  !CheckSpellState(LastSeenBy(Myself),MINOR_SPELL_TURNING)
  !CheckSpellState(LastSeenBy(Myself),SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_PROTECTION_FROM_FIRE)  // SPWI319.SPL (Protection From Fire)
    RemoveSpell(WIZARD_PROTECTION_FROM_FIRE)  // SPWI319.SPL (Protection From Fire)
END

IF
  Global("MO_BUFF","LOCALS",1)
  See(FourthNearest([PC]))
  HaveSpell(WIZARD_PROTECTION_FROM_FIRE)  // SPWI319.SPL (Protection From Fire)
  CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),MINOR_GLOBE)
  !CheckSpellState(LastSeenBy(Myself),GLOBE)
  !CheckSpellState(LastSeenBy(Myself),MINOR_SPELL_TURNING)
  !CheckSpellState(LastSeenBy(Myself),SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_PROTECTION_FROM_FIRE)  // SPWI319.SPL (Protection From Fire)
    RemoveSpell(WIZARD_PROTECTION_FROM_FIRE)  // SPWI319.SPL (Protection From Fire)
END

IF
  Global("MO_BUFF","LOCALS",1)
  See(FifthNearest([PC]))
  HaveSpell(WIZARD_PROTECTION_FROM_FIRE)  // SPWI319.SPL (Protection From Fire)
  CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),MINOR_GLOBE)
  !CheckSpellState(LastSeenBy(Myself),GLOBE)
  !CheckSpellState(LastSeenBy(Myself),MINOR_SPELL_TURNING)
  !CheckSpellState(LastSeenBy(Myself),SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_PROTECTION_FROM_FIRE)  // SPWI319.SPL (Protection From Fire)
    RemoveSpell(WIZARD_PROTECTION_FROM_FIRE)  // SPWI319.SPL (Protection From Fire)
END

IF
  Global("MO_BUFF","LOCALS",1)
  See(SixthNearest([PC]))
  HaveSpell(WIZARD_PROTECTION_FROM_FIRE)  // SPWI319.SPL (Protection From Fire)
  CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),MINOR_GLOBE)
  !CheckSpellState(LastSeenBy(Myself),GLOBE)
  !CheckSpellState(LastSeenBy(Myself),MINOR_SPELL_TURNING)
  !CheckSpellState(LastSeenBy(Myself),SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_PROTECTION_FROM_FIRE)  // SPWI319.SPL (Protection From Fire)
    RemoveSpell(WIZARD_PROTECTION_FROM_FIRE)  // SPWI319.SPL (Protection From Fire)
END

IF
  Global("MO_BUFF","LOCALS",1)
  See(Myself)
  HaveSpell(WIZARD_PROTECTION_FROM_COLD)  // SPWI320.SPL (Protection From Cold)
  CheckStatLT(LastSeenBy(Myself),100,RESISTCOLD)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),MINOR_GLOBE)
  !CheckSpellState(LastSeenBy(Myself),GLOBE)
  !CheckSpellState(LastSeenBy(Myself),MINOR_SPELL_TURNING)
  !CheckSpellState(LastSeenBy(Myself),SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_PROTECTION_FROM_COLD)  // SPWI320.SPL (Protection From Cold)
    RemoveSpell(WIZARD_PROTECTION_FROM_COLD)  // SPWI320.SPL (Protection From Cold)
END

IF
  Global("MO_BUFF","LOCALS",1)
  See([PC])
  HaveSpell(WIZARD_PROTECTION_FROM_COLD)  // SPWI320.SPL (Protection From Cold)
  CheckStatLT(LastSeenBy(Myself),100,RESISTCOLD)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),MINOR_GLOBE)
  !CheckSpellState(LastSeenBy(Myself),GLOBE)
  !CheckSpellState(LastSeenBy(Myself),MINOR_SPELL_TURNING)
  !CheckSpellState(LastSeenBy(Myself),SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_PROTECTION_FROM_COLD)  // SPWI320.SPL (Protection From Cold)
    RemoveSpell(WIZARD_PROTECTION_FROM_COLD)  // SPWI320.SPL (Protection From Cold)
END

IF
  Global("MO_BUFF","LOCALS",1)
  See(SecondNearest([PC]))
  HaveSpell(WIZARD_PROTECTION_FROM_COLD)  // SPWI320.SPL (Protection From Cold)
  CheckStatLT(LastSeenBy(Myself),100,RESISTCOLD)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),MINOR_GLOBE)
  !CheckSpellState(LastSeenBy(Myself),GLOBE)
  !CheckSpellState(LastSeenBy(Myself),MINOR_SPELL_TURNING)
  !CheckSpellState(LastSeenBy(Myself),SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_PROTECTION_FROM_COLD)  // SPWI320.SPL (Protection From Cold)
    RemoveSpell(WIZARD_PROTECTION_FROM_COLD)  // SPWI320.SPL (Protection From Cold)
END

IF
  Global("MO_BUFF","LOCALS",1)
  See(ThirdNearest([PC]))
  HaveSpell(WIZARD_PROTECTION_FROM_COLD)  // SPWI320.SPL (Protection From Cold)
  CheckStatLT(LastSeenBy(Myself),100,RESISTCOLD)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),MINOR_GLOBE)
  !CheckSpellState(LastSeenBy(Myself),GLOBE)
  !CheckSpellState(LastSeenBy(Myself),MINOR_SPELL_TURNING)
  !CheckSpellState(LastSeenBy(Myself),SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_PROTECTION_FROM_COLD)  // SPWI320.SPL (Protection From Cold)
    RemoveSpell(WIZARD_PROTECTION_FROM_COLD)  // SPWI320.SPL (Protection From Cold)
END

IF
  Global("MO_BUFF","LOCALS",1)
  See(FourthNearest([PC]))
  HaveSpell(WIZARD_PROTECTION_FROM_COLD)  // SPWI320.SPL (Protection From Cold)
  CheckStatLT(LastSeenBy(Myself),100,RESISTCOLD)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),MINOR_GLOBE)
  !CheckSpellState(LastSeenBy(Myself),GLOBE)
  !CheckSpellState(LastSeenBy(Myself),MINOR_SPELL_TURNING)
  !CheckSpellState(LastSeenBy(Myself),SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_PROTECTION_FROM_COLD)  // SPWI320.SPL (Protection From Cold)
    RemoveSpell(WIZARD_PROTECTION_FROM_COLD)  // SPWI320.SPL (Protection From Cold)
END

IF
  Global("MO_BUFF","LOCALS",1)
  See(FifthNearest([PC]))
  HaveSpell(WIZARD_PROTECTION_FROM_COLD)  // SPWI320.SPL (Protection From Cold)
  CheckStatLT(LastSeenBy(Myself),100,RESISTCOLD)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),MINOR_GLOBE)
  !CheckSpellState(LastSeenBy(Myself),GLOBE)
  !CheckSpellState(LastSeenBy(Myself),MINOR_SPELL_TURNING)
  !CheckSpellState(LastSeenBy(Myself),SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_PROTECTION_FROM_COLD)  // SPWI320.SPL (Protection From Cold)
    RemoveSpell(WIZARD_PROTECTION_FROM_COLD)  // SPWI320.SPL (Protection From Cold)
END

IF
  Global("MO_BUFF","LOCALS",1)
  See(SixthNearest([PC]))
  HaveSpell(WIZARD_PROTECTION_FROM_COLD)  // SPWI320.SPL (Protection From Cold)
  CheckStatLT(LastSeenBy(Myself),100,RESISTCOLD)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),MINOR_GLOBE)
  !CheckSpellState(LastSeenBy(Myself),GLOBE)
  !CheckSpellState(LastSeenBy(Myself),MINOR_SPELL_TURNING)
  !CheckSpellState(LastSeenBy(Myself),SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_PROTECTION_FROM_COLD)  // SPWI320.SPL (Protection From Cold)
    RemoveSpell(WIZARD_PROTECTION_FROM_COLD)  // SPWI320.SPL (Protection From Cold)
END

IF
  Global("MO_BUFF","LOCALS",1)
  See(Myself)
  HaveSpell(WIZARD_PROTECTION_FROM_ACID)  // SPWI517.SPL (Protection From Acid)
  CheckStatLT(LastSeenBy(Myself),100,RESISTACID)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_PROTECTION_FROM_ACID)  // SPWI517.SPL (Protection From Acid)
    RemoveSpell(WIZARD_PROTECTION_FROM_ACID)  // SPWI517.SPL (Protection From Acid)
END

IF
  Global("MO_BUFF","LOCALS",1)
  See([PC])
  HaveSpell(WIZARD_PROTECTION_FROM_ACID)  // SPWI517.SPL (Protection From Acid)
  CheckStatLT(LastSeenBy(Myself),100,RESISTACID)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),GLOBE)
  !CheckSpellState(LastSeenBy(Myself),SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_PROTECTION_FROM_ACID)  // SPWI517.SPL (Protection From Acid)
    RemoveSpell(WIZARD_PROTECTION_FROM_ACID)  // SPWI517.SPL (Protection From Acid)
END

IF
  Global("MO_BUFF","LOCALS",1)
  See(SecondNearest([PC]))
  HaveSpell(WIZARD_PROTECTION_FROM_ACID)  // SPWI517.SPL (Protection From Acid)
  CheckStatLT(LastSeenBy(Myself),100,RESISTACID)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),GLOBE)
  !CheckSpellState(LastSeenBy(Myself),SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_PROTECTION_FROM_ACID)  // SPWI517.SPL (Protection From Acid)
    RemoveSpell(WIZARD_PROTECTION_FROM_ACID)  // SPWI517.SPL (Protection From Acid)
END

IF
  Global("MO_BUFF","LOCALS",1)
  See(ThirdNearest([PC]))
  HaveSpell(WIZARD_PROTECTION_FROM_ACID)  // SPWI517.SPL (Protection From Acid)
  CheckStatLT(LastSeenBy(Myself),100,RESISTACID)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),GLOBE)
  !CheckSpellState(LastSeenBy(Myself),SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_PROTECTION_FROM_ACID)  // SPWI517.SPL (Protection From Acid)
    RemoveSpell(WIZARD_PROTECTION_FROM_ACID)  // SPWI517.SPL (Protection From Acid)
END

IF
  Global("MO_BUFF","LOCALS",1)
  See(FourthNearest([PC]))
  HaveSpell(WIZARD_PROTECTION_FROM_ACID)  // SPWI517.SPL (Protection From Acid)
  CheckStatLT(LastSeenBy(Myself),100,RESISTACID)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),GLOBE)
  !CheckSpellState(LastSeenBy(Myself),SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_PROTECTION_FROM_ACID)  // SPWI517.SPL (Protection From Acid)
    RemoveSpell(WIZARD_PROTECTION_FROM_ACID)  // SPWI517.SPL (Protection From Acid)
END

IF
  Global("MO_BUFF","LOCALS",1)
  See(FifthNearest([PC]))
  HaveSpell(WIZARD_PROTECTION_FROM_ACID)  // SPWI517.SPL (Protection From Acid)
  CheckStatLT(LastSeenBy(Myself),100,RESISTACID)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),GLOBE)
  !CheckSpellState(LastSeenBy(Myself),SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_PROTECTION_FROM_ACID)  // SPWI517.SPL (Protection From Acid)
    RemoveSpell(WIZARD_PROTECTION_FROM_ACID)  // SPWI517.SPL (Protection From Acid)
END

IF
  Global("MO_BUFF","LOCALS",1)
  See(SixthNearest([PC]))
  HaveSpell(WIZARD_PROTECTION_FROM_ACID)  // SPWI517.SPL (Protection From Acid)
  CheckStatLT(LastSeenBy(Myself),100,RESISTACID)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),GLOBE)
  !CheckSpellState(LastSeenBy(Myself),SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_PROTECTION_FROM_ACID)  // SPWI517.SPL (Protection From Acid)
    RemoveSpell(WIZARD_PROTECTION_FROM_ACID)  // SPWI517.SPL (Protection From Acid)
END

IF
  Global("MO_BUFF","LOCALS",1)
  HaveSpell(CLERIC_SHIELD_OF_THE_ARCHONS)  // SPPR701.SPL (Shield of the Archons)
  CheckStatLT(Myself,1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREPRIEST)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(Myself,CLERIC_SHIELD_OF_THE_ARCHONS)  // SPPR701.SPL (Shield of the Archons)
    RemoveSpell(CLERIC_SHIELD_OF_THE_ARCHONS)  // SPPR701.SPL (Shield of the Archons)
END

IF
  Global("MO_BUFF","LOCALS",1)
  Global("MO_TeamProtEvil","GLOBAL",0)
  HaveSpell(CLERIC_PROTECT_FROM_EVIL)  // SPPR107.SPL (Protection From Evil)
  See(Myself)
  CheckStat(LastSeenBy(Myself),0,PROTECTION_FROM_EVIL)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),GLOBE)
  !CheckSpellState(LastSeenBy(Myself),MINOR_SPELL_TURNING)
  !CheckSpellState(LastSeenBy(Myself),SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREPRIEST)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(LastSeenBy(Myself),CLERIC_PROTECT_FROM_EVIL)  // SPPR107.SPL (Protection From Evil)
    RemoveSpell(CLERIC_PROTECT_FROM_EVIL)  // SPPR107.SPL (Protection From Evil)
END

IF
  Global("MO_BUFF","LOCALS",1)
  Global("MO_TeamProtEvil","GLOBAL",0)
  HaveSpell(CLERIC_PROTECT_FROM_EVIL)  // SPPR107.SPL (Protection From Evil)
  See([PC])
  CheckStat(LastSeenBy(Myself),0,PROTECTION_FROM_EVIL)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),GLOBE)
  !CheckSpellState(LastSeenBy(Myself),MINOR_SPELL_TURNING)
  !CheckSpellState(LastSeenBy(Myself),SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREPRIEST)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(LastSeenBy(Myself),CLERIC_PROTECT_FROM_EVIL)  // SPPR107.SPL (Protection From Evil)
    RemoveSpell(CLERIC_PROTECT_FROM_EVIL)  // SPPR107.SPL (Protection From Evil)
END

IF
  Global("MO_BUFF","LOCALS",1)
  Global("MO_TeamProtEvil","GLOBAL",0)
  HaveSpell(CLERIC_PROTECT_FROM_EVIL)  // SPPR107.SPL (Protection From Evil)
  See(SecondNearest([PC]))
  CheckStat(LastSeenBy(Myself),0,PROTECTION_FROM_EVIL)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),GLOBE)
  !CheckSpellState(LastSeenBy(Myself),MINOR_SPELL_TURNING)
  !CheckSpellState(LastSeenBy(Myself),SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREPRIEST)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(LastSeenBy(Myself),CLERIC_PROTECT_FROM_EVIL)  // SPPR107.SPL (Protection From Evil)
    RemoveSpell(CLERIC_PROTECT_FROM_EVIL)  // SPPR107.SPL (Protection From Evil)
END

IF
  Global("MO_BUFF","LOCALS",1)
  Global("MO_TeamProtEvil","GLOBAL",0)
  HaveSpell(CLERIC_PROTECT_FROM_EVIL)  // SPPR107.SPL (Protection From Evil)
  See(ThirdNearest([PC]))
  CheckStat(LastSeenBy(Myself),0,PROTECTION_FROM_EVIL)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),GLOBE)
  !CheckSpellState(LastSeenBy(Myself),MINOR_SPELL_TURNING)
  !CheckSpellState(LastSeenBy(Myself),SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREPRIEST)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(LastSeenBy(Myself),CLERIC_PROTECT_FROM_EVIL)  // SPPR107.SPL (Protection From Evil)
    RemoveSpell(CLERIC_PROTECT_FROM_EVIL)  // SPPR107.SPL (Protection From Evil)
END

IF
  Global("MO_BUFF","LOCALS",1)
  Global("MO_TeamProtEvil","GLOBAL",0)
  HaveSpell(CLERIC_PROTECT_FROM_EVIL)  // SPPR107.SPL (Protection From Evil)
  See(FourthNearest([PC]))
  CheckStat(LastSeenBy(Myself),0,PROTECTION_FROM_EVIL)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),GLOBE)
  !CheckSpellState(LastSeenBy(Myself),MINOR_SPELL_TURNING)
  !CheckSpellState(LastSeenBy(Myself),SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREPRIEST)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(LastSeenBy(Myself),CLERIC_PROTECT_FROM_EVIL)  // SPPR107.SPL (Protection From Evil)
    RemoveSpell(CLERIC_PROTECT_FROM_EVIL)  // SPPR107.SPL (Protection From Evil)
END

IF
  Global("MO_BUFF","LOCALS",1)
  Global("MO_TeamProtEvil","GLOBAL",0)
  HaveSpell(CLERIC_PROTECT_FROM_EVIL)  // SPPR107.SPL (Protection From Evil)
  See(FifthNearest([PC]))
  CheckStat(LastSeenBy(Myself),0,PROTECTION_FROM_EVIL)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),GLOBE)
  !CheckSpellState(LastSeenBy(Myself),MINOR_SPELL_TURNING)
  !CheckSpellState(LastSeenBy(Myself),SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREPRIEST)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(LastSeenBy(Myself),CLERIC_PROTECT_FROM_EVIL)  // SPPR107.SPL (Protection From Evil)
    RemoveSpell(CLERIC_PROTECT_FROM_EVIL)  // SPPR107.SPL (Protection From Evil)
END

IF
  Global("MO_BUFF","LOCALS",1)
  Global("MO_TeamProtEvil","GLOBAL",0)
  HaveSpell(CLERIC_PROTECT_FROM_EVIL)  // SPPR107.SPL (Protection From Evil)
  See(SixthNearest([PC]))
  CheckStat(LastSeenBy(Myself),0,PROTECTION_FROM_EVIL)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),GLOBE)
  !CheckSpellState(LastSeenBy(Myself),MINOR_SPELL_TURNING)
  !CheckSpellState(LastSeenBy(Myself),SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREPRIEST)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(LastSeenBy(Myself),CLERIC_PROTECT_FROM_EVIL)  // SPPR107.SPL (Protection From Evil)
    RemoveSpell(CLERIC_PROTECT_FROM_EVIL)  // SPPR107.SPL (Protection From Evil)
END

IF
  Global("MO_BUFF","LOCALS",1)
  HaveSpell(CLERIC_PROTECTION_FROM_LIGHTNING)  // SPPR407.SPL (Protection From Lightning)
  See(Myself)
  CheckStatLT(LastSeenBy(Myself),100,RESISTELECTRICITY)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),GLOBE)
  !CheckSpellState(LastSeenBy(Myself),SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREPRIEST)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(LastSeenBy(Myself),CLERIC_PROTECTION_FROM_LIGHTNING)  // SPPR407.SPL (Protection From Lightning)
    RemoveSpell(CLERIC_PROTECTION_FROM_LIGHTNING)  // SPPR407.SPL (Protection From Lightning)
END

IF
  Global("MO_BUFF","LOCALS",1)
  HaveSpell(CLERIC_PROTECTION_FROM_LIGHTNING)  // SPPR407.SPL (Protection From Lightning)
  See([PC])
  CheckStatLT(LastSeenBy(Myself),100,RESISTELECTRICITY)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),GLOBE)
  !CheckSpellState(LastSeenBy(Myself),SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREPRIEST)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(LastSeenBy(Myself),CLERIC_PROTECTION_FROM_LIGHTNING)  // SPPR407.SPL (Protection From Lightning)
    RemoveSpell(CLERIC_PROTECTION_FROM_LIGHTNING)  // SPPR407.SPL (Protection From Lightning)
END

IF
  Global("MO_BUFF","LOCALS",1)
  HaveSpell(CLERIC_PROTECTION_FROM_LIGHTNING)  // SPPR407.SPL (Protection From Lightning)
  See(SecondNearest([PC]))
  CheckStatLT(LastSeenBy(Myself),100,RESISTELECTRICITY)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),GLOBE)
  !CheckSpellState(LastSeenBy(Myself),SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREPRIEST)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(LastSeenBy(Myself),CLERIC_PROTECTION_FROM_LIGHTNING)  // SPPR407.SPL (Protection From Lightning)
    RemoveSpell(CLERIC_PROTECTION_FROM_LIGHTNING)  // SPPR407.SPL (Protection From Lightning)
END

IF
  Global("MO_BUFF","LOCALS",1)
  HaveSpell(CLERIC_PROTECTION_FROM_LIGHTNING)  // SPPR407.SPL (Protection From Lightning)
  See(ThirdNearest([PC]))
  CheckStatLT(LastSeenBy(Myself),100,RESISTELECTRICITY)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),GLOBE)
  !CheckSpellState(LastSeenBy(Myself),SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREPRIEST)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(LastSeenBy(Myself),CLERIC_PROTECTION_FROM_LIGHTNING)  // SPPR407.SPL (Protection From Lightning)
    RemoveSpell(CLERIC_PROTECTION_FROM_LIGHTNING)  // SPPR407.SPL (Protection From Lightning)
END

IF
  Global("MO_BUFF","LOCALS",1)
  HaveSpell(CLERIC_PROTECTION_FROM_LIGHTNING)  // SPPR407.SPL (Protection From Lightning)
  See(FourthNearest([PC]))
  CheckStatLT(LastSeenBy(Myself),100,RESISTELECTRICITY)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),GLOBE)
  !CheckSpellState(LastSeenBy(Myself),SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREPRIEST)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(LastSeenBy(Myself),CLERIC_PROTECTION_FROM_LIGHTNING)  // SPPR407.SPL (Protection From Lightning)
    RemoveSpell(CLERIC_PROTECTION_FROM_LIGHTNING)  // SPPR407.SPL (Protection From Lightning)
END

IF
  Global("MO_BUFF","LOCALS",1)
  HaveSpell(CLERIC_PROTECTION_FROM_LIGHTNING)  // SPPR407.SPL (Protection From Lightning)
  See(FifthNearest([PC]))
  CheckStatLT(LastSeenBy(Myself),100,RESISTELECTRICITY)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),GLOBE)
  !CheckSpellState(LastSeenBy(Myself),SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREPRIEST)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(LastSeenBy(Myself),CLERIC_PROTECTION_FROM_LIGHTNING)  // SPPR407.SPL (Protection From Lightning)
    RemoveSpell(CLERIC_PROTECTION_FROM_LIGHTNING)  // SPPR407.SPL (Protection From Lightning)
END

IF
  Global("MO_BUFF","LOCALS",1)
  HaveSpell(CLERIC_PROTECTION_FROM_LIGHTNING)  // SPPR407.SPL (Protection From Lightning)
  See(SixthNearest([PC]))
  CheckStatLT(LastSeenBy(Myself),100,RESISTELECTRICITY)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),GLOBE)
  !CheckSpellState(LastSeenBy(Myself),SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREPRIEST)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(LastSeenBy(Myself),CLERIC_PROTECTION_FROM_LIGHTNING)  // SPPR407.SPL (Protection From Lightning)
    RemoveSpell(CLERIC_PROTECTION_FROM_LIGHTNING)  // SPPR407.SPL (Protection From Lightning)
END

IF
  Global("MO_BUFF","LOCALS",1)
  HaveSpell(CLERIC_SPIRIT_WARD)  // SPPR150.SPL (Spirit Ward)
  See(Myself)
  !CheckSpellState(LastSeenBy(Myself),SPIRIT_WARD)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),GLOBE)
  !CheckSpellState(LastSeenBy(Myself),MINOR_SPELL_TURNING)
  !CheckSpellState(LastSeenBy(Myself),SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREPRIEST)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(LastSeenBy(Myself),CLERIC_SPIRIT_WARD)  // SPPR150.SPL (Spirit Ward)
    RemoveSpell(CLERIC_SPIRIT_WARD)  // SPPR150.SPL (Spirit Ward)
END

IF
  Global("MO_BUFF","LOCALS",1)
  HaveSpell(CLERIC_SPIRIT_WARD)  // SPPR150.SPL (Spirit Ward)
  See([PC])
  !CheckSpellState(LastSeenBy(Myself),SPIRIT_WARD)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),GLOBE)
  !CheckSpellState(LastSeenBy(Myself),MINOR_SPELL_TURNING)
  !CheckSpellState(LastSeenBy(Myself),SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREPRIEST)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(LastSeenBy(Myself),CLERIC_SPIRIT_WARD)  // SPPR150.SPL (Spirit Ward)
    RemoveSpell(CLERIC_SPIRIT_WARD)  // SPPR150.SPL (Spirit Ward)
END

IF
  Global("MO_BUFF","LOCALS",1)
  HaveSpell(CLERIC_SPIRIT_WARD)  // SPPR150.SPL (Spirit Ward)
  See(SecondNearest([PC]))
  !CheckSpellState(LastSeenBy(Myself),SPIRIT_WARD)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),GLOBE)
  !CheckSpellState(LastSeenBy(Myself),MINOR_SPELL_TURNING)
  !CheckSpellState(LastSeenBy(Myself),SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREPRIEST)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(LastSeenBy(Myself),CLERIC_SPIRIT_WARD)  // SPPR150.SPL (Spirit Ward)
    RemoveSpell(CLERIC_SPIRIT_WARD)  // SPPR150.SPL (Spirit Ward)
END

IF
  Global("MO_BUFF","LOCALS",1)
  HaveSpell(CLERIC_SPIRIT_WARD)  // SPPR150.SPL (Spirit Ward)
  See(ThirdNearest([PC]))
  !CheckSpellState(LastSeenBy(Myself),SPIRIT_WARD)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),GLOBE)
  !CheckSpellState(LastSeenBy(Myself),MINOR_SPELL_TURNING)
  !CheckSpellState(LastSeenBy(Myself),SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREPRIEST)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(LastSeenBy(Myself),CLERIC_SPIRIT_WARD)  // SPPR150.SPL (Spirit Ward)
    RemoveSpell(CLERIC_SPIRIT_WARD)  // SPPR150.SPL (Spirit Ward)
END

IF
  Global("MO_BUFF","LOCALS",1)
  HaveSpell(CLERIC_SPIRIT_WARD)  // SPPR150.SPL (Spirit Ward)
  See(FourthNearest([PC]))
  !CheckSpellState(LastSeenBy(Myself),SPIRIT_WARD)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),GLOBE)
  !CheckSpellState(LastSeenBy(Myself),MINOR_SPELL_TURNING)
  !CheckSpellState(LastSeenBy(Myself),SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREPRIEST)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(LastSeenBy(Myself),CLERIC_SPIRIT_WARD)  // SPPR150.SPL (Spirit Ward)
    RemoveSpell(CLERIC_SPIRIT_WARD)  // SPPR150.SPL (Spirit Ward)
END

IF
  Global("MO_BUFF","LOCALS",1)
  HaveSpell(CLERIC_SPIRIT_WARD)  // SPPR150.SPL (Spirit Ward)
  See(FifthNearest([PC]))
  !CheckSpellState(LastSeenBy(Myself),SPIRIT_WARD)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),GLOBE)
  !CheckSpellState(LastSeenBy(Myself),MINOR_SPELL_TURNING)
  !CheckSpellState(LastSeenBy(Myself),SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREPRIEST)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(LastSeenBy(Myself),CLERIC_SPIRIT_WARD)  // SPPR150.SPL (Spirit Ward)
    RemoveSpell(CLERIC_SPIRIT_WARD)  // SPPR150.SPL (Spirit Ward)
END

IF
  Global("MO_BUFF","LOCALS",1)
  HaveSpell(CLERIC_SPIRIT_WARD)  // SPPR150.SPL (Spirit Ward)
  See(SixthNearest([PC]))
  !CheckSpellState(LastSeenBy(Myself),SPIRIT_WARD)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),GLOBE)
  !CheckSpellState(LastSeenBy(Myself),MINOR_SPELL_TURNING)
  !CheckSpellState(LastSeenBy(Myself),SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREPRIEST)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(LastSeenBy(Myself),CLERIC_SPIRIT_WARD)  // SPPR150.SPL (Spirit Ward)
    RemoveSpell(CLERIC_SPIRIT_WARD)  // SPPR150.SPL (Spirit Ward)
END

IF
  Global("MO_BUFF","LOCALS",1)
  HaveSpell(WIZARD_HASTE)  // SPWI305.SPL (Haste)
  !StateCheck(Myself,STATE_HASTED)
  CheckStat(Myself,0,IMPROVEDHASTE)
  !StateCheck(Myself,STATE_NOT_TARGETABLE)
  !CheckStat(Myself,8,WIZARD_SPELL_IMMUNITY)
  !CheckSpellState(Myself,MINOR_GLOBE)
  !CheckSpellState(Myself,GLOBE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(Myself,WIZARD_HASTE)  // SPWI305.SPL (Haste)
    RemoveSpell(WIZARD_HASTE)  // SPWI305.SPL (Haste)
END

IF
  Global("MO_BUFF","LOCALS",1)
  HaveSpell(WIZARD_SPELL_SHIELD)  // SPWI519.SPL (Spell Shield)
  !CheckSpellState(Myself,SPELL_SHIELD)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(Myself,WIZARD_SPELL_SHIELD)  // SPWI519.SPL (Spell Shield)
    RemoveSpell(WIZARD_SPELL_SHIELD)  // SPWI519.SPL (Spell Shield)
END

IF
  Global("MO_BUFF","LOCALS",1)
  HaveSpell(WIZARD_SPELL_TURNING)  // SPWI701.SPL (Spell Turning)
  !CheckSpellState(Myself,SPELL_TURNING)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(Myself,WIZARD_SPELL_TURNING)  // SPWI701.SPL (Spell Turning)
    RemoveSpell(WIZARD_SPELL_TURNING)  // SPWI701.SPL (Spell Turning)
END

IF
  Global("MO_BUFF","LOCALS",1)
  HasItemEquiped("RING34",Myself)  // Ring of Spell Turning
  GlobalLT("MO_UsedSpellTurning","GLOBAL",1)
  !CheckSpellState(Myself,SPELL_TURNING)
THEN
  RESPONSE #100
    UseItem("RING34",Myself)  // Ring of Spell Turning
    IncrementGlobal("MO_UsedSpellTurning","GLOBAL",1)
END

IF
  Global("MO_BUFF","LOCALS",1)
  HaveSpell(WIZARD_MINOR_SPELL_TURNING)  // SPWI522.SPL (Minor Spell Turning)
  !CheckSpellState(Myself,MINOR_SPELL_TURNING)
  !CheckSpellState(Myself,SPELL_TURNING)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(Myself,WIZARD_MINOR_SPELL_TURNING)  // SPWI522.SPL (Minor Spell Turning)
    RemoveSpell(WIZARD_MINOR_SPELL_TURNING)  // SPWI522.SPL (Minor Spell Turning)
END

IF
  Global("MO_BUFF","LOCALS",1)
  HaveSpell(WIZARD_SPELL_DEFLECTION)  // SPWI618.SPL (Spell Deflection)
  CheckStatLT(Myself,1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(Myself,WIZARD_SPELL_DEFLECTION)  // SPWI618.SPL (Spell Deflection)
    RemoveSpell(WIZARD_SPELL_DEFLECTION)  // SPWI618.SPL (Spell Deflection)
END

IF
  Global("MO_BUFF","LOCALS",1)
  HaveSpell(WIZARD_MINOR_SPELL_DEFLECTION)  // SPWI318.SPL (Minor Spell Deflection)
  CheckStatLT(Myself,1,WIZARD_SPELL_DEFLECTION)
  !CheckSpellState(Myself,MINOR_GLOBE)
  !CheckSpellState(Myself,GLOBE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(Myself,WIZARD_MINOR_SPELL_DEFLECTION)  // SPWI318.SPL (Minor Spell Deflection)
    RemoveSpell(WIZARD_MINOR_SPELL_DEFLECTION)  // SPWI318.SPL (Minor Spell Deflection)
END

IF
  Global("MO_BUFF","LOCALS",1)
  !CheckStatGT(Myself,0,IMPROVEDHASTE)
  GlobalLT("MO_UsedCheetah","GLOBAL",1)
  HasItemEquiped("AMUL26",Myself)  // Amulet of Cheetah Speed
THEN
  RESPONSE #100
    UseItem("AMUL26",Myself)  // Amulet of Cheetah Speed
    IncrementGlobal("MO_UsedCheetah","GLOBAL",1)
END

IF
  Global("MO_BUFF","LOCALS",1)
  HaveSpell(CLERIC_ARMOR_OF_FAITH)  // SPPR111.SPL (Armor of Faith)
  !CheckSpellState(Myself,ARMOR_OF_FAITH)
  !CheckSpellState(Myself,MINOR_GLOBE)
  !CheckSpellState(Myself,GLOBE)
  CheckStatLT(Myself,20,SPELLFAILUREPRIEST)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(Myself,CLERIC_ARMOR_OF_FAITH)  // SPPR111.SPL (Armor of Faith)
    RemoveSpell(CLERIC_ARMOR_OF_FAITH)  // SPPR111.SPL (Armor of Faith)
END

IF
  Global("MO_BUFF","LOCALS",1)
  HaveSpell(WIZARD_BLUR)  // SPWI201.SPL (Blur)
  !StateCheck(Myself,STATE_BLUR)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(Myself,WIZARD_BLUR)  // SPWI201.SPL (Blur)
    RemoveSpell(WIZARD_BLUR)  // SPWI201.SPL (Blur)
END

IF
  Global("MO_BUFF","LOCALS",1)
  !StateCheck(Myself,STATE_MIRRORIMAGE)
  HaveSpell(WIZARD_MIRROR_IMAGE)  // SPWI212.SPL (Mirror Image)
  !CheckSpellState(Myself,MINOR_GLOBE)
  !CheckSpellState(Myself,GLOBE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStat(Myself,1,PUPPETTYPE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(Myself,WIZARD_MIRROR_IMAGE)  // SPWI212.SPL (Mirror Image)
    RemoveSpell(WIZARD_MIRROR_IMAGE)  // SPWI212.SPL (Mirror Image)
END

IF
  Global("MO_BUFF","LOCALS",1)
  HaveSpell(WIZARD_FIRE_SHIELD_RED)  // SPWI418.SPL (Fire Shield (Red))
  !CheckSpellState(Myself,RED_FIRESHIELD)
  !CheckSpellState(Myself,BLUE_FIRESHIELD)
  !CheckSpellState(Myself,GLOBE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(Myself,WIZARD_FIRE_SHIELD_RED)  // SPWI418.SPL (Fire Shield (Red))
    RemoveSpell(WIZARD_FIRE_SHIELD_RED)  // SPWI418.SPL (Fire Shield (Red))
END

IF
  Global("MO_BUFF","LOCALS",1)
  HaveSpell(WIZARD_FIRE_SHIELD_BLUE)  // SPWI403.SPL (Fire Shield (Blue))
  !CheckSpellState(Myself,RED_FIRESHIELD)
  !CheckSpellState(Myself,BLUE_FIRESHIELD)
  !CheckSpellState(Myself,GLOBE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(Myself,WIZARD_FIRE_SHIELD_BLUE)  // SPWI403.SPL (Fire Shield (Blue))
    RemoveSpell(WIZARD_FIRE_SHIELD_BLUE)  // SPWI403.SPL (Fire Shield (Blue))
END

IF
  Global("MO_BUFF","LOCALS",1)
  See(Myself)
  HaveSpell(CLERIC_PROTECTION_FROM_FIRE)  // SPPR306.SPL (Protection From Fire)
  CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),MINOR_GLOBE)
  !CheckSpellState(LastSeenBy(Myself),GLOBE)
  !CheckSpellState(LastSeenBy(Myself),SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREPRIEST)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(Myself,CLERIC_PROTECTION_FROM_FIRE)  // SPPR306.SPL (Protection From Fire)
    RemoveSpell(CLERIC_PROTECTION_FROM_FIRE)  // SPPR306.SPL (Protection From Fire)
END

IF
  Global("MO_BUFF","LOCALS",1)
  See([PC])
  HaveSpell(CLERIC_PROTECTION_FROM_FIRE)  // SPPR306.SPL (Protection From Fire)
  CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),MINOR_GLOBE)
  !CheckSpellState(LastSeenBy(Myself),GLOBE)
  !CheckSpellState(LastSeenBy(Myself),SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREPRIEST)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(Myself,CLERIC_PROTECTION_FROM_FIRE)  // SPPR306.SPL (Protection From Fire)
    RemoveSpell(CLERIC_PROTECTION_FROM_FIRE)  // SPPR306.SPL (Protection From Fire)
END

IF
  Global("MO_BUFF","LOCALS",1)
  See(SecondNearest([PC]))
  HaveSpell(CLERIC_PROTECTION_FROM_FIRE)  // SPPR306.SPL (Protection From Fire)
  CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),MINOR_GLOBE)
  !CheckSpellState(LastSeenBy(Myself),GLOBE)
  !CheckSpellState(LastSeenBy(Myself),SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREPRIEST)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(Myself,CLERIC_PROTECTION_FROM_FIRE)  // SPPR306.SPL (Protection From Fire)
    RemoveSpell(CLERIC_PROTECTION_FROM_FIRE)  // SPPR306.SPL (Protection From Fire)
END

IF
  Global("MO_BUFF","LOCALS",1)
  See(ThirdNearest([PC]))
  HaveSpell(CLERIC_PROTECTION_FROM_FIRE)  // SPPR306.SPL (Protection From Fire)
  CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),MINOR_GLOBE)
  !CheckSpellState(LastSeenBy(Myself),GLOBE)
  !CheckSpellState(LastSeenBy(Myself),SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREPRIEST)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(Myself,CLERIC_PROTECTION_FROM_FIRE)  // SPPR306.SPL (Protection From Fire)
    RemoveSpell(CLERIC_PROTECTION_FROM_FIRE)  // SPPR306.SPL (Protection From Fire)
END

IF
  Global("MO_BUFF","LOCALS",1)
  See(FourthNearest([PC]))
  HaveSpell(CLERIC_PROTECTION_FROM_FIRE)  // SPPR306.SPL (Protection From Fire)
  CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),MINOR_GLOBE)
  !CheckSpellState(LastSeenBy(Myself),GLOBE)
  !CheckSpellState(LastSeenBy(Myself),SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREPRIEST)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(Myself,CLERIC_PROTECTION_FROM_FIRE)  // SPPR306.SPL (Protection From Fire)
    RemoveSpell(CLERIC_PROTECTION_FROM_FIRE)  // SPPR306.SPL (Protection From Fire)
END

IF
  Global("MO_BUFF","LOCALS",1)
  See(FifthNearest([PC]))
  HaveSpell(CLERIC_PROTECTION_FROM_FIRE)  // SPPR306.SPL (Protection From Fire)
  CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),MINOR_GLOBE)
  !CheckSpellState(LastSeenBy(Myself),GLOBE)
  !CheckSpellState(LastSeenBy(Myself),SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREPRIEST)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(Myself,CLERIC_PROTECTION_FROM_FIRE)  // SPPR306.SPL (Protection From Fire)
    RemoveSpell(CLERIC_PROTECTION_FROM_FIRE)  // SPPR306.SPL (Protection From Fire)
END

IF
  Global("MO_BUFF","LOCALS",1)
  See(SixthNearest([PC]))
  HaveSpell(CLERIC_PROTECTION_FROM_FIRE)  // SPPR306.SPL (Protection From Fire)
  CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),MINOR_GLOBE)
  !CheckSpellState(LastSeenBy(Myself),GLOBE)
  !CheckSpellState(LastSeenBy(Myself),SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREPRIEST)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(Myself,CLERIC_PROTECTION_FROM_FIRE)  // SPPR306.SPL (Protection From Fire)
    RemoveSpell(CLERIC_PROTECTION_FROM_FIRE)  // SPPR306.SPL (Protection From Fire)
END

IF
  Global("MO_BUFF","LOCALS",1)
  !StateCheck(Myself,STATE_MIRRORIMAGE)
  GlobalLT("MO_UsedIlbratha","GLOBAL",1)
  HasItemEquiped("SW1H26",Myself)  // Ilbratha +1
  !CheckSpellState(Myself,MINOR_GLOBE)
  !CheckSpellState(Myself,GLOBE)
THEN
  RESPONSE #100
    UseItemAbility("SW1H26",Myself,SLOT_AMMO3,1)  // Ilbratha +1
    IncrementGlobal("MO_UsedIlbratha","GLOBAL",1)
END

IF
  Global("MO_BUFF","LOCALS",1)
  !StateCheck(Myself,STATE_MIRRORIMAGE)
  GlobalLT("MO_UsedDuplication","GLOBAL",3)
  HasItemEquiped("OHRRING1",Myself)  // Ring of Duplication
  !CheckSpellState(Myself,MINOR_GLOBE)
  !CheckSpellState(Myself,GLOBE)
THEN
  RESPONSE #100
    UseItem("OHRRING1",Myself)  // Ring of Duplication
    IncrementGlobal("MO_UsedDuplication","GLOBAL",1)
END

IF
  Global("MO_BUFF","LOCALS",1)
  HaveSpell(WIZARD_IMPROVED_HASTE)  // SPWI613.SPL (Improved Haste)
  !CheckStatGT(Myself,0,IMPROVEDHASTE)
  OR(5)
		Class(Myself,THIEF_ALL)
		Class(Myself,FIGHTER_ALL)
		Class(Myself,BARD_ALL)
		Class(Myself,DRUID_ALL)
		Class(Myself,CLERIC_ALL)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(Myself,WIZARD_IMPROVED_HASTE)  // SPWI613.SPL (Improved Haste)
    RemoveSpell(WIZARD_IMPROVED_HASTE)  // SPWI613.SPL (Improved Haste)
END

IF
  Global("MO_BUFF","LOCALS",1)
  HaveSpell(CLERIC_AID)  // SPPR201.SPL (Aid)
  !StateCheck(Myself,STATE_AID)
  !CheckSpellState(Myself,MINOR_GLOBE)
  !CheckSpellState(Myself,GLOBE)
  CheckStatLT(Myself,20,SPELLFAILUREPRIEST)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(Myself,CLERIC_AID)  // SPPR201.SPL (Aid)
    RemoveSpell(CLERIC_AID)  // SPPR201.SPL (Aid)
END

IF
  Global("MO_BUFF","LOCALS",1)
  HaveSpell(CLERIC_MAGIC_RESISTANCE)  // SPPR509.SPL (Magic Resistance)
  CheckStatLT(Myself,20,RESISTMAGIC)
  CheckStatLT(Myself,20,SPELLFAILUREPRIEST)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(Myself,CLERIC_MAGIC_RESISTANCE)  // SPPR509.SPL (Magic Resistance)
    RemoveSpell(CLERIC_MAGIC_RESISTANCE)  // SPPR509.SPL (Magic Resistance)
END

IF
  Global("MO_BUFF","LOCALS",1)
  HaveSpell(WIZARD_PROTECTION_FROM_ENERGY)  // SPWI803.SPL (Protection From Energy)
  !CheckStatGT(Myself,0,WIZARD_PROTECTION_FROM_ENERGY)
  !CheckStatGT(Myself,0,WIZARD_PROTECTION_FROM_THE_ELEMENTS)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_ENERGY)  // SPWI803.SPL (Protection From Energy)
    RemoveSpell(WIZARD_PROTECTION_FROM_ENERGY)  // SPWI803.SPL (Protection From Energy)
END

IF
  Global("MO_BUFF","LOCALS",1)
  HaveSpell(WIZARD_PROTECTION_FROM_THE_ELEMENTS)  // SPWI702.SPL (Protection From The Elements)
  !CheckStatGT(Myself,0,WIZARD_PROTECTION_FROM_ENERGY)
  !CheckStatGT(Myself,0,WIZARD_PROTECTION_FROM_THE_ELEMENTS)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_THE_ELEMENTS)  // SPWI702.SPL (Protection From The Elements)
    RemoveSpell(WIZARD_PROTECTION_FROM_THE_ELEMENTS)  // SPWI702.SPL (Protection From The Elements)
END

IF
  Global("MO_BUFF","LOCALS",1)
  HaveSpell(WIZARD_GLOBE_OF_INVULNERABILITY)  // SPWI602.SPL (Globe of Invulnerability)
  !CheckSpellState(Myself,MINOR_GLOBE)
  !CheckSpellState(Myself,GLOBE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(Myself,WIZARD_GLOBE_OF_INVULNERABILITY)  // SPWI602.SPL (Globe of Invulnerability)
    RemoveSpell(WIZARD_GLOBE_OF_INVULNERABILITY)  // SPWI602.SPL (Globe of Invulnerability)
END

IF
  Global("MO_BUFF","LOCALS",1)
  HaveSpell(WIZARD_MINOR_GLOBE_OF_INVULNERABILITY)  // SPWI406.SPL (Minor Globe of Invulnerability)
  !CheckSpellState(Myself,MINOR_GLOBE)
  !CheckSpellState(Myself,GLOBE)
  !HasImmunityEffects(Myself)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(Myself,WIZARD_MINOR_GLOBE_OF_INVULNERABILITY)  // SPWI406.SPL (Minor Globe of Invulnerability)
    RemoveSpell(WIZARD_MINOR_GLOBE_OF_INVULNERABILITY)  // SPWI406.SPL (Minor Globe of Invulnerability)
END

IF
  Global("MO_BUFF","LOCALS",1)
  GlobalLT("MO_UsedBltMnrInv","GLOBAL",1)
  HasItemEquiped("OHRBELT2",Myself)  // Belt of Minor Invulnerability
  !CheckSpellState(Myself,MINOR_GLOBE)
  !CheckSpellState(Myself,GLOBE)
  Global("MO_CastAthkatla","LOCALS",1)
THEN
  RESPONSE #100
    UseItem("OHRBELT2",Myself)  // Belt of Minor Invulnerability
    IncrementGlobal("MO_UsedBltMnrInv","GLOBAL",1)
END

IF
  Global("MO_BUFF","LOCALS",1)
  HaveSpell(WIZARD_SPELL_IMMUNITY)  // SPWI510.SPL (Spell Immunity)
  !CheckStat(Myself,1,WIZARD_SPELL_IMMUNITY)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(Myself,WIZARD_SPELL_IMMUNITY_ABJURATION)  // SPWI590.SPL (Immunity: Abjuration)
    RemoveSpell(WIZARD_SPELL_IMMUNITY)  // SPWI510.SPL (Spell Immunity)
END

IF
  Global("MO_BUFF","LOCALS",1)
  HaveSpell(CLERIC_RIGHTEOUS_MAGIC)  // SPPR513.SPL (Righteous Magic)
  !CheckSpellState(Myself,RIGHTEOUS_MAGIC)
  CheckStatLT(Myself,20,SPELLFAILUREPRIEST)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(Myself,CLERIC_RIGHTEOUS_MAGIC)  // SPPR513.SPL (Righteous Magic)
    RemoveSpell(CLERIC_RIGHTEOUS_MAGIC)  // SPPR513.SPL (Righteous Magic)
END

IF
  Global("MO_BUFF","LOCALS",1)
  HaveSpell(LATHANDER_BOON)
  !CheckSpellState(Myself,LATHANDER_BOON)
  CheckStatLT(Myself,20,SPELLFAILUREPRIEST)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(Myself,LATHANDER_BOON)
    RemoveSpell(LATHANDER_BOON)
END

IF
  Global("MO_BUFF","LOCALS",1)
  HaveSpell(TALOS_STORMSHIELD)
  !CheckSpellState(Myself,STORM_SHELL)
  CheckStatLT(Myself,20,SPELLFAILUREPRIEST)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(Myself,TALOS_STORMSHIELD)
    RemoveSpell(TALOS_STORMSHIELD)
END

IF
  Global("MO_BUFF","LOCALS",1)
  HaveSpell(CLERIC_AURA_OF_FLAMING_DEATH)  // SPPR730.SPL (Aura of Flaming Death)
  CheckStat(Myself,0,WIZARD_FIRE_SHIELD)
  CheckStatLT(Myself,1,CLERIC_BLADE_BARRIER)
  CheckStatLT(Myself,89,RESISTFIRE)
  CheckStatLT(Myself,20,SPELLFAILUREPRIEST)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(Myself,CLERIC_AURA_OF_FLAMING_DEATH)  // SPPR730.SPL (Aura of Flaming Death)
    RemoveSpell(CLERIC_AURA_OF_FLAMING_DEATH)  // SPPR730.SPL (Aura of Flaming Death)
END

IF
  Global("MO_BUFF","LOCALS",1)
  HaveSpell(WARRIOR_HARDINESS)  // SPCL907.SPL (Hardiness)
  !CheckSpellState(Myself,HARDINESS)
  CheckStatLT(Myself,20,SPELLFAILUREPRIEST)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(Myself,WARRIOR_HARDINESS)  // SPCL907.SPL (Hardiness)
    RemoveSpell(WARRIOR_HARDINESS)  // SPCL907.SPL (Hardiness)
END

IF
  Global("MO_BUFF","LOCALS",1)
  HaveSpell(WIZARD_SPELL_TRAP)  // SPWI902.SPL (Spell Trap)
  CheckStatLT(Myself,1,WIZARD_SPELL_TRAP)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(Myself,WIZARD_SPELL_TRAP)  // SPWI902.SPL (Spell Trap)
    RemoveSpell(WIZARD_SPELL_TRAP)  // SPWI902.SPL (Spell Trap)
END

IF
  Global("MO_BUFF","LOCALS",1)
  HaveSpell(WIZARD_BLACK_BLADE_OF_DISASTER)  // SPWI915.SPL (Black Blade of Disaster)
  !HasItemEquiped("BLAKBLAD",Myself)  // Black Blade of Disaster
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(Myself,WIZARD_BLACK_BLADE_OF_DISASTER)  // SPWI915.SPL (Black Blade of Disaster)
    RemoveSpell(WIZARD_BLACK_BLADE_OF_DISASTER)  // SPWI915.SPL (Black Blade of Disaster)
END

IF
  Global("MO_BUFF","LOCALS",1)
  HaveSpell(CLERIC_GLOBE_OF_BLADES)  // SPPR725.SPL (Globe of Blades)
  CheckStat(Myself,0,WIZARD_FIRE_SHIELD)
  CheckStatLT(Myself,1,CLERIC_BLADE_BARRIER)
  CheckStatLT(Myself,20,SPELLFAILUREPRIEST)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(Myself,CLERIC_GLOBE_OF_BLADES)  // SPPR725.SPL (Globe of Blades)
    RemoveSpell(CLERIC_GLOBE_OF_BLADES)  // SPPR725.SPL (Globe of Blades)
END

IF
  Global("MO_BUFF","LOCALS",1)
  HaveSpell(CLERIC_BLADE_BARRIER)  // SPPR603.SPL (Blade Barrier)
  CheckStat(Myself,0,WIZARD_FIRE_SHIELD)
  CheckStatLT(Myself,1,CLERIC_BLADE_BARRIER)
  CheckStatLT(Myself,20,SPELLFAILUREPRIEST)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(Myself,CLERIC_BLADE_BARRIER)  // SPPR603.SPL (Blade Barrier)
    RemoveSpell(CLERIC_BLADE_BARRIER)  // SPPR603.SPL (Blade Barrier)
END

IF
  Global("MO_BUFF","LOCALS",1)
  HaveSpell(CLERIC_DRAW_UPON_HOLY_MIGHT)  // SPPR214.SPL (Draw Upon Holy Might)
  !StateCheck(Myself,STATE_DRAWUPONHOLYMIGHT)
  CheckStatLT(Myself,25,STR)
  !CheckSpellState(Myself,MINOR_GLOBE)
  !CheckSpellState(Myself,GLOBE)
  CheckStatLT(Myself,20,SPELLFAILUREPRIEST)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(Myself,CLERIC_DRAW_UPON_HOLY_MIGHT)  // SPPR214.SPL (Draw Upon Holy Might)
    RemoveSpell(CLERIC_DRAW_UPON_HOLY_MIGHT)  // SPPR214.SPL (Draw Upon Holy Might)
END

IF
  Global("MO_BUFF","LOCALS",1)
  HaveSpellRES("SPIN103")  // Divine Might
  !StateCheck(Myself,STATE_DRAWUPONHOLYMIGHT)
  CheckStatLT(Myself,25,STR)
  !CheckSpellState(Myself,MINOR_GLOBE)
  !CheckSpellState(Myself,GLOBE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    ReallyForceSpellRES("SPIN103",Myself)  // Divine Might
    RemoveSpellRES("SPIN103")  // Divine Might
END

IF
  Global("MO_BUFF","LOCALS",1)
  HaveSpell(CLERIC_PHYSICAL_MIRROR)  // sppr525.spl (Physical Mirror)
  CheckStatLT(Myself,1,CLERIC_PHYSICAL_MIRROR)
  CheckStatLT(Myself,20,SPELLFAILUREPRIEST)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(Myself,CLERIC_PHYSICAL_MIRROR)  // sppr525.spl (Physical Mirror)
    RemoveSpell(CLERIC_PHYSICAL_MIRROR)  // sppr525.spl (Physical Mirror)
END

IF
  Global("MO_BUFF","LOCALS",1)
  HaveSpell(CLERIC_BLESS)  // SPPR101.SPL (Bless)
  !StateCheck(Myself,STATE_BLESS)
  !CheckSpellState(Myself,MINOR_GLOBE)
  !CheckSpellState(Myself,GLOBE)
  CheckStatLT(Myself,20,SPELLFAILUREPRIEST)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(Myself,CLERIC_BLESS)  // SPPR101.SPL (Bless)
    RemoveSpell(CLERIC_BLESS)  // SPPR101.SPL (Bless)
END

IF
  Global("MO_BUFF","LOCALS",1)
  HaveSpell(CLERIC_DEFENSIVE_HARMONY)  // SPPR406.SPL (Defensive Harmony)
  !CheckSpellState(Myself,GLOBE)
  CheckStatLT(Myself,20,SPELLFAILUREPRIEST)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  CheckStat(Myself,0,CLERIC_DEFENSIVE_HARMONY)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(Myself,CLERIC_DEFENSIVE_HARMONY)  // SPPR406.SPL (Defensive Harmony)
    RemoveSpell(CLERIC_DEFENSIVE_HARMONY)  // SPPR406.SPL (Defensive Harmony)
END

IF
  Global("MO_BUFF","LOCALS",1)
  HaveSpell(CLERIC_NEGATIVE_PLANE_PROTECTION)  // SPPR413.SPL (Negative Plane Protection)
  See(Myself)
  !Kit(LastSeenBy(Myself),UNDEADHUNTER)
  !CheckSpellState(LastSeenBy(Myself),LATHANDER_BOON)
  !CheckSpellState(LastSeenBy(Myself),LEVEL_DRAIN_IMMUNITY)
  !HasItemEquiped("AMUL21",Myself)  // Amulet of Power
  !HasItemEquipedReal("BLUN25",LastSeenBy(Myself))  // Mace of Disruption +2
  !HasItemEquipedReal("SW1H69",LastSeenBy(Myself))  // Spectral Brand +5
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_IMMUNITY)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),GLOBE)
  !CheckSpellState(LastSeenBy(Myself),MINOR_SPELL_TURNING)
  !CheckSpellState(LastSeenBy(Myself),SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREPRIEST)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(LastSeenBy(Myself),CLERIC_NEGATIVE_PLANE_PROTECTION)  // SPPR413.SPL (Negative Plane Protection)
    RemoveSpell(CLERIC_NEGATIVE_PLANE_PROTECTION)  // SPPR413.SPL (Negative Plane Protection)
END

IF
  Global("MO_BUFF","LOCALS",1)
  HaveSpell(CLERIC_NEGATIVE_PLANE_PROTECTION)  // SPPR413.SPL (Negative Plane Protection)
  See([PC])
  !Kit(LastSeenBy(Myself),UNDEADHUNTER)
  !CheckSpellState(LastSeenBy(Myself),LATHANDER_BOON)
  !CheckSpellState(LastSeenBy(Myself),LEVEL_DRAIN_IMMUNITY)
  !HasItemEquiped("AMUL21",Myself)  // Amulet of Power
  !HasItemEquipedReal("BLUN25",LastSeenBy(Myself))  // Mace of Disruption +2
  !HasItemEquipedReal("SW1H69",LastSeenBy(Myself))  // Spectral Brand +5
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_IMMUNITY)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),GLOBE)
  !CheckSpellState(LastSeenBy(Myself),MINOR_SPELL_TURNING)
  !CheckSpellState(LastSeenBy(Myself),SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREPRIEST)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(LastSeenBy(Myself),CLERIC_NEGATIVE_PLANE_PROTECTION)  // SPPR413.SPL (Negative Plane Protection)
    RemoveSpell(CLERIC_NEGATIVE_PLANE_PROTECTION)  // SPPR413.SPL (Negative Plane Protection)
END

IF
  Global("MO_BUFF","LOCALS",1)
  HaveSpell(CLERIC_NEGATIVE_PLANE_PROTECTION)  // SPPR413.SPL (Negative Plane Protection)
  See(SecondNearest([PC]))
  !Kit(LastSeenBy(Myself),UNDEADHUNTER)
  !CheckSpellState(LastSeenBy(Myself),LATHANDER_BOON)
  !CheckSpellState(LastSeenBy(Myself),LEVEL_DRAIN_IMMUNITY)
  !HasItemEquiped("AMUL21",Myself)  // Amulet of Power
  !HasItemEquipedReal("BLUN25",LastSeenBy(Myself))  // Mace of Disruption +2
  !HasItemEquipedReal("SW1H69",LastSeenBy(Myself))  // Spectral Brand +5
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_IMMUNITY)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),GLOBE)
  !CheckSpellState(LastSeenBy(Myself),MINOR_SPELL_TURNING)
  !CheckSpellState(LastSeenBy(Myself),SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREPRIEST)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(LastSeenBy(Myself),CLERIC_NEGATIVE_PLANE_PROTECTION)  // SPPR413.SPL (Negative Plane Protection)
    RemoveSpell(CLERIC_NEGATIVE_PLANE_PROTECTION)  // SPPR413.SPL (Negative Plane Protection)
END

IF
  Global("MO_BUFF","LOCALS",1)
  HaveSpell(CLERIC_NEGATIVE_PLANE_PROTECTION)  // SPPR413.SPL (Negative Plane Protection)
  See(ThirdNearest([PC]))
  !Kit(LastSeenBy(Myself),UNDEADHUNTER)
  !CheckSpellState(LastSeenBy(Myself),LATHANDER_BOON)
  !CheckSpellState(LastSeenBy(Myself),LEVEL_DRAIN_IMMUNITY)
  !HasItemEquiped("AMUL21",Myself)  // Amulet of Power
  !HasItemEquipedReal("BLUN25",LastSeenBy(Myself))  // Mace of Disruption +2
  !HasItemEquipedReal("SW1H69",LastSeenBy(Myself))  // Spectral Brand +5
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_IMMUNITY)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),GLOBE)
  !CheckSpellState(LastSeenBy(Myself),MINOR_SPELL_TURNING)
  !CheckSpellState(LastSeenBy(Myself),SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREPRIEST)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(LastSeenBy(Myself),CLERIC_NEGATIVE_PLANE_PROTECTION)  // SPPR413.SPL (Negative Plane Protection)
    RemoveSpell(CLERIC_NEGATIVE_PLANE_PROTECTION)  // SPPR413.SPL (Negative Plane Protection)
END

IF
  Global("MO_BUFF","LOCALS",1)
  HaveSpell(CLERIC_NEGATIVE_PLANE_PROTECTION)  // SPPR413.SPL (Negative Plane Protection)
  See(FourthNearest([PC]))
  !Kit(LastSeenBy(Myself),UNDEADHUNTER)
  !CheckSpellState(LastSeenBy(Myself),LATHANDER_BOON)
  !CheckSpellState(LastSeenBy(Myself),LEVEL_DRAIN_IMMUNITY)
  !HasItemEquiped("AMUL21",Myself)  // Amulet of Power
  !HasItemEquipedReal("BLUN25",LastSeenBy(Myself))  // Mace of Disruption +2
  !HasItemEquipedReal("SW1H69",LastSeenBy(Myself))  // Spectral Brand +5
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_IMMUNITY)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),GLOBE)
  !CheckSpellState(LastSeenBy(Myself),MINOR_SPELL_TURNING)
  !CheckSpellState(LastSeenBy(Myself),SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREPRIEST)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(LastSeenBy(Myself),CLERIC_NEGATIVE_PLANE_PROTECTION)  // SPPR413.SPL (Negative Plane Protection)
    RemoveSpell(CLERIC_NEGATIVE_PLANE_PROTECTION)  // SPPR413.SPL (Negative Plane Protection)
END

IF
  Global("MO_BUFF","LOCALS",1)
  HaveSpell(CLERIC_NEGATIVE_PLANE_PROTECTION)  // SPPR413.SPL (Negative Plane Protection)
  See(FifthNearest([PC]))
  !Kit(LastSeenBy(Myself),UNDEADHUNTER)
  !CheckSpellState(LastSeenBy(Myself),LATHANDER_BOON)
  !CheckSpellState(LastSeenBy(Myself),LEVEL_DRAIN_IMMUNITY)
  !HasItemEquiped("AMUL21",Myself)  // Amulet of Power
  !HasItemEquipedReal("BLUN25",LastSeenBy(Myself))  // Mace of Disruption +2
  !HasItemEquipedReal("SW1H69",LastSeenBy(Myself))  // Spectral Brand +5
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_IMMUNITY)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),GLOBE)
  !CheckSpellState(LastSeenBy(Myself),MINOR_SPELL_TURNING)
  !CheckSpellState(LastSeenBy(Myself),SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREPRIEST)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(LastSeenBy(Myself),CLERIC_NEGATIVE_PLANE_PROTECTION)  // SPPR413.SPL (Negative Plane Protection)
    RemoveSpell(CLERIC_NEGATIVE_PLANE_PROTECTION)  // SPPR413.SPL (Negative Plane Protection)
END

IF
  Global("MO_BUFF","LOCALS",1)
  HaveSpell(CLERIC_NEGATIVE_PLANE_PROTECTION)  // SPPR413.SPL (Negative Plane Protection)
  See(SixthNearest([PC]))
  !Kit(LastSeenBy(Myself),UNDEADHUNTER)
  !CheckSpellState(LastSeenBy(Myself),LATHANDER_BOON)
  !CheckSpellState(LastSeenBy(Myself),LEVEL_DRAIN_IMMUNITY)
  !HasItemEquiped("AMUL21",Myself)  // Amulet of Power
  !HasItemEquipedReal("BLUN25",LastSeenBy(Myself))  // Mace of Disruption +2
  !HasItemEquipedReal("SW1H69",LastSeenBy(Myself))  // Spectral Brand +5
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_IMMUNITY)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckSpellState(LastSeenBy(Myself),GLOBE)
  !CheckSpellState(LastSeenBy(Myself),MINOR_SPELL_TURNING)
  !CheckSpellState(LastSeenBy(Myself),SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREPRIEST)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    ReallyForceSpell(LastSeenBy(Myself),CLERIC_NEGATIVE_PLANE_PROTECTION)  // SPPR413.SPL (Negative Plane Protection)
    RemoveSpell(CLERIC_NEGATIVE_PLANE_PROTECTION)  // SPPR413.SPL (Negative Plane Protection)
END

IF
  Global("MO_BUFF","LOCALS",1)
  HaveSpell(BERSERKER_RAGE)  // SPCL321.SPL (Enrage)
  !CheckSpellState(Myself,BERSERKER_RAGE_FATIGUE)
  !CheckSpellState(Myself,BERSERKER_RAGE)
THEN
  RESPONSE #100
    Spell(Myself,BERSERKER_RAGE)  // SPCL321.SPL (Enrage)
END

IF
  Global("MO_BUFF","LOCALS",1)
  HaveSpell(BARBARIAN_RAGE)  // SPCL152.SPL (Barbarian Rage)
  !CheckSpellState(Myself,BARBARIAN_RAGE)
THEN
  RESPONSE #100
    Spell(Myself,BARBARIAN_RAGE)  // SPCL152.SPL (Barbarian Rage)
END

IF
  Global("MO_BUFF","LOCALS",1)
THEN
  RESPONSE #100
    SetGlobal("MO_BUFF","LOCALS",0)
    DisplayStringHead(Myself,421)  // Combat ready!
END
