///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Import AI Scripts into the Game                                       //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Copy .BS files to scripts folder                                      //
///////////////////////////////////////////////////////////////////////////

ACTION_IF (MOD_IS_INSTALLED ~setup-spell_rev.tp2~ ~0~) BEGIN
	COPY ~powergamingscripts/baf/Accelerated/SR/Archer.baf~      ~scripts/Archer.bs~
	     ~powergamingscripts/baf/Accelerated/SR/ClerRang.baf~    ~scripts/ClerRang.bs~
	     ~powergamingscripts/baf/Accelerated/SR/FigMagCl.baf~    ~scripts/FigMagCl.bs~
	     ~powergamingscripts/baf/Accelerated/SR/FigMage.baf~     ~scripts/FigMage.bs~
	     ~powergamingscripts/baf/Accelerated/SR/Inquis.baf~      ~scripts/Inquis.bs~
	     ~powergamingscripts/baf/Accelerated/SR/Monk.baf~        ~scripts/Monk.bs~
	     ~powergamingscripts/baf/Accelerated/SR/Skald.baf~       ~scripts/Skald.bs~
	     ~powergamingscripts/baf/Accelerated/SR/Sorcerer.baf~    ~scripts/Sorcerer.bs~
	     ~powergamingscripts/baf/Accelerated/SR/BasicAI.baf~     ~scripts/BasicAI.bs~
	  COMPILE_BAF_TO_BCS
END
ELSE ACTION_IF (MOD_IS_INSTALLED ~setup-stratagems.tp2~ ~1500~ && MOD_IS_INSTALLED ~setup-stratagems.tp2~ ~1510~) || (MOD_IS_INSTALLED ~iwdification/setup-iwdification.tp2~ 30 && MOD_IS_INSTALLED ~iwdification/setup-iwdification.tp2~ 40) BEGIN
	COPY ~powergamingscripts/baf/Accelerated/IWD/Archer.baf~      ~scripts/Archer.bs~
	     ~powergamingscripts/baf/Accelerated/IWD/ClerRang.baf~    ~scripts/ClerRang.bs~
	     ~powergamingscripts/baf/Accelerated/IWD/FigMagCl.baf~    ~scripts/FigMagCl.bs~
	     ~powergamingscripts/baf/Accelerated/IWD/FigMage.baf~     ~scripts/FigMage.bs~
	     ~powergamingscripts/baf/Accelerated/IWD/Inquis.baf~      ~scripts/Inquis.bs~
	     ~powergamingscripts/baf/Accelerated/IWD/Monk.baf~        ~scripts/Monk.bs~
	     ~powergamingscripts/baf/Accelerated/IWD/Skald.baf~       ~scripts/Skald.bs~
	     ~powergamingscripts/baf/Accelerated/IWD/Sorcerer.baf~    ~scripts/Sorcerer.bs~
	     ~powergamingscripts/baf/Accelerated/IWD/BasicAI.baf~     ~scripts/BasicAI.bs~
	  COMPILE_BAF_TO_BCS
END
ELSE BEGIN
	COPY ~powergamingscripts/baf/Accelerated/Archer.baf~      ~scripts/Archer.bs~
	     ~powergamingscripts/baf/Accelerated/ClerRang.baf~    ~scripts/ClerRang.bs~
	     ~powergamingscripts/baf/Accelerated/FigMagCl.baf~    ~scripts/FigMagCl.bs~
	     ~powergamingscripts/baf/Accelerated/FigMage.baf~     ~scripts/FigMage.bs~
	     ~powergamingscripts/baf/Accelerated/Inquis.baf~      ~scripts/Inquis.bs~
	     ~powergamingscripts/baf/Accelerated/Monk.baf~        ~scripts/Monk.bs~
	     ~powergamingscripts/baf/Accelerated/Skald.baf~       ~scripts/Skald.bs~
	     ~powergamingscripts/baf/Accelerated/Sorcerer.baf~    ~scripts/Sorcerer.bs~
	     ~powergamingscripts/baf/Accelerated/BasicAI.baf~     ~scripts/BasicAI.bs~
	  COMPILE_BAF_TO_BCS
END
///////////////////////////////////////////////////////////////////////////
// Add descriptions of the scripts to scrpdesc.2da                       //
///////////////////////////////////////////////////////////////////////////

APPEND ~scrpdesc.2DA~
~Archer      999990       999989
ClerRang     999988       999987
FigMagCl     999986       999985
FigMage      999984       999983
Inquis       999982       999981
Monk         999980       999979
Skald        999978       999977
Sorcerer     999976       999975
BasicAI		 999974		  999973~

///////////////////////////////////////////////////////////////////////////
// Copy the appended scrpdesc.2da to the override folder                 //
///////////////////////////////////////////////////////////////////////////

COPY_EXISTING ~scrpdesc.2da~ ~override~
REPLACE ~999990~ @1010
REPLACE ~999989~ @1011
REPLACE ~999988~ @1020
REPLACE ~999987~ @1021
REPLACE ~999986~ @1030
REPLACE ~999985~ @1031
REPLACE ~999984~ @1040
REPLACE ~999983~ @1041
REPLACE ~999982~ @1050
REPLACE ~999981~ @1051
REPLACE ~999980~ @1060
REPLACE ~999979~ @1061
REPLACE ~999978~ @1070
REPLACE ~999977~ @1071
REPLACE ~999976~ @1080
REPLACE ~999975~ @1081
REPLACE ~999974~ @1090
REPLACE ~999973~ @1091