COPY ~enhanced-powergaming-scripts/baf/upload/morang.baf~ ~enhanced-powergaming-scripts/baf/upload/morang.baf~

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Remove Script Dialog                                                  //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Remove Potion Use Dialog @5005                                        //
///////////////////////////////////////////////////////////////////////////
  LPF REPLACE_MULTILINE
    INT_VAR
    strict = 1
    verbose = 0
    warn = 0
    STR_VAR
    pattern = ~~~~~DisplayStringHead(Myself,@5005)
END~~~~~
    string = ~~~~~END~~~~~ //"
  END

///////////////////////////////////////////////////////////////////////////
// Remove Protect Spell Dialog @5006                                     //
///////////////////////////////////////////////////////////////////////////
  LPF REPLACE_MULTILINE
    INT_VAR
    strict = 1
    verbose = 0
    warn = 0
    STR_VAR
    pattern = ~~~~~SetInterrupt(FALSE)
    DisplayStringHead(Myself,@5006)~~~~~
    string = ~~~~~SetInterrupt(FALSE)~~~~~ //"
  END

///////////////////////////////////////////////////////////////////////////
// Remove Sanctuary Dialog @5007                                         //
///////////////////////////////////////////////////////////////////////////
  LPF REPLACE_MULTILINE
    INT_VAR
    strict = 1
    verbose = 0
    warn = 0
    STR_VAR
    pattern = ~~~~~SetInterrupt(FALSE)
    DisplayStringHead(Myself,@5007)~~~~~
    string = ~~~~~SetInterrupt(FALSE)~~~~~ //"
  END

///////////////////////////////////////////////////////////////////////////
// Remove Raise Dead Dialog @5008                                        //
///////////////////////////////////////////////////////////////////////////
  LPF REPLACE_MULTILINE
    INT_VAR
    strict = 1
    verbose = 0
    warn = 0
    STR_VAR
    pattern = ~~~~~SetInterrupt(FALSE)
    DisplayStringHead(Myself,@5008)~~~~~
    string = ~~~~~SetInterrupt(FALSE)~~~~~ //"
  END

///////////////////////////////////////////////////////////////////////////
// Remove Restoration Dialog @5009                                       //
///////////////////////////////////////////////////////////////////////////
  LPF REPLACE_MULTILINE
    INT_VAR
    strict = 1
    verbose = 0
    warn = 0
    STR_VAR
    pattern = ~~~~~SetInterrupt(FALSE)
    DisplayStringHead(Myself,@5009)~~~~~
    string = ~~~~~SetInterrupt(FALSE)~~~~~ //"
  END

///////////////////////////////////////////////////////////////////////////
// Remove Paralysis Dialog @5010                                         //
///////////////////////////////////////////////////////////////////////////
  LPF REPLACE_MULTILINE
    INT_VAR
    strict = 1
    verbose = 0
    warn = 0
    STR_VAR
    pattern = ~~~~~SetInterrupt(FALSE)
    DisplayStringHead(Myself,@5010)~~~~~
    string = ~~~~~SetInterrupt(FALSE)~~~~~ //"
  END

///////////////////////////////////////////////////////////////////////////
// Remove Poison Dialog @5011                                            //
///////////////////////////////////////////////////////////////////////////
  LPF REPLACE_MULTILINE
    INT_VAR
    strict = 1
    verbose = 0
    warn = 0
    STR_VAR
    pattern = ~~~~~SetInterrupt(FALSE)
    DisplayStringHead(Myself,@5011)~~~~~
    string = ~~~~~SetInterrupt(FALSE)~~~~~ //"
  END

///////////////////////////////////////////////////////////////////////////
// Remove Fear Dialog @5012                                              //
///////////////////////////////////////////////////////////////////////////
  LPF REPLACE_MULTILINE
    INT_VAR
    strict = 1
    verbose = 0
    warn = 0
    STR_VAR
    pattern = ~~~~~SetInterrupt(FALSE)
    DisplayStringHead(Myself,@5012)~~~~~
    string = ~~~~~SetInterrupt(FALSE)~~~~~ //"
  END

///////////////////////////////////////////////////////////////////////////
// Remove Toxic Cloud Dialog @5013                                       //
///////////////////////////////////////////////////////////////////////////
  LPF REPLACE_MULTILINE
    INT_VAR
    strict = 1
    verbose = 0
    warn = 0
    STR_VAR
    pattern = ~~~~~SetInterrupt(FALSE)
    DisplayStringHead(Myself,@5013)~~~~~
    string = ~~~~~SetInterrupt(FALSE)~~~~~ //"
  END

///////////////////////////////////////////////////////////////////////////
// Remove Invisibility Dialog @5014                                      //
///////////////////////////////////////////////////////////////////////////
  LPF REPLACE_MULTILINE
    INT_VAR
    strict = 1
    verbose = 0
    warn = 0
    STR_VAR
    pattern = ~~~~~SetInterrupt(FALSE)
    DisplayStringHead(Myself,@5014)~~~~~
    string = ~~~~~SetInterrupt(FALSE)~~~~~ //"
  END

///////////////////////////////////////////////////////////////////////////
// Remove Combat Protections Dialog @5015                                //
///////////////////////////////////////////////////////////////////////////
  LPF REPLACE_MULTILINE
    INT_VAR
    strict = 1
    verbose = 0
    warn = 0
    STR_VAR
    pattern = ~~~~~SetInterrupt(FALSE)
    DisplayStringHead(Myself,@5015)~~~~~
    string = ~~~~~SetInterrupt(FALSE)~~~~~ //"
  END

///////////////////////////////////////////////////////////////////////////
// Remove Spell Protections Dialog @5016                                 //
///////////////////////////////////////////////////////////////////////////
  LPF REPLACE_MULTILINE
    INT_VAR
    strict = 1
    verbose = 0
    warn = 0
    STR_VAR
    pattern = ~~~~~SetInterrupt(FALSE)
    DisplayStringHead(Myself,@5016)~~~~~
    string = ~~~~~SetInterrupt(FALSE)~~~~~ //"
  END

///////////////////////////////////////////////////////////////////////////
// Remove Illusions Dialog @5017                                         //
///////////////////////////////////////////////////////////////////////////
  LPF REPLACE_MULTILINE
    INT_VAR
    strict = 1
    verbose = 0
    warn = 0
    STR_VAR
    pattern = ~~~~~SetInterrupt(FALSE)
    DisplayStringHead(Myself,@5017)~~~~~
    string = ~~~~~SetInterrupt(FALSE)~~~~~ //"
  END