LOAD_TRA ~enhanced-powergaming-scripts/languages/%LANGUAGE%/script_dialog.tra~

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Enhanced Scripts for Summoned Celestials                              //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

ACTION_IF spell_revisions BEGIN
	COPY ~enhanced-powergaming-scripts/baf/celestials/sr/deva.baf~   	~enhanced-powergaming-scripts/baf/upload/devaevil.baf~
	COPY ~enhanced-powergaming-scripts/baf/celestials/sr/plangood.baf~  ~enhanced-powergaming-scripts/baf/upload/plangood.baf~
END ELSE BEGIN
	COPY ~enhanced-powergaming-scripts/baf/celestials/deva.baf~  		~enhanced-powergaming-scripts/baf/upload/devaevil.baf~
	COPY ~enhanced-powergaming-scripts/baf/celestials/plangood.baf~   	~enhanced-powergaming-scripts/baf/upload/plangood.baf~
END

///////////////////////////////////////////////////////////////////////////
// Update Hot Keys                                                       //
///////////////////////////////////////////////////////////////////////////
INCLUDE ~enhanced-powergaming-scripts/lib/deva_hotkey.tph~
INCLUDE ~enhanced-powergaming-scripts/lib/plangood_hotkey.tph~

///////////////////////////////////////////////////////////////////////////
// Good Deva                                                             //
///////////////////////////////////////////////////////////////////////////
COPY ~enhanced-powergaming-scripts/baf/upload/devaevil.baf~   		~enhanced-powergaming-scripts/baf/upload/devagood.baf~

///////////////////////////////////////////////////////////////////////////
// Copy .BCS files to override folder                                    //
///////////////////////////////////////////////////////////////////////////
COPY ~enhanced-powergaming-scripts/baf/upload/devaevil.baf~   	   ~override/devaevil.bcs~
	 ~enhanced-powergaming-scripts/baf/upload/devagood.baf~   	   ~override/devagood.bcs~
	 ~enhanced-powergaming-scripts/baf/upload/plangood.baf~   	   ~override/plangood.bcs~
  COMPILE_BAF_TO_BCS