///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Enhanced Scripts for Summoned Celestials                              //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

ACTION_IF (MOD_IS_INSTALLED ~setup-spell_rev.tp2~ ~0~) BEGIN
	COPY ~enhanced-powergaming-scripts/baf/sr/devaevil.baf~   ~enhanced-powergaming-scripts/baf/upload/devaevil.baf~
	COPY ~enhanced-powergaming-scripts/baf/sr/devagood.baf~   ~enhanced-powergaming-scripts/baf/upload/devagood.baf~
	COPY ~enhanced-powergaming-scripts/baf/sr/plangood.baf~   ~enhanced-powergaming-scripts/baf/upload/plangood.baf~
END ELSE BEGIN
	COPY ~enhanced-powergaming-scripts/baf/devaevil.baf~   ~enhanced-powergaming-scripts/baf/upload/devaevil.baf~
	COPY ~enhanced-powergaming-scripts/baf/devagood.baf~   ~enhanced-powergaming-scripts/baf/upload/devagood.baf~
	COPY ~enhanced-powergaming-scripts/baf/plangood.baf~   ~enhanced-powergaming-scripts/baf/upload/plangood.baf~
END

///////////////////////////////////////////////////////////////////////////
// Copy .BCS files to override folder                                    //
///////////////////////////////////////////////////////////////////////////
COPY ~enhanced-powergaming-scripts/baf/upload/devaevil.baf~   	   ~override/devaevil.bcs~
	 ~enhanced-powergaming-scripts/baf/upload/devagood.baf~   	   ~override/devagood.bcs~
	 ~enhanced-powergaming-scripts/baf/upload/plangood.baf~   	   ~override/plangood.bcs~
  COMPILE_BAF_TO_BCS