LOAD_TRA ~enhanced-powergaming-scripts/languages/%LANGUAGE%/script_dialog.tra~

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Enhanced Scripts for Summoned Celestials                              //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Spell Revisions                                                       //
///////////////////////////////////////////////////////////////////////////
ACTION_IF spell_revisions BEGIN
	COPY ~enhanced-powergaming-scripts/baf/celestials/sr/deva.baf~   	~enhanced-powergaming-scripts/baf/upload/devaevil.baf~
	COPY ~enhanced-powergaming-scripts/baf/celestials/sr/plangood.baf~  ~enhanced-powergaming-scripts/baf/upload/plangood.baf~

///////////////////////////////////////////////////////////////////////////
// SR - d5 Random Tweaks - Cure Bypass Deflection                        //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF d5_deflected BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/celestial/sr_deva_d5_cure_dispelling.tph~
		INCLUDE ~enhanced-powergaming-scripts/lib/celestial/sr_planet_d5_cure_dispelling.tph~
	END

///////////////////////////////////////////////////////////////////////////
// Non-Spell Revisions                                                   //
///////////////////////////////////////////////////////////////////////////
END ELSE BEGIN
	COPY ~enhanced-powergaming-scripts/baf/celestials/deva.baf~  		~enhanced-powergaming-scripts/baf/upload/devaevil.baf~
	COPY ~enhanced-powergaming-scripts/baf/celestials/plangood.baf~   	~enhanced-powergaming-scripts/baf/upload/plangood.baf~

///////////////////////////////////////////////////////////////////////////
// d5 Random Tweaks - Cure Bypass Deflection                             //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF d5_deflected BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/celestial/deva_d5_cure_dispelling.tph~
		INCLUDE ~enhanced-powergaming-scripts/lib/celestial/planet_d5_cure_dispelling.tph~
	END
END

ACTION_IF GAME_IS ~iwdee~ BEGIN
	INCLUDE ~enhanced-powergaming-scripts/lib/iwdee/remove_wight_deva.tph~
	INCLUDE ~enhanced-powergaming-scripts/lib/iwdee/remove_wight_plan.tph~
END

COPY_EXISTING ~devagood.bcs~ 	~override/mogdd02.bcs~
COPY_EXISTING ~devaevil.bcs~ 	~override/moevd02.bcs~
COPY_EXISTING ~plangood.bcs~ 	~override/mopln02.bcs~ 

COPY ~enhanced-powergaming-scripts/baf/celestials/mopln01.baf~ ~enhanced-powergaming-scripts/baf/upload/mopln01.baf~
COPY ~enhanced-powergaming-scripts/baf/celestials/moevd01.baf~ ~enhanced-powergaming-scripts/baf/upload/moevd01.baf~
COPY ~enhanced-powergaming-scripts/baf/celestials/mogdd01.baf~ ~enhanced-powergaming-scripts/baf/upload/mogdd01.baf~

///////////////////////////////////////////////////////////////////////////
// EEex Check                                                            //
///////////////////////////////////////////////////////////////////////////
ACTION_IF NOT eeex_present BEGIN
	INCLUDE ~enhanced-powergaming-scripts/lib/celestial/deva_eeex.tph~
	INCLUDE ~enhanced-powergaming-scripts/lib/celestial/plan_eeex.tph~
END

///////////////////////////////////////////////////////////////////////////
// Update Hot Keys                                                       //
///////////////////////////////////////////////////////////////////////////
INCLUDE ~enhanced-powergaming-scripts/lib/deva_hotkey.tph~
INCLUDE ~enhanced-powergaming-scripts/lib/plangood_hotkey.tph~

///////////////////////////////////////////////////////////////////////////
// Good Deva                                                             //
///////////////////////////////////////////////////////////////////////////
COPY ~enhanced-powergaming-scripts/baf/upload/devaevil.baf~   		~enhanced-powergaming-scripts/baf/upload/devagood.baf~
INCLUDE ~enhanced-powergaming-scripts/lib/deva_switch.tph~ 

///////////////////////////////////////////////////////////////////////////
// Copy .BCS files to override folder                                    //
///////////////////////////////////////////////////////////////////////////
COPY ~enhanced-powergaming-scripts/baf/upload/devaevil.baf~   	   ~override/moevd03.bcs~
	 ~enhanced-powergaming-scripts/baf/upload/devagood.baf~   	   ~override/mogdd03.bcs~
	 ~enhanced-powergaming-scripts/baf/upload/plangood.baf~   	   ~override/mopln03.bcs~
	 ~enhanced-powergaming-scripts/baf/upload/mopln01.baf~		   ~override/plangood.bcs~
	 ~enhanced-powergaming-scripts/baf/upload/moevd01.baf~		   ~override/devaevil.bcs~
	 ~enhanced-powergaming-scripts/baf/upload/mogdd01.baf~		   ~override/devagood.bcs~
  COMPILE_BAF_TO_BCS