LOAD_TRA ~enhanced-powergaming-scripts/languages/%LANGUAGE%/script_dialog.tra~

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Final Modifications to Base Script                                    //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Faiths & Powers - Cleric Kits                                         //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF fp_cleric BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/prebuff_fp_cleric_kit.tph~
	END

///////////////////////////////////////////////////////////////////////////
// Faiths & Powers - Paladin Kits                                        //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF fp_paladin BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/prebuff_fp_paladin_kit.tph~
	END

///////////////////////////////////////////////////////////////////////////
// MiH - Arcane Spells Major Globe                                       //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF mih_arcane BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/core_mih_globe.tph~
	END

///////////////////////////////////////////////////////////////////////////
// Skills and Abilities Psi Warrior                                      //
///////////////////////////////////////////////////////////////////////////
ACTION_IF psi_warrior BEGIN
	INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/prebuff_core_psi_warrior.tph~
END

///////////////////////////////////////////////////////////////////////////
// Remove Athkatla Check from Pre-Buffing (BGEE ONLY)                    //
///////////////////////////////////////////////////////////////////////////
ACTION_IF GAME_IS ~bgee~ BEGIN
	INCLUDE ~enhanced-powergaming-scripts/lib/BGEE/bgee_remove_athkatla.tph~
END

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// SR - Split up and Modify Individual Scripts                           //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
ACTION_IF spell_revisions BEGIN

///////////////////////////////////////////////////////////////////////////
// SR - Build out MO-Core                                                //
///////////////////////////////////////////////////////////////////////////	
	INCLUDE ~enhanced-powergaming-scripts/lib/sr_core_base.tph~
	
	ACTION_IF GAME_IS ~bgee~ BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/bgee/sr_core_bgee.tph~
	END

/*
///////////////////////////////////////////////////////////////////////////
// BGEE Wight Check                                                      //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF GAME_IS ~bgee~ BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/ini/remove_wight.tph~
	END
*/

///////////////////////////////////////////////////////////////////////////
// SR - 5e Spellcasting                                                  //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF 5e_spellcasting BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/sr_core_5e.tph~

		ACTION_FOR_EACH 5e_spell IN
				WIZARD_VOCALIZE
				WIZARD_ABSOLUTE_IMMUNITY
				WIZARD_PROTECTION_FROM_MAGIC_WEAPONS
				WIZARD_MOMENT_OF_PRESCIENCE
				WIZARD_MANTLE
				WIZARD_STONE_SKIN
				CLERIC_IRONSKIN
				WIZARD_ARMOR
				WIZARD_MIND_BLANK
				CLERIC_SANCTUARY
				CLERIC_MASS_RAISE_DEAD
				CLERIC_RESURRECTION
				CLERIC_RAISE_DEAD
				CLERIC_BREAK_ENCHANTMENT
				WIZARD_BREAK_ENCHANTMENT
				CLERIC_RESTORATION
				CLERIC_LESSER_RESTORATION
				CLERIC_REMOVE_PARALYSIS
				CLERIC_CURE_DISEASE
				CLERIC_NEUTRALIZE_POISON
				CLERIC_SLOW_POISON
				WIZARD_RESIST_FEAR
				CLERIC_REMOVE_FEAR
				CLERIC_GUST_OF_WIND
				WIZARD_TRUE_SIGHT
				CLERIC_TRUE_SIGHT
				WIZARD_DETECT_INVISIBILITY
				CLERIC_INVISIBILITY_PURGE
				WIZARD_BREACH
				WIZARD_PIERCE_SHIELD
				WIZARD_SPELL_THRUST
				WIZARD_SECRET_WORD
				WIZARD_PIERCE_MAGIC
				WIZARD_WARDING_WHIP
				WIZARD_RUBY_RAY_OF_REVERSAL
				WIZARD_SPELL_STRIKE
				WIZARD_MELF_METEOR
				CLERIC_HEAL
				CLERIC_CURE_SERIOUS_WOUNDS
				CLERIC_CURE_MEDIUM_WOUNDS
				CLERIC_CURE_MODERATE_WOUNDS
				CLERIC_CURE_LIGHT_WOUNDS
				WIZARD_SPELL_SHIELD
				WIZARD_SPELL_TRAP
				WIZARD_GREATER_SPELL_DEFLECTION
				WIZARD_SPELL_DEFLECTION
				WIZARD_MINOR_SPELL_DEFLECTION
				CLERIC_AURA_OF_FLAMING_DEATH
				CLERIC_GLOBE_OF_BLADES
				WIZARD_MESTILS_ACID_SHEATH
				WIZARD_FIRE_SHIELD_RED
				CLERIC_SHIELD_OF_THE_ARCHONS
				WIZARD_PROTECTION_FROM_NORMAL_MISSILES
				CLERIC_PHYSICAL_MIRROR
				CLERIC_BLADE_BARRIER
				CLERIC_DRAW_UPON_HOLY_MIGHT
				CLERIC_ARMOR_OF_FAITH
				CLERIC_PROTECTION_FROM_FIRE
				WIZARD_MIRROR_IMAGE
				WIZARD_IMPROVED_HASTE
				WIZARD_TRUE_STRIKE
				WIZARD_MAGIC_MISSILE
				CLERIC_DOOM
				CLERIC_INSECT_PLAGUE
				CLERIC_SUNRAY
				CLERIC_FALSE_DAWN
				CLERIC_HOLD_PERSON
				CLERIC_SILENCE_15_FOOT
				CLERIC_MISCAST_MAGIC
				CLERIC_GREATER_COMMAND
				CLERIC_COMMAND
				CLERIC_RIGHTEOUS_MAGIC
				WIZARD_GREATER_MALISON
				WIZARD_LOWER_RESISTANCE
				WIZARD_SLOW
				WIZARD_SLEEP
				WIZARD_HOLD_PERSON
				WIZARD_CONFUSION
				WIZARD_EMOTION_HOPELESSNESS
				WIZARD_CHAOS
			BEGIN
				LAF RES_NUM_OF_SPELL_NAME STR_VAR spell_name = ~%5e_spell%~ RET spell_res END
				COPY ~enhanced-powergaming-scripts/baf/upload/mocore.baf~ ~enhanced-powergaming-scripts/baf/upload/mocore.baf~
					REPLACE_TEXTUALLY CASE_INSENSITIVE ~RES(%5e_spell%~ ~RES(%spell_res%~
			END
	END

///////////////////////////////////////////////////////////////////////////
// SR - Turn Undead Overhaul                                             //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF turn_undead BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/bg2ee/core_turn_undead.tph~
	END

///////////////////////////////////////////////////////////////////////////
// SR - DSotSC                                                           //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF dsotsc_divine && !mih_divine && !iwdification BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/core_dsotsc_d.tph~
	END

///////////////////////////////////////////////////////////////////////////
// SR - Tome & Blood                                                     //
///////////////////////////////////////////////////////////////////////////
	// Invisibility Changes
	ACTION_IF tome_and_blood BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/sr_core_tb_inv.tph~
	END

///////////////////////////////////////////////////////////////////////////
// SR - Faiths & Powers - Ranger Kits                                    //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF fp_ranger BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/sr_ranger_fp_kit.tph~
	END

///////////////////////////////////////////////////////////////////////////
// SR - Faiths & Powers - Paladin Kits                                   //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF fp_paladin BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/paladin_fp_kit.tph~
	END

///////////////////////////////////////////////////////////////////////////
// SR - MiH Spell Restorations                                           //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF mih_restorations BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/sr_core_mih_sr.tph~

		ACTION_IF 5e_spellcasting BEGIN
			INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/sr_core_mih_sr_5e.tph~

			ACTION_FOR_EACH 5e_mih_sr IN
				CLERIC_CURE_BLIND_DEAF
			BEGIN
				LAF RES_NUM_OF_SPELL_NAME STR_VAR spell_name = ~%5e_mih_sr%~ RET spell_res END
				COPY ~enhanced-powergaming-scripts/baf/upload/mocore.baf~ ~enhanced-powergaming-scripts/baf/upload/mocore.baf~
					REPLACE_TEXTUALLY CASE_INSENSITIVE ~RES(%5e_mih_sr%~ ~RES(%spell_res%~
			END
		END
	END

///////////////////////////////////////////////////////////////////////////
// SR - MiH Arcane Spells                                                //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF mih_arcane BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/core_mih_arcane.tph~

		ACTION_IF 5e_spellcasting BEGIN
			INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/core_mih_arcane_5e.tph~

			ACTION_FOR_EACH 5e_mih_arcane IN
				WIZARD_SUPERHEROISM
				WIZARD_HEROISM
				WIZARD_SEEKING
			BEGIN
				LAF RES_NUM_OF_SPELL_NAME STR_VAR spell_name = ~%5e_mih_arcane%~ RET spell_res END
				COPY ~enhanced-powergaming-scripts/baf/upload/mocore.baf~ ~enhanced-powergaming-scripts/baf/upload/mocore.baf~
					REPLACE_TEXTUALLY CASE_INSENSITIVE ~RES(%5e_mih_arcane%~ ~RES(%spell_res%~
			END
		END
	END

///////////////////////////////////////////////////////////////////////////
// SR - MiH Divine Spells                                                //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF mih_divine BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/sr_core_mih_divine.tph~

		ACTION_IF 5e_spellcasting BEGIN
			INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/sr_core_mih_divine_5e.tph~

			ACTION_FOR_EACH 5e_mih_divine IN
				CLERIC_SUPERHEROISM
				CLERIC_HEROISM
				CLERIC_SEEKING
				CLERIC_STRIKING
				CLERIC_CELESTIAL_PROTECTION
				CLERIC_REPEL_INSECTS
			BEGIN
				LAF RES_NUM_OF_SPELL_NAME STR_VAR spell_name = ~%5e_mih_divine%~ RET spell_res END
				COPY ~enhanced-powergaming-scripts/baf/upload/mocore.baf~ ~enhanced-powergaming-scripts/baf/upload/mocore.baf~
					REPLACE_TEXTUALLY CASE_INSENSITIVE ~RES(%5e_mih_divine%~ ~RES(%spell_res%~
			END
		END
	END

///////////////////////////////////////////////////////////////////////////
// SR - MiH - Item Pack Pre-Buffing                                      //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF mih_items AND FILE_EXISTS_IN_GAME ~MH#AMUL4.ITM~ BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/sr_core_mih_items.tph~
	END

///////////////////////////////////////////////////////////////////////////
// SR - IWD Spells                                                       //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF iwd_scs OR iwdification BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/sr_core_iwd.tph~

		ACTION_IF 5e_spellcasting BEGIN
			INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/sr_core_iwd_5e.tph~

			ACTION_FOR_EACH 5e_iwd IN
				CLERIC_IMPERVIOUS_SANCTITY_OF_MIND
				CLERIC_GREATER_SHIELD_OF_LATHANDER
				CLERIC_SHIELD_OF_LATHANDER
			BEGIN
				LAF RES_NUM_OF_SPELL_NAME STR_VAR spell_name = ~%5e_iwd%~ RET spell_res END
				COPY ~enhanced-powergaming-scripts/baf/upload/mocore.baf~ ~enhanced-powergaming-scripts/baf/upload/mocore.baf~
					REPLACE_TEXTUALLY CASE_INSENSITIVE ~RES(%5e_iwd%~ ~RES(%spell_res%~
			END
		END
	END

///////////////////////////////////////////////////////////////////////////
// SR - d5 Random Tweaks - Cure Bypass Deflection                        //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF d5_deflected BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/sr_d5_cure_dispelling.tph~
	END

///////////////////////////////////////////////////////////////////////////
// SR - Faiths & Powers - FnP Spheres                                    //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF fp_spheres BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/sr_core_fp_spl.tph~

		ACTION_IF 5e_spellcasting BEGIN
			INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/sr_core_fp_spl_5e.tph~

			ACTION_FOR_EACH 5e_fp_spl IN
				CLERIC_SPIRITUAL_CLARITY
			BEGIN
				LAF RES_NUM_OF_SPELL_NAME STR_VAR spell_name = ~%5e_fp_spl%~ RET spell_res END
				COPY ~enhanced-powergaming-scripts/baf/upload/mocore.baf~ ~enhanced-powergaming-scripts/baf/upload/mocore.baf~
					REPLACE_TEXTUALLY CASE_INSENSITIVE ~RES(%5e_fp_spl%~ ~RES(%spell_res%~
			END
		END
	END

///////////////////////////////////////////////////////////////////////////
// SR - Update IWD Dispelling Checks                                     //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF iwd_scs OR iwdification BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/sr_iwd_dispelling.tph~
	END

///////////////////////////////////////////////////////////////////////////
// SR - Update Dispelling - SCS, IWD, and MiH                            //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF scs_breach BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/sr_scs_breach.tph~
		ACTION_IF iwd_scs OR iwdification BEGIN
			ACTION_IF mih_arcane BEGIN
				INCLUDE ~enhanced-powergaming-scripts/lib/bg2ee/sr_core_breach_globe_iwd.tph~
			END ELSE BEGIN
				INCLUDE ~enhanced-powergaming-scripts/lib/sr_core_breach_iwd.tph~
			END
		END ELSE BEGIN
			ACTION_IF mih_arcane BEGIN
				INCLUDE ~enhanced-powergaming-scripts/lib/bg2ee/sr_core_breach_globe.tph~
			END ELSE BEGIN
				INCLUDE ~enhanced-powergaming-scripts/lib/sr_core_breach.tph~
			END			
		END
	END ELSE BEGIN
		ACTION_IF mih_arcane BEGIN
			INCLUDE ~enhanced-powergaming-scripts/lib/bg2ee/sr_globe.tph~
		END
	END

///////////////////////////////////////////////////////////////////////////
// SCS - Golems                                                          //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF scs_golem BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/sr_core_golem.tph~
	END

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Add Mod Components to Scripts without Spell Revisions                 //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

END ELSE BEGIN
///////////////////////////////////////////////////////////////////////////
// Build out MO-Core                                                     //
///////////////////////////////////////////////////////////////////////////		
	INCLUDE ~enhanced-powergaming-scripts/lib/core_base.tph~

	ACTION_IF GAME_IS ~bgee~ BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/bgee/core_bgee.tph~
	END

/*
///////////////////////////////////////////////////////////////////////////
// BGEE Remove Wights                                                    //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF GAME_IS ~bgee~ BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/ini/remove_wight.tph~
	END
*/

///////////////////////////////////////////////////////////////////////////
// 5e Spellcasting                                                       //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF 5e_spellcasting BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/core_5e.tph~

		ACTION_FOR_EACH 5e_spell IN
				WIZARD_VOCALIZE
				WIZARD_PROTECTION_FROM_MAGIC_WEAPONS
				WIZARD_ABSOLUTE_IMMUNITY
				WIZARD_IMPROVED_MANTLE
				WIZARD_MANTLE
				WIZARD_STONE_SKIN
				CLERIC_IRONSKIN
				CLERIC_SANCTUARY
				CLERIC_MASS_RAISE_DEAD
				CLERIC_RESURRECTION
				CLERIC_RAISE_DEAD
				CLERIC_RESTORATION
				CLERIC_LESSER_RESTORATION
				WIZARD_STONE_TO_FLESH
				CLERIC_REMOVE_PARALYSIS
				CLERIC_CURE_DISEASE
				CLERIC_NEUTRALIZE_POISON
				CLERIC_SLOW_POISON
				WIZARD_RESIST_FEAR
				CLERIC_REMOVE_FEAR
				CLERIC_ZONE_OF_SWEET_AIR
				WIZARD_TRUE_SIGHT
				CLERIC_TRUE_SIGHT
				CLERIC_INVISIBILITY_PURGE
				WIZARD_DETECT_INVISIBILITY
				WIZARD_BREACH
				WIZARD_SPELL_THRUST
				WIZARD_SECRET_WORD
				WIZARD_PIERCE_MAGIC
				WIZARD_WARDING_WHIP
				WIZARD_SPELL_STRIKE
				WIZARD_PIERCE_SHIELD
				WIZARD_RUBY_RAY_OF_REVERSAL
				WIZARD_DETECT_ILLUSION
				WIZARD_MELF_METEOR
				CLERIC_HEAL
				CLERIC_CURE_SERIOUS_WOUNDS
				CLERIC_CURE_MEDIUM_WOUNDS
				CLERIC_CURE_LIGHT_WOUNDS
				CLERIC_REGENERATE
				WIZARD_MIRROR_IMAGE
				WIZARD_SPELL_SHIELD
				WIZARD_SPELL_TRAP
				WIZARD_SPELL_DEFLECTION
				WIZARD_SPELL_TURNING
				WIZARD_GLOBE_OF_INVULNERABILITY
				WIZARD_MINOR_SPELL_TURNING
				WIZARD_MINOR_SPELL_DEFLECTION
				WIZARD_MINOR_GLOBE_OF_INVULNERABILITY
				CLERIC_AURA_OF_FLAMING_DEATH
				CLERIC_GLOBE_OF_BLADES
				WIZARD_FIRE_SHIELD_RED
				WIZARD_FIRE_SHIELD_BLUE
				CLERIC_SHIELD_OF_THE_ARCHONS
				WIZARD_PROTECTION_FROM_NORMAL_MISSILES
				CLERIC_PHYSICAL_MIRROR
				CLERIC_BLADE_BARRIER
				CLERIC_DRAW_UPON_HOLY_MIGHT
				CLERIC_ARMOR_OF_FAITH
				CLERIC_PROTECTION_FROM_FIRE
				WIZARD_BLACK_BLADE_OF_DISASTER
				WIZARD_IMPROVED_HASTE
				WIZARD_MAGIC_MISSILE
				CLERIC_DOOM
				CLERIC_INSECT_PLAGUE
				CLERIC_SUNRAY
				CLERIC_FALSE_DAWN
				CLERIC_HOLD_PERSON
				CLERIC_SILENCE_15_FOOT
				CLERIC_MISCAST_MAGIC
				CLERIC_GREATER_COMMAND
				WIZARD_SUMMON_HAKEASHAR
				WIZARD_SUMMON_NISHRUU
				CLERIC_COMMAND
				CLERIC_RIGHTEOUS_MAGIC
				WIZARD_GREATER_MALISON
				WIZARD_LOWER_RESISTANCE
				WIZARD_SLOW
				WIZARD_SLEEP
				WIZARD_HOLD_PERSON
				WIZARD_CONFUSION
				WIZARD_EMOTION_HOPELESSNESS
				WIZARD_CHAOS
			BEGIN
				LAF RES_NUM_OF_SPELL_NAME STR_VAR spell_name = ~%5e_spell%~ RET spell_res END
				COPY ~enhanced-powergaming-scripts/baf/upload/mocore.baf~ ~enhanced-powergaming-scripts/baf/upload/mocore.baf~
					REPLACE_TEXTUALLY CASE_INSENSITIVE ~RES(%5e_spell%~ ~RES(%spell_res%~
			END
	END

///////////////////////////////////////////////////////////////////////////
// Turn Undead Overhaul                                                  //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF turn_undead BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/bg2ee/core_turn_undead.tph~
	END

///////////////////////////////////////////////////////////////////////////
// DSotSC                                                                //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF dsotsc_divine && !mih_divine && !iwdification BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/core_dsotsc_d.tph~
	END

///////////////////////////////////////////////////////////////////////////
// Faiths & Powers - Ranger Kits                                          //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF fp_ranger BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/ranger_fp_kit.tph~
	END

///////////////////////////////////////////////////////////////////////////
// Tome & Blood                                                          //
///////////////////////////////////////////////////////////////////////////
	// Invisibility Changes
	ACTION_IF tome_and_blood BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/core_tb_inv.tph~
	END

///////////////////////////////////////////////////////////////////////////
// Faiths & Powers - Paladin Kits                                        //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF fp_paladin BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/paladin_fp_kit.tph~
	END

///////////////////////////////////////////////////////////////////////////
// MiH - Spell Restorations                                              //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF mih_restorations BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/core_mih_sr.tph~

		ACTION_IF 5e_spellcasting BEGIN
			INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/core_mih_sr_5e.tph~

			ACTION_FOR_EACH 5e_mih_sr IN
				CLERIC_CURE_BLIND_DEAF
			BEGIN
				LAF RES_NUM_OF_SPELL_NAME STR_VAR spell_name = ~%5e_mih_sr%~ RET spell_res END
				COPY ~enhanced-powergaming-scripts/baf/upload/mocore.baf~ ~enhanced-powergaming-scripts/baf/upload/mocore.baf~
					REPLACE_TEXTUALLY CASE_INSENSITIVE ~RES(%5e_mih_sr%~ ~RES(%spell_res%~
			END
		END
	END
	
///////////////////////////////////////////////////////////////////////////
// MiH - Arcane Spells                                                   //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF mih_arcane BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/core_mih_arcane.tph~

		ACTION_IF 5e_spellcasting BEGIN
			INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/core_mih_arcane_5e.tph~

			ACTION_FOR_EACH 5e_mih_arcane IN
				WIZARD_SUPERHEROISM
				WIZARD_HEROISM
				WIZARD_SEEKING
			BEGIN
				LAF RES_NUM_OF_SPELL_NAME STR_VAR spell_name = ~%5e_mih_arcane%~ RET spell_res END
				COPY ~enhanced-powergaming-scripts/baf/upload/mocore.baf~ ~enhanced-powergaming-scripts/baf/upload/mocore.baf~
					REPLACE_TEXTUALLY CASE_INSENSITIVE ~RES(%5e_mih_arcane%~ ~RES(%spell_res%~
			END
		END
	END

///////////////////////////////////////////////////////////////////////////
// MiH - Divine Spells                                                   //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF mih_divine BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/core_mih_divine.tph~

		ACTION_IF 5e_spellcasting BEGIN
			INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/core_mih_divine_5e.tph~

			ACTION_FOR_EACH 5e_mih_divine IN
				CLERIC_SUPERHEROISM
				CLERIC_HEROISM
				CLERIC_SEEKING
				CLERIC_STRIKING
				CLERIC_CELESTIAL_PROTECTION
				CLERIC_REPEL_INSECTS
				CLERIC_BREAK_ENCHANTMENT
			BEGIN
				LAF RES_NUM_OF_SPELL_NAME STR_VAR spell_name = ~%5e_mih_divine%~ RET spell_res END
				COPY ~enhanced-powergaming-scripts/baf/upload/mocore.baf~ ~enhanced-powergaming-scripts/baf/upload/mocore.baf~
					REPLACE_TEXTUALLY CASE_INSENSITIVE ~RES(%5e_mih_divine%~ ~RES(%spell_res%~
			END
		END
	END

///////////////////////////////////////////////////////////////////////////
// MiH - Item Pack Pre-Buffing                                           //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF mih_items AND FILE_EXISTS_IN_GAME ~MH#AMUL4.ITM~ BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/core_mih_items.tph~
	END

///////////////////////////////////////////////////////////////////////////
// IWD Spells                                                            //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF iwd_scs OR iwdification BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/core_iwd.tph~

		ACTION_IF 5e_spellcasting BEGIN
			INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/core_iwd_5e.tph~

			ACTION_FOR_EACH 5e_iwd IN
				WIZARD_MIND_BLANK
				CLERIC_IMPERVIOUS_SANCTITY_OF_MIND
				CLERIC_GREATER_SHIELD_OF_LATHANDER
				CLERIC_SHIELD_OF_LATHANDER
				CLERIC_CURE_MODERATE_WOUNDS
			BEGIN
				LAF RES_NUM_OF_SPELL_NAME STR_VAR spell_name = ~%5e_iwd%~ RET spell_res END
				COPY ~enhanced-powergaming-scripts/baf/upload/mocore.baf~ ~enhanced-powergaming-scripts/baf/upload/mocore.baf~
					REPLACE_TEXTUALLY CASE_INSENSITIVE ~RES(%5e_iwd%~ ~RES(%spell_res%~
			END
		END
	END

///////////////////////////////////////////////////////////////////////////
// d5 Random Tweaks - Cure Bypass Deflection                             //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF d5_deflected BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/d5_cure_dispelling.tph~

		ACTION_IF 5e_spellcasting BEGIN
			INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/d5_cure_dispelling_5e.tph~
		END
	END

///////////////////////////////////////////////////////////////////////////
// Faiths & Powers - FnP Spheres                                         //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF fp_spheres BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/core_fp_spl.tph~

		ACTION_IF 5e_spellcasting BEGIN
			INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/core_fp_spl_5e.tph~

			ACTION_FOR_EACH 5e_fp_spl IN
				CLERIC_SPIRITUAL_CLARITY
			BEGIN
				LAF RES_NUM_OF_SPELL_NAME STR_VAR spell_name = ~%5e_fp_spl%~ RET spell_res END
				COPY ~enhanced-powergaming-scripts/baf/upload/mocore.baf~ ~enhanced-powergaming-scripts/baf/upload/mocore.baf~
					REPLACE_TEXTUALLY CASE_INSENSITIVE ~RES(%5e_fp_spl%~ ~RES(%spell_res%~
			END
		END
	END

///////////////////////////////////////////////////////////////////////////
// Update IWD Dispelling Checks                                          //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF iwd_scs OR iwdification BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/iwd_dispelling.tph~
	END

///////////////////////////////////////////////////////////////////////////
// Update Dispelling - SCS, IWD, and MiH                                 //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF scs_breach BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/scs_breach.tph~
		ACTION_IF iwd_scs OR iwdification BEGIN
			ACTION_IF mih_arcane BEGIN
				INCLUDE ~enhanced-powergaming-scripts/lib/bg2ee/core_breach_globe_iwd.tph~
			END ELSE BEGIN
				INCLUDE ~enhanced-powergaming-scripts/lib/core_breach_iwd.tph~
			END
		END ELSE BEGIN
			ACTION_IF mih_arcane BEGIN
				INCLUDE ~enhanced-powergaming-scripts/lib/bg2ee/core_breach_globe.tph~
			END ELSE BEGIN
				INCLUDE ~enhanced-powergaming-scripts/lib/core_breach.tph~
			END			
		END
	END ELSE BEGIN
		ACTION_IF iwd_scs OR iwdification BEGIN
			ACTION_IF mih_arcane BEGIN
				INCLUDE ~enhanced-powergaming-scripts/lib/bg2ee/globe_iwd.tph~
			END
		END ELSE BEGIN
			ACTION_IF mih_arcane BEGIN
				INCLUDE ~enhanced-powergaming-scripts/lib/bg2ee/globe.tph~
			END
		END
	END

///////////////////////////////////////////////////////////////////////////
// Golems                                                                //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF scs_golem BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/core_golem.tph~

		ACTION_IF 5e_spellcasting BEGIN
			INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/core_golem_5e.tph~
		END
	END
END

///////////////////////////////////////////////////////////////////////////
// Update ini Presets                                                    //
///////////////////////////////////////////////////////////////////////////
// Fast Healing
ACTION_IF fst_heal BEGIN
	INCLUDE ~enhanced-powergaming-scripts/lib/ini/core_fast_healing.tph~
END

// Removes Dialog Hovertext from Scripts
ACTION_IF scp_dlg BEGIN
	INCLUDE ~enhanced-powergaming-scripts/lib/ini/core_dialog.tph~
END

///////////////////////////////////////////////////////////////////////////
// Faith and Powers Old                                                  //
///////////////////////////////////////////////////////////////////////////
ACTION_IF fp_old BEGIN
	INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/core_fp_spl_off.tph~
END

///////////////////////////////////////////////////////////////////////////
// MiH - Arcane Spells Major Globe                                       //
///////////////////////////////////////////////////////////////////////////
ACTION_IF mih_arcane BEGIN
	INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/core_mih_globe.tph~
END
	
///////////////////////////////////////////////////////////////////////////
// Thieving Skills for Bards                                             //
///////////////////////////////////////////////////////////////////////////
ACTION_IF bard_thief BEGIN
	INCLUDE ~enhanced-powergaming-scripts/lib/bard_thief.tph~
END

///////////////////////////////////////////////////////////////////////////
// Remove Athkatla Check from Main (BGEE ONLY)                           //
///////////////////////////////////////////////////////////////////////////
ACTION_IF GAME_IS ~bgee~ BEGIN
	INCLUDE ~enhanced-powergaming-scripts/lib/BGEE/bgee_remove_athkatla.tph~
END

///////////////////////////////////////////////////////////////////////////
// Turn Undead Overhaul - END                                            //
///////////////////////////////////////////////////////////////////////////
ACTION_IF turn_undead BEGIN
	INCLUDE ~enhanced-powergaming-scripts/lib/bg2ee/core_turn_undead_end.tph~
END

///////////////////////////////////////////////////////////////////////////
// Morpheus562's Kitpack Battle Master                                   //
///////////////////////////////////////////////////////////////////////////
ACTION_IF battle_master BEGIN
	INCLUDE ~enhanced-powergaming-scripts/lib/bg2ee/core_mo_battlemaster.tph~
END

///////////////////////////////////////////////////////////////////////////
// Morpheus562's Kitpack Champion of the Wild                            //
///////////////////////////////////////////////////////////////////////////
ACTION_IF champion_wild BEGIN
	INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/core_mo_champwild.tph~

	ACTION_IF !FILE_EXISTS_IN_GAME ~mochk01.itm~ AND GAME_IS ~bg2ee eet~ BEGIN
		COPY ~enhanced-powergaming-scripts/itm/mochk01.itm~ ~override~ // Check Item
		INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/core_pally_smite_check.tph~
	END ELSE ACTION_IF GAME_IS ~bgee~ BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/BGEE/core_pally_smite_check.tph~
	END
END

///////////////////////////////////////////////////////////////////////////
// Morpheus562's Kitpack Templar                                         //
///////////////////////////////////////////////////////////////////////////
ACTION_IF templar BEGIN
	INCLUDE ~enhanced-powergaming-scripts/lib/bg2ee/core_mo_templar.tph~
END

///////////////////////////////////////////////////////////////////////////
// Morpheus562's Kitpack Stormlord                                       //
///////////////////////////////////////////////////////////////////////////
ACTION_IF stormlord BEGIN
	INCLUDE ~enhanced-powergaming-scripts/lib/bg2ee/core_mo_stormlord.tph~

	ACTION_IF GAME_IS ~bgee~ BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/BGEE/core_stormlord_check.tph~
	END
END

///////////////////////////////////////////////////////////////////////////
// Skills and Abilities Update HLAs                                      //
///////////////////////////////////////////////////////////////////////////
ACTION_IF saa_hla BEGIN
	INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/core_sa_hla.tph~
END

///////////////////////////////////////////////////////////////////////////
// Skills and Abilities Paladin Overhaul                                 //
///////////////////////////////////////////////////////////////////////////
ACTION_IF pally_smite BEGIN
	INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/core_pally_smite.tph~

	ACTION_IF !FILE_EXISTS_IN_GAME ~mochk01.itm~ AND GAME_IS ~bg2ee eet~ BEGIN
		COPY ~enhanced-powergaming-scripts/itm/mochk01.itm~ ~override~ // Check Item
		INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/core_pally_smite_check.tph~
	END ELSE ACTION_IF GAME_IS ~bgee~ BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/BGEE/core_pally_smite_check.tph~
	END
END

///////////////////////////////////////////////////////////////////////////
// Skills and Abilities Psi Warrior                                      //
///////////////////////////////////////////////////////////////////////////
ACTION_IF psi_warrior BEGIN
	INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/core_psi_warrior.tph~
	INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/core_psi_warrior_check.tph~
END

///////////////////////////////////////////////////////////////////////////
// Skills and Abilities Eldritch Scion                                   //
///////////////////////////////////////////////////////////////////////////
ACTION_IF eldritch_scion BEGIN
	INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/core_eldritch_scion.tph~
END

///////////////////////////////////////////////////////////////////////////
// Skills and Abilities Fighter Updates                                  //
///////////////////////////////////////////////////////////////////////////
ACTION_IF fighter_overhaul BEGIN
	INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/core_sa_wind.tph~
END

///////////////////////////////////////////////////////////////////////////
// Tome and Blood - Magus                                                //
///////////////////////////////////////////////////////////////////////////
ACTION_IF magus BEGIN
	INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/core_magus.tph~
END

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// 5e Spellcasting names                                                 //
// Code in this section provided by Subtledoctor                         //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
ACTION_IF 5e_spellcasting BEGIN
	COPY_EXISTING ~d5zclons.2da~ ~override~
  	COUNT_2DA_COLS cols
  	COUNT_2DA_ROWS cols rows
  	FOR (row = 1; row < rows; ++row) BEGIN
    	READ_2DA_ENTRY row 0 cols ind_num
    	READ_2DA_ENTRY row 2 cols mem_spl
    	SPRINT $5e_spells_array(~d5z%ind_num%i~)~%mem_spl%~
  	END
	BUT_ONLY

	COPY ~enhanced-powergaming-scripts/baf/upload/mocore.baf~ ~enhanced-powergaming-scripts/baf/upload/mocore.baf~
	  PHP_EACH 5e_spells_array AS new_spl => old_spl BEGIN
	    REPLACE_TEXTUALLY CASE_INSENSITIVE ~%old_spl%~ ~"%new_spl%"~
	  END
END

///////////////////////////////////////////////////////////////////////////
// EEex Check                                                            //
///////////////////////////////////////////////////////////////////////////
ACTION_IF eeex_present BEGIN
	COPY ~enhanced-powergaming-scripts/lua/m_actri1.lua~  ~override~ 
	COPY ~enhanced-powergaming-scripts/lua/m_actri2.lua~  ~override~
	ACTION_IF eeex_verion BEGIN
		COPY ~enhanced-powergaming-scripts/lua/m_mochal.lua~ ~override~
		COPY ~enhanced-powergaming-scripts/lua/m_motarg.lua~ ~override~
	END ELSE BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/core_eeex_version_check.tph~
	END
END ELSE BEGIN
	INCLUDE ~enhanced-powergaming-scripts/lib/core_eeex.tph~
	INCLUDE ~enhanced-powergaming-scripts/lib/core_eeex_version_check.tph~
END

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Import AI Script into the Game                                        //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Copy .BCS file to override folder                                     //
///////////////////////////////////////////////////////////////////////////
COPY ~enhanced-powergaming-scripts/baf/upload/mocore.baf~ ~override/bddefai.bcs~
  COMPILE_BAF_TO_BCS

///////////////////////////////////////////////////////////////////////////
// Copied from Stratagems to update partyai.2da                          //
///////////////////////////////////////////////////////////////////////////
COPY_EXISTING "PARTYAI.2da" override
    COUNT_2DA_ROWS 2 rowcount
    FOR (i=1;i<rowcount;i+=1) BEGIN
       SET_2DA_ENTRY i 1 2 "BDDEFAI"
    END
 BUT_ONLY

///////////////////////////////////////////////////////////////////////////
// Update Lua Files                                                      //
// Please Note: This accounts for vanilla and changes made by SCS        //
///////////////////////////////////////////////////////////////////////////
OUTER_SPRINT smartscript      @1110
OUTER_SPRINT smartscriptdesc  @1120
OUTER_SPRINT scriptatk        @1130
OUTER_SPRINT findtrap         @1140
OUTER_SPRINT findtrapdesc     @1150
OUTER_SPRINT hideshdws        @1160
OUTER_SPRINT hideshdwsdesc    @1170
OUTER_SPRINT bardsong         @1180
OUTER_SPRINT bardsongdesc     @1190
OUTER_SPRINT trnund           @1200
OUTER_SPRINT trnunddesc       @1210
OUTER_SPRINT defense          @1220
OUTER_SPRINT defensedesc      @1230
OUTER_SPRINT useitem          @1240
OUTER_SPRINT useitemdesc      @1250
OUTER_SPRINT solobuff         @1260
OUTER_SPRINT solobuffdesc     @1270
OUTER_SPRINT offense          @1280
OUTER_SPRINT offensedesc      @1290
OUTER_SPRINT groupbuff        @1300
OUTER_SPRINT groupbuffdesc    @1310
OUTER_SPRINT specbuff         @1320
OUTER_SPRINT specbuffdesc     @1330

ACTION_FOR_EACH luafile IN
		CS_CZ
		DE_DE
		EN_US
		ES_ES
		FR_FR
		IT_IT
		KO_KR
		PL_PL
		PT_BR
		RU_RU
		ZN_CN
	BEGIN
		ACTION_IF FILE_EXISTS_IN_GAME ~L_%luafile%.LUA~ BEGIN
			COPY_EXISTING "L_%luafile%.LUA" ~override~
				REPLACE_TEXTUALLY EVALUATE_REGEXP ~CHARACTER_SCRIPT_SMART_SCRIPT = \".*\"~ ~CHARACTER_SCRIPT_SMART_SCRIPT = "%smartscript%"~
				REPLACE_TEXTUALLY EVALUATE_REGEXP ~CHARACTER_SCRIPT_SMART_SCRIPT_DESCRIPTION = \".*\"~ ~CHARACTER_SCRIPT_SMART_SCRIPT_DESCRIPTION = "%smartscriptdesc%"~
				REPLACE_TEXTUALLY EVALUATE_REGEXP ~SCRIPT_ATTACK_ENEMIES_DESCRIPTION = \".*\"~ ~SCRIPT_ATTACK_ENEMIES_DESCRIPTION = "%scriptatk%"~
				REPLACE_TEXTUALLY EVALUATE_REGEXP ~SCRIPT_FIND_TRAPS_LABEL = \".*\"~ ~SCRIPT_FIND_TRAPS_LABEL = "%findtrap%"~
				REPLACE_TEXTUALLY EVALUATE_REGEXP ~SCRIPT_FIND_TRAPS_DESCRIPTION = \".*\"~ ~SCRIPT_FIND_TRAPS_DESCRIPTION = "%findtrapdesc%"~
				REPLACE_TEXTUALLY EVALUATE_REGEXP ~SCRIPT_HIDE_IN_SHADOWS_LABEL = \".*\"~ ~SCRIPT_HIDE_IN_SHADOWS_LABEL = "%hideshdws%"~
				REPLACE_TEXTUALLY EVALUATE_REGEXP ~SCRIPT_HIDE_IN_SHADOWS_DESCRIPTION = \".*\"~ ~SCRIPT_HIDE_IN_SHADOWS_DESCRIPTION = "%hideshdwsdesc%"~
				REPLACE_TEXTUALLY EVALUATE_REGEXP ~SCRIPT_SING_BATTLESONG_LABEL = \".*\"~ ~SCRIPT_SING_BATTLESONG_LABEL = "%bardsong%"~
				REPLACE_TEXTUALLY EVALUATE_REGEXP ~SCRIPT_SING_BATTLESONG_DESCRIPTION = \".*\"~ ~SCRIPT_SING_BATTLESONG_DESCRIPTION = "%bardsongdesc%"~
				REPLACE_TEXTUALLY EVALUATE_REGEXP ~SCRIPT_TURN_UNDEAD_LABEL = \".*\"~ ~SCRIPT_TURN_UNDEAD_LABEL = "%trnund%"~
				REPLACE_TEXTUALLY EVALUATE_REGEXP ~SCRIPT_TURN_UNDEAD_DESCRIPTION = \".*\"~ ~SCRIPT_TURN_UNDEAD_DESCRIPTION = "%trnunddesc%"~
				REPLACE_TEXTUALLY EVALUATE_REGEXP ~SCRIPT_USE_DEFENSIVE_SPELLS_LABEL = \".*\"~ ~SCRIPT_USE_DEFENSIVE_SPELLS_LABEL = "%defense%"~
				REPLACE_TEXTUALLY EVALUATE_REGEXP ~SCRIPT_USE_DEFENSIVE_SPELLS_DESCRIPTION = \".*\"~ ~SCRIPT_USE_DEFENSIVE_SPELLS_DESCRIPTION = "%defensedesc%"~
				REPLACE_TEXTUALLY EVALUATE_REGEXP ~SCRIPT_USE_ITEMS_LABEL = \".*\"~ ~SCRIPT_USE_ITEMS_LABEL = "%useitem%"~
				REPLACE_TEXTUALLY EVALUATE_REGEXP ~SCRIPT_USE_ITEMS_DESCRIPTION = \".*\"~ ~SCRIPT_USE_ITEMS_DESCRIPTION = "%useitemdesc%"~
				REPLACE_TEXTUALLY EVALUATE_REGEXP ~SCRIPT_USE_MELEE_WEAPONS_LABEL = \".*\"~ ~SCRIPT_USE_MELEE_WEAPONS_LABEL = "%solobuff%"~
				REPLACE_TEXTUALLY EVALUATE_REGEXP ~SCRIPT_USE_MELEE_WEAPONS_DESCRIPTION = \".*\"~ ~SCRIPT_USE_MELEE_WEAPONS_DESCRIPTION = "%solobuffdesc%"~
				REPLACE_TEXTUALLY EVALUATE_REGEXP ~SCRIPT_USE_OFFENSIVE_SPELLS_LABEL = \".*\"~ ~SCRIPT_USE_OFFENSIVE_SPELLS_LABEL = "%offense%"~
				REPLACE_TEXTUALLY EVALUATE_REGEXP ~SCRIPT_USE_OFFENSIVE_SPELLS_DESCRIPTION = \".*\"~ ~SCRIPT_USE_OFFENSIVE_SPELLS_DESCRIPTION = "%offensedesc%"~
				REPLACE_TEXTUALLY EVALUATE_REGEXP ~SCRIPT_USE_RANGED_WEAPONS_LABEL = \".*\"~ ~SCRIPT_USE_RANGED_WEAPONS_LABEL = "%groupbuff%"~
				REPLACE_TEXTUALLY EVALUATE_REGEXP ~SCRIPT_USE_RANGED_WEAPONS_DESCRIPTION = \".*\"~ ~SCRIPT_USE_RANGED_WEAPONS_DESCRIPTION = "%groupbuffdesc%"~
				REPLACE_TEXTUALLY EVALUATE_REGEXP ~SCRIPT_USE_SPECIAL_ABILITIES_LABEL = \".*\"~ ~SCRIPT_USE_SPECIAL_ABILITIES_LABEL = "%specbuff%"~
				REPLACE_TEXTUALLY EVALUATE_REGEXP ~SCRIPT_USE_SPECIAL_ABILITIES_DESCRIPTION = \".*\"~ ~SCRIPT_USE_SPECIAL_ABILITIES_DESCRIPTION = "%specbuffdesc%"~
	   		BUT_ONLY
		END
	END
