LOAD_TRA ~enhanced-powergaming-scripts/languages/%LANGUAGE%/script_dialog.tra~

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Add SR Mod Components to Scripts for BGII: EE and EET                 //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
ACTION_IF spell_revisions BEGIN

///////////////////////////////////////////////////////////////////////////
// SR - Base Game                                                        //
///////////////////////////////////////////////////////////////////////////
	COPY ~enhanced-powergaming-scripts/baf/normal/sr/morang.baf~  ~enhanced-powergaming-scripts/baf/upload/morang.baf~
	COPY ~enhanced-powergaming-scripts/baf/normal/sr/mocore.baf~  ~enhanced-powergaming-scripts/baf/upload/mobasic.baf~
	COPY ~enhanced-powergaming-scripts/baf/normal/sr/mocore.baf~  ~enhanced-powergaming-scripts/baf/upload/mocore.baf~
	COPY ~enhanced-powergaming-scripts/baf/normal/sr/mopal.baf~   ~enhanced-powergaming-scripts/baf/upload/mopal.baf~
	COPY ~enhanced-powergaming-scripts/baf/normal/sr/momonk.baf~  ~enhanced-powergaming-scripts/baf/upload/momonk.baf~

	INCLUDE ~enhanced-powergaming-scripts/lib/sr_ranger_base.tph~
	INCLUDE ~enhanced-powergaming-scripts/lib/sr_basic_base.tph~
	INCLUDE ~enhanced-powergaming-scripts/lib/sr_core_base.tph~
	INCLUDE ~enhanced-powergaming-scripts/lib/sr_monk_base.tph~
	INCLUDE ~enhanced-powergaming-scripts/lib/sr_paladin_base.tph~

///////////////////////////////////////////////////////////////////////////
// SR - Song & Silence                                                   //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF song_and_silence BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/sr_basic_ss.tph~
		INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/sr_core_ss.tph~
	END

///////////////////////////////////////////////////////////////////////////
// SR - Tome & Blood                                                     //
///////////////////////////////////////////////////////////////////////////
	// Invisibility Changes
	ACTION_IF tome_and_blood BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/sr_core_tb_inv.tph~
	END

///////////////////////////////////////////////////////////////////////////
// SR - Faiths & Powers - Ranger Kits                                    //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF fp_ranger BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/sr_ranger_fp_kit.tph~
	END

///////////////////////////////////////////////////////////////////////////
// SR - Faiths & Powers - Paladin Kits                                   //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF fp_paladin BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/sr_paladin_fp_kit.tph~
	END

///////////////////////////////////////////////////////////////////////////
// SR- Faiths & Powers - Cleric Kits                                     //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF fp_cleric BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/core_fp_kit.tph~
	END

///////////////////////////////////////////////////////////////////////////
// SR - Faiths & Powers - FnP Spheres                                    //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF fp_spheres BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/sr_ranger_fp_spl.tph~
		INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/sr_basic_fp_spl.tph~
		INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/sr_core_fp_spl.tph~
	END

///////////////////////////////////////////////////////////////////////////
// SR - IWD Spells                                                       //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF iwd_scs OR iwdification BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/sr_paladin_iwd.tph~

		ACTION_IF fp_ranger BEGIN
			INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/sr_basic_iwd_fp.tph~
			INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/sr_ranger_iwd_fp_kit.tph~
			INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/sr_core_iwd_fp.tph~
		END ELSE BEGIN
			INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/sr_core_iwd.tph~
			INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/sr_basic_iwd.tph~
		END
	END

///////////////////////////////////////////////////////////////////////////
// SR - SCS - Breach                                                     //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF scs_breach BEGIN
		ACTION_IF iwd_scs OR iwdification BEGIN
			INCLUDE ~enhanced-powergaming-scripts/lib/sr_core_breach_iwd.tph~
		END ELSE BEGIN
			INCLUDE ~enhanced-powergaming-scripts/lib/sr_core_breach.tph~
		END
	END

///////////////////////////////////////////////////////////////////////////
// SCS - Golems                                                          //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF scs_golem BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/sr_core_golem.tph~
		INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/sr_paladin_golem.tph~
	END

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Add Mod Components to Scripts without Spell Revisions                 //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

END ELSE BEGIN
///////////////////////////////////////////////////////////////////////////
// Base Game                                                             //
///////////////////////////////////////////////////////////////////////////
	COPY ~enhanced-powergaming-scripts/baf/normal/morang.baf~  ~enhanced-powergaming-scripts/baf/upload/morang.baf~
	COPY ~enhanced-powergaming-scripts/baf/normal/mocore.baf~  ~enhanced-powergaming-scripts/baf/upload/mobasic.baf~
	COPY ~enhanced-powergaming-scripts/baf/normal/mocore.baf~  ~enhanced-powergaming-scripts/baf/upload/mocore.baf~
	COPY ~enhanced-powergaming-scripts/baf/normal/mopal.baf~   ~enhanced-powergaming-scripts/baf/upload/mopal.baf~
	COPY ~enhanced-powergaming-scripts/baf/normal/momonk.baf~  ~enhanced-powergaming-scripts/baf/upload/momonk.baf~

	INCLUDE ~enhanced-powergaming-scripts/lib/ranger_base.tph~
	INCLUDE ~enhanced-powergaming-scripts/lib/basic_base.tph~
	INCLUDE ~enhanced-powergaming-scripts/lib/core_base.tph~
	INCLUDE ~enhanced-powergaming-scripts/lib/monk_base.tph~
	INCLUDE ~enhanced-powergaming-scripts/lib/paladin_base.tph~

///////////////////////////////////////////////////////////////////////////
// DSotSC                                                                //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF dsotsc_arcane && !mih_arcane && !iwdification BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/core_dsotsc_w.tph~
	END

	ACTION_IF dsotsc_divine && !mih_divine && !iwdification BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/core_dsotsc_d.tph~
	END

///////////////////////////////////////////////////////////////////////////
// Song & Silence                                                        //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF song_and_silence BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/basic_ss.tph~
		INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/core_ss.tph~
	END

///////////////////////////////////////////////////////////////////////////
// IWD Spells                                                            //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF iwd_scs OR iwdification BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/ranger_iwd.tph~
		INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/basic_iwd.tph~
		INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/core_iwd.tph~
		INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/paladin_iwd.tph~
	END

///////////////////////////////////////////////////////////////////////////
// Tome & Blood                                                          //
///////////////////////////////////////////////////////////////////////////
	// Invisibility Changes
	ACTION_IF tome_and_blood BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/core_tb_inv.tph~
	END

///////////////////////////////////////////////////////////////////////////
// Faiths & Powers - Ranger Kits                                          //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF fp_ranger BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/ranger_fp_kit.tph~

		ACTION_IF iwd_scs OR iwdification BEGIN
			INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/ranger_iwd_fp_kit.tph~
		END
	END

///////////////////////////////////////////////////////////////////////////
// Faiths & Powers - Paladin Kits                                        //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF fp_paladin BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/paladin_fp_kit.tph~
	END

///////////////////////////////////////////////////////////////////////////
// Faiths & Powers - Cleric Kits                                         //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF fp_cleric BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/core_fp_kit.tph~
	END

///////////////////////////////////////////////////////////////////////////
// Faiths & Powers - FnP Spheres                                         //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF fp_spheres BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/ranger_fp_spl.tph~
		INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/basic_fp_spl.tph~
		INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/core_fp_spl.tph~

		ACTION_IF iwd_scs OR iwdification BEGIN
			INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/ranger_iwd_fp_spl.tph~
		END
	END

///////////////////////////////////////////////////////////////////////////
// SCS - Breach                                                          //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF scs_breach BEGIN
		ACTION_IF iwd_scs OR iwdification BEGIN
			INCLUDE ~enhanced-powergaming-scripts/lib/core_breach_iwd.tph~
		END ELSE BEGIN
			INCLUDE ~enhanced-powergaming-scripts/lib/core_breach.tph~
		END

		ACTION_IF fp_ranger BEGIN
			INCLUDE ~enhanced-powergaming-scripts/lib/ranger_breach.tph~
		END
	END

///////////////////////////////////////////////////////////////////////////
// SCS - Golems                                                          //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF scs_golem BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/core_golem.tph~
		INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/paladin_golem.tph~
	END
END

///////////////////////////////////////////////////////////////////////////
// Update Hot Keys                                                       //
///////////////////////////////////////////////////////////////////////////
	INCLUDE ~enhanced-powergaming-scripts/lib/core_hotkey.tph~
	INCLUDE ~enhanced-powergaming-scripts/lib/basic_hotkey.tph~
	INCLUDE ~enhanced-powergaming-scripts/lib/monk_hotkey.tph~
	INCLUDE ~enhanced-powergaming-scripts/lib/paladin_hotkey.tph~
	INCLUDE ~enhanced-powergaming-scripts/lib/ranger_hotkey.tph~

///////////////////////////////////////////////////////////////////////////
// Update ini Presets                                                    //
///////////////////////////////////////////////////////////////////////////
	
	// Removes Potion Use in Pre-Buffing
	ACTION_IF pot_use BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/ini/core_pot.tph~
		INCLUDE ~enhanced-powergaming-scripts/lib/ini/basic_pot.tph~
		INCLUDE ~enhanced-powergaming-scripts/lib/ini/monk_pot.tph~
		INCLUDE ~enhanced-powergaming-scripts/lib/ini/paladin_pot.tph~
		INCLUDE ~enhanced-powergaming-scripts/lib/ini/ranger_pot.tph~
	END

	// Basic AI will Auto-Attack Enemies
	ACTION_IF bsc_atk BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/ini/basic_atk.tph~
	END

	// Removes Dialog Hovertext from Scripts
	ACTION_IF scp_dlg BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/ini/core_dialog.tph~
		INCLUDE ~enhanced-powergaming-scripts/lib/ini/basic_dialog.tph~
		INCLUDE ~enhanced-powergaming-scripts/lib/ini/monk_dialog.tph~
		INCLUDE ~enhanced-powergaming-scripts/lib/ini/paladin_dialog.tph~
		INCLUDE ~enhanced-powergaming-scripts/lib/ini/ranger_dialog.tph~
	END

///////////////////////////////////////////////////////////////////////////
// Make Skald Script after Core                                          //
///////////////////////////////////////////////////////////////////////////
	INCLUDE ~enhanced-powergaming-scripts/lib/skald_base.tph~

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Import AI Scripts into the Game                                       //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Copy .BS files to scripts folder                                      //
///////////////////////////////////////////////////////////////////////////
COPY ~enhanced-powergaming-scripts/baf/upload/morang.baf~   ~scripts/morang.bs~
	 ~enhanced-powergaming-scripts/baf/upload/mobasic.baf~  ~scripts/mobasic.bs~
	 ~enhanced-powergaming-scripts/baf/upload/mocore.baf~   ~scripts/mocore.bs~
	 ~enhanced-powergaming-scripts/baf/upload/momonk.baf~   ~scripts/momonk.bs~
	 ~enhanced-powergaming-scripts/baf/upload/mopal.baf~    ~scripts/mopal.bs~
	 ~enhanced-powergaming-scripts/baf/upload/moskd.baf~    ~scripts/moskd.bs~
  COMPILE_BAF_TO_BCS

///////////////////////////////////////////////////////////////////////////
// Add descriptions of the scripts to scrpdesc.2da                       //
///////////////////////////////////////////////////////////////////////////
APPEND ~scrpdesc.2DA~
~morang		999990		 999989
mobasic		999988		 999987
mocore      999986       999985
momonk		999984		 999983
mopal		999982		 999981
moskd		999980		 999979~

///////////////////////////////////////////////////////////////////////////
// Copy the appended scrpdesc.2da to the override folder                 //
///////////////////////////////////////////////////////////////////////////
COPY_EXISTING ~scrpdesc.2da~ ~override~
REPLACE ~999990~ @1010
REPLACE ~999989~ @1011
REPLACE ~999988~ @1090
REPLACE ~999987~ @1091
REPLACE ~999986~ @1100
REPLACE ~999985~ @1101
REPLACE ~999984~ @1060
REPLACE ~999983~ @1061
REPLACE ~999982~ @1050
REPLACE ~999981~ @1051
REPLACE ~999980~ @1070
REPLACE ~999979~ @1071