LOAD_TRA ~enhanced-powergaming-scripts/languages/%LANGUAGE%/script_dialog.tra~

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Final Modifications to Base Script                                    //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Faiths & Powers - Cleric Kits                                         //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF fp_cleric BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/prebuff_fp_cleric_kit.tph~
	END

///////////////////////////////////////////////////////////////////////////
// Faiths & Powers - Paladin Kits                                        //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF fp_paladin BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/prebuff_fp_paladin_kit.tph~
	END

///////////////////////////////////////////////////////////////////////////
// MiH - Arcane Spells Major Globe                                       //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF mih_arcane BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/core_mih_globe.tph~
	END

///////////////////////////////////////////////////////////////////////////
// Skills and Abilities Psi Warrior                                      //
///////////////////////////////////////////////////////////////////////////
ACTION_IF psi_warrior BEGIN
	INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/prebuff_core_psi_warrior.tph~
END

///////////////////////////////////////////////////////////////////////////
// Remove Athkatla Check from Pre-Buffing (BGEE ONLY)                    //
///////////////////////////////////////////////////////////////////////////
ACTION_IF GAME_IS ~bgee~ BEGIN
	INCLUDE ~enhanced-powergaming-scripts/lib/BGEE/bgee_remove_athkatla.tph~
END

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// SR - Split up and Modify Individual Scripts                           //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
ACTION_IF spell_revisions BEGIN

///////////////////////////////////////////////////////////////////////////
// SR - Build out MO-Core                                                //
///////////////////////////////////////////////////////////////////////////	
	INCLUDE ~enhanced-powergaming-scripts/lib/sr_core_base.tph~
	
	ACTION_IF GAME_IS ~bgee~ BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/bgee/sr_core_bgee.tph~
	END

///////////////////////////////////////////////////////////////////////////
// BGEE Wight Check                                                      //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF GAME_IS ~bgee~ BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/ini/remove_wight.tph~
	END

///////////////////////////////////////////////////////////////////////////
// SR - 5e Spellcasting                                                  //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF 5e_spellcasting BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/sr_core_5e.tph~

		ACTION_FOR_EACH 5e_spell IN
				WIZARD_VOCALIZE
				WIZARD_ABSOLUTE_IMMUNITY
				WIZARD_PROTECTION_FROM_MAGIC_WEAPONS
				WIZARD_MOMENT_OF_PRESCIENCE
				WIZARD_MANTLE
				WIZARD_STONE_SKIN
				CLERIC_IRONSKIN
				WIZARD_ARMOR
				WIZARD_MIND_BLANK
				CLERIC_SANCTUARY
				CLERIC_MASS_RAISE_DEAD
				CLERIC_RESURRECTION
				CLERIC_RAISE_DEAD
				CLERIC_BREAK_ENCHANTMENT
				WIZARD_BREAK_ENCHANTMENT
				CLERIC_RESTORATION
				CLERIC_LESSER_RESTORATION
				CLERIC_REMOVE_PARALYSIS
				CLERIC_CURE_DISEASE
				CLERIC_NEUTRALIZE_POISON
				CLERIC_SLOW_POISON
				WIZARD_RESIST_FEAR
				CLERIC_REMOVE_FEAR
				CLERIC_GUST_OF_WIND
				WIZARD_TRUE_SIGHT
				CLERIC_TRUE_SIGHT
				WIZARD_DETECT_INVISIBILITY
				CLERIC_INVISIBILITY_PURGE
				WIZARD_BREACH
				WIZARD_PIERCE_SHIELD
				WIZARD_SPELL_THRUST
				WIZARD_SECRET_WORD
				WIZARD_PIERCE_MAGIC
				WIZARD_WARDING_WHIP
				WIZARD_RUBY_RAY_OF_REVERSAL
				WIZARD_SPELL_STRIKE
				WIZARD_MELF_METEOR
				CLERIC_HEAL
				CLERIC_CURE_SERIOUS_WOUNDS
				CLERIC_CURE_MEDIUM_WOUNDS
				CLERIC_CURE_MODERATE_WOUNDS
				CLERIC_CURE_LIGHT_WOUNDS
				WIZARD_SPELL_SHIELD
				WIZARD_SPELL_TRAP
				WIZARD_GREATER_SPELL_DEFLECTION
				WIZARD_SPELL_DEFLECTION
				WIZARD_MINOR_SPELL_DEFLECTION
				CLERIC_AURA_OF_FLAMING_DEATH
				CLERIC_GLOBE_OF_BLADES
				WIZARD_MESTILS_ACID_SHEATH
				WIZARD_FIRE_SHIELD_RED
				CLERIC_SHIELD_OF_THE_ARCHONS
				WIZARD_PROTECTION_FROM_NORMAL_MISSILES
				CLERIC_PHYSICAL_MIRROR
				CLERIC_BLADE_BARRIER
				CLERIC_DRAW_UPON_HOLY_MIGHT
				CLERIC_ARMOR_OF_FAITH
				CLERIC_PROTECTION_FROM_FIRE
				WIZARD_MIRROR_IMAGE
				WIZARD_IMPROVED_HASTE
				WIZARD_TRUE_STRIKE
				WIZARD_MAGIC_MISSILE
				CLERIC_DOOM
				CLERIC_INSECT_PLAGUE
				CLERIC_SUNRAY
				CLERIC_FALSE_DAWN
				CLERIC_HOLD_PERSON
				CLERIC_SILENCE_15_FOOT
				WIZARD_GREATER_MALISON
				WIZARD_SLOW
				WIZARD_SLEEP
				WIZARD_HOLD_PERSON
				WIZARD_CONFUSION
				WIZARD_EMOTION_HOPELESSNESS
			BEGIN
				LAF RES_NUM_OF_SPELL_NAME STR_VAR spell_name = ~%5e_spell%~ RET spell_res END
				COPY ~enhanced-powergaming-scripts/baf/upload/mocore.baf~ ~enhanced-powergaming-scripts/baf/upload/mocore.baf~
					REPLACE_TEXTUALLY CASE_INSENSITIVE ~RES(%5e_spell%~ ~RES(%spell_res%~
			END
	END

///////////////////////////////////////////////////////////////////////////
// SR - Turn Undead Overhaul                                             //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF turn_undead BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/bg2ee/core_turn_undead.tph~
	END

///////////////////////////////////////////////////////////////////////////
// SR - DSotSC                                                           //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF dsotsc_divine && !mih_divine && !iwdification BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/core_dsotsc_d.tph~
	END

///////////////////////////////////////////////////////////////////////////
// SR - Tome & Blood                                                     //
///////////////////////////////////////////////////////////////////////////
	// Invisibility Changes
	ACTION_IF tome_and_blood BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/sr_core_tb_inv.tph~
	END

///////////////////////////////////////////////////////////////////////////
// SR - Faiths & Powers - Ranger Kits                                    //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF fp_ranger BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/sr_ranger_fp_kit.tph~
	END

///////////////////////////////////////////////////////////////////////////
// SR - Faiths & Powers - Paladin Kits                                   //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF fp_paladin BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/paladin_fp_kit.tph~
	END

///////////////////////////////////////////////////////////////////////////
// SR - MiH Spell Restorations                                           //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF mih_restorations BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/sr_core_mih_sr.tph~

		ACTION_IF 5e_spellcasting BEGIN
			INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/sr_core_mih_sr_5e.tph~

			ACTION_FOR_EACH 5e_mih_sr IN
				CLERIC_CURE_BLIND_DEAF
			BEGIN
				LAF RES_NUM_OF_SPELL_NAME STR_VAR spell_name = ~%5e_mih_sr%~ RET spell_res END
				COPY ~enhanced-powergaming-scripts/baf/upload/mocore.baf~ ~enhanced-powergaming-scripts/baf/upload/mocore.baf~
					REPLACE_TEXTUALLY CASE_INSENSITIVE ~RES(%5e_mih_sr%~ ~RES(%spell_res%~
			END
		END
	END

///////////////////////////////////////////////////////////////////////////
// SR - MiH Arcane Spells                                                //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF mih_arcane BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/core_mih_arcane.tph~

		ACTION_IF 5e_spellcasting BEGIN
			INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/core_mih_arcane_5e.tph~

			ACTION_FOR_EACH 5e_mih_arcane IN
				WIZARD_SUPERHEROISM
				WIZARD_HEROISM
				WIZARD_SEEKING
			BEGIN
				LAF RES_NUM_OF_SPELL_NAME STR_VAR spell_name = ~%5e_mih_arcane%~ RET spell_res END
				COPY ~enhanced-powergaming-scripts/baf/upload/mocore.baf~ ~enhanced-powergaming-scripts/baf/upload/mocore.baf~
					REPLACE_TEXTUALLY CASE_INSENSITIVE ~RES(%5e_mih_arcane%~ ~RES(%spell_res%~
			END
		END
	END

///////////////////////////////////////////////////////////////////////////
// SR - MiH Divine Spells                                                //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF mih_divine BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/sr_core_mih_divine.tph~

		ACTION_IF 5e_spellcasting BEGIN
			INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/sr_core_mih_divine_5e.tph~

			ACTION_FOR_EACH 5e_mih_divine IN
				CLERIC_SUPERHEROISM
				CLERIC_HEROISM
				CLERIC_SEEKING
				CLERIC_STRIKING
				CLERIC_CELESTIAL_PROTECTION
				CLERIC_REPEL_INSECTS
			BEGIN
				LAF RES_NUM_OF_SPELL_NAME STR_VAR spell_name = ~%5e_mih_divine%~ RET spell_res END
				COPY ~enhanced-powergaming-scripts/baf/upload/mocore.baf~ ~enhanced-powergaming-scripts/baf/upload/mocore.baf~
					REPLACE_TEXTUALLY CASE_INSENSITIVE ~RES(%5e_mih_divine%~ ~RES(%spell_res%~
			END
		END
	END

///////////////////////////////////////////////////////////////////////////
// SR - MiH - Item Pack Pre-Buffing                                      //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF mih_items AND FILE_EXISTS_IN_GAME ~MH#AMUL4.ITM~ BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/sr_core_mih_items.tph~
	END

///////////////////////////////////////////////////////////////////////////
// SR - IWD Spells                                                       //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF iwd_scs OR iwdification BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/sr_core_iwd.tph~

		ACTION_IF 5e_spellcasting BEGIN
			INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/sr_core_iwd_5e.tph~

			ACTION_FOR_EACH 5e_iwd IN
				CLERIC_IMPERVIOUS_SANCTITY_OF_MIND
				CLERIC_GREATER_SHIELD_OF_LATHANDER
				CLERIC_SHIELD_OF_LATHANDER
			BEGIN
				LAF RES_NUM_OF_SPELL_NAME STR_VAR spell_name = ~%5e_iwd%~ RET spell_res END
				COPY ~enhanced-powergaming-scripts/baf/upload/mocore.baf~ ~enhanced-powergaming-scripts/baf/upload/mocore.baf~
					REPLACE_TEXTUALLY CASE_INSENSITIVE ~RES(%5e_iwd%~ ~RES(%spell_res%~
			END
		END
	END

///////////////////////////////////////////////////////////////////////////
// SR - d5 Random Tweaks - Cure Bypass Deflection                        //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF d5_deflected BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/sr_d5_cure_dispelling.tph~
	END

///////////////////////////////////////////////////////////////////////////
// SR - Faiths & Powers - FnP Spheres                                    //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF fp_spheres BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/sr_core_fp_spl.tph~

		ACTION_IF 5e_spellcasting BEGIN
			INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/sr_core_fp_spl_5e.tph~

			ACTION_FOR_EACH 5e_fp_spl IN
				CLERIC_SPIRITUAL_CLARITY
			BEGIN
				LAF RES_NUM_OF_SPELL_NAME STR_VAR spell_name = ~%5e_fp_spl%~ RET spell_res END
				COPY ~enhanced-powergaming-scripts/baf/upload/mocore.baf~ ~enhanced-powergaming-scripts/baf/upload/mocore.baf~
					REPLACE_TEXTUALLY CASE_INSENSITIVE ~RES(%5e_fp_spl%~ ~RES(%spell_res%~
			END
		END
	END

///////////////////////////////////////////////////////////////////////////
// SR - Update IWD Dispelling Checks                                     //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF iwd_scs OR iwdification BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/sr_iwd_dispelling.tph~
	END

///////////////////////////////////////////////////////////////////////////
// SR - Update Dispelling - SCS, IWD, and MiH                            //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF scs_breach BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/sr_scs_breach.tph~
		ACTION_IF iwd_scs OR iwdification BEGIN
			ACTION_IF mih_arcane BEGIN
				INCLUDE ~enhanced-powergaming-scripts/lib/bg2ee/sr_core_breach_globe_iwd.tph~
			END ELSE BEGIN
				INCLUDE ~enhanced-powergaming-scripts/lib/sr_core_breach_iwd.tph~
			END
		END ELSE BEGIN
			ACTION_IF mih_arcane BEGIN
				INCLUDE ~enhanced-powergaming-scripts/lib/bg2ee/sr_core_breach_globe.tph~
			END ELSE BEGIN
				INCLUDE ~enhanced-powergaming-scripts/lib/sr_core_breach.tph~
			END			
		END
	END ELSE BEGIN
		ACTION_IF mih_arcane BEGIN
			INCLUDE ~enhanced-powergaming-scripts/lib/bg2ee/sr_globe.tph~
		END
	END

///////////////////////////////////////////////////////////////////////////
// SCS - Golems                                                          //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF scs_golem BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/sr_core_golem.tph~
	END

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Add Mod Components to Scripts without Spell Revisions                 //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

END ELSE BEGIN
///////////////////////////////////////////////////////////////////////////
// Build out MO-Core                                                     //
///////////////////////////////////////////////////////////////////////////		
	INCLUDE ~enhanced-powergaming-scripts/lib/core_base.tph~

	ACTION_IF GAME_IS ~bgee~ BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/bgee/core_bgee.tph~
	END

///////////////////////////////////////////////////////////////////////////
// BGEE Remove Wights                                                    //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF GAME_IS ~bgee~ BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/ini/remove_wight.tph~
	END

///////////////////////////////////////////////////////////////////////////
// 5e Spellcasting                                                       //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF 5e_spellcasting BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/core_5e.tph~

		ACTION_FOR_EACH 5e_spell IN
				WIZARD_VOCALIZE
				WIZARD_PROTECTION_FROM_MAGIC_WEAPONS
				WIZARD_ABSOLUTE_IMMUNITY
				WIZARD_IMPROVED_MANTLE
				WIZARD_MANTLE
				WIZARD_STONE_SKIN
				CLERIC_IRONSKIN
				CLERIC_SANCTUARY
				CLERIC_MASS_RAISE_DEAD
				CLERIC_RESURRECTION
				CLERIC_RAISE_DEAD
				CLERIC_RESTORATION
				CLERIC_LESSER_RESTORATION
				CLERIC_REMOVE_PARALYSIS
				CLERIC_CURE_DISEASE
				CLERIC_NEUTRALIZE_POISON
				CLERIC_SLOW_POISON
				WIZARD_RESIST_FEAR
				CLERIC_REMOVE_FEAR
				CLERIC_ZONE_OF_SWEET_AIR
				WIZARD_TRUE_SIGHT
				CLERIC_TRUE_SIGHT
				CLERIC_INVISIBILITY_PURGE
				WIZARD_DETECT_INVISIBILITY
				WIZARD_BREACH
				WIZARD_SPELL_THRUST
				WIZARD_SECRET_WORD
				WIZARD_PIERCE_MAGIC
				WIZARD_WARDING_WHIP
				WIZARD_SPELL_STRIKE
				WIZARD_PIERCE_SHIELD
				WIZARD_RUBY_RAY_OF_REVERSAL
				WIZARD_DETECT_ILLUSION
				WIZARD_MELF_METEOR
				CLERIC_HEAL
				CLERIC_CURE_SERIOUS_WOUNDS
				CLERIC_CURE_MEDIUM_WOUNDS
				CLERIC_CURE_LIGHT_WOUNDS
				CLERIC_REGENERATE
				WIZARD_MIRROR_IMAGE
				WIZARD_SPELL_SHIELD
				WIZARD_SPELL_TRAP
				WIZARD_SPELL_DEFLECTION
				WIZARD_SPELL_TURNING
				WIZARD_GLOBE_OF_INVULNERABILITY
				WIZARD_MINOR_SPELL_TURNING
				WIZARD_MINOR_SPELL_DEFLECTION
				WIZARD_MINOR_GLOBE_OF_INVULNERABILITY
				CLERIC_AURA_OF_FLAMING_DEATH
				CLERIC_GLOBE_OF_BLADES
				WIZARD_FIRE_SHIELD_RED
				WIZARD_FIRE_SHIELD_BLUE
				CLERIC_SHIELD_OF_THE_ARCHONS
				WIZARD_PROTECTION_FROM_NORMAL_MISSILES
				CLERIC_PHYSICAL_MIRROR
				CLERIC_BLADE_BARRIER
				CLERIC_DRAW_UPON_HOLY_MIGHT
				CLERIC_ARMOR_OF_FAITH
				CLERIC_PROTECTION_FROM_FIRE
				WIZARD_BLACK_BLADE_OF_DISASTER
				WIZARD_IMPROVED_HASTE
				WIZARD_MAGIC_MISSILE
				CLERIC_DOOM
				CLERIC_INSECT_PLAGUE
				CLERIC_SUNRAY
				CLERIC_FALSE_DAWN
				CLERIC_HOLD_PERSON
				CLERIC_SILENCE_15_FOOT
				WIZARD_GREATER_MALISON
				WIZARD_SLOW
				WIZARD_SLEEP
				WIZARD_HOLD_PERSON
				WIZARD_CONFUSION
				WIZARD_EMOTION_HOPELESSNESS
			BEGIN
				LAF RES_NUM_OF_SPELL_NAME STR_VAR spell_name = ~%5e_spell%~ RET spell_res END
				COPY ~enhanced-powergaming-scripts/baf/upload/mocore.baf~ ~enhanced-powergaming-scripts/baf/upload/mocore.baf~
					REPLACE_TEXTUALLY CASE_INSENSITIVE ~RES(%5e_spell%~ ~RES(%spell_res%~
			END
	END

///////////////////////////////////////////////////////////////////////////
// Turn Undead Overhaul                                                  //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF turn_undead BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/bg2ee/core_turn_undead.tph~
	END

///////////////////////////////////////////////////////////////////////////
// DSotSC                                                                //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF dsotsc_divine && !mih_divine && !iwdification BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/core_dsotsc_d.tph~
	END

///////////////////////////////////////////////////////////////////////////
// Faiths & Powers - Ranger Kits                                          //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF fp_ranger BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/ranger_fp_kit.tph~
	END

///////////////////////////////////////////////////////////////////////////
// Tome & Blood                                                          //
///////////////////////////////////////////////////////////////////////////
	// Invisibility Changes
	ACTION_IF tome_and_blood BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/core_tb_inv.tph~
	END

///////////////////////////////////////////////////////////////////////////
// Faiths & Powers - Paladin Kits                                        //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF fp_paladin BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/paladin_fp_kit.tph~
	END

///////////////////////////////////////////////////////////////////////////
// MiH - Spell Restorations                                              //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF mih_restorations BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/core_mih_sr.tph~

		ACTION_IF 5e_spellcasting BEGIN
			INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/core_mih_sr_5e.tph~

			ACTION_FOR_EACH 5e_mih_sr IN
				CLERIC_CURE_BLIND_DEAF
			BEGIN
				LAF RES_NUM_OF_SPELL_NAME STR_VAR spell_name = ~%5e_mih_sr%~ RET spell_res END
				COPY ~enhanced-powergaming-scripts/baf/upload/mocore.baf~ ~enhanced-powergaming-scripts/baf/upload/mocore.baf~
					REPLACE_TEXTUALLY CASE_INSENSITIVE ~RES(%5e_mih_sr%~ ~RES(%spell_res%~
			END
		END
	END
	
///////////////////////////////////////////////////////////////////////////
// MiH - Arcane Spells                                                   //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF mih_arcane BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/core_mih_arcane.tph~

		ACTION_IF 5e_spellcasting BEGIN
			INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/core_mih_arcane_5e.tph~

			ACTION_FOR_EACH 5e_mih_arcane IN
				WIZARD_SUPERHEROISM
				WIZARD_HEROISM
				WIZARD_SEEKING
			BEGIN
				LAF RES_NUM_OF_SPELL_NAME STR_VAR spell_name = ~%5e_mih_arcane%~ RET spell_res END
				COPY ~enhanced-powergaming-scripts/baf/upload/mocore.baf~ ~enhanced-powergaming-scripts/baf/upload/mocore.baf~
					REPLACE_TEXTUALLY CASE_INSENSITIVE ~RES(%5e_mih_arcane%~ ~RES(%spell_res%~
			END
		END
	END

///////////////////////////////////////////////////////////////////////////
// MiH - Divine Spells                                                   //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF mih_divine BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/core_mih_divine.tph~

		ACTION_IF 5e_spellcasting BEGIN
			INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/core_mih_divine_5e.tph~

			ACTION_FOR_EACH 5e_mih_divine IN
				CLERIC_SUPERHEROISM
				CLERIC_HEROISM
				CLERIC_SEEKING
				CLERIC_STRIKING
				CLERIC_CELESTIAL_PROTECTION
				CLERIC_REPEL_INSECTS
				CLERIC_BREAK_ENCHANTMENT
			BEGIN
				LAF RES_NUM_OF_SPELL_NAME STR_VAR spell_name = ~%5e_mih_divine%~ RET spell_res END
				COPY ~enhanced-powergaming-scripts/baf/upload/mocore.baf~ ~enhanced-powergaming-scripts/baf/upload/mocore.baf~
					REPLACE_TEXTUALLY CASE_INSENSITIVE ~RES(%5e_mih_divine%~ ~RES(%spell_res%~
			END
		END
	END

///////////////////////////////////////////////////////////////////////////
// MiH - Item Pack Pre-Buffing                                           //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF mih_items AND FILE_EXISTS_IN_GAME ~MH#AMUL4.ITM~ BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/core_mih_items.tph~
	END

///////////////////////////////////////////////////////////////////////////
// IWD Spells                                                            //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF iwd_scs OR iwdification BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/core_iwd.tph~

		ACTION_IF 5e_spellcasting BEGIN
			INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/core_iwd_5e.tph~

			ACTION_FOR_EACH 5e_iwd IN
				WIZARD_MIND_BLANK
				CLERIC_IMPERVIOUS_SANCTITY_OF_MIND
				CLERIC_GREATER_SHIELD_OF_LATHANDER
				CLERIC_SHIELD_OF_LATHANDER
				CLERIC_CURE_MODERATE_WOUNDS
			BEGIN
				LAF RES_NUM_OF_SPELL_NAME STR_VAR spell_name = ~%5e_iwd%~ RET spell_res END
				COPY ~enhanced-powergaming-scripts/baf/upload/mocore.baf~ ~enhanced-powergaming-scripts/baf/upload/mocore.baf~
					REPLACE_TEXTUALLY CASE_INSENSITIVE ~RES(%5e_iwd%~ ~RES(%spell_res%~
			END
		END
	END

///////////////////////////////////////////////////////////////////////////
// d5 Random Tweaks - Cure Bypass Deflection                             //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF d5_deflected BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/d5_cure_dispelling.tph~

		ACTION_IF 5e_spellcasting BEGIN
			INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/d5_cure_dispelling_5e.tph~
		END
	END

///////////////////////////////////////////////////////////////////////////
// Faiths & Powers - FnP Spheres                                         //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF fp_spheres BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/core_fp_spl.tph~

		ACTION_IF 5e_spellcasting BEGIN
			INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/core_fp_spl_5e.tph~

			ACTION_FOR_EACH 5e_fp_spl IN
				CLERIC_SPIRITUAL_CLARITY
			BEGIN
				LAF RES_NUM_OF_SPELL_NAME STR_VAR spell_name = ~%5e_fp_spl%~ RET spell_res END
				COPY ~enhanced-powergaming-scripts/baf/upload/mocore.baf~ ~enhanced-powergaming-scripts/baf/upload/mocore.baf~
					REPLACE_TEXTUALLY CASE_INSENSITIVE ~RES(%5e_fp_spl%~ ~RES(%spell_res%~
			END
		END
	END

///////////////////////////////////////////////////////////////////////////
// Update IWD Dispelling Checks                                          //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF iwd_scs OR iwdification BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/iwd_dispelling.tph~
	END

///////////////////////////////////////////////////////////////////////////
// Update Dispelling - SCS, IWD, and MiH                                 //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF scs_breach BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/scs_breach.tph~
		ACTION_IF iwd_scs OR iwdification BEGIN
			ACTION_IF mih_arcane BEGIN
				INCLUDE ~enhanced-powergaming-scripts/lib/bg2ee/core_breach_globe_iwd.tph~
			END ELSE BEGIN
				INCLUDE ~enhanced-powergaming-scripts/lib/core_breach_iwd.tph~
			END
		END ELSE BEGIN
			ACTION_IF mih_arcane BEGIN
				INCLUDE ~enhanced-powergaming-scripts/lib/bg2ee/core_breach_globe.tph~
			END ELSE BEGIN
				INCLUDE ~enhanced-powergaming-scripts/lib/core_breach.tph~
			END			
		END
	END ELSE BEGIN
		ACTION_IF iwd_scs OR iwdification BEGIN
			ACTION_IF mih_arcane BEGIN
				INCLUDE ~enhanced-powergaming-scripts/lib/bg2ee/globe_iwd.tph~
			END
		END ELSE BEGIN
			ACTION_IF mih_arcane BEGIN
				INCLUDE ~enhanced-powergaming-scripts/lib/bg2ee/globe.tph~
			END
		END
	END

///////////////////////////////////////////////////////////////////////////
// Golems                                                                //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF scs_golem BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/core_golem.tph~

		ACTION_IF 5e_spellcasting BEGIN
			INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/core_golem_5e.tph~
		END
	END
END

///////////////////////////////////////////////////////////////////////////
// Update ini Presets                                                    //
///////////////////////////////////////////////////////////////////////////
// Fast Healing
ACTION_IF fst_heal BEGIN
	INCLUDE ~enhanced-powergaming-scripts/lib/ini/core_fast_healing.tph~
END

// Removes Dialog Hovertext from Scripts
ACTION_IF scp_dlg BEGIN
	INCLUDE ~enhanced-powergaming-scripts/lib/ini/core_dialog.tph~
END

///////////////////////////////////////////////////////////////////////////
// MiH - Arcane Spells Major Globe                                       //
///////////////////////////////////////////////////////////////////////////
ACTION_IF mih_arcane BEGIN
	INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/core_mih_globe.tph~
END
	
///////////////////////////////////////////////////////////////////////////
// Thieving Skills for Bards                                             //
///////////////////////////////////////////////////////////////////////////
ACTION_IF bard_thief BEGIN
	INCLUDE ~enhanced-powergaming-scripts/lib/bard_thief.tph~
END

///////////////////////////////////////////////////////////////////////////
// Remove Athkatla Check from Main (BGEE ONLY)                           //
///////////////////////////////////////////////////////////////////////////
ACTION_IF GAME_IS ~bgee~ BEGIN
	INCLUDE ~enhanced-powergaming-scripts/lib/BGEE/bgee_remove_athkatla.tph~
END

///////////////////////////////////////////////////////////////////////////
// Turn Undead Overhaul - END                                            //
///////////////////////////////////////////////////////////////////////////
ACTION_IF turn_undead BEGIN
	INCLUDE ~enhanced-powergaming-scripts/lib/bg2ee/core_turn_undead_end.tph~
END

///////////////////////////////////////////////////////////////////////////
// Skills and Abilities Paladin Overhaul                                 //
///////////////////////////////////////////////////////////////////////////
ACTION_IF pally_smite BEGIN
	INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/core_pally_smite.tph~

	ACTION_IF GAME_IS ~bg2ee eet~ BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/core_pally_smite_check.tph~
	END ELSE ACTION_IF GAME_IS ~bgee~ BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/BGEE/core_pally_smite_check.tph~
	END
END

///////////////////////////////////////////////////////////////////////////
// Skills and Abilities Psi Warrior                                      //
///////////////////////////////////////////////////////////////////////////
ACTION_IF psi_warrior BEGIN
	INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/core_psi_warrior.tph~
	INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/core_psi_warrior_check.tph~
END

///////////////////////////////////////////////////////////////////////////
// Skills and Abilities Eldritch Scion                                   //
///////////////////////////////////////////////////////////////////////////
ACTION_IF eldritch_scion BEGIN
	INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/core_eldritch_scion.tph~
END

///////////////////////////////////////////////////////////////////////////
// Skills and Abilities Fighter Updates                                  //
///////////////////////////////////////////////////////////////////////////
ACTION_IF fighter_overhaul BEGIN
	INCLUDE ~enhanced-powergaming-scripts/lib/BG2EE/core_sa_wind.tph~
END

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// 5e Spellcasting names                                                 //
// Code in this section provided by Subtledoctor                         //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
ACTION_IF 5e_spellcasting BEGIN
	COPY_EXISTING ~d5zclons.2da~ ~override~
  	COUNT_2DA_COLS cols
  	COUNT_2DA_ROWS cols rows
  	FOR (row = 1; row < rows; ++row) BEGIN
    	READ_2DA_ENTRY row 0 cols ind_num
    	READ_2DA_ENTRY row 2 cols mem_spl
    	SPRINT $5e_spells_array(~d5z%ind_num%i~)~%mem_spl%~
  	END
	BUT_ONLY

	COPY ~enhanced-powergaming-scripts/baf/upload/mocore.baf~ ~enhanced-powergaming-scripts/baf/upload/mocore.baf~
	  PHP_EACH 5e_spells_array AS new_spl => old_spl BEGIN
	    REPLACE_TEXTUALLY CASE_INSENSITIVE ~%old_spl%~ ~"%new_spl%"~
	  END
END

///////////////////////////////////////////////////////////////////////////
// EEex Check                                                            //
///////////////////////////////////////////////////////////////////////////
ACTION_IF eeex_present BEGIN
	COPY ~enhanced-powergaming-scripts/lua/m_actri1.lua~  ~override~ 
	COPY ~enhanced-powergaming-scripts/lua/m_actri2.lua~  ~override~
END ELSE BEGIN
	INCLUDE ~enhanced-powergaming-scripts/lib/core_eeex.tph~
END

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Import AI Script into the Game                                        //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Copy .BCS file to override folder                                     //
///////////////////////////////////////////////////////////////////////////
COPY ~enhanced-powergaming-scripts/baf/upload/mocore.baf~ ~override/bddefai.bcs~
  COMPILE_BAF_TO_BCS

///////////////////////////////////////////////////////////////////////////
// Copied from Stratagems to update partyai.2da                          //
///////////////////////////////////////////////////////////////////////////
COPY_EXISTING "PARTYAI.2da" override
    COUNT_2DA_ROWS 2 rowcount
    FOR (i=1;i<rowcount;i+=1) BEGIN
       SET_2DA_ENTRY i 1 2 "BDDEFAI"
    END
 BUT_ONLY

///////////////////////////////////////////////////////////////////////////
// Update Lua Files                                                      //
// Please Note: This accounts for vanilla and changes made by SCS        //
///////////////////////////////////////////////////////////////////////////
OUTER_SPRINT smartscript1a     @1110
OUTER_SPRINT smartscript1b     @1111
OUTER_SPRINT smartscript2      @1112
OUTER_SPRINT smartscriptdesc1a @1120
OUTER_SPRINT smartscriptdesc1b @1121
OUTER_SPRINT smartscriptdesc2  @1122
OUTER_SPRINT scriptatk1        @1130
OUTER_SPRINT scriptatk2        @1131
OUTER_SPRINT findtrap1         @1140
OUTER_SPRINT findtrap2         @1141
OUTER_SPRINT findtrapdesc1a    @1150
OUTER_SPRINT findtrapdesc1b    @1151
OUTER_SPRINT findtrapdesc2     @1152
OUTER_SPRINT hideshdws1        @1160
OUTER_SPRINT hideshdws2        @1161
OUTER_SPRINT hideshdwsdesc1    @1170
OUTER_SPRINT hideshdwsdesc2    @1171
OUTER_SPRINT bardsong1         @1180
OUTER_SPRINT bardsong2         @1181
OUTER_SPRINT bardsongdesc1a    @1190
OUTER_SPRINT bardsongdesc1b    @1191
OUTER_SPRINT bardsongdesc2     @1192
OUTER_SPRINT trnund1           @1200
OUTER_SPRINT trnund2           @1201
OUTER_SPRINT trnunddesc1a      @1210
OUTER_SPRINT trnunddesc1b      @1211
OUTER_SPRINT trnunddesc2       @1212
OUTER_SPRINT defense1          @1220
OUTER_SPRINT defense2          @1221
OUTER_SPRINT defensedesc1      @1230
OUTER_SPRINT defensedesc2      @1231
OUTER_SPRINT useitem1          @1240
OUTER_SPRINT useitem2          @1241
OUTER_SPRINT useitemdesc1      @1250
OUTER_SPRINT useitemdesc2      @1251
OUTER_SPRINT solobuff1         @1260
OUTER_SPRINT solobuff2         @1261
OUTER_SPRINT solobuffdesc1a    @1270
OUTER_SPRINT solobuffdesc1b    @1271
OUTER_SPRINT solobuffdesc2     @1272
OUTER_SPRINT offense1          @1280
OUTER_SPRINT offense2          @1281
OUTER_SPRINT offensedesc1      @1290
OUTER_SPRINT offensedesc2      @1291
OUTER_SPRINT groupbuff1        @1300
OUTER_SPRINT groupbuff2        @1301
OUTER_SPRINT groupbuffdesc1a   @1310
OUTER_SPRINT groupbuffdesc1b   @1311
OUTER_SPRINT groupbuffdesc2    @1312
OUTER_SPRINT specbuff1a        @1320
OUTER_SPRINT specbuff1b        @1321
OUTER_SPRINT specbuff2         @1322
OUTER_SPRINT specbuffdesc1a    @1330
OUTER_SPRINT specbuffdesc1b    @1331
OUTER_SPRINT specbuffdesc2     @1332

ACTION_FOR_EACH luafile IN
		CS_CZ
		DE_DE
		EN_US
		ES_ES
		FR_FR
		IT_IT
		KO_KR
		PL_PL
		PT_BR
		RU_RU
		ZN_CN
	BEGIN
		ACTION_IF FILE_EXISTS_IN_GAME ~L_%luafile%.LUA~ BEGIN
			COPY_EXISTING "L_%luafile%.LUA" ~override~
				REPLACE_TEXTUALLY ~%smartscript1a%~     ~%smartscript2%~
	    		REPLACE_TEXTUALLY ~%smartscript1b%~     ~%smartscript2%~
	    		REPLACE_TEXTUALLY ~%smartscriptdesc1a%~ ~%smartscriptdesc2%~
	   			REPLACE_TEXTUALLY ~%smartscriptdesc1b%~ ~%smartscriptdesc2%~
	   			REPLACE_TEXTUALLY ~%scriptatk1%~        ~%scriptatk2%~
	   			REPLACE_TEXTUALLY ~%findtrap1%~         ~%findtrap2%~
	   			REPLACE_TEXTUALLY ~%findtrapdesc1a%~    ~%findtrapdesc2%~
	   			REPLACE_TEXTUALLY ~%findtrapdesc1b%~    ~%findtrapdesc2%~
	   			REPLACE_TEXTUALLY ~%hideshdws1%~        ~%hideshdws2%~
	   			REPLACE_TEXTUALLY ~%hideshdwsdesc1%~    ~%hideshdwsdesc2%~
	   			REPLACE_TEXTUALLY ~%bardsong1%~         ~%bardsong2%~
	   			REPLACE_TEXTUALLY ~%bardsongdesc1a%~    ~%bardsongdesc2%~
	   			REPLACE_TEXTUALLY ~%bardsongdesc1b%~    ~%bardsongdesc2%~
	   			REPLACE_TEXTUALLY ~%trnund1%~           ~%trnund2%~
	   			REPLACE_TEXTUALLY ~%trnunddesc1a%~      ~%trnunddesc2%~
	   			REPLACE_TEXTUALLY ~%trnunddesc1b%~      ~%trnunddesc2%~
	   			REPLACE_TEXTUALLY ~%defense1%~          ~%defense2%~
	   			REPLACE_TEXTUALLY ~%defensedesc1%~      ~%defensedesc2%~
	   			REPLACE_TEXTUALLY ~%useitem1%~          ~%useitem2%~
	   			REPLACE_TEXTUALLY ~%useitemdesc1%~      ~%useitemdesc2%~
	   			REPLACE_TEXTUALLY ~%solobuff1%~         ~%solobuff2%~
	   			REPLACE_TEXTUALLY ~%solobuffdesc1a%~    ~%solobuffdesc2%~
	   			REPLACE_TEXTUALLY ~%solobuffdesc1b%~    ~%solobuffdesc2%~
	   			REPLACE_TEXTUALLY ~%offense1%~          ~%offense2%~
	   			REPLACE_TEXTUALLY ~%offensedesc1%~      ~%offensedesc2%~
	   			REPLACE_TEXTUALLY ~%groupbuff1%~        ~%groupbuff2%~
	   			REPLACE_TEXTUALLY ~%groupbuffdesc1a%~   ~%groupbuffdesc2%~
	   			REPLACE_TEXTUALLY ~%groupbuffdesc1b%~   ~%groupbuffdesc2%~
	   			REPLACE_TEXTUALLY ~%specbuff1a%~        ~%specbuff2%~
	   			REPLACE_TEXTUALLY ~%specbuff1b%~        ~%specbuff2%~
	   			REPLACE_TEXTUALLY ~%specbuff1a%~        ~%specbuff2%~
	   			REPLACE_TEXTUALLY ~%specbuff1b%~        ~%specbuff2%~
	   			REPLACE_TEXTUALLY ~%specbuff1b%~        ~%specbuff2%~
	   			REPLACE_TEXTUALLY ~%specbuffdesc1a%~    ~%specbuffdesc2%~
	   			REPLACE_TEXTUALLY ~%specbuffdesc1b%~    ~%specbuffdesc2%~
	   		BUT_ONLY
		END
	END
