///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Restore Vanilla Haste Spells                                          //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Restores Haste                                                        //
///////////////////////////////////////////////////////////////////////////

COPY ~enhanced-powergaming-scripts\spl\SPWI305.SPL~     ~override~  
  SAY NAME1 @4010    
  SAY NAME2 @4010
  SAY UNIDENTIFIED_DESC @4011
  SAY IDENTIFIED_DESC @4011
COPY ~enhanced-powergaming-scripts\spl\SCRL1H.ITM~     ~override~
  SAY NAME1 @4010    
  SAY NAME2 @4010
  SAY UNIDENTIFIED_DESC @4011
  SAY IDENTIFIED_DESC @4011

COPY ~enhanced-powergaming-scripts\spl\dwsw305.spl~     ~override~  
  SAY NAME1 @4010    
  SAY NAME2 @4010
  SAY UNIDENTIFIED_DESC @4011
  SAY IDENTIFIED_DESC @4011

///////////////////////////////////////////////////////////////////////////
// Restores Improved Haste                                               //
///////////////////////////////////////////////////////////////////////////

COPY ~enhanced-powergaming-scripts\spl\SPWI613.SPL~     ~override~
  SAY NAME1 @4020
  SAY NAME2 @4020     
  SAY UNIDENTIFIED_DESC @4021
  SAY IDENTIFIED_DESC   @4021
COPY ~enhanced-powergaming-scripts\spl\SCRL7Q.ITM~     ~override~
  SAY NAME1 @4020
  SAY NAME2 @4020     
  SAY UNIDENTIFIED_DESC @4021
  SAY IDENTIFIED_DESC   @4021

COPY ~enhanced-powergaming-scripts\spl\dwsw613.spl~     ~override~
  SAY NAME1 @4020
  SAY NAME2 @4020     
  SAY UNIDENTIFIED_DESC @4021
  SAY IDENTIFIED_DESC   @4021
