LOAD_TRA ~enhanced-powergaming-scripts/languages/%LANGUAGE%/script_dialog.tra~

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Enhanced Scripts for Simulacrum                                       //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
ACTION_IF GAME_IS ~iwdee~ BEGIN
	INCLUDE ~enhanced-powergaming-scripts/lib/IWDEE/mosim07_iwd.tph~
	INCLUDE ~enhanced-powergaming-scripts/lib/IWDEE/mosim07_iwd_hla.tph~

	/*
	ACTION_IF !saa_hla BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/IWDEE/mosim07_iwd_hla.tph~
	END
	*/
END

COPY ~enhanced-powergaming-scripts/baf/upload/mocore.baf~  ~enhanced-powergaming-scripts/baf/upload/mosim02.baf~

INCLUDE ~enhanced-powergaming-scripts/lib/simulacrum/core_sim.tph~

///////////////////////////////////////////////////////////////////////////
// EEex Check                                                            //
///////////////////////////////////////////////////////////////////////////
ACTION_IF NOT eeex_present BEGIN
	INCLUDE ~enhanced-powergaming-scripts/lib/simulacrum/mosim02_eeex.tph~
	INCLUDE ~enhanced-powergaming-scripts/lib/simulacrum/mosim07_eeex.tph~
END

///////////////////////////////////////////////////////////////////////////
// Copy .BCS files to override folder                                    //
///////////////////////////////////////////////////////////////////////////
COPY ~enhanced-powergaming-scripts/baf/upload/mosim02.baf~   	   ~override/mosim02.bcs~
	 ~enhanced-powergaming-scripts/baf/simulacrum/mosim07.baf~     ~override/mosim07.bcs~
	 ~enhanced-powergaming-scripts/baf/simulacrum/mosim01.baf~     ~override/mosim01.bcs~
  COMPILE_BAF_TO_BCS

ACTION_IF scs_breach BEGIN
	//EXTEND_BOTTOM ~dw#image.bcs~ ~enhanced-powergaming-scripts/baf/simulacrum/mosim01.baf~
	COPY_EXISTING ~SIMULACR.SPL~ ~override~ 
		  LPF DELETE_SPELL_EFFECT INT_VAR opcode_to_delete = 82 END
		  LPF ADD_SPELL_EFFECT STR_VAR opcode = 82 target = 1 power = 0 parameter2 = 6 timing = 9 resource = ~mosim01~ END
END ELSE BEGIN
	COPY_EXISTING ~SIMULACR.SPL~ ~override~ 
		  LPF ADD_SPELL_EFFECT STR_VAR opcode = 82 target = 1 power = 0 parameter2 = 6 timing = 9 resource = ~mosim01~ END
END