///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Enhanced Scripts for Simulacrum                                       //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Copy .BCS files to override folder                                    //
///////////////////////////////////////////////////////////////////////////
COPY ~enhanced-powergaming-scripts/baf/upload/morang.baf~   	   ~override/mosim05.bcs~
	 ~enhanced-powergaming-scripts/baf/upload/mocore.baf~   	   ~override/mosim02.bcs~
	 ~enhanced-powergaming-scripts/baf/upload/momonk.baf~   	   ~override/mosim03.bcs~
	 ~enhanced-powergaming-scripts/baf/upload/mopal.baf~    	   ~override/mosim04.bcs~
	 ~enhanced-powergaming-scripts/baf/upload/moskd.baf~ 		   ~override/mosim06.bcs~
	 ~enhanced-powergaming-scripts/baf/simulacrum/mosim07.baf~     ~override/mosim07.bcs~
	 ~enhanced-powergaming-scripts/baf/simulacrum/mosim01.baf~     ~override/mosim01.bcs~
  COMPILE_BAF_TO_BCS

COPY_EXISTING ~SIMULACR.SPL~ ~override~ 
	  LPF ADD_SPELL_EFFECT STR_VAR opcode = 82 target = 1 power = 0 parameter2 = 6 timing = 9 resource = ~mosim01~ END