COPY ~enhanced-powergaming-scripts/baf/upload/mocore.baf~ ~enhanced-powergaming-scripts/baf/upload/mocore.baf~

///////////////////////////////////////////////////////////////////////////
// Add Major Globe                                                       //
///////////////////////////////////////////////////////////////////////////
  LPF REPLACE_MULTILINE
    INT_VAR
    strict = 1
    verbose = 0
    STR_VAR
    pattern = ~~~~~!CheckSpellState(Myself,GLOBE)~~~~~
    string = ~~~~~!CheckSpellState(Myself,GLOBE)
  !CheckSpellState(Myself,MAJOR_GLOBE)~~~~~ //"
  END

  LPF REPLACE_MULTILINE
    INT_VAR
    strict = 1
    verbose = 0
    STR_VAR
    pattern = ~~~~~// Major Globe~~~~~
    string = ~~~~~!CheckSpellState(Myself,MAJOR_GLOBE)~~~~~ //"
  END

