COPY ~enhanced-powergaming-scripts/baf/upload/mocore.baf~ ~enhanced-powergaming-scripts/baf/upload/mocore.baf~

///////////////////////////////////////////////////////////////////////////
// Restoration, Disease, Poison, Heal, Break Enchantment (MiH)           //
///////////////////////////////////////////////////////////////////////////
  LPF REPLACE_MULTILINE
    INT_VAR
    strict = 1
    verbose = 0
    STR_VAR
    pattern = ~~~~~!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION) // d5 cure dispelling~~~~~
    string = ~~~~~~~~~~ //"
  END


