COPY ~enhanced-powergaming-scripts/baf/upload/mocore.baf~ ~enhanced-powergaming-scripts/baf/upload/mocore.baf~

///////////////////////////////////////////////////////////////////////////
// Add Reckless Abandon                                                  //
///////////////////////////////////////////////////////////////////////////
  LPF REPLACE_MULTILINE
    INT_VAR
    strict = 1
    verbose = 0
    STR_VAR
    pattern = ~~~~~// Morpheus562 Kitpack Prebuff Reckless Abandon~~~~~
    string = ~~~~~IF
  Global("MO_BUFF","LOCALS",1)
  HaveSpellRES("MOBTR01")
  !CheckSpellState(Myself,BERSERKER_RAGE_FATIGUE)
  !CheckSpellState(Myself,BERSERKER_RAGE)
THEN
  RESPONSE #100
    SpellRES("MOBTR01",Myself)
END~~~~~ //"
  END
