COPY ~enhanced-powergaming-scripts/baf/upload/moskd.baf~ ~enhanced-powergaming-scripts/baf/upload/moskd.baf~

///////////////////////////////////////////////////////////////////////////
// Remove Cast Athkatla Check                                            //
///////////////////////////////////////////////////////////////////////////
  LPF REPLACE_MULTILINE
    INT_VAR
    strict = 1
    verbose = 0
    STR_VAR
    pattern = ~~~~~Global("MO_CastAthkatla","LOCALS",1)~~~~~
    string = ~~~~~~~~~~ //"
  END