// **********************************************************************
// *           Segment Name: moevd01.baf
// **********************************************************************
// *
// * Description:
// * This script sets ai for Evil Deva

IF
  Allegiance(Myself,GOODCUTOFF)
THEN
  RESPONSE #100
    ChangeAIScript("moevd03",OVERRIDE)
END

IF
  !Allegiance(Myself,GOODCUTOFF)
THEN
  RESPONSE #100
    ChangeAIScript("moevd02",OVERRIDE)
END