// **********************************************************************
// *           Segment Name: mogdd01.baf
// **********************************************************************
// *
// * Description:
// * This script sets ai for Good Deva

IF
  Allegiance(Myself,GOODCUTOFF)
THEN
  RESPONSE #100
    ChangeAIScript("mogdd03",OVERRIDE)
END

IF
  !Allegiance(Myself,GOODCUTOFF)
THEN
  RESPONSE #100
    ChangeAIScript("mogdd02",OVERRIDE)
END