// **********************************************************************
// *           Segment Name: mogdd01.baf
// **********************************************************************
// *
// * Description:
// * This script sets ai for Good Deva

IF
  Allegiance(Myself,GOODCUTOFF)
THEN
  RESPONSE #100
    ChangeAIScript("mogdd03",GENERAL)
END

IF
  !Allegiance(Myself,GOODCUTOFF)
THEN
  RESPONSE #100
    ChangeAIScript("mogdd02",GENERAL)
END