///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Add Mod Components to Scripts with Spell Revisions                    //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
ACTION_IF (MOD_IS_INSTALLED ~setup-spell_rev.tp2~ ~0~) BEGIN

///////////////////////////////////////////////////////////////////////////
// SR- Base Game                                                         //
///////////////////////////////////////////////////////////////////////////
	COPY ~enhanced-powergaming-scripts/baf/Accelerated/sr/morang.baf~  ~enhanced-powergaming-scripts/baf/upload/morang.baf~
	COPY ~enhanced-powergaming-scripts/baf/Accelerated/sr/mocore.baf~  ~enhanced-powergaming-scripts/baf/upload/mobasic.baf~
	COPY ~enhanced-powergaming-scripts/baf/Accelerated/sr/mocore.baf~  ~enhanced-powergaming-scripts/baf/upload/mocore.baf~
	COPY ~enhanced-powergaming-scripts/baf/Accelerated/sr/mopal.baf~   ~enhanced-powergaming-scripts/baf/upload/mopal.baf~
	COPY ~enhanced-powergaming-scripts/baf/Accelerated/sr/momonk.baf~  ~enhanced-powergaming-scripts/baf/upload/momonk.baf~

	INCLUDE ~enhanced-powergaming-scripts/lib/sr_ranger_base.tph~
	INCLUDE ~enhanced-powergaming-scripts/lib/sr_basic_base.tph~
	INCLUDE ~enhanced-powergaming-scripts/lib/sr_core_base.tph~
	INCLUDE ~enhanced-powergaming-scripts/lib/sr_monk_base.tph~
	INCLUDE ~enhanced-powergaming-scripts/lib/sr_paladin_base.tph~

///////////////////////////////////////////////////////////////////////////
// SR - Song & Silence                                                   //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF (MOD_IS_INSTALLED ~setup-song_and_silence.tp2~ ~8~) BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/basic_ss_a.tph~
		INCLUDE ~enhanced-powergaming-scripts/lib/core_ss_a.tph~
	END

///////////////////////////////////////////////////////////////////////////
// SR - IWD Spells                                                       //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF (MOD_IS_INSTALLED ~setup-stratagems.tp2~ ~1500~ && MOD_IS_INSTALLED ~setup-stratagems.tp2~ ~1510~) || (MOD_IS_INSTALLED ~iwdification/setup-iwdification.tp2~ 30 && MOD_IS_INSTALLED ~iwdification/setup-iwdification.tp2~ 40) BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/sr_basic_iwd_a.tph~
		INCLUDE ~enhanced-powergaming-scripts/lib/sr_core_iwd_a.tph~
		INCLUDE ~enhanced-powergaming-scripts/lib/sr_paladin_iwd.tph~
	END

///////////////////////////////////////////////////////////////////////////
// SR - Tome & Blood                                                     //
///////////////////////////////////////////////////////////////////////////
	// Invisibility Changes
	ACTION_IF (MOD_IS_INSTALLED ~setup-TomeAndBlood.tp2~ ~14~) BEGIN
		
		ACTION_IF (MOD_IS_INSTALLED ~setup-stratagems.tp2~ ~1500~ && MOD_IS_INSTALLED ~setup-stratagems.tp2~ ~1510~) || (MOD_IS_INSTALLED ~iwdification/setup-iwdification.tp2~ 30 && MOD_IS_INSTALLED ~iwdification/setup-iwdification.tp2~ 40) BEGIN
			INCLUDE ~enhanced-powergaming-scripts/lib/sr_core_iwd_tb_inv.tph~
		END ELSE BEGIN
			INCLUDE ~enhanced-powergaming-scripts/lib/sr_core_tb_inv.tph~
		END
	END

///////////////////////////////////////////////////////////////////////////
// SR - Faiths & Powers - Ranger Kits                                    //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF (MOD_IS_INSTALLED ~setup-faiths_and_powers.tp2~ ~37~) BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/sr_ranger_fp_kit_a.tph~
		
		ACTION_IF (MOD_IS_INSTALLED ~setup-stratagems.tp2~ ~1500~ && MOD_IS_INSTALLED ~setup-stratagems.tp2~ ~1510~) || (MOD_IS_INSTALLED ~iwdification/setup-iwdification.tp2~ 30 && MOD_IS_INSTALLED ~iwdification/setup-iwdification.tp2~ 40) BEGIN
			INCLUDE ~enhanced-powergaming-scripts/lib/sr_ranger_iwd_fp_kit.tph~
		END
	END

///////////////////////////////////////////////////////////////////////////
// SR - Faiths & Powers - Paladin Kits                                   //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF (MOD_IS_INSTALLED ~setup-faiths_and_powers.tp2~ ~35~) BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/sr_paladin_fp_kit.tph~
	END

///////////////////////////////////////////////////////////////////////////
// SR- Faiths & Powers - Cleric Kits                                     //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF (MOD_IS_INSTALLED ~setup-faiths_and_powers.tp2~ ~35~) BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/core_fp_kit.tph~
	END

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Add Mod Components to Scripts without Spell Revisions                 //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

END ELSE BEGIN
///////////////////////////////////////////////////////////////////////////
// Base Game                                                             //
///////////////////////////////////////////////////////////////////////////
	COPY ~enhanced-powergaming-scripts/baf/Accelerated/morang.baf~  ~enhanced-powergaming-scripts/baf/upload/morang.baf~
	COPY ~enhanced-powergaming-scripts/baf/Accelerated/mocore.baf~  ~enhanced-powergaming-scripts/baf/upload/mobasic.baf~
	COPY ~enhanced-powergaming-scripts/baf/Accelerated/mocore.baf~  ~enhanced-powergaming-scripts/baf/upload/mocore.baf~
	COPY ~enhanced-powergaming-scripts/baf/Accelerated/mopal.baf~   ~enhanced-powergaming-scripts/baf/upload/mopal.baf~
	COPY ~enhanced-powergaming-scripts/baf/Accelerated/momonk.baf~  ~enhanced-powergaming-scripts/baf/upload/momonk.baf~

	INCLUDE ~enhanced-powergaming-scripts/lib/ranger_base.tph~
	INCLUDE ~enhanced-powergaming-scripts/lib/basic_base.tph~
	INCLUDE ~enhanced-powergaming-scripts/lib/core_base.tph~
	INCLUDE ~enhanced-powergaming-scripts/lib/monk_base.tph~
	INCLUDE ~enhanced-powergaming-scripts/lib/paladin_base.tph~

///////////////////////////////////////////////////////////////////////////
// DSotSC                                                                //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF FILE_EXISTS_IN_GAME ~WIZARD_ARMY_OF_ONE~ BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/core_dsotsc_w_a.tph~
	END 
	
	ACTION_IF FILE_EXISTS_IN_GAME ~sppr519.spl~ && FILE_EXISTS_IN_GAME ~sppr716.spl~ BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/core_dsotsc_d_a.tph~
	END

///////////////////////////////////////////////////////////////////////////
// Song & Silence                                                        //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF (MOD_IS_INSTALLED ~setup-song_and_silence.tp2~ ~8~) BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/basic_ss_a.tph~
		INCLUDE ~enhanced-powergaming-scripts/lib/core_ss_a.tph~
	END

///////////////////////////////////////////////////////////////////////////
// IWD Spells                                                            //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF (MOD_IS_INSTALLED ~setup-stratagems.tp2~ ~1500~ && MOD_IS_INSTALLED ~setup-stratagems.tp2~ ~1510~) || (MOD_IS_INSTALLED ~iwdification/setup-iwdification.tp2~ 30 && MOD_IS_INSTALLED ~iwdification/setup-iwdification.tp2~ 40) BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/ranger_iwd_a.tph~
		INCLUDE ~enhanced-powergaming-scripts/lib/basic_iwd_a.tph~
		INCLUDE ~enhanced-powergaming-scripts/lib/core_iwd_a.tph~
		INCLUDE ~enhanced-powergaming-scripts/lib/paladin_iwd_a.tph~
	END

///////////////////////////////////////////////////////////////////////////
// Tome & Blood                                                          //
///////////////////////////////////////////////////////////////////////////
	// Invisibility Changes
	ACTION_IF (MOD_IS_INSTALLED ~setup-TomeAndBlood.tp2~ ~14~) BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/core_tb_inv.tph~
	END

///////////////////////////////////////////////////////////////////////////
// Faiths & Powers - Ranger Kits                                          //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF (MOD_IS_INSTALLED ~setup-faiths_and_powers.tp2~ ~37~) BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/ranger_fp_kit_a.tph~
		
		ACTION_IF (MOD_IS_INSTALLED ~setup-stratagems.tp2~ ~1500~ && MOD_IS_INSTALLED ~setup-stratagems.tp2~ ~1510~) || (MOD_IS_INSTALLED ~iwdification/setup-iwdification.tp2~ 30 && MOD_IS_INSTALLED ~iwdification/setup-iwdification.tp2~ 40) BEGIN
			INCLUDE ~enhanced-powergaming-scripts/lib/ranger_iwd_fp_kit.tph~
		END
	END

///////////////////////////////////////////////////////////////////////////
// Faiths & Powers - Paladin Kits                                        //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF (MOD_IS_INSTALLED ~setup-faiths_and_powers.tp2~ ~35~) BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/paladin_fp_kit.tph~
	END

///////////////////////////////////////////////////////////////////////////
// Faiths & Powers - Cleric Kits                                         //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF (MOD_IS_INSTALLED ~setup-faiths_and_powers.tp2~ ~35~) BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/core_fp_kit.tph~
	END

///////////////////////////////////////////////////////////////////////////
// Faiths & Powers - FnP Spheres                                         //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF (MOD_IS_INSTALLED ~setup-faiths_and_powers.tp2~ ~21~) BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/ranger_fp_spl_a.tph~
		INCLUDE ~enhanced-powergaming-scripts/lib/basic_fp_spl_a.tph~
		INCLUDE ~enhanced-powergaming-scripts/lib/core_fp_spl_a.tph~

		ACTION_IF (MOD_IS_INSTALLED ~setup-stratagems.tp2~ ~1500~ && MOD_IS_INSTALLED ~setup-stratagems.tp2~ ~1510~) || (MOD_IS_INSTALLED ~iwdification/setup-iwdification.tp2~ 30 && MOD_IS_INSTALLED ~iwdification/setup-iwdification.tp2~ 40) BEGIN
			INCLUDE ~enhanced-powergaming-scripts/lib/ranger_iwd_fp_spl.tph~
		END
	END

///////////////////////////////////////////////////////////////////////////
// SCS - Breach                                                          //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF (MOD_IS_INSTALLED ~setup-stratagems.tp2~ ~5900~) BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/core_breach.tph~

		ACTION_IF (MOD_IS_INSTALLED ~setup-faiths_and_powers.tp2~ ~37~) BEGIN
			INCLUDE ~enhanced-powergaming-scripts/lib/ranger_breach.tph~
		END
	END
END

///////////////////////////////////////////////////////////////////////////
// Create Skald Script Modeled After Core                                //
///////////////////////////////////////////////////////////////////////////
	INCLUDE ~enhanced-powergaming-scripts/lib/skald_base.tph~

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Import AI Scripts into the Game                                       //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Copy .BS files to scripts folder                                      //
///////////////////////////////////////////////////////////////////////////
COPY ~enhanced-powergaming-scripts/baf/upload/morang.baf~   ~scripts/morang.bs~
	 ~enhanced-powergaming-scripts/baf/upload/mobasic.baf~  ~scripts/mobasic.bs~
	 ~enhanced-powergaming-scripts/baf/upload/mocore.baf~   ~scripts/mocore.bs~
	 ~enhanced-powergaming-scripts/baf/upload/momonk.baf~   ~scripts/momonk.bs~
	 ~enhanced-powergaming-scripts/baf/upload/mopal.baf~    ~scripts/mopal.bs~
	 ~enhanced-powergaming-scripts/baf/upload/moskd.baf~    ~scripts/moskd.bs~
  COMPILE_BAF_TO_BCS


///////////////////////////////////////////////////////////////////////////
// Add descriptions of the scripts to scrpdesc.2da                       //
///////////////////////////////////////////////////////////////////////////
APPEND ~scrpdesc.2DA~
~morang		999990		 999989
mobasic		999988		 999987
mocore      999986       999985
momonk		999984		 999983
mopal		999982		 999981
moskd		999980		 999979~

///////////////////////////////////////////////////////////////////////////
// Copy the appended scrpdesc.2da to the override folder                 //
///////////////////////////////////////////////////////////////////////////
COPY_EXISTING ~scrpdesc.2da~ ~override~
REPLACE ~999990~ @1010
REPLACE ~999989~ @1011
REPLACE ~999988~ @1090
REPLACE ~999987~ @1091
REPLACE ~999986~ @1100
REPLACE ~999985~ @1101
REPLACE ~999984~ @1060
REPLACE ~999983~ @1061
REPLACE ~999982~ @1050
REPLACE ~999981~ @1051
REPLACE ~999980~ @1070
REPLACE ~999979~ @1071