///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Add Mod Components to Scripts                                         //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
ACTION_IF !(MOD_IS_INSTALLED ~setup-spell_rev.tp2~ ~0~) BEGIN

///////////////////////////////////////////////////////////////////////////
// Base Game                                                             //
///////////////////////////////////////////////////////////////////////////
	COPY ~enhanced-powergaming-scripts/baf/normal/morang.baf~  ~enhanced-powergaming-scripts/baf/upload/morang.baf~
	COPY ~enhanced-powergaming-scripts/baf/normal/mocore.baf~ ~enhanced-powergaming-scripts/baf/upload/mobasic.baf~
	COPY ~enhanced-powergaming-scripts/baf/normal/mocore.baf~  ~enhanced-powergaming-scripts/baf/upload/mocore.baf~
	COPY ~enhanced-powergaming-scripts/baf/normal/mopal.baf~   ~enhanced-powergaming-scripts/baf/upload/mopal.baf~
	COPY ~enhanced-powergaming-scripts/baf/normal/momonk.baf~  ~enhanced-powergaming-scripts/baf/upload/momonk.baf~

	INCLUDE ~enhanced-powergaming-scripts/lib/ranger_base.tph~
	INCLUDE ~enhanced-powergaming-scripts/lib/basic_base.tph~
	INCLUDE ~enhanced-powergaming-scripts/lib/core_base.tph~
	INCLUDE ~enhanced-powergaming-scripts/lib/monk_base.tph~
	INCLUDE ~enhanced-powergaming-scripts/lib/paladin_base.tph~

///////////////////////////////////////////////////////////////////////////
// DSotSC                                                                //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF FILE_EXISTS_IN_GAME ~spwi327.spl~ BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/core_dsotsc_w.tph~
	END 
	
	ACTION_IF FILE_EXISTS_IN_GAME ~sppr519.spl~ && FILE_EXISTS_IN_GAME ~sppr716.spl~ BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/core_dsotsc_d.tph~
	END
	
///////////////////////////////////////////////////////////////////////////
// Song & Silence                                                        //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF (MOD_IS_INSTALLED ~setup-song_and_silence.tp2~ ~8~) BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/basic_ss.tph~
		INCLUDE ~enhanced-powergaming-scripts/lib/core_ss.tph~
	END

///////////////////////////////////////////////////////////////////////////
// IWD Spells                                                            //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF (MOD_IS_INSTALLED ~setup-stratagems.tp2~ ~1500~ && MOD_IS_INSTALLED ~setup-stratagems.tp2~ ~1510~) || (MOD_IS_INSTALLED ~iwdification/setup-iwdification.tp2~ 30 && MOD_IS_INSTALLED ~iwdification/setup-iwdification.tp2~ 40) BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/ranger_iwd.tph~
		INCLUDE ~enhanced-powergaming-scripts/lib/basic_iwd.tph~
		INCLUDE ~enhanced-powergaming-scripts/lib/core_iwd.tph~
		INCLUDE ~enhanced-powergaming-scripts/lib/paladin_iwd.tph~
	END

///////////////////////////////////////////////////////////////////////////
// Tome & Blood                                                          //
///////////////////////////////////////////////////////////////////////////
	// Invisibility Changes
	ACTION_IF (MOD_IS_INSTALLED ~setup-TomeAndBlood.tp2~ ~14~) BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/core_tb_inv.tph~
	END

///////////////////////////////////////////////////////////////////////////
// Faiths & Powers - Ranger Kits                                          //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF (MOD_IS_INSTALLED ~setup-faiths_and_powers.tp2~ ~37~) BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/ranger_fp_kit.tph~

		ACTION_IF (MOD_IS_INSTALLED ~setup-stratagems.tp2~ ~1500~ && MOD_IS_INSTALLED ~setup-stratagems.tp2~ ~1510~) || (MOD_IS_INSTALLED ~iwdification/setup-iwdification.tp2~ 30 && MOD_IS_INSTALLED ~iwdification/setup-iwdification.tp2~ 40) BEGIN
			INCLUDE ~enhanced-powergaming-scripts/lib/ranger_iwd_fp_kit.tph~
		END
	END

///////////////////////////////////////////////////////////////////////////
// Faiths & Powers - Paladin Kits                                        //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF (MOD_IS_INSTALLED ~setup-faiths_and_powers.tp2~ ~35~) BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/paladin_fp_kit.tph~
	END

///////////////////////////////////////////////////////////////////////////
// Faiths & Powers - Paladin Kits                                        //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF (MOD_IS_INSTALLED ~setup-faiths_and_powers.tp2~ ~35~) BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/paladin_fp_kit.tph~
	END

///////////////////////////////////////////////////////////////////////////
// Faiths & Powers - FnP Spheres                                         //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF (MOD_IS_INSTALLED ~setup-faiths_and_powers.tp2~ ~21~) BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/ranger_fp_spl.tph~
		INCLUDE ~enhanced-powergaming-scripts/lib/basic_fp_spl.tph~
		INCLUDE ~enhanced-powergaming-scripts/lib/core_fp_spl.tph~

		ACTION_IF (MOD_IS_INSTALLED ~setup-stratagems.tp2~ ~1500~ && MOD_IS_INSTALLED ~setup-stratagems.tp2~ ~1510~) || (MOD_IS_INSTALLED ~iwdification/setup-iwdification.tp2~ 30 && MOD_IS_INSTALLED ~iwdification/setup-iwdification.tp2~ 40) BEGIN
			INCLUDE ~enhanced-powergaming-scripts/lib/ranger_iwd_fp_spl.tph~
		END
	END

///////////////////////////////////////////////////////////////////////////
// SCS - Breach                                                          //
///////////////////////////////////////////////////////////////////////////
	ACTION_IF (MOD_IS_INSTALLED ~setup-stratagems.tp2~ ~5900~) BEGIN
		INCLUDE ~enhanced-powergaming-scripts/lib/core_breach.tph~
		
		ACTION_IF (MOD_IS_INSTALLED ~setup-faiths_and_powers.tp2~ ~37~) BEGIN
			INCLUDE ~enhanced-powergaming-scripts/lib/ranger_breach.tph~
		END
	END

///////////////////////////////////////////////////////////////////////////
// Make Skald Script after Core                                          //
///////////////////////////////////////////////////////////////////////////
	INCLUDE ~enhanced-powergaming-scripts/lib/skald_base.tph~
END

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Import AI Scripts into the Game                                       //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Copy .BS files to scripts folder                                      //
///////////////////////////////////////////////////////////////////////////
ACTION_IF (MOD_IS_INSTALLED ~setup-spell_rev.tp2~ ~0~) BEGIN
	COPY ~enhanced-powergaming-scripts/baf/normal/SR/morang.baf~   ~scripts/morang.bs~
		 ~enhanced-powergaming-scripts/baf/normal/SR/mobasic.baf~  ~scripts/mobasic.bs~
		 ~enhanced-powergaming-scripts/baf/normal/SR/mocore.baf~   ~scripts/mocore.bs~
	     ~enhanced-powergaming-scripts/baf/normal/SR/mopal.baf~    ~scripts/mopal.bs~
	     ~enhanced-powergaming-scripts/baf/normal/SR/momonk.baf~   ~scripts/momonk.bs~
	     ~enhanced-powergaming-scripts/baf/normal/SR/moskd.baf~    ~scripts/moskd.bs~
	  COMPILE_BAF_TO_BCS
END ELSE BEGIN
	COPY ~enhanced-powergaming-scripts/baf/upload/morang.baf~   ~scripts/morang.bs~
		 ~enhanced-powergaming-scripts/baf/upload/mobasic.baf~  ~scripts/mobasic.bs~
		 ~enhanced-powergaming-scripts/baf/upload/mocore.baf~   ~scripts/mocore.bs~
		 ~enhanced-powergaming-scripts/baf/upload/momonk.baf~   ~scripts/momonk.bs~
		 ~enhanced-powergaming-scripts/baf/upload/mopal.baf~    ~scripts/mopal.bs~
		 ~enhanced-powergaming-scripts/baf/upload/moskd.baf~    ~scripts/moskd.bs~
	  COMPILE_BAF_TO_BCS
END

///////////////////////////////////////////////////////////////////////////
// Add descriptions of the scripts to scrpdesc.2da                       //
///////////////////////////////////////////////////////////////////////////
APPEND ~scrpdesc.2DA~
~morang		999990		 999989
mobasic		999988		 999987
mocore      999986       999985
momonk		999984		 999983
mopal		999982		 999981
moskd		999980		 999979~

///////////////////////////////////////////////////////////////////////////
// Copy the appended scrpdesc.2da to the override folder                 //
///////////////////////////////////////////////////////////////////////////
COPY_EXISTING ~scrpdesc.2da~ ~override~
REPLACE ~999990~ @1010
REPLACE ~999989~ @1011
REPLACE ~999988~ @1090
REPLACE ~999987~ @1091
REPLACE ~999986~ @1100
REPLACE ~999985~ @1101
REPLACE ~999984~ @1060
REPLACE ~999983~ @1061
REPLACE ~999982~ @1050
REPLACE ~999981~ @1051
REPLACE ~999980~ @1070
REPLACE ~999979~ @1071