///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Import AI Scripts into the Game                                       //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Copy .BS files to scripts folder                                      //
///////////////////////////////////////////////////////////////////////////

ACTION_IF (MOD_IS_INSTALLED ~setup-spell_rev.tp2~ ~0~) BEGIN
	COPY ~enhanced-powergaming-scripts/baf/Accelerated/SR/moarch.baf~   ~scripts/moarch.bs~
	     ~enhanced-powergaming-scripts/baf/Accelerated/SR/modiv.baf~    ~scripts/modiv.bs~
	     ~enhanced-powergaming-scripts/baf/Accelerated/SR/mofm.baf~     ~scripts/mofm.bs~
	     ~enhanced-powergaming-scripts/baf/Accelerated/SR/mopal.baf~    ~scripts/mopal.bs~
	     ~enhanced-powergaming-scripts/baf/Accelerated/SR/momonk.baf~   ~scripts/momonk.bs~
	     ~enhanced-powergaming-scripts/baf/Accelerated/SR/moskd.baf~    ~scripts/moskd.bs~
	     ~enhanced-powergaming-scripts/baf/Accelerated/SR/mosorc.baf~   ~scripts/mosorc.bs~
	     ~enhanced-powergaming-scripts/baf/Accelerated/SR/mobasic.baf~  ~scripts/mobasic.bs~
	  COMPILE_BAF_TO_BCS
END
ELSE ACTION_IF (MOD_IS_INSTALLED ~setup-stratagems.tp2~ ~1500~ && MOD_IS_INSTALLED ~setup-stratagems.tp2~ ~1510~) || (MOD_IS_INSTALLED ~iwdification/setup-iwdification.tp2~ 30 && MOD_IS_INSTALLED ~iwdification/setup-iwdification.tp2~ 40) BEGIN
	COPY ~enhanced-powergaming-scripts/baf/Accelerated/SR/moarch.baf~   ~scripts/moarch.bs~
	     ~enhanced-powergaming-scripts/baf/Accelerated/SR/modiv.baf~    ~scripts/modiv.bs~
	     ~enhanced-powergaming-scripts/baf/Accelerated/SR/mofm.baf~     ~scripts/mofm.bs~
	     ~enhanced-powergaming-scripts/baf/Accelerated/SR/mopal.baf~    ~scripts/mopal.bs~
	     ~enhanced-powergaming-scripts/baf/Accelerated/SR/momonk.baf~   ~scripts/momonk.bs~
	     ~enhanced-powergaming-scripts/baf/Accelerated/SR/moskd.baf~    ~scripts/moskd.bs~
	     ~enhanced-powergaming-scripts/baf/Accelerated/SR/mosorc.baf~   ~scripts/mosorc.bs~
	     ~enhanced-powergaming-scripts/baf/Accelerated/SR/mobasic.baf~  ~scripts/mobasic.bs~
	  COMPILE_BAF_TO_BCS
END
ELSE BEGIN
	COPY ~enhanced-powergaming-scripts/baf/Accelerated/SR/moarch.baf~   ~scripts/moarch.bs~
	     ~enhanced-powergaming-scripts/baf/Accelerated/SR/modiv.baf~    ~scripts/modiv.bs~
	     ~enhanced-powergaming-scripts/baf/Accelerated/SR/mofm.baf~     ~scripts/mofm.bs~
	     ~enhanced-powergaming-scripts/baf/Accelerated/SR/mopal.baf~    ~scripts/mopal.bs~
	     ~enhanced-powergaming-scripts/baf/Accelerated/SR/momonk.baf~   ~scripts/momonk.bs~
	     ~enhanced-powergaming-scripts/baf/Accelerated/SR/moskd.baf~    ~scripts/moskd.bs~
	     ~enhanced-powergaming-scripts/baf/Accelerated/SR/mosorc.baf~   ~scripts/mosorc.bs~
	     ~enhanced-powergaming-scripts/baf/Accelerated/SR/mobasic.baf~  ~scripts/mobasic.bs~
	  COMPILE_BAF_TO_BCS
END
///////////////////////////////////////////////////////////////////////////
// Add descriptions of the scripts to scrpdesc.2da                       //
///////////////////////////////////////////////////////////////////////////

APPEND ~scrpdesc.2DA~
~moarch      999990       999989
modiv        999988       999987
mofm         999986       999985
mopal        999984       999983
momonk       999982       999981
moskd        999980       999979
mosorc       999978       999977
mobasic		 999976		  999975~

///////////////////////////////////////////////////////////////////////////
// Copy the appended scrpdesc.2da to the override folder                 //
///////////////////////////////////////////////////////////////////////////

COPY_EXISTING ~scrpdesc.2da~ ~override~
REPLACE ~999990~ @1010
REPLACE ~999989~ @1011
REPLACE ~999988~ @1030
REPLACE ~999987~ @1031
REPLACE ~999986~ @1040
REPLACE ~999985~ @1041
REPLACE ~999984~ @1050
REPLACE ~999983~ @1051
REPLACE ~999982~ @1060
REPLACE ~999981~ @1061
REPLACE ~999980~ @1070
REPLACE ~999979~ @1071
REPLACE ~999978~ @1080
REPLACE ~999977~ @1081
REPLACE ~999976~ @1090
REPLACE ~999975~ @1091