COPY ~enhanced-powergaming-scripts/baf/upload/mocore.baf~ ~enhanced-powergaming-scripts/baf/upload/mocore.baf~

///////////////////////////////////////////////////////////////////////////
// Update Bard Thief                                                     //
///////////////////////////////////////////////////////////////////////////
  LPF REPLACE_MULTILINE
    INT_VAR
    strict = 1
    verbose = 0
    STR_VAR
    pattern = ~~~~~OR(3)
    Class(Myself,THIEF_ALL)
    Class(Myself,MONK)
    Class(Myself,SHAMAN)~~~~~
    string = ~~~~~OR(4)
    Class(Myself,THIEF_ALL)
    Class(Myself,MONK)
    Class(Myself,SHAMAN)
    Class(Myself,BARD_ALL)~~~~~ //"
  END
