COPY ~enhanced-powergaming-scripts/baf/upload/mocore.baf~ ~enhanced-powergaming-scripts/baf/upload/mocore.baf~

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Update Hotkeys                                                        //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Update Hotkey Buffing                                                 //
///////////////////////////////////////////////////////////////////////////
  SPRINT value_buff EVAL "%hot_key_Buffing%"

  LPF REPLACE_MULTILINE
    INT_VAR
    strict = 1
    verbose = 0
    STR_VAR
    pattern = ~~~~~HotKey(hot_key_Buffing)~~~~~
    string = ~~~~~HotKey(%value_buff%)~~~~~ //"
  END

///////////////////////////////////////////////////////////////////////////
// Update Hotkey Long Buffing                                            //
///////////////////////////////////////////////////////////////////////////
  SPRINT value_longbuff EVAL "%hot_key_LongBuffing%"

  LPF REPLACE_MULTILINE
    INT_VAR
    strict = 1
    verbose = 0
    STR_VAR
    pattern = ~~~~~HotKey(hot_key_LongBuffing)~~~~~
    string = ~~~~~HotKey(%value_longbuff%)~~~~~ //"
  END

///////////////////////////////////////////////////////////////////////////
// Update Hotkey Cowled Check                                            //
///////////////////////////////////////////////////////////////////////////
  SPRINT value_cowled EVAL "%hot_key_CowledCheck%"

  LPF REPLACE_MULTILINE
    INT_VAR
    strict = 1
    verbose = 0
    warn = 0
    STR_VAR
    pattern = ~~~~~HotKey(hot_key_CowledCheck)~~~~~
    string = ~~~~~HotKey(%value_cowled%)~~~~~ //"
  END

///////////////////////////////////////////////////////////////////////////
// Update Hotkey Weapon Swap                                             //
///////////////////////////////////////////////////////////////////////////
  SPRINT value_wswap EVAL "%hot_key_WeaponSwap%"

  LPF REPLACE_MULTILINE
    INT_VAR
    strict = 1
    verbose = 0
    warn = 0
    STR_VAR
    pattern = ~~~~~HotKey(hot_key_WeaponSwap)~~~~~
    string = ~~~~~HotKey(%value_wswap%)~~~~~ //"
  END

///////////////////////////////////////////////////////////////////////////
// Update Hotkey Solo Buff                                               //
///////////////////////////////////////////////////////////////////////////
  SPRINT value_solobuff EVAL "%hot_key_SoloBuff%"

  LPF REPLACE_MULTILINE
    INT_VAR
    strict = 1
    verbose = 0
    warn = 0
    STR_VAR
    pattern = ~~~~~HotKey(hot_key_SoloBuff)~~~~~
    string = ~~~~~HotKey(%value_solobuff%)~~~~~ //"
  END

///////////////////////////////////////////////////////////////////////////
// Update Hotkey Swap Skills                                             //
///////////////////////////////////////////////////////////////////////////
  SPRINT value_skillswap EVAL "%hot_key_SwapSkills%"

  LPF REPLACE_MULTILINE
    INT_VAR
    strict = 1
    verbose = 0
    warn = 0
    STR_VAR
    pattern = ~~~~~HotKey(hot_key_SwapSkills)~~~~~
    string = ~~~~~HotKey(%value_skillswap%)~~~~~ //"
  END