COPY ~enhanced-powergaming-scripts/baf/upload/mocore.baf~ ~enhanced-powergaming-scripts/baf/upload/mocore.baf~

///////////////////////////////////////////////////////////////////////////
// Challenge Rating                                                      //
///////////////////////////////////////////////////////////////////////////
  LPF REPLACE_MULTILINE
    INT_VAR
    strict = 1
    verbose = 0
    warn = 0
    STR_VAR
    pattern = ~~~~~EEex_LuaTrigger("return ChallengeRating()")~~~~~
    string = ~~~~~NumCreatureGT([EVILCUTOFF],3)~~~~~ //"
  END

///////////////////////////////////////////////////////////////////////////
// Check Current Target                                                  //
///////////////////////////////////////////////////////////////////////////
  LPF REPLACE_MULTILINE
    INT_VAR
    strict = 1
    verbose = 0
    warn = 0
    STR_VAR
    pattern = ~~~~~IF
  EEex_LuaTrigger("return AmAttacking()")
  EEex_LuaTrigger("return MoFillCurrentTarget()")
  See(EEex_Target("MoCurrentTarget"))
  OR(2)
    !WeaponEffectiveVs(LastSeenBy(Myself),MAINHAND)
    !WeaponCanDamage(LastSeenBy(Myself),MAINHAND)
THEN
  RESPONSE #100
    ActionOverride(Myself,ClearActions(Myself))
END~~~~~
    string = ~~~~~~~~~~ //"
  END
