COPY ~enhanced-powergaming-scripts/baf/upload/mocore.baf~ ~enhanced-powergaming-scripts/baf/upload/mocore.baf~

///////////////////////////////////////////////////////////////////////////
// Challenge Rating                                                      //
///////////////////////////////////////////////////////////////////////////
  LPF REPLACE_MULTILINE
    INT_VAR
    strict = 1
    verbose = 0
    warn = 0
    STR_VAR
    pattern = ~~~~~EEex_LuaTrigger("return ChallengeRating()")~~~~~
    string = ~~~~~NumCreatureGT([EVILCUTOFF],3)~~~~~ //"
  END
