COPY ~enhanced-powergaming-scripts/baf/upload/mocore.baf~ ~enhanced-powergaming-scripts/baf/upload/mocore.baf~

///////////////////////////////////////////////////////////////////////////
// Update Hotkey Turn Undead                                             //
///////////////////////////////////////////////////////////////////////////
  SPRINT value_turn EVAL "%hot_key_TurnUndead%"

  LPF REPLACE_MULTILINE
    INT_VAR
    strict = 1
    verbose = 0
    STR_VAR
    pattern = ~~~~~HotKey(%hot_key_TurnUndead%)~~~~~
    string = ~~~~~HotKey(%value_turn%)~~~~~ //"
  END

///////////////////////////////////////////////////////////////////////////
// Update Hotkey Buffing                                                 //
///////////////////////////////////////////////////////////////////////////
  SPRINT value_buff EVAL "%hot_key_Buffing%"

  LPF REPLACE_MULTILINE
    INT_VAR
    strict = 1
    verbose = 0
    STR_VAR
    pattern = ~~~~~HotKey(%hot_key_Buffing%)~~~~~
    string = ~~~~~HotKey(%value_buff%)~~~~~ //"
  END
