COPY ~enhanced-powergaming-scripts/baf/upload/moskd.baf~ ~enhanced-powergaming-scripts/baf/upload/moskd.baf~

///////////////////////////////////////////////////////////////////////////
// Make EEex Check False                                                 //
///////////////////////////////////////////////////////////////////////////
  LPF REPLACE_MULTILINE
    INT_VAR
    strict = 1
    verbose = 0
    warn = 0
    STR_VAR
    pattern = ~~~~~EEex_LuaTrigger("return AmAttacking()")~~~~~
    string = ~~~~~False()~~~~~ //"
  END

///////////////////////////////////////////////////////////////////////////
// Make EEex Check True                                                  //
///////////////////////////////////////////////////////////////////////////
  LPF REPLACE_MULTILINE
    INT_VAR
    strict = 1
    verbose = 0
    warn = 0
    STR_VAR
    pattern = ~~~~~!EEex_LuaTrigger("return AmMoving()")~~~~~
    string = ~~~~~True()~~~~~ //"
  END