// **********************************************************************
// *           Segment Name: ca#dastr.baf
// **********************************************************************
// *
// * Description:
// * This script sets ai for Good and Evil Celestials

IF
  Allegiance(Myself,GOODCUTOFF)
THEN
  RESPONSE #100
    ChangeAIScript("mocel01",CLASS)
END

IF
  !Allegiance(Myself,GOODCUTOFF)
THEN
  RESPONSE #100
    ChangeAIScript("mocel02",CLASS)
END