// **********************************************************************
// *           Segment Name: FigMage.baf
// **********************************************************************
// *
// * FigMage.baf
// * -----------
// * AI Script for:             BGEET with Sword Coast Stratagems
// * Written by:                Mark Evinger (morpheus562)
// * Version:                   Version 2.0 (16 March 2021)
// * Comments to:               mark.evinger@hotmail.com
// * Depends on:                BGEET
//                              Sword Coast Stratagems
//
//
// * Description:
// * This script works for Kensai/Berserker -> Mage dual classes and the FM and 
// * FMT multiclasses. If playing a FMT, the script will constantly be detecting 
// * traps while idle. Will pre-buff using the following spells (in alphabetical order): 
// * Berserker Rage, Divine Might, Fire Shield Red/Blue, (Minor) Globe of Invulnerability, 
// * Improved Haste, Mirror Image, Protection from Energy, Protection from Normal Missiles, 
// * Protection from the Elements, (Minor) Spell Deflection, Spell Immunity: 
// * Abjuration*, Spell Shield, Spell Trap, and (Minor) Spell Turning. Will pre-buff using 
// * the following potions: Potion of Heroism, Potion of Fire/Cold Resistance, Potion of 
// * Absorption, Potion of Magic Protection, Potion of Invulnerability, and all of the 
// * strength potions. Outside of pre-buffing, the script uses healing potions and 
// * healing/curative spells as appropriate. Automatic use of Vocalize if the player gets 
// * muted. The script also keeps constant uptime of stoneskins. If the 
// * character's life drops below 50%, will automatically cast PfMW. Once those are taken 
// * care of, the next priority is detecting any invisible enemies and debuffing them. The 
// * script will also cast many of the spells and abilities in the pre-buffing section if 
// * certain types and quantities of enemies appear. To note: Kai, Improved Haste, and GWW 
// * will only be cast if the player is capable of damaging and hitting the enemy. This is 
// * to prevent using the ability and not actually being able to hurt the enemy.

IF
  Global("MO_TrueSightActive","LOCALS",1)
  CheckStat(Myself,0,TRUE_SIGHT)
THEN
  RESPONSE #100
    SetGlobal("MO_TrueSightActive","LOCALS",0)
    SetGlobal("MO_PartyTrueSight","GLOBAL",0)
END

IF
  Global("MO_TrueSightActive","LOCALS",0)
  CheckStatGT(Myself,0,TRUE_SIGHT)
THEN
  RESPONSE #100
    SetGlobal("MO_TrueSightActive","LOCALS",1)
    SetGlobal("MO_PartyTrueSight","GLOBAL",1)
END

IF
  OR(7)
    AreaCheck("AR0700")  // Waukeen's Promenade
    AreaCheck("AR0020")  // City Gates
    AreaCheck("AR0800")  // Graveyard
    AreaCheck("AR0400")  // Slums
    AreaCheck("AR0300")  // The Docks
    AreaCheck("AR1000")  // Government District
    AreaCheck("AR0900")  // Temple District
  Global("BRIBEDCOWLED","GLOBAL",0)
  GlobalLT("CowledWarning","GLOBAL",7)
  Global("MO_CastAthkatla","LOCALS",1)
THEN
  RESPONSE #100
    SetGlobal("MO_CastAthkatla","LOCALS",0)
END

IF
  !AreaCheck("AR0700")  // Waukeen's Promenade
  !AreaCheck("AR0020")  // City Gates
  !AreaCheck("AR0800")  // Graveyard
  !AreaCheck("AR0400")  // Slums
  !AreaCheck("AR0300")  // The Docks
  !AreaCheck("AR1000")  // Government District
  !AreaCheck("AR0900")  // Temple District
  Global("MO_CastAthkatla","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("MO_CastAthkatla","LOCALS",1)
END

IF
  OR(2)
    Global("BRIBEDCOWLED","GLOBAL",1)
    Global("CowledWarning","GLOBAL",7)
  Global("MO_CastAthkatla","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("MO_CastAthkatla","LOCALS",1)
END

IF
  Global("MO_BUFF","LOCALS",0)
  HotKey(D)
THEN
  RESPONSE #50
    SetGlobal("MO_BUFF","LOCALS",1)
    DisplayStringHead(Myself,91061)  // Right. I'll get started then.
  RESPONSE #50
    SetGlobal("MO_BUFF","LOCALS",1)
    DisplayStringHead(Myself,91057)  // Right, I'll get started then. Please excuse me.
END

IF
  Global("MO_BUFF","LOCALS",1)
  OR(2)
    HotKey(D)
    See([EVILCUTOFF])
THEN
  RESPONSE #100
    SetGlobal("MO_BUFF","LOCALS",0)
    DisplayStringHead(Myself,50742)  // I have not yet completed the task.
END

IF
  Global("MO_BUFF","LOCALS",1)
  HasItemEquiped("potn09",Myself)  // Potion of Heroism
  !CheckSpellState(Myself,BUFF_ENHANCEMENT)
THEN
  RESPONSE #100
    UseItem("potn09",Myself)  // Potion of Heroism
END

IF
  Global("MO_BUFF","LOCALS",1)
  HasItemEquiped("potn02",Myself)  // Potion of Fire Resistance
THEN
  RESPONSE #100
    UseItem("potn02",Myself)  // Potion of Fire Resistance
END

IF
  Global("MO_BUFF","LOCALS",1)
  HasItemEquiped("potn22",Myself)  // Potion of Cold Resistance
THEN
  RESPONSE #100
    UseItem("potn22",Myself)  // Potion of Cold Resistance
END

IF
  Global("MO_BUFF","LOCALS",1)
  HasItemEquiped("potn18",Myself)  // Potion of Absorption
  CheckStatLT(Myself,100,RESISTELECTRICITY)
THEN
  RESPONSE #100
    UseItem("potn18",Myself)  // Potion of Absorption
END

IF
  Global("MO_BUFF","LOCALS",1)
  HasItemEquiped("potn34",Myself)  // Potion of Magic Protection
THEN
  RESPONSE #100
    UseItem("potn34",Myself)  // Potion of Magic Protection
END

IF
  Global("MO_BUFF","LOCALS",1)
  HasItemEquiped("potn07",Myself)  // Potion of Storm Giant Strength
  CheckStatLT(Myself,24,STR)
THEN
  RESPONSE #100
    UseItem("potn07",Myself)  // Potion of Storm Giant Strength
END

IF
  Global("MO_BUFF","LOCALS",1)
  HasItemEquiped("potn06",Myself)  // Potion of Cloud Giant Strength
  CheckStatLT(Myself,23,STR)
THEN
  RESPONSE #100
    UseItem("potn06",Myself)  // Potion of Cloud Giant Strength
END

IF
  Global("MO_BUFF","LOCALS",1)
  HasItemEquiped("potn05",Myself)  // Potion of Fire Giant Strength
  CheckStatLT(Myself,22,STR)
THEN
  RESPONSE #100
    UseItem("potn05",Myself)  // Potion of Fire Giant Strength
END

IF
  Global("MO_BUFF","LOCALS",1)
  HasItemEquiped("potn04",Myself)  // Potion of Frost Giant Strength
  CheckStatLT(Myself,21,STR)
THEN
  RESPONSE #100
    UseItem("potn04",Myself)  // Potion of Frost Giant Strength
END

IF
  Global("MO_BUFF","LOCALS",1)
  HasItemEquiped("potn12",Myself)  // Potion of Stone Giant Strength
  CheckStatLT(Myself,20,STR)
THEN
  RESPONSE #100
    UseItem("potn12",Myself)  // Potion of Stone Giant Strength
END

IF
  Global("MO_BUFF","LOCALS",1)
  HasItemEquiped("potn03",Myself)  // Potion of Hill Giant Strength
  CheckStatLT(Myself,19,STR)
THEN
  RESPONSE #100
    UseItem("potn03",Myself)  // Potion of Hill Giant Strength
END

IF
  Global("MO_BUFF","LOCALS",1)
  HasItemEquiped("potn11",Myself)  // Potion of Invulnerability
  CheckStatGT(Myself,0,ARMORCLASS)
THEN
  RESPONSE #100
    UseItem("potn11",Myself)  // Potion of Invulnerability
END

IF
  Global("MO_BUFF","LOCALS",1)
  IfValidForPartyDialog(Myself)
  HaveSpell(WIZARD_PROTECTION_FROM_NORMAL_MISSILES)  // SPWI311.SPL (Protection From Normal Missiles)
  !CheckSpellState(Myself,PROTECTION_FROM_NORMAL_MISSILES)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    Spell(Myself,WIZARD_PROTECTION_FROM_NORMAL_MISSILES)  // SPWI311.SPL (Protection From Normal Missiles)
END

IF
  Global("MO_BUFF","LOCALS",1)
  IfValidForPartyDialog(Myself)
  HaveSpell(WIZARD_PROTECTION_FROM_MAGIC_ENERGY)  // SPWI606.SPL (Protection From Magic Energy)
  !CheckStatGT(Myself,0,WIZARD_PROTECTION_FROM_MAGIC_ENERGY)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    Spell(Myself,WIZARD_PROTECTION_FROM_MAGIC_ENERGY)  // SPWI606.SPL (Protection From Magic Energy)
END

IF
  Global("MO_BUFF","LOCALS",1)
  IfValidForPartyDialog(Myself)
  HaveSpell(WIZARD_HASTE)  // SPWI305.SPL (Haste)
  !StateCheck(LastSeenBy(Myself),STATE_HASTED)
  CheckStat(LastSeenBy(Myself),0,IMPROVEDHASTE)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !CheckStat(LastSeenBy(Myself),8,WIZARD_SPELL_IMMUNITY)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    Spell(Myself,WIZARD_HASTE)  // SPWI305.SPL (Haste)
END

IF
  Global("MO_BUFF","LOCALS",1)
  IfValidForPartyDialog(Myself)
  HaveSpell(WIZARD_SPELL_SHIELD)  // SPWI519.SPL (Spell Shield)
  !CheckSpellState(Myself,SPELL_SHIELD)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    Spell(Myself,WIZARD_SPELL_SHIELD)  // SPWI519.SPL (Spell Shield)
END

IF
  Global("MO_BUFF","LOCALS",1)
  IfValidForPartyDialog(Myself)
  HaveSpell(WIZARD_SPELL_TURNING)  // SPWI701.SPL (Spell Turning)
  CheckStatLT(Myself,1,WIZARD_SPELL_TURNING)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    Spell(Myself,WIZARD_SPELL_TURNING)  // SPWI701.SPL (Spell Turning)
END

IF
  Global("MO_BUFF","LOCALS",1)
  IfValidForPartyDialog(Myself)
  HaveSpell(WIZARD_MINOR_SPELL_TURNING)  // SPWI522.SPL (Minor Spell Turning)
  CheckStatLT(Myself,1,WIZARD_SPELL_TURNING)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    Spell(Myself,WIZARD_MINOR_SPELL_TURNING)  // SPWI522.SPL (Minor Spell Turning)
END

IF
  Global("MO_BUFF","LOCALS",1)
  IfValidForPartyDialog(Myself)
  HaveSpell(WIZARD_SPELL_DEFLECTION)  // SPWI618.SPL (Spell Deflection)
  CheckStatLT(Myself,1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    Spell(Myself,WIZARD_SPELL_DEFLECTION)  // SPWI618.SPL (Spell Deflection)
END

IF
  Global("MO_BUFF","LOCALS",1)
  IfValidForPartyDialog(Myself)
  HaveSpell(WIZARD_MINOR_SPELL_DEFLECTION)  // SPWI318.SPL (Minor Spell Deflection)
  CheckStatLT(Myself,1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    Spell(Myself,WIZARD_MINOR_SPELL_DEFLECTION)  // SPWI318.SPL (Minor Spell Deflection)
END

IF
  Global("MO_BUFF","LOCALS",1)
  IfValidForPartyDialog(Myself)
  !StateCheck(Myself,STATE_MIRRORIMAGE)
  HaveSpell(WIZARD_MIRROR_IMAGE)  // SPWI212.SPL (Mirror Image)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStat(Myself,1,PUPPETTYPE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    Spell(Myself,WIZARD_MIRROR_IMAGE)  // SPWI212.SPL (Mirror Image)
END

IF
  Global("MO_BUFF","LOCALS",1)
  IfValidForPartyDialog(Myself)
  HaveSpell(WIZARD_FIRE_SHIELD_RED)  // SPWI418.SPL (Fire Shield (Red))
  !CheckSpellState(Myself,RED_FIRESHIELD)
  !CheckSpellState(Myself,BLUE_FIRESHIELD)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    Spell(Myself,WIZARD_FIRE_SHIELD_RED)  // SPWI418.SPL (Fire Shield (Red))
END

IF
  Global("MO_BUFF","LOCALS",1)
  IfValidForPartyDialog(Myself)
  HaveSpell(WIZARD_FIRE_SHIELD_BLUE)  // SPWI403.SPL (Fire Shield (Blue))
  !CheckSpellState(Myself,RED_FIRESHIELD)
  !CheckSpellState(Myself,BLUE_FIRESHIELD)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    Spell(Myself,WIZARD_FIRE_SHIELD_BLUE)  // SPWI403.SPL (Fire Shield (Blue))
END

IF
  Global("MO_BUFF","LOCALS",1)
  IfValidForPartyDialog(Myself)
  HaveSpell(WIZARD_IMPROVED_HASTE)  // SPWI613.SPL (Improved Haste)
  !CheckStatGT(Myself,0,IMPROVEDHASTE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    Spell(Myself,WIZARD_IMPROVED_HASTE)  // SPWI613.SPL (Improved Haste)
END

IF
  Global("MO_BUFF","LOCALS",1)
  IfValidForPartyDialog(Myself)
  HaveSpell(WIZARD_PROTECTION_FROM_ENERGY)  // SPWI803.SPL (Protection From Energy)
  !CheckStatGT(Myself,0,WIZARD_PROTECTION_FROM_ENERGY)
  !CheckStatGT(Myself,0,WIZARD_PROTECTION_FROM_THE_ELEMENTS)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    Spell(Myself,WIZARD_PROTECTION_FROM_ENERGY)  // SPWI803.SPL (Protection From Energy)
END

IF
  Global("MO_BUFF","LOCALS",1)
  IfValidForPartyDialog(Myself)
  HaveSpell(WIZARD_PROTECTION_FROM_THE_ELEMENTS)  // SPWI702.SPL (Protection From The Elements)
  !CheckStatGT(Myself,0,WIZARD_PROTECTION_FROM_ENERGY)
  !CheckStatGT(Myself,0,WIZARD_PROTECTION_FROM_THE_ELEMENTS)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    Spell(Myself,WIZARD_PROTECTION_FROM_THE_ELEMENTS)  // SPWI702.SPL (Protection From The Elements)
END

IF
  Global("MO_BUFF","LOCALS",1)
  IfValidForPartyDialog(Myself)
  HaveSpell(WIZARD_GLOBE_OF_INVULNERABILITY)  // SPWI602.SPL (Globe of Invulnerability)
  CheckStatLT(Myself,1,MINORGLOBE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    Spell(Myself,WIZARD_GLOBE_OF_INVULNERABILITY)  // SPWI602.SPL (Globe of Invulnerability)
END

IF
  Global("MO_BUFF","LOCALS",1)
  IfValidForPartyDialog(Myself)
  HaveSpell(WIZARD_MINOR_GLOBE_OF_INVULNERABILITY)  // SPWI406.SPL (Minor Globe of Invulnerability)
  CheckStatLT(Myself,1,MINORGLOBE)
  !HasImmunityEffects(Myself)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    Spell(Myself,WIZARD_MINOR_GLOBE_OF_INVULNERABILITY)  // SPWI406.SPL (Minor Globe of Invulnerability)
END

IF
  Global("MO_BUFF","LOCALS",1)
  IfValidForPartyDialog(Myself)
  HaveSpell(WIZARD_SPELL_IMMUNITY)  // SPWI510.SPL (Spell Immunity)
  !CheckStat(Myself,1,WIZARD_SPELL_IMMUNITY)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    Spell(Myself,WIZARD_SPELL_IMMUNITY_ABJURATION)  // SPWI590.SPL (Immunity: Abjuration)
END

IF
  Global("MO_BUFF","LOCALS",1)
  IfValidForPartyDialog(Myself)
  HaveSpell(WIZARD_SPELL_TRAP)  // SPWI902.SPL (Spell Trap)
  CheckStatLT(Myself,1,WIZARD_SPELL_TRAP)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    Spell(Myself,WIZARD_SPELL_TRAP)  // SPWI902.SPL (Spell Trap)
END

IF
  Global("MO_BUFF","LOCALS",1)
  IfValidForPartyDialog(Myself)
  HaveSpellRES("SPIN103")  // Divine Might
  !StateCheck(Myself,STATE_DRAWUPONHOLYMIGHT)
  CheckStatLT(Myself,25,STR)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SpellRES("SPIN103",Myself)  // Divine Might
END

IF
  Global("MO_BUFF","LOCALS",1)
  IfValidForPartyDialog(Myself)
  HaveSpell(BERSERKER_RAGE)  // SPCL321.SPL (Enrage)
  !CheckSpellState(Myself,BERSERKER_RAGE_FATIGUE)
  !CheckSpellState(Myself,BERSERKER_RAGE)
THEN
  RESPONSE #100
    Spell(Myself,BERSERKER_RAGE)  // SPCL321.SPL (Enrage)
END

IF
  Global("MO_BUFF","LOCALS",1)
THEN
  RESPONSE #100
    SetGlobal("MO_BUFF","LOCALS",0)
    DisplayStringHead(Myself,421)  // Combat ready!
END

IF
  !GlobalTimerNotExpired("MO_SpellCast","LOCALS")
  OR(2)
    StateCheck(Myself,STATE_POISONED)
    CheckSpellState(Myself,DISEASED)
  HasItemEquiped("POTN17",Myself)  // Elixir of Health
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCast","LOCALS",ONE_ROUND)
    UseItem("POTN17",Myself)  // Elixir of Health
    DisplayString(Myself,46150)  // *quaffs a potion*
END

IF
  !GlobalTimerNotExpired("MO_SpellCast","LOCALS")
  StateCheck(Myself,STATE_POISONED)
  HasItemEquiped("POTN20",Myself)  // Antidote
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCast","LOCALS",ONE_ROUND)
    UseItem("POTN20",Myself)  // Antidote
    DisplayString(Myself,46150)  // *quaffs a potion*
END

IF
  ActionListEmpty()
  !GlobalTimerNotExpired("MO_SpellCast","LOCALS")
  See([EVILCUTOFF])
  HPPercentLT(Myself,51)
  HasItemEquiped("POTN55",Myself)  // Potion of Superior Healing
  ActuallyInCombat()
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCast","LOCALS",ONE_ROUND)
    UseItem("POTN55",Myself)  // Potion of Superior Healing
    DisplayString(Myself,46150)  // *quaffs a potion*
END

IF
  ActionListEmpty()
  !GlobalTimerNotExpired("MO_SpellCast","LOCALS")
  See([EVILCUTOFF])
  HPPercentLT(Myself,51)
  HasItemEquiped("POTN52",Myself)  // Potion of Extra Healing
  ActuallyInCombat()
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCast","LOCALS",ONE_ROUND)
    UseItem("POTN52",Myself)  // Potion of Extra Healing
    DisplayString(Myself,46150)  // *quaffs a potion*
END

IF
  ActionListEmpty()
  !GlobalTimerNotExpired("MO_SpellCast","LOCALS")
  See([EVILCUTOFF])
  HPPercentLT(Myself,51)
  HasItemEquiped("POTN08",Myself)  // Potion of Healing
  ActuallyInCombat()
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCast","LOCALS",ONE_ROUND)
    UseItem("POTN08",Myself)  // Potion of Healing
    DisplayString(Myself,46150)  // *quaffs a potion*
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_SpellCast","LOCALS")
  HaveSpellRES("SPIN102")  // Cure Affliction
  See([PC])
  StateCheck(LastSeenBy(Myself),STATE_POISONED)
  OR(2)
    Range(LastSeenBy(Myself),6)
    !Range(NearestEnemyOf(Myself),30)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCast","LOCALS",ONE_ROUND)
    SetInterrupt(FALSE)
    SpellRES("SPIN102",LastSeenBy(Myself))  // Cure Affliction
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_SpellCast","LOCALS")
  HaveSpellRES("SPIN102")  // Cure Affliction
  See(SecondNearest([PC]))
  StateCheck(LastSeenBy(Myself),STATE_POISONED)
  OR(2)
    Range(LastSeenBy(Myself),6)
    !Range(NearestEnemyOf(Myself),30)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCast","LOCALS",ONE_ROUND)
    SetInterrupt(FALSE)
    SpellRES("SPIN102",LastSeenBy(Myself))  // Cure Affliction
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_SpellCast","LOCALS")
  HaveSpellRES("SPIN102")  // Cure Affliction
  See(ThirdNearest([PC]))
  StateCheck(LastSeenBy(Myself),STATE_POISONED)
  OR(2)
    Range(LastSeenBy(Myself),6)
    !Range(NearestEnemyOf(Myself),30)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCast","LOCALS",ONE_ROUND)
    SetInterrupt(FALSE)
    SpellRES("SPIN102",LastSeenBy(Myself))  // Cure Affliction
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_SpellCast","LOCALS")
  HaveSpellRES("SPIN102")  // Cure Affliction
  See(FourthNearest([PC]))
  StateCheck(LastSeenBy(Myself),STATE_POISONED)
  OR(2)
    Range(LastSeenBy(Myself),6)
    !Range(NearestEnemyOf(Myself),30)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCast","LOCALS",ONE_ROUND)
    SetInterrupt(FALSE)
    SpellRES("SPIN102",LastSeenBy(Myself))  // Cure Affliction
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_SpellCast","LOCALS")
  HaveSpellRES("SPIN102")  // Cure Affliction
  See(FifthNearest([PC]))
  StateCheck(LastSeenBy(Myself),STATE_POISONED)
  OR(2)
    Range(LastSeenBy(Myself),6)
    !Range(NearestEnemyOf(Myself),30)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCast","LOCALS",ONE_ROUND)
    SetInterrupt(FALSE)
    SpellRES("SPIN102",LastSeenBy(Myself))  // Cure Affliction
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_SpellCast","LOCALS")
  HaveSpellRES("SPIN102")  // Cure Affliction
  See(SixthNearest([PC]))
  StateCheck(LastSeenBy(Myself),STATE_POISONED)
  OR(2)
    Range(LastSeenBy(Myself),6)
    !Range(NearestEnemyOf(Myself),30)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCast","LOCALS",ONE_ROUND)
    SetInterrupt(FALSE)
    SpellRES("SPIN102",LastSeenBy(Myself))  // Cure Affliction
    SetInterrupt(TRUE)
END

IF
  ActionListEmpty()
  IfValidForPartyDialog(Myself)
  HaveSpellRES("SPIN101")  // Healing Touch
  !See([EVILCUTOFF])
  See(MostDamagedOf([PC]))
  HPPercentLT(LastSeenBy(Myself),80)
  IfValidForPartyDialog(LastSeenBy(Myself))
  OR(2)
    Range(MostDamagedOf([PC]),6)
    !Range(NearestEnemyOf(Myself),30)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_APPROACHABLE)
  !StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckStat(LastSeenBy(Myself),2,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREPRIEST)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SpellRES("SPIN101",LastSeenBy(Myself))  // Healing Touch
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCast","LOCALS")
  See(NearestEnemyOf(Myself))
  StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  HaveSpell(WIZARD_VOCALIZE)  // SPWI219.SPL (Vocalize)
  CheckStat(Myself,0,MINORGLOBE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCast","LOCALS",ONE_ROUND)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_VOCALIZE)  // SPWI219.SPL (Vocalize)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCast","LOCALS")
  See([EVILCUTOFF])
  HPPercentLT(Myself,51)
  IfValidForPartyDialog(Myself)
  HaveSpell(WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)  // SPWI611.SPL (Protection From Magical Weapons)
  !CheckSpellState(Myself,PROTECTION_FROM_MAGICAL_WEAPONS)
  !CheckSpellState(Myself,ABSOLUTE_IMMUNITY)
  !CheckSpellState(Myself,MANTLE)
  !CheckSpellState(Myself,IMPROVED_MANTLE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCast","LOCALS",ONE_ROUND)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)  // SPWI611.SPL (Protection From Magical Weapons)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCast","LOCALS")
  CheckStatLT(Myself,1,STONESKINS)
  HaveSpell(WIZARD_STONE_SKIN)  // SPWI408.SPL (Stoneskin)
  CheckStat(Myself,0,MINORGLOBE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCast","LOCALS",ONE_ROUND)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_STONE_SKIN)  // SPWI408.SPL (Stoneskin)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_SpellCast","LOCALS")
  HaveSpell(WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
  OR(6)
    SpellCast([EVILCUTOFF],WIZARD_PROJECT_IMAGE)  // SPWI703.SPL (Project Image)
    SpellCast([EVILCUTOFF],WIZARD_SIMULACRUM)  // SPWI804.SPL (Simulacrum)
    SpellCast([EVILCUTOFF],WIZARD_MISLEAD)  // SPWI607.SPL (Mislead)
    SpellCast([EVILCUTOFF],WIZARD_SHADOW_DOOR)  // SPWI505.SPL (Shadow Door)
    SpellCast([EVILCUTOFF],WIZARD_IMPROVED_INVISIBILITY)  // SPWI405.SPL (Improved Invisibility)
    SpellCast([EVILCUTOFF],WIZARD_INVISIBILITY)  // SPWI206.SPL (Invisibility)
  !CheckStat([EVILCUTOFF],3,WIZARD_SPELL_IMMUNITY)
  Global("MO_PartyTrueSight","GLOBAL",0)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobal("MO_TrueSightActive","LOCALS",1)
    SetGlobal("MO_PartyTrueSight","GLOBAL",1)
    SetGlobalTimer("MO_SpellCast","LOCALS",ONE_ROUND)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_SpellCast","LOCALS")
  HaveSpell(WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
  Detect([EVILCUTOFF])
  OR(4)
    StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
    StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
    CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
    Gender(LastSeenBy(Myself),ILLUSIONARY)
  !CheckStat(LastSeenBy(Myself),3,WIZARD_SPELL_IMMUNITY)
  Global("MO_PartyTrueSight","GLOBAL",0)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobal("MO_TrueSightActive","LOCALS",1)
    SetGlobal("MO_PartyTrueSight","GLOBAL",1)
    SetGlobalTimer("MO_SpellCast","LOCALS",ONE_ROUND)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_SpellCast","LOCALS")
  HaveSpell(WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
  See(NearestEnemyOf(Myself))
  OR(4)
    StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
    StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
    CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
    Gender(LastSeenBy(Myself),ILLUSIONARY)
  !CheckStat(LastSeenBy(Myself),3,WIZARD_SPELL_IMMUNITY)
  Global("MO_PartyTrueSight","GLOBAL",0)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobal("MO_TrueSightActive","LOCALS",1)
    SetGlobal("MO_PartyTrueSight","GLOBAL",1)
    SetGlobalTimer("MO_SpellCast","LOCALS",ONE_ROUND)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_SpellCast","LOCALS")
  HaveSpell(WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
  See(SecondNearestEnemyOf(Myself))
  OR(4)
    StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
    StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
    CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
    Gender(LastSeenBy(Myself),ILLUSIONARY)
  !CheckStat(LastSeenBy(Myself),3,WIZARD_SPELL_IMMUNITY)
  Global("MO_PartyTrueSight","GLOBAL",0)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobal("MO_TrueSightActive","LOCALS",1)
    SetGlobal("MO_PartyTrueSight","GLOBAL",1)
    SetGlobalTimer("MO_SpellCast","LOCALS",ONE_ROUND)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_SpellCast","LOCALS")
  HaveSpell(WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
  See(ThirdNearestEnemyOf(Myself))
  OR(4)
    StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
    StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
    CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
    Gender(LastSeenBy(Myself),ILLUSIONARY)
  !CheckStat(LastSeenBy(Myself),3,WIZARD_SPELL_IMMUNITY)
  Global("MO_PartyTrueSight","GLOBAL",0)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobal("MO_TrueSightActive","LOCALS",1)
    SetGlobal("MO_PartyTrueSight","GLOBAL",1)
    SetGlobalTimer("MO_SpellCast","LOCALS",ONE_ROUND)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_SpellCast","LOCALS")
  HaveSpell(WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
  See(FourthNearestEnemyOf(Myself))
  OR(4)
    StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
    StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
    CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
    Gender(LastSeenBy(Myself),ILLUSIONARY)
  !CheckStat(LastSeenBy(Myself),3,WIZARD_SPELL_IMMUNITY)
  Global("MO_PartyTrueSight","GLOBAL",0)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobal("MO_TrueSightActive","LOCALS",1)
    SetGlobal("MO_PartyTrueSight","GLOBAL",1)
    SetGlobalTimer("MO_SpellCast","LOCALS",ONE_ROUND)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_SpellCast","LOCALS")
  HaveSpell(WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
  See(FifthNearestEnemyOf(Myself))
  OR(4)
    StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
    StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
    CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
    Gender(LastSeenBy(Myself),ILLUSIONARY)
  !CheckStat(LastSeenBy(Myself),3,WIZARD_SPELL_IMMUNITY)
  Global("MO_PartyTrueSight","GLOBAL",0)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobal("MO_TrueSightActive","LOCALS",1)
    SetGlobal("MO_PartyTrueSight","GLOBAL",1)
    SetGlobalTimer("MO_SpellCast","LOCALS",ONE_ROUND)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_SpellCast","LOCALS")
  HaveSpell(WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
  See(SixthNearestEnemyOf(Myself))
  OR(4)
    StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
    StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
    CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
    Gender(LastSeenBy(Myself),ILLUSIONARY)
  !CheckStat(LastSeenBy(Myself),3,WIZARD_SPELL_IMMUNITY)
  Global("MO_PartyTrueSight","GLOBAL",0)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobal("MO_TrueSightActive","LOCALS",1)
    SetGlobal("MO_PartyTrueSight","GLOBAL",1)
    SetGlobalTimer("MO_SpellCast","LOCALS",ONE_ROUND)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_SpellCast","LOCALS")
  HaveSpell(WIZARD_DETECT_INVISIBILITY)  // SPWI203.SPL (Detect Invisibility)
  Detect([EVILCUTOFF])
  OR(3)
    StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
    StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
    CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_NONDETECTION)
  !CheckStat(LastSeenBy(Myself),3,WIZARD_SPELL_IMMUNITY)
  Global("MO_PartyTrueSight","GLOBAL",0)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCast","LOCALS",ONE_ROUND)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_DETECT_INVISIBILITY)  // SPWI203.SPL (Detect Invisibility)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_SpellCast","LOCALS")
  HaveSpell(WIZARD_DETECT_INVISIBILITY)  // SPWI203.SPL (Detect Invisibility)
  See(NearestEnemyOf(Myself))
  OR(3)
    StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
    StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
    CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_NONDETECTION)
  !CheckStat(LastSeenBy(Myself),3,WIZARD_SPELL_IMMUNITY)
  Global("MO_PartyTrueSight","GLOBAL",0)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCast","LOCALS",ONE_ROUND)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_DETECT_INVISIBILITY)  // SPWI203.SPL (Detect Invisibility)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_SpellCast","LOCALS")
  HaveSpell(WIZARD_DETECT_INVISIBILITY)  // SPWI203.SPL (Detect Invisibility)
  See(SecondNearestEnemyOf(Myself))
  OR(3)
    StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
    StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
    CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_NONDETECTION)
  !CheckStat(LastSeenBy(Myself),3,WIZARD_SPELL_IMMUNITY)
  Global("MO_PartyTrueSight","GLOBAL",0)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCast","LOCALS",ONE_ROUND)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_DETECT_INVISIBILITY)  // SPWI203.SPL (Detect Invisibility)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_SpellCast","LOCALS")
  HaveSpell(WIZARD_DETECT_INVISIBILITY)  // SPWI203.SPL (Detect Invisibility)
  See(ThirdNearestEnemyOf(Myself))
  OR(3)
    StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
    StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
    CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_NONDETECTION)
  !CheckStat(LastSeenBy(Myself),3,WIZARD_SPELL_IMMUNITY)
  Global("MO_PartyTrueSight","GLOBAL",0)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCast","LOCALS",ONE_ROUND)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_DETECT_INVISIBILITY)  // SPWI203.SPL (Detect Invisibility)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_SpellCast","LOCALS")
  HaveSpell(WIZARD_DETECT_INVISIBILITY)  // SPWI203.SPL (Detect Invisibility)
  See(FourthNearestEnemyOf(Myself))
  OR(3)
    StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
    StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
    CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_NONDETECTION)
  !CheckStat(LastSeenBy(Myself),3,WIZARD_SPELL_IMMUNITY)
  CheckStat(Myself,0,TRUE_SIGHT)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCast","LOCALS",ONE_ROUND)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_DETECT_INVISIBILITY)  // SPWI203.SPL (Detect Invisibility)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_SpellCast","LOCALS")
  HaveSpell(WIZARD_DETECT_INVISIBILITY)  // SPWI203.SPL (Detect Invisibility)
  See(FifthNearestEnemyOf(Myself))
  OR(3)
    StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
    StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
    CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_NONDETECTION)
  !CheckStat(LastSeenBy(Myself),3,WIZARD_SPELL_IMMUNITY)
  Global("MO_PartyTrueSight","GLOBAL",0)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCast","LOCALS",ONE_ROUND)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_DETECT_INVISIBILITY)  // SPWI203.SPL (Detect Invisibility)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_SpellCast","LOCALS")
  HaveSpell(WIZARD_DETECT_INVISIBILITY)  // SPWI203.SPL (Detect Invisibility)
  See(SixthNearestEnemyOf(Myself))
  OR(3)
    StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
    StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
    CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_NONDETECTION)
  !CheckStat(LastSeenBy(Myself),3,WIZARD_SPELL_IMMUNITY)
  Global("MO_PartyTrueSight","GLOBAL",0)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCast","LOCALS",ONE_ROUND)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_DETECT_INVISIBILITY)  // SPWI203.SPL (Detect Invisibility)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_SpellCast","LOCALS")
  HaveSpell(WIZARD_BREACH)  // SPWI513.SPL (Breach)
  See([EVILCUTOFF])
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  !CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
  !CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_IMMUNITY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCast","LOCALS",ONE_ROUND)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_BREACH)  // SPWI513.SPL (Breach)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_SpellCast","LOCALS")
  HaveSpell(WIZARD_BREACH)  // SPWI513.SPL (Breach)
  See(SecondNearest([EVILCUTOFF]))
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  !CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
  !CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_IMMUNITY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCast","LOCALS",ONE_ROUND)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_BREACH)  // SPWI513.SPL (Breach)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_SpellCast","LOCALS")
  HaveSpell(WIZARD_BREACH)  // SPWI513.SPL (Breach)
  See(ThirdNearest([EVILCUTOFF]))
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  !CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
  !CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_IMMUNITY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCast","LOCALS",ONE_ROUND)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_BREACH)  // SPWI513.SPL (Breach)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_SpellCast","LOCALS")
  HaveSpell(WIZARD_BREACH)  // SPWI513.SPL (Breach)
  See(FourthNearest([EVILCUTOFF]))
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  !CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
  !CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_IMMUNITY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCast","LOCALS",ONE_ROUND)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_BREACH)  // SPWI513.SPL (Breach)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_SpellCast","LOCALS")
  HaveSpell(WIZARD_BREACH)  // SPWI513.SPL (Breach)
  See(FifthNearest([EVILCUTOFF]))
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  !CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
  !CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_IMMUNITY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCast","LOCALS",ONE_ROUND)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_BREACH)  // SPWI513.SPL (Breach)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_SpellCast","LOCALS")
  HaveSpell(WIZARD_BREACH)  // SPWI513.SPL (Breach)
  See(SixthNearest([EVILCUTOFF]))
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  !CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
  !CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_IMMUNITY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCast","LOCALS",ONE_ROUND)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_BREACH)  // SPWI513.SPL (Breach)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_SpellCast","LOCALS")
  HaveSpell(WIZARD_SPELL_THRUST)  // SPWI321.SPL (Spell Thrust)
  See([EVILCUTOFF])
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !ImmuneToSpellLevel(LastSeenBy(Myself),3)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  OR(3)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
    CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  CheckStatLT(Myself,1,MINORGLOBE)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCast","LOCALS",ONE_ROUND)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_SPELL_THRUST)  // SPWI321.SPL (Spell Thrust)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_SpellCast","LOCALS")
  HaveSpell(WIZARD_SPELL_THRUST)  // SPWI321.SPL (Spell Thrust)
  See(SecondNearest([EVILCUTOFF]))
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !ImmuneToSpellLevel(LastSeenBy(Myself),3)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  OR(3)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
    CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  CheckStatLT(Myself,1,MINORGLOBE)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCast","LOCALS",ONE_ROUND)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_SPELL_THRUST)  // SPWI321.SPL (Spell Thrust)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_SpellCast","LOCALS")
  HaveSpell(WIZARD_SPELL_THRUST)  // SPWI321.SPL (Spell Thrust)
  See(ThirdNearest([EVILCUTOFF]))
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !ImmuneToSpellLevel(LastSeenBy(Myself),3)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  OR(3)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
    CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  CheckStatLT(Myself,1,MINORGLOBE)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCast","LOCALS",ONE_ROUND)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_SPELL_THRUST)  // SPWI321.SPL (Spell Thrust)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_SpellCast","LOCALS")
  HaveSpell(WIZARD_SPELL_THRUST)  // SPWI321.SPL (Spell Thrust)
  See(FourthNearest([EVILCUTOFF]))
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !ImmuneToSpellLevel(LastSeenBy(Myself),3)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  OR(3)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
    CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  CheckStatLT(Myself,1,MINORGLOBE)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCast","LOCALS",ONE_ROUND)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_SPELL_THRUST)  // SPWI321.SPL (Spell Thrust)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_SpellCast","LOCALS")
  HaveSpell(WIZARD_SPELL_THRUST)  // SPWI321.SPL (Spell Thrust)
  See(FifthNearest([EVILCUTOFF]))
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !ImmuneToSpellLevel(LastSeenBy(Myself),3)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  OR(3)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
    CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  CheckStatLT(Myself,1,MINORGLOBE)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCast","LOCALS",ONE_ROUND)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_SPELL_THRUST)  // SPWI321.SPL (Spell Thrust)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_SpellCast","LOCALS")
  HaveSpell(WIZARD_SPELL_THRUST)  // SPWI321.SPL (Spell Thrust)
  See(SixthNearest([EVILCUTOFF]))
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !ImmuneToSpellLevel(LastSeenBy(Myself),3)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  OR(3)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
    CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  CheckStatLT(Myself,1,MINORGLOBE)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCast","LOCALS",ONE_ROUND)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_SPELL_THRUST)  // SPWI321.SPL (Spell Thrust)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_SpellCast","LOCALS")
  HaveSpell(WIZARD_SECRET_WORD)  // SPWI419.SPL (Secret Word)
  See([EVILCUTOFF])
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !ImmuneToSpellLevel(LastSeenBy(Myself),4)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  OR(5)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_IMMUNITY)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
    CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  CheckStatLT(Myself,1,MINORGLOBE)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCast","LOCALS",ONE_ROUND)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_SECRET_WORD)  // SPWI419.SPL (Secret Word)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_SpellCast","LOCALS")
  HaveSpell(WIZARD_SECRET_WORD)  // SPWI419.SPL (Secret Word)
  See(SecondNearest([EVILCUTOFF]))
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !ImmuneToSpellLevel(LastSeenBy(Myself),4)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  OR(5)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_IMMUNITY)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
    CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  CheckStatLT(Myself,1,MINORGLOBE)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCast","LOCALS",ONE_ROUND)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_SECRET_WORD)  // SPWI419.SPL (Secret Word)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_SpellCast","LOCALS")
  HaveSpell(WIZARD_SECRET_WORD)  // SPWI419.SPL (Secret Word)
  See(ThirdNearest([EVILCUTOFF]))
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !ImmuneToSpellLevel(LastSeenBy(Myself),4)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  OR(5)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_IMMUNITY)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
    CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  CheckStatLT(Myself,1,MINORGLOBE)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCast","LOCALS",ONE_ROUND)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_SECRET_WORD)  // SPWI419.SPL (Secret Word)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_SpellCast","LOCALS")
  HaveSpell(WIZARD_SECRET_WORD)  // SPWI419.SPL (Secret Word)
  See(FourthNearest([EVILCUTOFF]))
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !ImmuneToSpellLevel(LastSeenBy(Myself),4)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  OR(5)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_IMMUNITY)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
    CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  CheckStatLT(Myself,1,MINORGLOBE)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCast","LOCALS",ONE_ROUND)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_SECRET_WORD)  // SPWI419.SPL (Secret Word)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_SpellCast","LOCALS")
  HaveSpell(WIZARD_SECRET_WORD)  // SPWI419.SPL (Secret Word)
  See(FifthNearest([EVILCUTOFF]))
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !ImmuneToSpellLevel(LastSeenBy(Myself),4)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  OR(5)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_IMMUNITY)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
    CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  CheckStatLT(Myself,1,MINORGLOBE)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCast","LOCALS",ONE_ROUND)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_SECRET_WORD)  // SPWI419.SPL (Secret Word)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_SpellCast","LOCALS")
  HaveSpell(WIZARD_SECRET_WORD)  // SPWI419.SPL (Secret Word)
  See(SixthNearest([EVILCUTOFF]))
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !ImmuneToSpellLevel(LastSeenBy(Myself),4)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  OR(5)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_IMMUNITY)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
    CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  CheckStatLT(Myself,1,MINORGLOBE)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCast","LOCALS",ONE_ROUND)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_SECRET_WORD)  // SPWI419.SPL (Secret Word)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_SpellCast","LOCALS")
  HaveSpell(WIZARD_PIERCE_MAGIC)  // SPWI608.SPL (Pierce Magic)
  See([EVILCUTOFF])
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !ImmuneToSpellLevel(LastSeenBy(Myself),6)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  OR(4)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_IMMUNITY)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
  !CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCast","LOCALS",ONE_ROUND)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_PIERCE_MAGIC)  // SPWI608.SPL (Pierce Magic)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_SpellCast","LOCALS")
  HaveSpell(WIZARD_PIERCE_MAGIC)  // SPWI608.SPL (Pierce Magic)
  See(SecondNearest([EVILCUTOFF]))
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !ImmuneToSpellLevel(LastSeenBy(Myself),6)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  OR(4)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_IMMUNITY)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
  !CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCast","LOCALS",ONE_ROUND)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_PIERCE_MAGIC)  // SPWI608.SPL (Pierce Magic)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_SpellCast","LOCALS")
  HaveSpell(WIZARD_PIERCE_MAGIC)  // SPWI608.SPL (Pierce Magic)
  See(ThirdNearest([EVILCUTOFF]))
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !ImmuneToSpellLevel(LastSeenBy(Myself),6)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  OR(4)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_IMMUNITY)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
  !CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCast","LOCALS",ONE_ROUND)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_PIERCE_MAGIC)  // SPWI608.SPL (Pierce Magic)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_SpellCast","LOCALS")
  HaveSpell(WIZARD_PIERCE_MAGIC)  // SPWI608.SPL (Pierce Magic)
  See(FourthNearest([EVILCUTOFF]))
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !ImmuneToSpellLevel(LastSeenBy(Myself),6)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  OR(4)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_IMMUNITY)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
  !CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCast","LOCALS",ONE_ROUND)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_PIERCE_MAGIC)  // SPWI608.SPL (Pierce Magic)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_SpellCast","LOCALS")
  HaveSpell(WIZARD_PIERCE_MAGIC)  // SPWI608.SPL (Pierce Magic)
  See(FifthNearest([EVILCUTOFF]))
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !ImmuneToSpellLevel(LastSeenBy(Myself),6)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  OR(4)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_IMMUNITY)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
  !CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCast","LOCALS",ONE_ROUND)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_PIERCE_MAGIC)  // SPWI608.SPL (Pierce Magic)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_SpellCast","LOCALS")
  HaveSpell(WIZARD_PIERCE_MAGIC)  // SPWI608.SPL (Pierce Magic)
  See(SixthNearest([EVILCUTOFF]))
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !ImmuneToSpellLevel(LastSeenBy(Myself),6)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  OR(4)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_IMMUNITY)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
  !CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCast","LOCALS",ONE_ROUND)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_PIERCE_MAGIC)  // SPWI608.SPL (Pierce Magic)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_SpellCast","LOCALS")
  HaveSpell(WIZARD_WARDING_WHIP)  // SPWI705.SPL (Khelben's Warding Whip)
  See([EVILCUTOFF])
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !ImmuneToSpellLevel(LastSeenBy(Myself),7)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  OR(5)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_IMMUNITY)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
    CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
  !CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_KHELBANS_WARDING_WHIP)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCast","LOCALS",ONE_ROUND)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_WARDING_WHIP)  // SPWI705.SPL (Khelben's Warding Whip)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_SpellCast","LOCALS")
  HaveSpell(WIZARD_WARDING_WHIP)  // SPWI705.SPL (Khelben's Warding Whip)
  See(SecondNearest([EVILCUTOFF]))
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !ImmuneToSpellLevel(LastSeenBy(Myself),7)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  OR(5)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_IMMUNITY)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
    CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
  !CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_KHELBANS_WARDING_WHIP)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCast","LOCALS",ONE_ROUND)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_WARDING_WHIP)  // SPWI705.SPL (Khelben's Warding Whip)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_SpellCast","LOCALS")
  HaveSpell(WIZARD_WARDING_WHIP)  // SPWI705.SPL (Khelben's Warding Whip)
  See(ThirdNearest([EVILCUTOFF]))
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !ImmuneToSpellLevel(LastSeenBy(Myself),7)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  OR(5)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_IMMUNITY)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
    CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
  !CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_KHELBANS_WARDING_WHIP)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCast","LOCALS",ONE_ROUND)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_WARDING_WHIP)  // SPWI705.SPL (Khelben's Warding Whip)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_SpellCast","LOCALS")
  HaveSpell(WIZARD_WARDING_WHIP)  // SPWI705.SPL (Khelben's Warding Whip)
  See(FourthNearest([EVILCUTOFF]))
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !ImmuneToSpellLevel(LastSeenBy(Myself),7)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  OR(5)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_IMMUNITY)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
    CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
  !CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_KHELBANS_WARDING_WHIP)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCast","LOCALS",ONE_ROUND)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_WARDING_WHIP)  // SPWI705.SPL (Khelben's Warding Whip)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_SpellCast","LOCALS")
  HaveSpell(WIZARD_WARDING_WHIP)  // SPWI705.SPL (Khelben's Warding Whip)
  See(FifthNearest([EVILCUTOFF]))
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !ImmuneToSpellLevel(LastSeenBy(Myself),7)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  OR(5)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_IMMUNITY)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
    CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
  !CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_KHELBANS_WARDING_WHIP)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCast","LOCALS",ONE_ROUND)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_WARDING_WHIP)  // SPWI705.SPL (Khelben's Warding Whip)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_SpellCast","LOCALS")
  HaveSpell(WIZARD_WARDING_WHIP)  // SPWI705.SPL (Khelben's Warding Whip)
  See(SixthNearest([EVILCUTOFF]))
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !ImmuneToSpellLevel(LastSeenBy(Myself),7)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  OR(5)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_IMMUNITY)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
    CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
  !CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_KHELBANS_WARDING_WHIP)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCast","LOCALS",ONE_ROUND)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_WARDING_WHIP)  // SPWI705.SPL (Khelben's Warding Whip)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_SpellCast","LOCALS")
  HaveSpell(WIZARD_SPELL_STRIKE)  // SPWI903.SPL (Spellstrike)
  See([EVILCUTOFF])
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !ImmuneToSpellLevel(LastSeenBy(Myself),9)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  OR(7)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_IMMUNITY)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    CheckStatGT(LastSeenBy(Myself),0,CLERIC_SHIELD_OF_THE_ARCHONS)
    CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
    CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCast","LOCALS",ONE_ROUND)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_SPELL_STRIKE)  // SPWI903.SPL (Spellstrike)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_SpellCast","LOCALS")
  HaveSpell(WIZARD_SPELL_STRIKE)  // SPWI903.SPL (Spellstrike)
  See(SecondNearest([EVILCUTOFF]))
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !ImmuneToSpellLevel(LastSeenBy(Myself),9)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  OR(7)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_IMMUNITY)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    CheckStatGT(LastSeenBy(Myself),0,CLERIC_SHIELD_OF_THE_ARCHONS)
    CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
    CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCast","LOCALS",ONE_ROUND)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_SPELL_STRIKE)  // SPWI903.SPL (Spellstrike)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_SpellCast","LOCALS")
  HaveSpell(WIZARD_SPELL_STRIKE)  // SPWI903.SPL (Spellstrike)
  See(ThirdNearest([EVILCUTOFF]))
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !ImmuneToSpellLevel(LastSeenBy(Myself),9)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  OR(7)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_IMMUNITY)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    CheckStatGT(LastSeenBy(Myself),0,CLERIC_SHIELD_OF_THE_ARCHONS)
    CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
    CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCast","LOCALS",ONE_ROUND)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_SPELL_STRIKE)  // SPWI903.SPL (Spellstrike)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_SpellCast","LOCALS")
  HaveSpell(WIZARD_SPELL_STRIKE)  // SPWI903.SPL (Spellstrike)
  See(FourthNearest([EVILCUTOFF]))
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !ImmuneToSpellLevel(LastSeenBy(Myself),9)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  OR(7)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_IMMUNITY)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    CheckStatGT(LastSeenBy(Myself),0,CLERIC_SHIELD_OF_THE_ARCHONS)
    CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
    CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCast","LOCALS",ONE_ROUND)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_SPELL_STRIKE)  // SPWI903.SPL (Spellstrike)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_SpellCast","LOCALS")
  HaveSpell(WIZARD_SPELL_STRIKE)  // SPWI903.SPL (Spellstrike)
  See(FifthNearest([EVILCUTOFF]))
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !ImmuneToSpellLevel(LastSeenBy(Myself),9)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  OR(7)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_IMMUNITY)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    CheckStatGT(LastSeenBy(Myself),0,CLERIC_SHIELD_OF_THE_ARCHONS)
    CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
    CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCast","LOCALS",ONE_ROUND)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_SPELL_STRIKE)  // SPWI903.SPL (Spellstrike)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_SpellCast","LOCALS")
  HaveSpell(WIZARD_SPELL_STRIKE)  // SPWI903.SPL (Spellstrike)
  See(SixthNearest([EVILCUTOFF]))
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !ImmuneToSpellLevel(LastSeenBy(Myself),9)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  OR(7)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_IMMUNITY)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    CheckStatGT(LastSeenBy(Myself),0,CLERIC_SHIELD_OF_THE_ARCHONS)
    CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
    CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCast","LOCALS",ONE_ROUND)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_SPELL_STRIKE)  // SPWI903.SPL (Spellstrike)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_SpellCast","LOCALS")
  HaveSpell(WIZARD_PIERCE_SHIELD)  // SPWI805.SPL (Pierce Shield)
  See([EVILCUTOFF])
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !ImmuneToSpellLevel(LastSeenBy(Myself),8)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  OR(6)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_IMMUNITY)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
    CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCast","LOCALS",ONE_ROUND)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_PIERCE_SHIELD)  // SPWI805.SPL (Pierce Shield)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_SpellCast","LOCALS")
  HaveSpell(WIZARD_PIERCE_SHIELD)  // SPWI805.SPL (Pierce Shield)
  See(SecondNearest([EVILCUTOFF]))
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !ImmuneToSpellLevel(LastSeenBy(Myself),8)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  OR(6)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_IMMUNITY)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
    CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCast","LOCALS",ONE_ROUND)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_PIERCE_SHIELD)  // SPWI805.SPL (Pierce Shield)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_SpellCast","LOCALS")
  HaveSpell(WIZARD_PIERCE_SHIELD)  // SPWI805.SPL (Pierce Shield)
  See(ThirdNearest([EVILCUTOFF]))
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !ImmuneToSpellLevel(LastSeenBy(Myself),8)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  OR(6)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_IMMUNITY)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
    CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCast","LOCALS",ONE_ROUND)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_PIERCE_SHIELD)  // SPWI805.SPL (Pierce Shield)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_SpellCast","LOCALS")
  HaveSpell(WIZARD_PIERCE_SHIELD)  // SPWI805.SPL (Pierce Shield)
  See(FourthNearest([EVILCUTOFF]))
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !ImmuneToSpellLevel(LastSeenBy(Myself),8)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  OR(6)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_IMMUNITY)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
    CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCast","LOCALS",ONE_ROUND)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_PIERCE_SHIELD)  // SPWI805.SPL (Pierce Shield)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_SpellCast","LOCALS")
  HaveSpell(WIZARD_PIERCE_SHIELD)  // SPWI805.SPL (Pierce Shield)
  See(FifthNearest([EVILCUTOFF]))
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !ImmuneToSpellLevel(LastSeenBy(Myself),8)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  OR(6)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_IMMUNITY)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
    CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCast","LOCALS",ONE_ROUND)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_PIERCE_SHIELD)  // SPWI805.SPL (Pierce Shield)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_SpellCast","LOCALS")
  HaveSpell(WIZARD_PIERCE_SHIELD)  // SPWI805.SPL (Pierce Shield)
  See(SixthNearest([EVILCUTOFF]))
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !ImmuneToSpellLevel(LastSeenBy(Myself),8)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  OR(6)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_IMMUNITY)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
    CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCast","LOCALS",ONE_ROUND)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_PIERCE_SHIELD)  // SPWI805.SPL (Pierce Shield)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_SpellCast","LOCALS")
  HaveSpell(WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
  See([EVILCUTOFF])
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !ImmuneToSpellLevel(LastSeenBy(Myself),7)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  OR(6)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_IMMUNITY)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
    CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCast","LOCALS",ONE_ROUND)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_SpellCast","LOCALS")
  HaveSpell(WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
  See(SecondNearest([EVILCUTOFF]))
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !ImmuneToSpellLevel(LastSeenBy(Myself),7)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  OR(6)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_IMMUNITY)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
    CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCast","LOCALS",ONE_ROUND)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_SpellCast","LOCALS")
  HaveSpell(WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
  See(ThirdNearest([EVILCUTOFF]))
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !ImmuneToSpellLevel(LastSeenBy(Myself),7)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  OR(6)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_IMMUNITY)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
    CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCast","LOCALS",ONE_ROUND)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_SpellCast","LOCALS")
  HaveSpell(WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
  See(FourthNearest([EVILCUTOFF]))
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !ImmuneToSpellLevel(LastSeenBy(Myself),7)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  OR(6)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_IMMUNITY)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
    CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCast","LOCALS",ONE_ROUND)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_SpellCast","LOCALS")
  HaveSpell(WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
  See(FifthNearest([EVILCUTOFF]))
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !ImmuneToSpellLevel(LastSeenBy(Myself),7)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  OR(6)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_IMMUNITY)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
    CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCast","LOCALS",ONE_ROUND)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
    SetInterrupt(TRUE)
END

IF
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_SpellCast","LOCALS")
  HaveSpell(WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
  See(SixthNearest([EVILCUTOFF]))
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !ImmuneToSpellLevel(LastSeenBy(Myself),7)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  OR(6)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_IMMUNITY)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
    CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCast","LOCALS",ONE_ROUND)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
    SetInterrupt(TRUE)
END

IF
  ActionListEmpty()
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_SpellCast","LOCALS")
  OR(17)
    Range([EVILCUTOFF.0.FAIRY],30)
    Range([EVILCUTOFF.0.DEMONIC],30)
    Range([EVILCUTOFF.0.RAKSHASA],30)
    Range([EVILCUTOFF.0.DRAGON],30)
    Range([EVILCUTOFF.0.DEMILICH],30)
    Range([EVILCUTOFF.0.LICH],30)
    Range([EVILCUTOFF.0.SOLAR],30)
    Range([EVILCUTOFF.0.PLANATAR],30)
    Range([EVILCUTOFF.0.ANTISOLAR],30)
    Range([EVILCUTOFF.0.DARKPLANATAR],30)
    See([ENEMY.0.0.MAGE_ALL])
    See([ENEMY.0.0.BARD_ALL])
    See([ENEMY.0.0.CLERIC_ALL])
    See([ENEMY.0.0.DRUID_ALL])
    See([ENEMY.0.0.SORCERER])
    See([ENEMY.0.0.CLERIC_MAGE])
    See([ENEMY.0.0.MAGE_ALL])
  HaveSpell(WIZARD_SPELL_SHIELD)  // SPWI519.SPL (Spell Shield)
  !CheckSpellState(Myself,SPELL_SHIELD)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCast","LOCALS",ONE_ROUND)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_SPELL_SHIELD)  // SPWI519.SPL (Spell Shield)
    SetInterrupt(TRUE)
END

IF
  ActionListEmpty()
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_SpellCast","LOCALS")
  OR(17)
    Range([EVILCUTOFF.0.FAIRY],30)
    Range([EVILCUTOFF.0.DEMONIC],30)
    Range([EVILCUTOFF.0.RAKSHASA],30)
    Range([EVILCUTOFF.0.DRAGON],30)
    Range([EVILCUTOFF.0.DEMILICH],30)
    Range([EVILCUTOFF.0.LICH],30)
    Range([EVILCUTOFF.0.SOLAR],30)
    Range([EVILCUTOFF.0.PLANATAR],30)
    Range([EVILCUTOFF.0.ANTISOLAR],30)
    Range([EVILCUTOFF.0.DARKPLANATAR],30)
    See([ENEMY.0.0.MAGE_ALL])
    See([ENEMY.0.0.BARD_ALL])
    See([ENEMY.0.0.CLERIC_ALL])
    See([ENEMY.0.0.DRUID_ALL])
    See([ENEMY.0.0.SORCERER])
    See([ENEMY.0.0.CLERIC_MAGE])
    See([ENEMY.0.0.MAGE_ALL])
  HaveSpell(WIZARD_SPELL_TRAP)  // SPWI902.SPL (Spell Trap)
  CheckStatLT(Myself,1,WIZARD_SPELL_TRAP)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCast","LOCALS",ONE_ROUND)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_SPELL_TRAP)  // SPWI902.SPL (Spell Trap)
    SetInterrupt(TRUE)
END

IF
  ActionListEmpty()
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_SpellCast","LOCALS")
  OR(17)
    Range([EVILCUTOFF.0.FAIRY],30)
    Range([EVILCUTOFF.0.DEMONIC],30)
    Range([EVILCUTOFF.0.RAKSHASA],30)
    Range([EVILCUTOFF.0.DRAGON],30)
    Range([EVILCUTOFF.0.DEMILICH],30)
    Range([EVILCUTOFF.0.LICH],30)
    Range([EVILCUTOFF.0.SOLAR],30)
    Range([EVILCUTOFF.0.PLANATAR],30)
    Range([EVILCUTOFF.0.ANTISOLAR],30)
    Range([EVILCUTOFF.0.DARKPLANATAR],30)
    See([ENEMY.0.0.MAGE_ALL])
    See([ENEMY.0.0.BARD_ALL])
    See([ENEMY.0.0.CLERIC_ALL])
    See([ENEMY.0.0.DRUID_ALL])
    See([ENEMY.0.0.SORCERER])
    See([ENEMY.0.0.CLERIC_MAGE])
    See([ENEMY.0.0.MAGE_ALL])
  HaveSpell(WIZARD_SPELL_DEFLECTION)  // SPWI618.SPL (Spell Deflection)
  CheckStatLT(Myself,1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCast","LOCALS",ONE_ROUND)
    SetInterrupt(FALSE)
    Spell(Myself,2802)  // SPWI802.SPL (Spell Deflection)
    SetInterrupt(TRUE)
END

IF
  ActionListEmpty()
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_SpellCast","LOCALS")
  OR(17)
    Range([EVILCUTOFF.0.FAIRY],30)
    Range([EVILCUTOFF.0.DEMONIC],30)
    Range([EVILCUTOFF.0.RAKSHASA],30)
    Range([EVILCUTOFF.0.DRAGON],30)
    Range([EVILCUTOFF.0.DEMILICH],30)
    Range([EVILCUTOFF.0.LICH],30)
    Range([EVILCUTOFF.0.SOLAR],30)
    Range([EVILCUTOFF.0.PLANATAR],30)
    Range([EVILCUTOFF.0.ANTISOLAR],30)
    Range([EVILCUTOFF.0.DARKPLANATAR],30)
    See([ENEMY.0.0.MAGE_ALL])
    See([ENEMY.0.0.BARD_ALL])
    See([ENEMY.0.0.CLERIC_ALL])
    See([ENEMY.0.0.DRUID_ALL])
    See([ENEMY.0.0.SORCERER])
    See([ENEMY.0.0.CLERIC_MAGE])
    See([ENEMY.0.0.MAGE_ALL])
  HaveSpell(WIZARD_SPELL_TURNING)  // SPWI701.SPL (Spell Turning)
  CheckStatLT(Myself,1,WIZARD_SPELL_TURNING)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCast","LOCALS",ONE_ROUND)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_SPELL_TURNING)  // SPWI701.SPL (Spell Turning)
    SetInterrupt(TRUE)
END

IF
  ActionListEmpty()
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_SpellCast","LOCALS")
  OR(17)
    Range([EVILCUTOFF.0.FAIRY],30)
    Range([EVILCUTOFF.0.DEMONIC],30)
    Range([EVILCUTOFF.0.RAKSHASA],30)
    Range([EVILCUTOFF.0.DRAGON],30)
    Range([EVILCUTOFF.0.DEMILICH],30)
    Range([EVILCUTOFF.0.LICH],30)
    Range([EVILCUTOFF.0.SOLAR],30)
    Range([EVILCUTOFF.0.PLANATAR],30)
    Range([EVILCUTOFF.0.ANTISOLAR],30)
    Range([EVILCUTOFF.0.DARKPLANATAR],30)
    See([ENEMY.0.0.MAGE_ALL])
    See([ENEMY.0.0.BARD_ALL])
    See([ENEMY.0.0.CLERIC_ALL])
    See([ENEMY.0.0.DRUID_ALL])
    See([ENEMY.0.0.SORCERER])
    See([ENEMY.0.0.CLERIC_MAGE])
    See([ENEMY.0.0.MAGE_ALL])
  HaveSpell(WIZARD_GLOBE_OF_INVULNERABILITY)  // SPWI602.SPL (Globe of Invulnerability)
  CheckStatLT(Myself,1,MINORGLOBE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCast","LOCALS",ONE_ROUND)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_GLOBE_OF_INVULNERABILITY)  // SPWI602.SPL (Globe of Invulnerability)
    SetInterrupt(TRUE)
END

IF
  ActionListEmpty()
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_SpellCast","LOCALS")
  OR(17)
    Range([EVILCUTOFF.0.FAIRY],30)
    Range([EVILCUTOFF.0.DEMONIC],30)
    Range([EVILCUTOFF.0.RAKSHASA],30)
    Range([EVILCUTOFF.0.DRAGON],30)
    Range([EVILCUTOFF.0.DEMILICH],30)
    Range([EVILCUTOFF.0.LICH],30)
    Range([EVILCUTOFF.0.SOLAR],30)
    Range([EVILCUTOFF.0.PLANATAR],30)
    Range([EVILCUTOFF.0.ANTISOLAR],30)
    Range([EVILCUTOFF.0.DARKPLANATAR],30)
    See([ENEMY.0.0.MAGE_ALL])
    See([ENEMY.0.0.BARD_ALL])
    See([ENEMY.0.0.CLERIC_ALL])
    See([ENEMY.0.0.DRUID_ALL])
    See([ENEMY.0.0.SORCERER])
    See([ENEMY.0.0.CLERIC_MAGE])
    See([ENEMY.0.0.MAGE_ALL])
  HaveSpell(WIZARD_MINOR_SPELL_TURNING)  // SPWI522.SPL (Minor Spell Turning)
  CheckStatLT(Myself,1,WIZARD_SPELL_TURNING)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCast","LOCALS",ONE_ROUND)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_MINOR_SPELL_TURNING)  // SPWI522.SPL (Minor Spell Turning)
    SetInterrupt(TRUE)
END

IF
  ActionListEmpty()
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_SpellCast","LOCALS")
  OR(17)
    Range([EVILCUTOFF.0.FAIRY],30)
    Range([EVILCUTOFF.0.DEMONIC],30)
    Range([EVILCUTOFF.0.RAKSHASA],30)
    Range([EVILCUTOFF.0.DRAGON],30)
    Range([EVILCUTOFF.0.DEMILICH],30)
    Range([EVILCUTOFF.0.LICH],30)
    Range([EVILCUTOFF.0.SOLAR],30)
    Range([EVILCUTOFF.0.PLANATAR],30)
    Range([EVILCUTOFF.0.ANTISOLAR],30)
    Range([EVILCUTOFF.0.DARKPLANATAR],30)
    See([ENEMY.0.0.MAGE_ALL])
    See([ENEMY.0.0.BARD_ALL])
    See([ENEMY.0.0.CLERIC_ALL])
    See([ENEMY.0.0.DRUID_ALL])
    See([ENEMY.0.0.SORCERER])
    See([ENEMY.0.0.CLERIC_MAGE])
    See([ENEMY.0.0.MAGE_ALL])
  HaveSpell(WIZARD_MINOR_SPELL_DEFLECTION)  // SPWI318.SPL (Minor Spell Deflection)
  CheckStatLT(Myself,1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCast","LOCALS",ONE_ROUND)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_MINOR_SPELL_DEFLECTION)  // SPWI318.SPL (Minor Spell Deflection)
    SetInterrupt(TRUE)
END

IF
  ActionListEmpty()
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_SpellCast","LOCALS")
  OR(17)
    Range([EVILCUTOFF.0.FAIRY],30)
    Range([EVILCUTOFF.0.DEMONIC],30)
    Range([EVILCUTOFF.0.RAKSHASA],30)
    Range([EVILCUTOFF.0.DRAGON],30)
    Range([EVILCUTOFF.0.DEMILICH],30)
    Range([EVILCUTOFF.0.LICH],30)
    Range([EVILCUTOFF.0.SOLAR],30)
    Range([EVILCUTOFF.0.PLANATAR],30)
    Range([EVILCUTOFF.0.ANTISOLAR],30)
    Range([EVILCUTOFF.0.DARKPLANATAR],30)
    See([ENEMY.0.0.MAGE_ALL])
    See([ENEMY.0.0.BARD_ALL])
    See([ENEMY.0.0.CLERIC_ALL])
    See([ENEMY.0.0.DRUID_ALL])
    See([ENEMY.0.0.SORCERER])
    See([ENEMY.0.0.CLERIC_MAGE])
    See([ENEMY.0.0.MAGE_ALL])
  HaveSpell(WIZARD_MINOR_GLOBE_OF_INVULNERABILITY)  // SPWI406.SPL (Minor Globe of Invulnerability)
  CheckStatLT(Myself,1,MINORGLOBE)
  !HasImmunityEffects(Myself)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCast","LOCALS",ONE_ROUND)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_MINOR_GLOBE_OF_INVULNERABILITY)  // SPWI406.SPL (Minor Globe of Invulnerability)
    SetInterrupt(TRUE)
END

IF
  ActionListEmpty()
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_SpellCast","LOCALS")
  HaveSpell(WIZARD_FIRE_SHIELD_RED)  // SPWI418.SPL (Fire Shield (Red))
  See([EVILCUTOFF])
  OR(19)
    NumCreatureGT([EVILCUTOFF],3)
    Range([EVILCUTOFF.0.KUO-TOA],30)
    Range([EVILCUTOFF.0.GENIE],30)
    Range([EVILCUTOFF.0.GITHYANKI],30)
    Range([EVILCUTOFF.0.RAKSHASA],30)
    Range([EVILCUTOFF.0.VAMPYRE],30)
    Range([EVILCUTOFF.0.MIND_FLAYER],30)
    Range([EVILCUTOFF.0.DRAGON],30)
    Range([EVILCUTOFF.0.DEMONIC],30)
    Range([EVILCUTOFF.0.BEHOLDER],30)
    Range([EVILCUTOFF.0.VAMPIRE],30)
    Range([EVILCUTOFF.0.LICH],30)
    Range([EVILCUTOFF.0.DEMILICH],30)
    Range([EVILCUTOFF.0.LICH],30)
    Range([EVILCUTOFF.0.SOLAR],30)
    Range([EVILCUTOFF.0.PLANATAR],30)
    Range([EVILCUTOFF.0.ANTISOLAR],30)
    Range([EVILCUTOFF.0.DARKPLANATAR],30)
    See([ENEMY.0.0.DRUID_ALL])
  !CheckSpellState(Myself,RED_FIRESHIELD)
  !CheckSpellState(Myself,BLUE_FIRESHIELD)
  CheckStat(Myself,0,MINORGLOBE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCast","LOCALS",ONE_ROUND)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_FIRE_SHIELD_RED)  // SPWI418.SPL (Fire Shield (Red))
    SetInterrupt(TRUE)
END

IF
  ActionListEmpty()
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_SpellCast","LOCALS")
  HaveSpell(WIZARD_FIRE_SHIELD_BLUE)  // SPWI403.SPL (Fire Shield (Blue))
  See([EVILCUTOFF])
  OR(19)
    NumCreatureGT([EVILCUTOFF],3)
    Range([EVILCUTOFF.0.KUO-TOA],30)
    Range([EVILCUTOFF.0.GENIE],30)
    Range([EVILCUTOFF.0.GITHYANKI],30)
    Range([EVILCUTOFF.0.RAKSHASA],30)
    Range([EVILCUTOFF.0.VAMPYRE],30)
    Range([EVILCUTOFF.0.MIND_FLAYER],30)
    Range([EVILCUTOFF.0.DRAGON],30)
    Range([EVILCUTOFF.0.DEMONIC],30)
    Range([EVILCUTOFF.0.BEHOLDER],30)
    Range([EVILCUTOFF.0.VAMPIRE],30)
    Range([EVILCUTOFF.0.LICH],30)
    Range([EVILCUTOFF.0.DEMILICH],30)
    Range([EVILCUTOFF.0.LICH],30)
    Range([EVILCUTOFF.0.SOLAR],30)
    Range([EVILCUTOFF.0.PLANATAR],30)
    Range([EVILCUTOFF.0.ANTISOLAR],30)
    Range([EVILCUTOFF.0.DARKPLANATAR],30)
    See([ENEMY.0.0.DRUID_ALL])
  !CheckSpellState(Myself,RED_FIRESHIELD)
  !CheckSpellState(Myself,BLUE_FIRESHIELD)
  CheckStat(Myself,0,MINORGLOBE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCast","LOCALS",ONE_ROUND)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_FIRE_SHIELD_BLUE)  // SPWI403.SPL (Fire Shield (Blue))
    SetInterrupt(TRUE)
END

IF
  ActionListEmpty()
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_SpellCast","LOCALS")
  HaveSpell(WIZARD_PROTECTION_FROM_NORMAL_MISSILES)  // SPWI311.SPL (Protection From Normal Missiles)
  OR(11)
    HitBy([ANYONE],MISSILE)
    IsWeaponRanged(NearestEnemyOf(Myself))
    IsWeaponRanged(SecondNearestEnemyOf(Myself))
    IsWeaponRanged(ThirdNearestEnemyOf(Myself))
    IsWeaponRanged(FourthNearestEnemyOf(Myself))
    IsWeaponRanged(FifthNearestEnemyOf(Myself))
    IsWeaponRanged(SixthNearestEnemyOf(Myself))
    IsWeaponRanged(SeventhNearestEnemyOf(Myself))
    IsWeaponRanged(EighthNearestEnemyOf(Myself))
    IsWeaponRanged(NinthNearestEnemyOf(Myself))
    IsWeaponRanged(TenthNearestEnemyOf(Myself))
  !CheckSpellState(Myself,PROTECTION_FROM_NORMAL_MISSILES)
  CheckStat(Myself,0,MINORGLOBE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCast","LOCALS",ONE_ROUND)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_PROTECTION_FROM_NORMAL_MISSILES)  // SPWI311.SPL (Protection From Normal Missiles)
    SetInterrupt(TRUE)
END

IF
  ActionListEmpty()
  IfValidForPartyDialog(Myself)
  !StateCheck(Myself,STATE_MIRRORIMAGE)
  !GlobalTimerNotExpired("MO_SpellCast","LOCALS")
  HaveSpell(WIZARD_MIRROR_IMAGE)  // SPWI212.SPL (Mirror Image)
  See(NearestEnemyOf(Myself))
  NumCreatureGT([EVILCUTOFF],3)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(NearestEnemyOf(Myself),0,TRUE_SIGHT)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,TRUE_SIGHT)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,TRUE_SIGHT)
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,TRUE_SIGHT)
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,TRUE_SIGHT)
  !CheckStatGT(SeventhNearestEnemyOf(Myself),0,TRUE_SIGHT)
  !CheckStatGT(EighthNearestEnemyOf(Myself),0,TRUE_SIGHT)
  !CheckStatGT(NinthNearestEnemyOf(Myself),0,TRUE_SIGHT)
  !CheckStatGT(TenthNearestEnemyOf(Myself),0,TRUE_SIGHT)
  !CheckStatGT([EVILCUTOFF.0.PLANATAR],0,TRUE_SIGHT)
  !CheckStatGT([EVILCUTOFF.0.DARKPLANATAR],0,TRUE_SIGHT)
  !CheckStat(Myself,1,PUPPETTYPE)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCast","LOCALS",ONE_ROUND)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_MIRROR_IMAGE)  // SPWI212.SPL (Mirror Image)
    SetInterrupt(TRUE)
END

IF
  ActionListEmpty()
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_SpellCast","LOCALS")
  HaveSpell(BERSERKER_RAGE)  // SPCL321.SPL (Enrage)
  !CheckSpellState(Myself,BERSERKER_RAGE_FATIGUE)
  !CheckSpellState(Myself,BERSERKER_RAGE)
  See([EVILCUTOFF])
  OR(34)
    NumCreatureGT([EVILCUTOFF],3)
    Range([EVILCUTOFF.0.GOLEM],30)
    Range([EVILCUTOFF.0.MIST],30)
    Range([EVILCUTOFF.0.KUO-TOA],30)
    Range([EVILCUTOFF.0.GENIE],30)
    Range([EVILCUTOFF.0.GITHYANKI],30)
    Range([EVILCUTOFF.0.RAKSHASA],30)
    Range([EVILCUTOFF.0.VAMPYRE],30)
    Range([EVILCUTOFF.0.MIND_FLAYER],30)
    Range([EVILCUTOFF.0.DRAGON],30)
    Range([EVILCUTOFF.0.DEMONIC],30)
    Range([EVILCUTOFF.0.BEHOLDER],30)
    Range([EVILCUTOFF.0.UMBERHULK],30)
    Range([EVILCUTOFF.0.MYCONID],30)
    Range([EVILCUTOFF.0.VAMPIRE],30)
    Range([EVILCUTOFF.0.LICH],30)
    Range([EVILCUTOFF.0.DEMILICH],30)
    Range([EVILCUTOFF.0.FAIRY],30)
    Range([EVILCUTOFF.0.0.WRAITH],30)
    Range([EVILCUTOFF.0.0.WIGHT],30)
    Range([EVILCUTOFF.0.0.SPECTRE],30)
    Range([EVILCUTOFF.0.0.WYVERN],30)
    Range([EVILCUTOFF.0.0.BASILISK],30)
    Range([EVILCUTOFF.0.LICH],30)
    Range([EVILCUTOFF.0.SOLAR],30)
    Range([EVILCUTOFF.0.PLANATAR],30)
    Range([EVILCUTOFF.0.ANTISOLAR],30)
    Range([EVILCUTOFF.0.DARKPLANATAR],30)
    See([ENEMY.0.0.MAGE_ALL])
    See([ENEMY.0.0.BARD_ALL])
    See([ENEMY.0.0.CLERIC_ALL])
    See([ENEMY.0.0.DRUID_ALL])
    See([ENEMY.0.0.SORCERER])
    See([ENEMY.0.0.CLERIC_MAGE])
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCast","LOCALS",ONE_ROUND)
    Spell(Myself,BERSERKER_RAGE)  // SPCL321.SPL (Enrage)
END

IF
  ActionListEmpty()
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_SpellCast","LOCALS")
  HaveSpell(KENSAI_KIA)  // SPCL144.SPL (Kai)
  !CheckSpellState(Myself,KENSAI_KIA)
  See([EVILCUTOFF])
  OR(6)
    WeaponEffectiveVs(NearestEnemyOf(Myself),MAINHAND)
    WeaponEffectiveVs(SecondNearestEnemyOf(Myself),MAINHAND)
    WeaponEffectiveVs(ThirdNearestEnemyOf(Myself),MAINHAND)
    WeaponEffectiveVs(FourthNearestEnemyOf(Myself),MAINHAND)
    WeaponEffectiveVs(FifthNearestEnemyOf(Myself),MAINHAND)
    WeaponEffectiveVs(SixthNearestEnemyOf(Myself),MAINHAND)
  OR(6)
    WeaponCanDamage(NearestEnemyOf(Myself),MAINHAND)
    WeaponCanDamage(SecondNearestEnemyOf(Myself),MAINHAND)
    WeaponCanDamage(ThirdNearestEnemyOf(Myself),MAINHAND)
    WeaponCanDamage(FourthNearestEnemyOf(Myself),MAINHAND)
    WeaponCanDamage(FifthNearestEnemyOf(Myself),MAINHAND)
    WeaponCanDamage(SixthNearestEnemyOf(Myself),MAINHAND)
  OR(34)
    NumCreatureGT([EVILCUTOFF],3)
    Range([EVILCUTOFF.0.GOLEM],30)
    Range([EVILCUTOFF.0.MIST],30)
    Range([EVILCUTOFF.0.KUO-TOA],30)
    Range([EVILCUTOFF.0.GENIE],30)
    Range([EVILCUTOFF.0.GITHYANKI],30)
    Range([EVILCUTOFF.0.RAKSHASA],30)
    Range([EVILCUTOFF.0.VAMPYRE],30)
    Range([EVILCUTOFF.0.MIND_FLAYER],30)
    Range([EVILCUTOFF.0.DRAGON],30)
    Range([EVILCUTOFF.0.DEMONIC],30)
    Range([EVILCUTOFF.0.BEHOLDER],30)
    Range([EVILCUTOFF.0.UMBERHULK],30)
    Range([EVILCUTOFF.0.MYCONID],30)
    Range([EVILCUTOFF.0.VAMPIRE],30)
    Range([EVILCUTOFF.0.LICH],30)
    Range([EVILCUTOFF.0.DEMILICH],30)
    Range([EVILCUTOFF.0.FAIRY],30)
    Range([EVILCUTOFF.0.0.WRAITH],30)
    Range([EVILCUTOFF.0.0.WIGHT],30)
    Range([EVILCUTOFF.0.0.SPECTRE],30)
    Range([EVILCUTOFF.0.0.WYVERN],30)
    Range([EVILCUTOFF.0.0.BASILISK],30)
    Range([EVILCUTOFF.0.LICH],30)
    Range([EVILCUTOFF.0.SOLAR],30)
    Range([EVILCUTOFF.0.PLANATAR],30)
    Range([EVILCUTOFF.0.ANTISOLAR],30)
    Range([EVILCUTOFF.0.DARKPLANATAR],30)
    See([ENEMY.0.0.MAGE_ALL])
    See([ENEMY.0.0.BARD_ALL])
    See([ENEMY.0.0.CLERIC_ALL])
    See([ENEMY.0.0.DRUID_ALL])
    See([ENEMY.0.0.SORCERER])
    See([ENEMY.0.0.CLERIC_MAGE])
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCast","LOCALS",ONE_ROUND)
    Spell(Myself,KENSAI_KIA)  // SPCL144.SPL (Kai)
END

IF
  ActionListEmpty()
  IfValidForPartyDialog(Myself)
  !GlobalTimerNotExpired("MO_SpellCast","LOCALS")
  HaveSpell(WIZARD_IMPROVED_HASTE)  // SPWI613.SPL (Improved Haste)
  !CheckStatGT(Myself,0,IMPROVEDHASTE)
  !CheckStat(Myself,5,OFFENSIVE_MODIFIER)
  See([EVILCUTOFF])
  OR(6)
    WeaponEffectiveVs(NearestEnemyOf(Myself),MAINHAND)
    WeaponEffectiveVs(SecondNearestEnemyOf(Myself),MAINHAND)
    WeaponEffectiveVs(ThirdNearestEnemyOf(Myself),MAINHAND)
    WeaponEffectiveVs(FourthNearestEnemyOf(Myself),MAINHAND)
    WeaponEffectiveVs(FifthNearestEnemyOf(Myself),MAINHAND)
    WeaponEffectiveVs(SixthNearestEnemyOf(Myself),MAINHAND)
  OR(6)
    WeaponCanDamage(NearestEnemyOf(Myself),MAINHAND)
    WeaponCanDamage(SecondNearestEnemyOf(Myself),MAINHAND)
    WeaponCanDamage(ThirdNearestEnemyOf(Myself),MAINHAND)
    WeaponCanDamage(FourthNearestEnemyOf(Myself),MAINHAND)
    WeaponCanDamage(FifthNearestEnemyOf(Myself),MAINHAND)
    WeaponCanDamage(SixthNearestEnemyOf(Myself),MAINHAND)
  OR(34)
    NumCreatureGT([EVILCUTOFF],3)
    Range([EVILCUTOFF.0.GOLEM],30)
    Range([EVILCUTOFF.0.MIST],30)
    Range([EVILCUTOFF.0.KUO-TOA],30)
    Range([EVILCUTOFF.0.GENIE],30)
    Range([EVILCUTOFF.0.GITHYANKI],30)
    Range([EVILCUTOFF.0.RAKSHASA],30)
    Range([EVILCUTOFF.0.VAMPYRE],30)
    Range([EVILCUTOFF.0.MIND_FLAYER],30)
    Range([EVILCUTOFF.0.DRAGON],30)
    Range([EVILCUTOFF.0.DEMONIC],30)
    Range([EVILCUTOFF.0.BEHOLDER],30)
    Range([EVILCUTOFF.0.UMBERHULK],30)
    Range([EVILCUTOFF.0.MYCONID],30)
    Range([EVILCUTOFF.0.VAMPIRE],30)
    Range([EVILCUTOFF.0.LICH],30)
    Range([EVILCUTOFF.0.DEMILICH],30)
    Range([EVILCUTOFF.0.FAIRY],30)
    Range([EVILCUTOFF.0.0.WRAITH],30)
    Range([EVILCUTOFF.0.0.WIGHT],30)
    Range([EVILCUTOFF.0.0.SPECTRE],30)
    Range([EVILCUTOFF.0.0.WYVERN],30)
    Range([EVILCUTOFF.0.0.BASILISK],30)
    Range([EVILCUTOFF.0.LICH],30)
    Range([EVILCUTOFF.0.SOLAR],30)
    Range([EVILCUTOFF.0.PLANATAR],30)
    Range([EVILCUTOFF.0.ANTISOLAR],30)
    Range([EVILCUTOFF.0.DARKPLANATAR],30)
    See([ENEMY.0.0.MAGE_ALL])
    See([ENEMY.0.0.BARD_ALL])
    See([ENEMY.0.0.CLERIC_ALL])
    See([ENEMY.0.0.DRUID_ALL])
    See([ENEMY.0.0.SORCERER])
    See([ENEMY.0.0.CLERIC_MAGE])
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_CastAthkatla","LOCALS",1)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCast","LOCALS",ONE_ROUND)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_IMPROVED_HASTE)  // SPWI613.SPL (Improved Haste)
    SetInterrupt(TRUE)
END

IF
  ActionListEmpty()
  !GlobalTimerNotExpired("MO_SpellCast","LOCALS")
  HaveSpell(WARRIOR_GREATER_WHIRLWIND)  // SPCL901.SPL (Greater Whirlwind Attack)
  !CheckStatGT(Myself,0,IMPROVEDHASTE)
  !CheckStat(Myself,5,OFFENSIVE_MODIFIER)
  See([EVILCUTOFF])
  OR(6)
    WeaponEffectiveVs(NearestEnemyOf(Myself),MAINHAND)
    WeaponEffectiveVs(SecondNearestEnemyOf(Myself),MAINHAND)
    WeaponEffectiveVs(ThirdNearestEnemyOf(Myself),MAINHAND)
    WeaponEffectiveVs(FourthNearestEnemyOf(Myself),MAINHAND)
    WeaponEffectiveVs(FifthNearestEnemyOf(Myself),MAINHAND)
    WeaponEffectiveVs(SixthNearestEnemyOf(Myself),MAINHAND)
  OR(6)
    WeaponCanDamage(NearestEnemyOf(Myself),MAINHAND)
    WeaponCanDamage(SecondNearestEnemyOf(Myself),MAINHAND)
    WeaponCanDamage(ThirdNearestEnemyOf(Myself),MAINHAND)
    WeaponCanDamage(FourthNearestEnemyOf(Myself),MAINHAND)
    WeaponCanDamage(FifthNearestEnemyOf(Myself),MAINHAND)
    WeaponCanDamage(SixthNearestEnemyOf(Myself),MAINHAND)
  OR(34)
    NumCreatureGT([EVILCUTOFF],3)
    Range([EVILCUTOFF.0.GOLEM],30)
    Range([EVILCUTOFF.0.MIST],30)
    Range([EVILCUTOFF.0.KUO-TOA],30)
    Range([EVILCUTOFF.0.GENIE],30)
    Range([EVILCUTOFF.0.GITHYANKI],30)
    Range([EVILCUTOFF.0.RAKSHASA],30)
    Range([EVILCUTOFF.0.VAMPYRE],30)
    Range([EVILCUTOFF.0.MIND_FLAYER],30)
    Range([EVILCUTOFF.0.DRAGON],30)
    Range([EVILCUTOFF.0.DEMONIC],30)
    Range([EVILCUTOFF.0.BEHOLDER],30)
    Range([EVILCUTOFF.0.UMBERHULK],30)
    Range([EVILCUTOFF.0.MYCONID],30)
    Range([EVILCUTOFF.0.VAMPIRE],30)
    Range([EVILCUTOFF.0.LICH],30)
    Range([EVILCUTOFF.0.DEMILICH],30)
    Range([EVILCUTOFF.0.FAIRY],30)
    Range([EVILCUTOFF.0.0.WRAITH],30)
    Range([EVILCUTOFF.0.0.WIGHT],30)
    Range([EVILCUTOFF.0.0.SPECTRE],30)
    Range([EVILCUTOFF.0.0.WYVERN],30)
    Range([EVILCUTOFF.0.0.BASILISK],30)
    Range([EVILCUTOFF.0.LICH],30)
    Range([EVILCUTOFF.0.SOLAR],30)
    Range([EVILCUTOFF.0.PLANATAR],30)
    Range([EVILCUTOFF.0.ANTISOLAR],30)
    Range([EVILCUTOFF.0.DARKPLANATAR],30)
    See([ENEMY.0.0.MAGE_ALL])
    See([ENEMY.0.0.BARD_ALL])
    See([ENEMY.0.0.CLERIC_ALL])
    See([ENEMY.0.0.DRUID_ALL])
    See([ENEMY.0.0.SORCERER])
    See([ENEMY.0.0.CLERIC_MAGE])
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCast","LOCALS",ONE_ROUND)
    Spell(Myself,WARRIOR_GREATER_WHIRLWIND)  // SPCL901.SPL (Greater Whirlwind Attack)
END

IF
  ActionListEmpty()
  See(NearestEnemyOf(Myself))
  WeaponEffectiveVs(NearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(NearestEnemyOf(Myself),MAINHAND)
THEN
  RESPONSE #100
    Attack(NearestEnemyOf(Myself))
END

IF
  ActionListEmpty()
  See(SecondNearestEnemyOf(Myself))
  WeaponEffectiveVs(SecondNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(SecondNearestEnemyOf(Myself),MAINHAND)
THEN
  RESPONSE #100
    Attack(SecondNearestEnemyOf(Myself))
END

IF
  ActionListEmpty()
  See(ThirdNearestEnemyOf(Myself))
  WeaponEffectiveVs(ThirdNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(ThirdNearestEnemyOf(Myself),MAINHAND)
THEN
  RESPONSE #100
    Attack(ThirdNearestEnemyOf(Myself))
END

IF
  ActionListEmpty()
  See(FourthNearestEnemyOf(Myself))
  WeaponEffectiveVs(FourthNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(FourthNearestEnemyOf(Myself),MAINHAND)
THEN
  RESPONSE #100
    Attack(FourthNearestEnemyOf(Myself))
END

IF
  ActionListEmpty()
  See(FifthNearestEnemyOf(Myself))
  WeaponEffectiveVs(FifthNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(FifthNearestEnemyOf(Myself),MAINHAND)
THEN
  RESPONSE #100
    Attack(FifthNearestEnemyOf(Myself))
END

IF
  ActionListEmpty()
  See(SixthNearestEnemyOf(Myself))
  WeaponEffectiveVs(SixthNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(SixthNearestEnemyOf(Myself),MAINHAND)
THEN
  RESPONSE #100
    Attack(SixthNearestEnemyOf(Myself))
END

IF
  ActionListEmpty()
  IfValidForPartyDialog(Myself)
  !See([EVILCUTOFF])
  !ModalState(DETECTTRAPS)
  !ModalState(STEALTH)
  OR(3)
    Class(Myself,THIEF_ALL)
    Class(Myself,MONK)
    Class(Myself,SHAMAN)
THEN
  RESPONSE #100
    FindTraps()
END

